### ISSUE TITLE
Update CMake dependency

### ISSUE THREAD

**Issue by jzakrzewski** [curl/curl#1010]
I'm starting this as a continuation of the discussion from #990. Please refer to there (especially @Lekensteyn 's excellent version and availability comparison: https://github.com/curl/curl/pull/990#issuecomment-245112823 ).

I'd simply like to hear more opinions.

I'm in favour of at least 2.8.12 even though it's not included in RHEL7 and Debian Wheezy repositories. It can however be downloaded or build with minimal effort. 2.8.11 would cover those two distros by default.

**Comment by jay** [comment]
This is an issue tracker, I'm not sure what the issue is here but maybe that's because I hardly use cmake. Can you please state what the issue is and why it needs fixing. What's wrong with leaving it at 2.8, is that no longer good enough anymore? It's the minimum _required_ version but if you have a later version you use that don't you? This is only going to reach about 400 people many of them fellow developers. I think you're better off starting a discussion about something like this on curl-library to see if anyone has an opinion there.

Also: curl is built on lots of old LTS stuff. I don't have any metrics on that though, but I know until within the last year or two there wasn't that much activity around curl's cmake build file.

**Comment by jzakrzewski** [comment]
Most of the stuff is bugfixes and doing things on a per-target or even per-source-file manner. Things like private / interface link dependencies or includes, more reliable find modules, automatic detection of compiler flags to activate certain features, etc. If we don't have it, we must write workarounds anyway. It also allows to keep cleaner CMakeLists because you can avoid many global settings in favour of per-target / per-source one.

I know, that curl is build on "lots of LTS stuff" but the chance of breaking anything is really minimal as most of those use autotools (partially because of the poor state of curl's CMake build). And, as stated earlier, installing CMake may be as easy as extracting a *.tar or, in worst case, 3 simple commands in CLI.

The newer versions are simply far more maintainable. At the same time I recognise the issue with too-new versions and this is why I don't think that pushing 3.x make sense. Another thing is I'm not really an expert (yet ;) ). I'd like have better CMake support in curl and I'm trying to make it happen but finding help regarding 2.8.0 is getting harder as everybody recommends newer, better syntax.

**Comment by Lekensteyn** [comment]
Two years ago CMake was [about to be dropped][1] due to its inferior state, currently it also prints a clear warning that the cmake system is poorly maintained. If an ancient version like CMake 2.8.0 is enforced, it will be harder to maintain/improve CMake support due to less flexibility and hacks to workaround missing CMake features.

Arguments/notes based on the [curl user survey from 2016][2]:

 - Users would like to see a build system for MingW that detects paths better.
 - Users would like to see better build instructions on Windows that results in a working .exe.
 - 32.6% (n=172) of the respondents build cURL themselves.
 - 36.2% use cURL on WIndows, 95.4% on Linux, 51.7% on OS X, 20.7% on *BSD. (Note that this does not tell us what Linux distro (version) they use and whether they compile cURL from source or just use provided binaries.)

Windows, OS X and *BSD users are generally not bound to a certain CMake version and can easily upgrade, so the minimum CMake version will be determined by Linux. As Linux users already have a functional autotools build system, I think that using CMake 2.8.12 is reasonable (Debian Wheezy and RHEL 7 users can then upgrade cmake or stick to autotools).

 [1]: https://curl.haxx.se/mail/lib-2014-07/0324.html
 [2]: https://daniel.haxx.se/blog/2016/06/21/curl-user-survey-results-2016/

**Comment by snikulov** [comment]
I vote for this change :+1:

**Comment by jay** [comment]
@jzakrzewski Your proposal has support from curl team members familiar with cmake and was not objected to by anyone here or [on the mailing list](https://curl.haxx.se/mail/lib-2016-09/0109.html) so you're good to go.

**Comment by bagder** [comment]
This issue is basically a request and the request has been granted. I figure the work should now be done and get submitted as a pull-request. As far as I can tell, this issue is handled with the outcome: Sure, we can up the requirement without objections.

**Comment by jzakrzewski** [comment]
Yes, sorry for the delay. I was on vacation and now I'm slowly getting back to everything. I plan to do some work on CMake an will probably bump the version in the process.

Thanks.
