### ISSUE TITLE
Unsupported proxy scheme for https

### ISSUE THREAD

**Issue by kodiakz** [curl/curl#1015]
### I did this
```
$curl https://github.com/rmarquis/pacaur/archive/4.6.9.tar.gz
curl: (7) Unsupported proxy scheme for 'https://xxx.xxx.xxx.xxx:80'

$export | grep https_proxy
https_proxy=https://xxx.xxx.xxx.xxx::80
```

### I expected the following
```
$curl https://github.com/rmarquis/pacaur/archive/4.6.9.tar.gz
<html><body>You are being <a href="https://codeload.github.com/rmarquis/pacaur/tar.gz/4.6.9">redirected</a>.</body></html>

$curl -V
curl 7.50.1 (x86_64-pc-linux-gnu) libcurl/7.50.1 OpenSSL/1.0.2h zlib/1.2.8 libidn/1.33 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

### curl/libcurl version
```
$curl -V
curl 7.50.2 (x86_64-pc-linux-gnu) libcurl/7.50.2 OpenSSL/1.0.2h zlib/1.2.8 libidn/1.33 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

### operating system
```
$lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

**Comment by bagder** [comment]
curl doesn't support HTTPS proxy so you get this message to make you aware of that so that you don't think you're actually are using a HTTPS proxy.

Previously curl would just ignore non-supported schemes in the proxy URL and that mislead people into believing things about what they accomplished. Now, curl will tell you when you try to use a proxy method that curl doesn't support. Like HTTPS.

If you instead specify http:// to the proxy, you'll see that it works (like before) and you don't long rely on curls silent downgrade.

**Comment by kodiakz** [comment]
https_proxy=http://xxx.xxx.xxx.xxx::80 works! Thx...

**Comment by nehaljwani** [comment]
cURL (>=7.52.0) supports HTTPS proxies https://daniel.haxx.se/blog/2016/11/26/https-proxy-with-curl/

**Comment by sponiasmona** [comment]
curl -x  localhost:80  https://github.com/rmarquis/pacaur/archive/4.6.9.tar.gz

**Comment by bagder** [comment]
@sponiasmona if you experience a bug with the latest curl, file a new bug. This is an old and closed report.
