### ISSUE TITLE
In the first 3 calls of `CURLOPT_XFERINFOFUNCTION`, `dltotal` is always equal to `dlnow` and `dltotal` < `content-lenght`

### ISSUE THREAD

**Issue by shithappens2016** [curl/curl#10246]
win10 64bit 
curl 7.87.0
downloading (https://dl.google.com/release2/chrome/hpuakki4r2k5lz4mtx5ai5ciby_108.0.5359.125/108.0.5359.125_chrome_installer.exe)

In the first **_3_** calls of `CURLOPT_XFERINFOFUNCTION`, `dltotal` is always equal to `dlnow` and `dltotal` < `content-lenght`

**Comment by bagder** [comment]
Is this not allowed per the docs?

**Comment by bagder** [comment]
Also, I'm pretty sure that they are not always three, could be more could be less depending on protocol and situation.

**Comment by jay** [comment]
Yup this isn't a bug. From [CURLOPT_XFERINFOFUNCTION](https://curl.se/libcurl/c/CURLOPT_XFERINFOFUNCTION.html):

_"Many times the callback will be called one or more times first, before it knows the data sizes so a program must be made to handle that."_

Also, for HTTP if content length is never provided then dltotal remains 0, though we have some flexibility here since that isn't explicitly documented. I had proposed at one point updating dltotal after a successful chunked transfer or HTTP/2 streaming transfer but it went stale, I forget why.

**Comment by shithappens2016** [comment]
@bagder 
@ jay

May i ask how to determine "it knows the data sizes", although some inelegant approaches can be used to "handle that".

**Comment by jay** [comment]
Evaluate dltotal > 0 for the expected size. Sometimes servers don't provide that size and stream instead. When I download your URL I do see the content length, so the server is providing the size. You are probably seeing dltotal 0 in the progress function before all the headers are parsed.

**Comment by shithappens2016** [comment]
@bagder
@jay 


This is what i got.  `dltotal` not always `0`  "before it knows the data sizes".
![无标题](https://user-images.githubusercontent.com/13523412/211154679-0e26fb49-1730-461c-b4e6-d729fdae6859.png)
