### ISSUE TITLE
Issue when compiling curl version >= 7.50.2 with LibreSSL 2.4.2

### ISSUE THREAD

**Issue by Micdu70** [curl/curl#1035]
### I did this

Installed LibreSSL 2.4.2 in /opt/libressl-2.4, so I wrote:

  `./configure --with-ssl=/opt/libressl-2.4`

then:

  `make`

and I get this issue (curl version >= 7.50.2):

`CCLD     curl`
`../lib/.libs/libcurl.so: undefined reference to 'SSL_get0_alpn_selected'`
`../lib/.libs/libcurl.so: undefined reference to 'SSL_CTX_set_alpn_protos'`

### I expected the following

Curl version 7.50.1 doesn't have this error...

### curl/libcurl version

Successfully compiled curl version 7.50.1
Curl version 7.50.2(+) and git master version = problem explained above...

### operating system
Debian 8 (Jessie) x86_64

**Comment by bagder** [comment]
Please show errors as plain text instead of images to make it easier for people to read your reports. Your screenshot build says your libressl lacks `SSL_get0_alpn_selected` and `SSL_set_alpn_protos`.

But I just built curl from git master with libressl 2.3.2 without any problems and my libressl has both of those versions. Did you do something special that removed ALPN support from your libressl? I wanted to try out the latest libressl here as well just to make sure but libressl git master currently fails to build so it faiedl.

**Comment by Micdu70** [comment]
I found this strange thing...

curl >= 7.50.2 with `./configure --with-ssl=/opt/libressl-2.5` and after unsuccessful`make`:

`ldd ./lib/.libs/libcurl.so`
...
`libssh2.so.1 => /usr/local/lib/libssh2.so.1 (0x00007fd936c8d000)`
`libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fd936a2c000)`
`libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fd936630000)`
...


curl 7.50.1 with `./configure --with-ssl=/opt/libressl-2.5` and after successful `make`:

`ldd ./lib/.libs/libcurl.so`
...
`libssh2.so.1 => /usr/local/lib/libssh2.so.1 (0x00007fd104537000)`
`libssl.so.39 => /opt/libressl-2.5/lib/libssl.so.39 (0x00007fd1042db000)`
`libcrypto.so.38 => /opt/libressl-2.5/lib/libcrypto.so.38 (0x00007fd103ef9000)`
...

Any ideas?

**Comment by bagder** [comment]
There was no change done to configure for openssl/libressl detection between those two versions. I think you should check your config.log for clues as to why it picks up the wrong version because you clearly have more than one version installed. I suppose using libssh2 can mess things up unless you also built that to use the correct libressl version.

**Comment by Micdu70** [comment]
I solved my problem using curl 7.50.1 "configure.ac" file instead. The main difference I see in config.log is (one example):

confi.log (curl 7.50.1):

`gcc -o conftest -O2 -Wno-system-headers  -I/opt/libressl-2.5/include   -L/opt/libressl-2.5/lib  conftest.c -lcrypto  -lssl -lcrypto  -llber -lldap -lz  >&5`

config.log (curl git master):

`gcc -o conftest -O2 -Wno-system-headers   -I/opt/libressl-2.5/include  -L/usr/lib/x86_64-linux-gnu   -L/opt/libressl-2.5/lib  conftest.c -lcrypto  -lssl -lcrypto  -llber -lldap -lz  >&5`

**Comment by bagder** [comment]
You're not helping us fix any problems though. Where did that `-L/usr/lib/x86_64-linux-gnu` come from? `config.log` most likely shows that.

**Comment by bagder** [comment]
My guess is that some other lib has that specified in its pkg-config, possible zlib.

**Comment by Micdu70** [comment]
> Where did that `-L/usr/lib/x86_64-linux-gnu` come from?

It comes after "checking for LDAP libraries" line, not before, in `config.log`.

> My guess is that some other lib has that specified in its pkg-config, possibly zlib.

Yes, that's the point... but it shouldn't interfere the compilation with a custom installation of LibreSSL, no?

**Comment by bagder** [comment]
> It comes after "checking for LDAP libraries" line

The LDAP check comes immediately after the zlib check, so it seems my guess might be right.

> it shouldn't interfere the compilation with a custom installation of LibreSSL, no

Ideally perhaps not, but if a library specifies a specific directory to be required for its build, that directory is then used to detect that library and it is then used further down in the configure script. And in this case, it seems your zlib has that (wrongly?) -L path set.

Try `pkg-config --libs-only-L zlib` and see if it does.

So yes, it *can* be fixed but I don't know of anyone planning to take that on anytime soon.

**Comment by Micdu70** [comment]
`pkg-config --libs-only-L zlib` => `-L/usr/lib/x86_64-linux-gnu`
zlib (1.2.8) comes from official Debian (Jessie) repo.

Okay, thank you for your help.

**Comment by bagder** [comment]
> zlib (1.2.8) comes from official Debian (Jessie) repo

I use zlib on Debian unstable and it doesn't say so! That command line gives a blank response for me.

**Comment by Micdu70** [comment]
I removed and re-installed "zlib1g-dev" package, it gives me `-L/usr/lib/x86_64-linux-gnu` again...

**Comment by bagder** [comment]
This particular problem is now listed in KNOWN_BUGS: https://curl.haxx.se/docs/knownbugs.html#configure_finding_libs_in_wrong

I don't personally have any plans on working on it in the near future.

**Comment by tessus** [comment]
@badger I am a bit puzzled by your statement _I don't personally have any plans on working on it in the near future._

Currently curl only compiles, if used with SSL provided by the system. I have tried to get it working with my own OpenSSL libraries (which include the package config files), but to no avail.

Your statement negates all configure options that allow you to use a different SSL flavor. It is not possible to use curl with your own openssl version.

The reason is that the compile process uses the system include files and system libraries for SSL, no matter what you specify in the configure script. This means the configure script is broken.

In that case you can remove all ssl options from your configure script, since nothing you do will change the fact that it only takes the system libraries.

**Comment by bagder** [comment]
That statement is incorrect. I build curl frequently with different SSL libraries installed in custom directories. It works great. My comment above refers to a specific flaw in the script. Additionally: anyone is free to work on this. I'm not stopping anyone.

**Comment by tessus** [comment]
@badger I'm sorry, if my comment sounded harsh. It was not my intention.

I've had serious problems and still can't get curl built with my own openssl version.
I've been searching for solutions, but only found numerous reports that were of no help.

If you were able to actually do what I've been trying to do, something else must be amiss. I'll open a new ticket on the weekend and provide a detailed problem description.

Unfortunatelty I'm quite busy with other projects right now, which makes it impossible to solve this issue by my own.

**Comment by bagder** [comment]
I build curl with a custom OpenSSL version *daily* with no problems. I suggest you either file an issue or just take your problem to the curl-library mailing list.
