### ISSUE TITLE
Setting CURLSSLOPT_NATIVE_CA for windows causes only the first cert in the chain to be valid for selfsigned CAs

### ISSUE THREAD

**Issue by danyhm** [curl/curl#10396]
### I did this
Hello,

Setting CURLSSLOPT_NATIVE_CA in `curl_easy_setopt(curl_easy_init(), CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);` causes only the first (the CA itself) to be valid for CURL, the rest of the chain including Intermediate and end-user certificates will not be valid and would cause a `code 35 , SSL connect error`
### I expected the following
all certificates signed by the custom selfsigned CA should be accepted
### curl/libcurl version
7.86.0

### operating system

windows 10 enterprise x64 build 19045.2364

### to reproduce
1 -create a selfsigned certificate CA. I'm using  `https://certificatetools.com/` here

2- now create another certificate with the webserver TSL authenticating key usage set and sign it with the CA created at step 1 and make sure it includes the domain name in the DNS and common name

3- add the CA to windows trust store.

4- use curl issue a request to the server which is providing cert in step 2 for it's negotiations.

5- get error 35

the above is not produced if the CA itself is provided by the webserver and the correct DNS names and common names are set.

also I've not tested this , but setting a custom CA with a path to cert might also produce this issue.

**Comment by jay** [comment]
Native CA store reads only from the CA root store, ie "Trusted Root Certification Authorities". It does not read from the intermediate or other stores. I did test this feature with a self signed certificate in the root store. It's possible that based on constraints or other attributes that libcurl skips importing the certificate.

Use [CURLOPT_VERBOSE](https://curl.se/libcurl/c/CURLOPT_VERBOSE.html) to see if the certificate is found and imported or skipped.  You should see
~~~
* SSL: Checking cert "yourcert"
* SSL: Imported cert "yourcert"
~~~
The first line means your cert was found in the root store, the second line means libcurl will use it for verification.

**Comment by danyhm** [comment]
thanks for taking the time.

i've created a sample server and certificate just for this issue

certificates:
[certs.zip](https://github.com/curl/curl/files/10567543/certs.zip)

example URL using the certificate : https://examplecurl.ignorelist.com:5001/api/v1/client/1/1

if you try to issue any post or get method to the URL , Curl will return a code 35 error on windows.
the CA certificate is added to "Trusted Root Certification Authorities" and the domain certificate is signed by the CA.

**Comment by danyhm** [comment]
could you reproduce the problem?

**Comment by jay** [comment]
> could you reproduce the problem?

Yes but I think there is a certificate problem and not a libcurl problem.

First off note that libcurl does not import certificates from the Windows root store that are missing Certificate Signing (aka OpenSSL keyCertSign) in the Key Usage:

https://github.com/curl/curl/blob/c12fb3ddaf48e709a7a4deaa55ec485e4df163ee/lib/vtls/openssl.c#L3154-L3160

I tested and libcurl is behaving as expected:

- If certDomain.crt (your server cert) is added to the root store then it is skipped and not imported by libcurl.
- If CA.crt (which signed certDomain.crt) is added to the root store then it is imported (X509_STORE_add_cert) by libcurl.

Yet even with that CA imported OpenSSL peer verification fails: with  and sends a :
- CA.crt in the root store
- Server with certDomain.crt/key
- Client libcurl w/ OpenSSL and CURLSSLOPT_NATIVE_CA set
- libcurl (openssl) error `unable to get local issuer certificate`
- libcurl (openssl) sends TLS alert `unknown ca` to the server

I can reproduce with just OpenSSL:
~~~
> openssl version -a
OpenSSL 1.1.1s  1 Nov 2022

> openssl verify -CAfile CA.crt CA.crt certDomain.crt
CA.crt: OK
CN = examplecurl.ignorelist.com, C = NL, ST = Flevoland, L = Dronten, O = curl example
error 20 at 0 depth lookup: unable to get local issuer certificate
error certDomain.crt: verification failed
~~~

An older version of OpenSSL will verify it successfully:
~~~
> openssl version -a
OpenSSL 1.0.2n  7 Dec 2017

> openssl verify -CAfile CA.crt CA.crt certDomain.crt
CA.crt: OK
certDomain.crt: OK
~~~

Since recent versions of OpenSSL fail verification maybe there is a problem with the way your server certificate is signed. Just to be sure this wasn't something on my end I created my own CA and signed server cert and it worked fine with that CA in the root store.

<details>
  <summary>Click to expand command used to create openssl-blank.cnf</summary>

~~~
echo [req]> openssl-blank.cnf
echo distinguished_name=dn>> openssl-blank.cnf
echo [ dn ]>> openssl-blank.cnf
~~~
</details>

<details>
  <summary>Click to expand command used to create test_ca.crt</summary>

~~~
openssl req ^
-config openssl-blank.cnf ^
-nodes ^
-subj "/C=US/O=Test CA/OU=Test CA/CN=Test CA" ^
-addext "subjectKeyIdentifier = hash" ^
-addext "authorityKeyIdentifier= keyid:always" ^
-addext basicConstraints=critical,CA:TRUE ^
-addext "keyUsage = critical,digitalSignature, cRLSign, keyCertSign" ^
-new ^
-x509 ^
-keyout test_ca.key ^
-out test_ca.crt ^
-sha256 ^
-days 3650 ^
-newkey rsa:4096

type test_ca.key > test_ca.pem
type test_ca.crt >> test_ca.pem
~~~
</details>

<details>
  <summary>Click to expand command used to create test_srv.crt</summary>

~~~
openssl req ^
-config openssl-blank.cnf ^
-nodes ^
-subj "/CN=*.test.com" ^
-addext "subjectAltName=DNS:test.com,DNS:*.test.com" ^
-addext "extendedKeyUsage = serverAuth, clientAuth" ^
-addext "keyUsage = critical,digitalSignature, keyEncipherment" ^
-addext basicConstraints=critical,CA:FALSE ^
-new ^
-x509 ^
-keyout test_srv.key ^
-out test_srv.crt ^
-sha256 ^
-days 3650 ^
-newkey rsa:4096

type test_srv.key > test_srv.pem
type test_srv.crt >> test_srv.pem
~~~
</details>

<details>
  <summary>Click to expand command used to create test_srv_signed.crt</summary>

~~~
openssl x509 ^
-set_serial 01 ^
-in test_srv.crt ^
-out test_srv_signed.crt ^
-CA test_ca.crt ^
-CAkey test_ca.key ^
-days 3650
cat test_srv.key test_srv_signed.crt > test_srv_signed.pem
~~~
</details>

---

_A few more things, everything below just for my notes so I don't forget:_


<details>
  <summary>In Windows it's possible to disallow user trusted CAs via group policy. (I don't have this enabled but it's worth remembering for troubleshooting.)</summary>

> Open Group Policy editor (gpedit.msc).
> 
> Under Per user certificate stores, clear the Allow user trusted root CAs to be used to validate certificates and Allow users to trust peer trust certificates check boxes.
> 
> In the console tree, go to Local Computer Policy, Computer Configuration, Windows Settings, Security Settings, and then click Public Key Policies. 
> 
> Double-click Certificate Path Validation Settings, and then click the Stores tab.
> 
> Select the Define these policy settings check box.
> 
> Under Per user certificate stores, clear the Allow user trusted root CAs to be used to validate certificates and Allow users to trust peer trust certificates check boxes.
> 
> Under Root certificate stores, select the root CAs that the client computers can trust, and then click OK to apply the new settings.

</details>

libcurl (openssl) can import test_srv / test_srv_signed from ms root store and verify successfully, but only if CERT_KEY_CERT_SIGN_KEY_USAGE check is commented out. If CERT_KEY_CERT_SIGN_KEY_USAGE is not commented out then the certificate is skipped and it would have to be passed to OpenSSL via CURLOPT_CAINFO for successful verification.

test_srv (unsigned) once imported shows in user's `Internet Properties > Content > Certificates > Trusted Root Certification Authorities` and `certmgr.msc > Trusted Root Certification Authorities > Certificates`.
test_srv_signed does not show in the former but does in the latter, probably because the issuer is different since it's a signed cert.

openssl verify -CAfile test_ca.crt test_ca.crt test_srv_signed.crt
(Verifies successfully in both 1.0.2 and 1.1.1)

**Comment by danyhm** [comment]
Thanks for your thorough explanation. i suppose my certificate generation is missing some essential parameters.
