### ISSUE TITLE
imaps connection fails with error in rustls_connection_read

### ISSUE THREAD

**Issue by fchandur** [curl/curl#10457]
### I did this
$ ./curl --trace log.txt --cacert /etc/ssl/certs/ca-certificates.crt imaps://imap.gmail.com
curl: (26) error in rustls_connection_read: 7010
### I expected the following
connection to succeed

### curl/libcurl version
$ ./curl --version
curl 7.87.1-DEV (x86_64-unknown-linux-gnu) libcurl/7.87.1-DEV rustls-ffi/0.9.2-alpha1/rustls/0.20.7 zlib/1.2.11 libssh2/1.9.0_DEV
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz SSL threadsafe UnixSockets

### operating system
Linux winxps 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### trace

== Info:   Trying 142.250.123.108:993...
== Info: Connected to imap.gmail.com (142.250.123.108) port 993 (#0)
== Info: rustls_connection wants us to write_tls.
== Info: Curl_socket_check: reading would block
== Info: rustls_connection wants us to read_tls.
== Info: Done handshaking
== Info: ALPN: server did not agree on a protocol. Uses default.
== Info: error in rustls_connection_read: 7010
== Info: Closing connection 0

**Comment by bagder** [comment]
Does it work against the same server if you use another TLS backend?

**Comment by fchandur** [comment]
AFICT, yes.

**Comment by jsha** [comment]
Thanks for trying curl with rustls, and thanks for the report! Error 7010 from rustls-ffi is "UnexpectedEof" (TODO: get better output for this error message).

Rustls will emit UnexpectedEof if the TCP connection is closed without first receiving, in the TLS session, a "close_notify" alert. This is technically what you're supposed to do in TLS, since it avoids a type of bug where an attacker causes the TCP connection to close, causing the application (in this case curl) to think it's got a whole response when it's only get N bytes. For instance, in an HTTP/1.1 response with no Content-Length header, and no Transfer-Encoding, the application assumes the response is "close-delimited" and might be tricked into accepting a partial response if the TLS library isn't strict about this.

However, it's sometimes acceptable to allow the TCP connection to close without doing a proper shutdown of the TLS session, depending on how the application protocol works. For instance, maybe in IMAP there are no close-delimited messages?

In any case, I suspect what is happening here is that `imap.gmail.com` is closing a connection without sending a TLS "close_notify", though I still need to check that.

**Comment by jsha** [comment]
I've opened https://github.com/curl/curl/pull/10463 to improve the error messages somewhat, and confirmed that Google's HTTPS servers exhibit the same behavior we see here for IMAPS: the TCP connection is reliably closed without sending `close_notify`.

You can see an example by forcing HTTP/1.0:

```
$ ./src/curl https://www.google.com/ -0 >/dev/null
...
curl: (26) rustls: peer closed TCP connection without first closing TLS connection
```

(this uses the better error from my PR)

I think for HTTP/1.0, the current behavior is okay. It's slightly stricter than the OpenSSL backend, but in a good way. It's unlikely to cause significant compatibility issues because most HTTP servers use one of Content-Length, Transfer-Encoding: chunked, or HTTP/2.

For other protocols it is probably suitable to provide a way for the application layer (IMAP in this case) to learn about the unclean TCP close and decide to ignore it if the protocol is not transferring a response, or if all messages are length-delimited. This probably requires introducing a new curl error code to pass the information, for instance `CURLE_SSL_UNCLEAN_SHUTDOWN` or `CURLE_SSL_UNEXPECTED_EOF`. Right now rustls just returns `CURLE_READ_ERROR` in this case. @bagder what do you think of this approach?

**Comment by bagder** [comment]
> what do you think of this approach?

I don't think introducing a new error code solves anything for this. Users are either expecting curl to not return an error or returning "read error" is probably fine. The judgement call and trick is rather when and how to act on the missing close_notify from TLS - and to do it in a consistent way in curl for different TLS backends.

**Comment by jsha** [comment]
I agree a user-facing error doesn't solve anything. I was thinking an internal error that would be emitted by TLS backends and handled by the higher protocol layer - either turning it into a "read error" for the user, or turning into a clean close if that is appropriate based on the protocol.

The problem is that the TLS backends send errors to the higher protocol layers using the same error codes as the user-facing ones. But we could allocate an error code just for internal use, and not expose it to the user.

**Comment by nevakrien** [comment]
Is it okay if I put some work into fixing this issue?

I saw it listed in the "KNOWN_BUGS" file and I'm fairly passionate about making Rust work well. so I’d really like to help get this working.

This would be my first pull request so it will likely take a while.

**Comment by bagder** [comment]
> Is it okay if I put some work into fixing this issue?

Of course! We love getting help to improve curl. Just ask if there's anything we can help you with along the way.

I would recommend you do it roughly like this:

1. fork the curl repo on GitHub, clone that and get a curl build (with rustls) running.
2. try to reproduce the bug you want to work on using your build
3. edit code, rebuild, iterate until it seems to work
4. make a local branch with the fix
5. submit a PR against the curl/curl repository
6. for the red CI builds, fix them and push more commits to your branch until all CI jobs are green
7. ask for a review when you feel content

**Comment by nevakrien** [comment]
so bug no longer reproduces the same I ran it on both the rustls and the regular version and in both cases i got 
curl: (21) Quote command returned error

the fork was made a few hours ago so the code there is the current version and my system level curl is curl 8.5.0 

I am on ubuntu 2024 tls 

now it could be the original issue is windows specific in which case I can try and reproduce it on windows 10 or windows 11 (i have a laptop with each one) but it could be that I am missing a detail about reproduction which is crucial here. 

does this require gmail have my SSH key? like is there anything here which would be enviorment specific? 
also are the logs safe to share? like idk if they might have info relating to my SSH keys and i would really prefer not to leak those

**Comment by bagder** [comment]
> in both cases i got curl: (21) Quote command returned error

That sounds like a completely different problem, and a surprising one since you didn't use any quote commands.

But maybe the TLS handshake succeeded then?

> my system level curl is curl 8.5.0

If you build from master (and run that) your system curl does not matter anymore.

> does this require gmail have my SSH key?

If you intend to successfully download email from gmail as the original command line tried, then I presume you need a gmail account etc with everything that may entail (I don't think we particularly know more about that than anyone else). But the curl command itself doesn't use SSH and thus of course does not require SSH key anywhere.

**Comment by nevakrien** [comment]
welll so I have a gmail acount but not really sure how to link it to my OS so that it can be used by curl...
seems that  curl managed to connect to gmail. which was the original bug this request was talking about

```
== Info: Host imap.gmail.com:993 was resolved.
== Info: IPv6: 2a00:1450:400c:c0d::6c, 2a00:1450:400c:c0d::6d
== Info: IPv4: 64.233.167.108, 64.233.167.109
== Info:   Trying [2a00:1450:400c:c0d::6c]:993...
== Info: ALPN: server did not agree on a protocol. Uses default.
== Info: rustls: handshake complete, TLSv1.3, cipher: TLS_AES_256_GCM_SHA384
== Info: Connected to imap.gmail.com (2a00:1450:400c:c0d::6c) port 993
== Info: IMAP 0x58090d62c630 state change from STOP to SERVERGREET
== Info: pp_statematch, timeout=120000
== Info: pp_statematch, timeout=120000
== Info: pp_statematch, timeout=119899
<= Recv header, 94 bytes (0x5e)
0000: 2a 20 4f 4b 20 47 69 6d 61 70 20 72 65 61 64 79 * OK Gimap ready
0010: 20 66 6f 72 20 72 65 71 75 65 73 74 73 20 66 72  for requests fr
0020: 6f 6d 20 32 61 30 36 3a 63 37 30 31 3a 39 64 36 om 2a06:c701:9d6
0030: 38 3a 32 65 30 30 3a 31 66 61 64 3a 36 63 65 31 8:2e00:1fad:6ce1
0040: 3a 31 62 66 31 3a 33 32 38 30 20 71 31 31 6d 62 :1bf1:3280 q11mb
0050: 31 30 37 34 31 37 33 34 38 77 72 6d 0d 0a       107417348wrm..
```

I took the liberty to double check with the openssl build as well. the error is the same in both but the logs differ a lot. 

they both have the  BAD Unknown


rustls:
```
0000: 41 30 30 32 20 42 41 44 20 55 6e 6b 6e 6f 77 6e A002 BAD Unknown
0010: 20 63 6f 6d 6d 61 6e 64 20 66 31 6d 62 31 30 37  command f1mb107
0020: 34 36 31 34 30 31 77 72 6d 0d 0a                461401wrm..
== Info: DO phase failed
== Info: shutting down connection #0
```

openssl:
```
0000: 41 30 30 32 20 42 41 44 20 55 6e 6b 6e 6f 77 6e A002 BAD Unknown
0010: 20 63 6f 6d 6d 61 6e 64 20 68 36 6d 62 31 31 33  command h6mb113
0020: 31 34 38 30 35 32 77 6d 71 0d 0a                148052wmq..
== Info: shutting down connection #0
```


I think this means that the original instructions to reproduce the bug with the rustls version are no longer relvant.
there is a separate issue here that's relvant to both AND the tls issue is no longer present.
so we might wana mark the known-bug as resolved and open a separate issue for this new weird behavior.

or alternatively we can try and find a different website where that issue arises (perhaps making a small locals server?) and then compare against that.

[fchandur](https://github.com/fchandur) can you elaborate on how to reproduce this bug?
