### ISSUE TITLE
-C - updates ctime no matter what

### ISSUE THREAD

**Issue by jidanni** [curl/curl#10504]
[--continue-at -](https://stackoverflow.com/questions/11856351/how-to-skip-already-existing-files-when-downloading-with-curl/47226987#47226987), alas, even if all the bytes are already there, still messes with the inode, updating the ctime of the file (ls -ltc) on Linux. Why can't it be more conservative?

And indeed I wouldn't need it, if there were a type of residue-free --no-clobber that worked just like the shell's test -f, or test -s.

And indeed didn't need to connect to the server at all.

Linux 6.1.0-4-amd64 curl 7.87.0

**Comment by bagder** [comment]
I'm sure it can be improved. Feel free to jump in and give it a shot.

**Comment by jidanni** [comment]
Well I can specifically help with the documentation, at least.

Here we are implementing these two UNIX test(1)s:

- -e FILE
- - FILE exists
- -s FILE
- - FILE exists and has a size greater than zero

So the new curl switches would be (names approximate):
- --dont-fetch-if-file-exists
- - Curl checks if the destination already exists and skips this file if so.

- --dont-fetch-if-file-greater-than-zero
- - Curl checks if the destination already exists and is not an empty file, and skips this file if so.

**Comment by bagder** [comment]
I thought this report was about how `--continue-at -` could be improved, not inventing new option names.

**Comment by jidanni** [comment]
Actually my two new feature suggestions could be implemented as options to -C: -C -0 for the zero byte check, -C -1 for the existence only check.

But that would only gum things up further.

Anyway, you are certainly doing something like opening the file for writing before you even know you need to write it.

Anyway I'm saying here's a way to not even try to connect over the network before you know you really need to.

**Comment by Smackd0wn** [comment]
> Anyway I'm saying here's a way to not even try to connect over the network before you know you really need to.

With `-C`, curl can't know if a file is incomplete (i.e., local file size is <, = or > remote file size) before it connects over the network.

True, it may be preferable for curl not to update ctime when the size matches (like when the server responds with HTTP 416 "Requested Range Not Satisfiable" because you're requesting a range past the end of file). But it is also possible that the local file (even when it exists and size > 0) is shorter than remote, and thus with `-C -` (or `-C <explicit offset>` for that matter) curl still need to fetch some data and append to the file.

**Comment by bagder** [comment]
This is not a bug as no docs claims the cmtime will be untouched for this case. If someone wants to work on improving how curl behaves, such work would of course be welcome.
