### ISSUE TITLE
Inconsistent behaviour of --fail switch with multiple files

### ISSUE THREAD

**Issue by DawidJanczak** [curl/curl#1054]
### I did this
Run `curl -f http://www.google.com http://nonexisting.domain` and `curl -f http://nonexisting.domain http://www.google.com`

### I expected the following
I expect both of these to fail, however only the first one does. It seems like it fails only if the last URL is unreachable.
Before I try fixing this I'd like to get some input as to whether it's a bug at all or is this expected for some reason.

### curl/libcurl version
curl 7.50.3 (x86_64-pc-linux-gnu) libcurl/7.50.3 OpenSSL/1.0.2f zlib/1.2.8 libidn/1.33 libssh2/1.7.0

[curl -V output perhaps?]
above

### operating system
4.7.4-1-ARCH x86_64 GNU/Linux (Arch Linux)

**Comment by bagder** [comment]
> I try fixing this

So what do you suggest is the correct way to handle this? From what I can tell, this is just a matter of preference so I think we should instead make sure that this is documented clearly so that users won't be surprised.

**Comment by DawidJanczak** [comment]
Personally I don't think order of arguments should change the behaviour, I would have assumed it to fail regardless of it. This would make `cron` incredibly helpful for certain tasks, e.g. "are all of the following URLs reachable?" This is of course still possible by invoking `curl` multiple times, but in that case the connection will not be reused (assuming all of the URLs are on the same server). If you disagree then feel free to close this, but yes, a change in documentation would be nice.

**Comment by bagder** [comment]
When doing multiple transfers, you'll basically only get the return code from the last one you did on the command line since it will perform the second transfer even if the first one failed and if the second succeeds it'll return 0 for that one. So order certainly does matter. This should probably be made clearer in the documentation.

What hear you asking is that it should stop and return failure on the first fail. That sounds like new behavior that we could do with a new option like `--fail-first` or similar.

**Comment by DawidJanczak** [comment]
Yes, in fact after I noticed this behaviour the first thing I did was look for `--fail-fast` option on the manpage. It would be great to have that.

**Comment by bagder** [comment]
Thanks. Now listed as [a TODO item](https://curl.haxx.se/docs/todo.html#Introduce_fail_fast_to_exit_on)

**Comment by bagder** [comment]
As such, I'll close this issue and hope that someone picks it up soon...
