### ISSUE TITLE
Bug again

### ISSUE THREAD

**Issue by ghost** [curl/curl#10802]
### I did this
As promised, one bug per version. I have a long list.
Read the manual. List of «EXIT CODES» (or «error codes»?).
Numbers from 0 to 99, all positive.
### I expected the following
List will be truthful, but:
```
C:\Глюк, а не программа\curl-8.0.1_1-win64-mingw\bin>curl.exe -V

C:\Глюк, а не программа\curl-8.0.1_1-win64-mingw\bin>Echo %ErrorLevel%
-1073741571
```

P.S.  Секрет заключается в содержании одного из служебных файлов cURL (упомянутых в документации), но почему я должен искать ошибки ЗА ВАС?  Догадайтесь, что за файл и что за содержание, а пока:
fix the manual, please.
### curl/libcurl version
8.0.1_1
[curl -V output]
-1073741571
### operating system
MS Windows 10

**Comment by jay** [comment]
Ref: curl/curl-for-win#43

-1073741571 == c00000fd. That's an error code from the OS and not curl. For our purposes it usually means curl could not be started because a DLL is missing or architecture mismatch. The [official curl.exe for Windows](https://curl.se/windows/) (what you seem to be using) has 3rd party dependencies built in (ie no DLLs) so let's assume you are missing some OS DLL, probably the Universal CRT which is required.

> P.S. Секрет заключается в содержании одного из служебных файлов cURL (упомянутых в документации), но почему я должен искать ошибки ЗА ВАС? Догадайтесь, что за файл и что за содержание, а пока:
fix the manual, please.

Please report in English. It seems as if you are implying you knew the cause of the error but purposely withheld it from the bug report.
