### ISSUE TITLE
The json data is not encoded as `UTF-8` default

### ISSUE THREAD

**Issue by liudonghua123** [curl/curl#10820]
### I did this

I try to execute the following command.

```
C:\ProgramData\chocolatey\bin\curl.exe --request POST --url "http://my-api-server/xxx" --header "content-type: application/json" --data "{\"cn\" : \"张三\"}"
```

The server could not decode the data passed, I also tried to execute the same command on linux, it's ok.

And I use wireshark to inspect the network traffic, and I found the data is encoded as `GBK` instead of `UTF-8`.

If I checked `Beta: Use Unicode UTF-8 for worldwide language support.` in Region control settings, then it works again.

![image](https://user-images.githubusercontent.com/2276718/227071658-2c25848f-fd69-444a-a95b-0e77cc2f5437.png)

I also tried execute `chcp 65001` before the mentioned command, but it's the same problem.

### I expected the following

I expected the data to be encoded as `UTF-8` default.

### curl/libcurl version

```
C:\Users\Liu.D.H>C:\ProgramData\chocolatey\bin\curl.exe --version
curl 8.0.1 (x86_64-w64-mingw32) libcurl/8.0.1 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.9.0 libgsasl/2.2.0
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd

C:\Users\Liu.D.H>
```

### operating system

`Microsoft Windows [Version 10.0.22621.1413]`

**Comment by dfandrich** [comment]
> I expected the data to be encoded as UTF-8 default.

Why did you expect this? Did the documentation say so?

**Comment by liudonghua123** [comment]
> I expected the data to be encoded as UTF-8 default.
> Why did you expect this? Did the documentation say so?

I did not find any documentation about the default encoding currently. However, `UTF-8` encoding/decoding is used widely and recommended in web in my opinion.

**Comment by dfandrich** [comment]
curl generally leaves data alone without doing any conversions. But, Windows does some odd things in this regard because of its history of not supporting standards like UTF-8, but I'll let someone who knows the details respond.

**Comment by vszakats** [comment]
Yeah, as for the request part, it's a known issue (not only for curl, but for all Windows apps). On Windows the notion of "just don't touch strings" method doesn't work, because the Win32 API traditionally offered one 8-bit API flavour without UTF-8 or Unicode support (they call this "ANSI") and another flavour which is Unicode aware, but requires codepage translation because it talks UTF-16 (called "WIDE"). For this translation, we'd need to know what to translate to/from and when. Knowing this is sometimes possible, sometimes not, and sometimes needs a spec overhaul and/or introducing a way to specify the source/target codepage manually.

The command-line curl receives is in an 8-bit (non-UTF-8!) codepage, as set via the global setting for non-Unicode apps. In this case "Chineses (Simplified, China)", and sends these bytes as-is to the server.

On newer Windows the escape hatch is the setting shown by OP (thanks for the screenshot!), by enabling UTF-8 support for the 8-bit "ANSI" API. The generic workaround is to use a file or stdin to pass the request.

For the response part it is a different problem. Here, curl is just saving/returning whatever bytes were returned from the server.

Discussion: https://github.com/curl/curl/discussions/10446

**Comment by jay** [comment]
Note Windows' ANSI API can use DBCS (double byte) characters for some codepages, like Chinese, and is not the same as the ANSI standard.

**Comment by bagder** [comment]
Several unicode on Windows issues are now mention in KNOWN_BUGS.
