### ISSUE TITLE
Documentation building hints on openssl location looks incorrect

### ISSUE THREAD

**Issue by alphons** [curl/curl#10828]
From: [https://curl.se/docs/install.html](https://curl.se/docs/install.html)
If you have OpenSSL installed, but with the libraries in one place and the header files somewhere else,
you have to set the LDFLAGS and CPPFLAGS environment variables prior to running configure. 
Something like this should work:
```
CPPFLAGS="-I/path/to/ssl/include" LDFLAGS="-L/path/to/ssl/lib" ./configure
```
It does NOT work ;-) CPPFLAGS must be **CFLAGS** , when using opensll location
This configure line works when openssl installed in /usr/local
```
CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" ./configure --prefix=/usr/local --with-openssl
```
BTW, why does the configure script not look into one of the default locations '/usr' and '/usr/local' for openssl ?

cheers

**Comment by bagder** [comment]
> BTW, why does the configure script not look into one of the default locations '/usr' and '/usr/local' for openssl ?

Because that has traditionally **not** been the default location path for OpenSSL. Is it now?

**Comment by jay** [comment]
> It does NOT work ;-) CPPFLAGS must be **CFLAGS** , when using opensll location

When you say it doesn't work what do you see in config.log? Is it possible that you have more than one OpenSSL include directory being included and that's why it doesn't work? It should work with CPPFLAGS. If it only works with CFLAGS then maybe it has something to do with the ordering of directories when both variables are used to compile C files.

Also, if you have a pkg-config file curl should use that. See https://github.com/curl/curl/blob/curl-8_0_1/m4/curl-openssl.m4
