### ISSUE TITLE
libcurl dont free memory after curl_easy_cleanup with ssl

### ISSUE THREAD

**Issue by anonbeat** [curl/curl#1086]
I ran the program from examples multithreads.c with 41 urls all https and the memory used was around 800M
I expected that after every call to the curl_easy_cleanup the memory used by that thread was free so at the end of the program and before calling curl_global_cleanup the memory used will be to near 0

I am using ubuntu 16.04 with libcurl 7.47

curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

This is the code I used and checked memory used in every keypress wait

compiled with 

`gcc multithread.c -o multithread 'pkg-config --cflags --libs libcurl' -lpthread -O2`

and run it with

`./multithread >/dev/null`

```
/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) 1998 - 2015, Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.haxx.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ***************************************************************************/
/* <DESC>
 * A multi-threaded example that uses pthreads to fetch several files at once
 * </DESC>
 */

#include <stdio.h>
#include <pthread.h>
#include <curl/curl.h>

#define NUMT 41

/*
  List of URLs to fetch.

  If you intend to use a SSL-based protocol here you MUST setup the OpenSSL
  callback functions as described here:

  https://www.openssl.org/docs/crypto/threads.html#DESCRIPTION

*/
const char * const urls[ NUMT ]= {
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/2995065b3f554a1bca444c29c0fb8530.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/174s/89e3eba4f1364816b86632248b7822c9.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/5d3e2c10541441d8c174e5568f109b3c.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/174s/c7b0885750f94e46a36fa41ed10691ec.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/dd70b650e5cd479bc7078ade2420e2d6.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/174s/5c84b957396c4cbdb61f22b92fc71558.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/a0ece142922e4750a065e2304043c681.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/174s/7a08394b697945b9bfa795dfeed46921.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/5d2211dbc3aa40e28e28dd2814bd318a.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c7b0885750f94e46a36fa41ed10691ec.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/666831aed9367cc366140dd2ffc0169e.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/174s/df3a1356b08e464ca51b1aa292a5c38a.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/a5943f15da8880f426be5f0e8d815b2c.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/02c05615600743628eca3bd9df4c8a4c.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/89e3eba4f1364816b86632248b7822c9.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/174s/407413a4bb614f1db08f1110a604f5df.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/1c27be1170c04612c6b40362bb2ca60b.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/29b50a52515d422abeafc3c01b3e2fab.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/174s/db766dc7b43d4aedb6a9fbea33980e71.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/ce627d7cda714050c0e68b02defcd7d5.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c42b09eb599449639cdf0201ac80c5c9.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/14737855b0474575c53f259f39cd22ad.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/d443f85ebdb24bf8cba7be75cc9cb0e2.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/b3061e8a3d2043ebc34a2a8c427a4e6f.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/0254a8a3201a42ad95ffa6f64ec3fa3b.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/c0abe2b16b6c49c3a240af8af1457983.png",
	"https://lastfm-img2.akamaized.net/i/u/300x300/89e3eba4f1364816b86632248b7822c9.png"
};

static void * pull_one_url( void * url )
{
  CURL * curl;

  curl = curl_easy_init();
  curl_easy_setopt( curl, CURLOPT_URL, url );
  curl_easy_perform( curl ); /* ignores error */
  curl_easy_cleanup( curl );

  return NULL;
}


/*
   int pthread_create(pthread_t *new_thread_ID,
   const pthread_attr_t *attr,
   void * (*start_func)(void *), void *arg);
*/

int main(int argc, char **argv)
{
	pthread_t tid[ NUMT ];
	int index;
	int error;

	/* Must initialize libcurl before any threads are started */
	curl_global_init( CURL_GLOBAL_ALL );

	for( index = 0; index < NUMT; index++ ) 
	{
		error = pthread_create( &tid[ index ],
		                       	NULL, 				/* default attributes please */
		                        pull_one_url,
		                        ( void * ) urls[ index ] );
		if( error != 0 )
		{
		  fprintf( stderr, "Couldn't run thread number %d, errno %d\n", index, error );
		}
		else
		{
		  fprintf( stderr, "Thread %d, gets '%s'\n", index, urls[ index ] );
		}
	}

	/* now wait for all threads to terminate */
	for( index = 0; index < NUMT; index++ ) 
	{
		error = pthread_join( tid[ index ], NULL );
		fprintf( stderr, "Thread %d terminated\n", index );
	}

	fprintf( stderr, "Press any key to close app...\n" );
	getchar();	

	curl_global_cleanup();

	fprintf( stderr, "Press any key to close app...\n" );
	getchar();

	return 0;
}

```

**Comment by bagder** [comment]
So can you show us a valgrind output from the leak? Are you saying that it doesn't leak if you don't use (many) threads?

**Comment by bagder** [comment]
I just tried the `multithread.c` example with my libcurl from git built against gnutls:

    libcurl/7.51.0-DEV GnuTLS/3.5.5 zlib/1.2.8 c-ares/1.12.0 libidn/1.33 libpsl/0.14.0 (+libicu/57.1) libssh2/1.7.0 nghttp2/1.15.0 librtmp/2.3

... and valgrind tells me there's no leaks.

**Comment by anonbeat** [comment]
What Im saying is that after ending all threads the memoy used is too high...
![screenshot_2016-10-25_22-23-12](https://cloud.githubusercontent.com/assets/724089/19704907/b0157176-9b01-11e6-9883-b4bb7763d219.png)

**Comment by bagder** [comment]
So change your example and use it within HTTPS and you can see how much is GnuTLS' fault and how much is libcurl's. But since it doesn't leak any of the memory, the allocations are made on purpose and thus not a bug.

In libcurl's case, you can't do much to limit its memory allocations. They will be in the few 100K per handle at the most, and libcurl will keep connection around after use so also the number of connections in the connection cache will matter.

**Comment by anonbeat** [comment]
shouldn't be freed once I call curl_easy_cleanup?

**Comment by bagder** [comment]
Ah yes, when using the easy interface libcurl won't keep anything around after you call `curl_easy_cleanup` on the handle. I can only presume the memory use you see is either just your tool reporting weirdly, you not reading the numbers right or GnuTLS holding on to something.

**Comment by anonbeat** [comment]
can you do that test please? see memory used once all threads are done and its waiting for keypress or even after call curl_global_cleanup (2nd keypress wait)

**Comment by bagder** [comment]
I don't really see the point. I don't see a curl bug or problem here and I know that may sound very blunt but for the curl issue tracker that is sort of the main thing to care about.

**Comment by anonbeat** [comment]
the point is that after calling curl_easy_cleanup or even curl_global_cleanup the memory used is too high... that is the point

**Comment by bagder** [comment]
You haven't clarified exactly what "the memory used" means. How exactly are you measuring? libcurl doesn't leak any memory for this setup in our general tests and in my specific tests in a similar case such as yours: so I don't think this is a libcurl problem.

You may still have a problem to solve, sure, I'm just insisting that the problem most probably not curl's fault. Possibly GnuTLS', possibly wrong data.

**Comment by anonbeat** [comment]
Im using cat status at the pid folder in /proc 

```
BEFORE CREATE THREADS...

Name:	multithread
State:	S (sleeping)
Tgid:	32265
Ngid:	0
Pid:	32265
PPid:	8551
TracerPid:	0
Uid:	1000	1000	1000	1000
Gid:	1000	1000	1000	1000
FDSize:	256
Groups:	4 20 24 27 30 46 109 125 128 138 1000 
NStgid:	32265
NSpid:	32265
NSpgid:	32265
NSsid:	8551
VmPeak:	   83140 kB
VmSize:	   83080 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	    3796 kB
VmRSS:	    3700 kB
VmData:	     488 kB
VmStk:	     136 kB
VmExe:	       8 kB
VmLib:	   10336 kB
VmPTE:	     172 kB
VmPMD:	      12 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
Threads:	1
SigQ:	0/63857
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	0000000180000000
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
Seccomp:	0
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	1
nonvoluntary_ctxt_switches:	1


CREATED THREADS

Name:	multithread
State:	S (sleeping)
Tgid:	32265
Ngid:	0
Pid:	32265
PPid:	8551
TracerPid:	0
Uid:	1000	1000	1000	1000
Gid:	1000	1000	1000	1000
FDSize:	256
Groups:	4 20 24 27 30 46 109 125 128 138 1000 
NStgid:	32265
NSpid:	32265
NSpgid:	32265
NSsid:	8551
VmPeak:	 4890308 kB
VmSize:	 4619840 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	  892936 kB
VmRSS:	  831760 kB
VmData:	 4531016 kB
VmStk:	     136 kB
VmExe:	       8 kB
VmLib:	   10408 kB
VmPTE:	    2340 kB
VmPMD:	      32 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
Threads:	18
SigQ:	0/63857
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	0000000180000000
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
Seccomp:	0
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	125
nonvoluntary_ctxt_switches:	10

TERMINATED THREADS

Name:	multithread
State:	S (sleeping)
Tgid:	32265
Ngid:	0
Pid:	32265
PPid:	8551
TracerPid:	0
Uid:	1000	1000	1000	1000
Gid:	1000	1000	1000	1000
FDSize:	256
Groups:	4 20 24 27 30 46 109 125 128 138 1000 
NStgid:	32265
NSpid:	32265
NSpgid:	32265
NSsid:	8551
VmPeak:	 4890308 kB
VmSize:	 4251020 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	  892936 kB
VmRSS:	  691680 kB
VmData:	 4162196 kB
VmStk:	     136 kB
VmExe:	       8 kB
VmLib:	   10408 kB
VmPTE:	    2144 kB
VmPMD:	      32 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
Threads:	1
SigQ:	0/63857
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	0000000180000000
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
Seccomp:	0
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	126
nonvoluntary_ctxt_switches:	10

AFTER CALLED curl_global_cleanup
Name:	multithread
State:	S (sleeping)
Tgid:	32265
Ngid:	0
Pid:	32265
PPid:	8551
TracerPid:	0
Uid:	1000	1000	1000	1000
Gid:	1000	1000	1000	1000
FDSize:	256
Groups:	4 20 24 27 30 46 109 125 128 138 1000 
NStgid:	32265
NSpid:	32265
NSpgid:	32265
NSsid:	8551
VmPeak:	 4890308 kB
VmSize:	 4251020 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	  892936 kB
VmRSS:	  691680 kB
VmData:	 4162196 kB
VmStk:	     136 kB
VmExe:	       8 kB
VmLib:	   10408 kB
VmPTE:	    2144 kB
VmPMD:	      32 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
Threads:	1
SigQ:	0/63857
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	0000000180000000
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
Seccomp:	0
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	127
nonvoluntary_ctxt_switches:	10

```

**Comment by KalimochoAz** [comment]
Sorry to interrupt this but seams interesting to me also.

Taking a look at the documentation:

".BI "void curl_easy_cleanup(CURL *" handle ");"
.SH DESCRIPTION
This function must be the last function to call for an easy session. It is the
opposite of the \fIcurl_easy_init(3)\fP function and must be called with the
same \fIhandle\fP as input that a \fIcurl_easy_init(3)\fP call returned.

This might close all connections this handle has used and possibly has kept
open until now - unless it was attached to a multi handle while doing the
transfers. Don't call this function if you intend to transfer more files,
re-using handles is a key to good performance with libcurl.

Occasionally you may get your progress callback or header callback called from
within \fIcurl_easy_cleanup(3)\fP (if previously set for the handle using
\fIcurl_easy_setopt(3)\fP). Like if libcurl decides to shut down the
connection and the protocol is of a kind that requires a command/response
sequence before disconnect. Examples of such protocols are FTP, POP3 and IMAP.

**Any use of the \fBhandle\fP after this function has been called and have
returned, is illegal. \fIcurl_easy_cleanup(3)\fP kills the handle and all
memory associated with it!**"

looking at the last sentence something needs to change there? because in some cases, like this one not all the memory associated with GnuTLS as you suggest is free. So that will depend on the app is called. Is that what we need to assume?

Thanks @bagder

**Comment by dfandrich** [comment]
You're probably just seeing the results of the glibc memory allocator not returning memory back to the system once it's freed. Just because a heap object has free() called on it doesn't mean it's returned to the system, for efficiency reasons as well as problems with fragmentation. See this discussion for example: https://stackoverflow.com/questions/2215259/will-malloc-implementations-return-free-ed-memory-back-to-the-system/2417950

**Comment by anonbeat** [comment]
@dfandrich even with 800MiB of memory?

**Comment by dfandrich** [comment]
It's certainly conceivable, depending on the usage patterns of the heap in your program (causing fragmentation, etc), but with an allocator that never returns RAM to the system, that figure would only ever go up. If the program isn't actually leaking memory, that's the most likely explanation. The info page for glibc under "Statistics for Memory Allocation with 'malloc'" lists some statistics you can pull out of the allocator at run time.

**Comment by KalimochoAz** [comment]
@dfandrich I also tryed that example from @anonbeat and seams not easy to justify this big amount of memory lost.

**Comment by dfandrich** [comment]
You could always try using a different allocator and see if that makes a difference.

**Comment by KalimochoAz** [comment]
@dfandrich you really are saying that the problem is in the memory alocation when calling https but not when callong the same image on http? So any application that uses GnuTLS it will have 800Mb of memory leak after 41 small images downloaded?

**Comment by bagder** [comment]
It is not an actual *leak* if the memory is ultimately freed. It is just a big memory consumption.

I still don't see how this memory consumption can be blamed on curl, as curl doesn't itself use this much memory. We cannot take responsibility for what GnuTLS does (or doesn't do). For reasons like this, we have written libcurl to allow it to get built with different TLS backends so that users can pick one they like.

If that amount of "used memory" is indeed just free heap space not being returned to the system, then it isn't even GnuTLS' fault but the malloc you're using (glibc?). The man page details @dfandrich mention is also available here: [Statistics for Memory Allocation with malloc](https://www.gnu.org/software/libc/manual/html_node/Statistics-of-Malloc.html)

Since those "41 small images" were all downloaded in parallel, in one thread each, a guess would be that GnuTLS needs thread-local data and then 41 threads add up.

An interesting comparison would be if you rewrote your code to instead use the multi interface to do parallel transfers as that will then perform them all in a single thread.

**Comment by ptor** [comment]
On 26 October 2016 at 00:02, J.Rios <notifications@github.com> wrote:

> the point is that after calling curl_easy_cleanup or even
> curl_global_cleanup the memory used is too high... that is the point
>

Note that traditionally, a Unix memory allocator (malloc) never returned
even one byte back to the operating system. It could only use sbrk(2) to
acquire memory from the system, but not give it back. And every
sbrk(2)-based malloc() implementation to this day behaves like that.

What it does is to allocate a chunk of memory, which it manages internally
to provide memory via the user's malloc(3) calls. free() simply returns
memory back to that memory pool which malloc() manages. It doesn't go back
to the operating system. In other words, once allocated, forever allocated
(that is, until the program exits), if you only look at the ps or top
statistics. As long as valgrind and other tools report that there are no
leaks, there are no leaks. If you, say, did a malloc() of 100MB, and after
that a free(), then malloc() of 2KB and nothing more again, then after some
time the operating system will in practice swap that unused memory out, and
it's not physical memory anymore. Even if 'ps' says it uses memory.

However, the Linux  libc malloc implementation switched to an 'mmap(2)'
based allocator many years ago. What mmap(2) does is to map disk pages to
memory, but the disk page can also be virtual, as in /dev/zero. Thus it can
be used as a memory allocator. But the thing is, when munmap(2) is called
on those pages, they are actually released back to the operating system. On
a page-by-page basis. But if you read the malloc manpage, it actually uses
a combination - normally it uses sbrk(2), but when more memory than a
certain threshold is needed it will use mmap(2).

In any case, when malloc()'ing and free()'ing memory in an application, the
memory allocator may not always be able to arrange the available memory so
that contiguous areas of the requested size are available. To fix that, it
allocates more from the operating system. Which means that even a
well-managed program can, over time, see increasing memory use. (In my
programs I always call free() in the opposite sequence of malloc(), i.e.
a=malloc(); b=malloc(); c=malloc(); free(c); free(b); free(a);. My thinking
is that this helps to avoid fragmentation of the malloc pool - if that's
true or not I have not verified, but it may help. It feels right, at
least..)

The short of it? If valgrind is happy, you should be happy. And try to
avoid fragmentation of memory (maybe that sequence thing actually helps),
so that malloc() can work with what it has and doesn't need to get more
memory, just to find a big enough piece.

**Comment by anonbeat** [comment]
@ptor Thanks... I have switched to libcurl4-openssl and now behaves as expected. This examples went from 800Mb used by gnutls to 40Mb used by openssl...
