### ISSUE TITLE
Problems with FTPS using CURL

### ISSUE THREAD

**Issue by Q-coder** [curl/curl#11269]
### Discussed in https://github.com/curl/curl/discussions/11263

<div type='discussions-op-text'>

<sup>Originally posted by **Q-coder** June  7, 2023</sup>
Hello,
I have two issues both related to FTPS/SFTP transfers using curl. The first one is a 450 error code from Proftpd during the upload.
Example:
curl -k -T MyFile.txt -u xxxUser ftps://xxxServert:990/inbound/MyFile.txt
Enter host password for user 'xxxUser':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36.0M    0     0  100 36.0M      0   100M --:--:-- --:--:-- --:--:--  100M
curl: (18) server did not report OK, got 450
Parts of the file is transferred. But it's couple of bytes short.  In this example the source file is 37790596 bytes but the arrived file is : 37437440 bytes.
When I try the same transfer with lftp, it works. No error code returned and the dest file has the same size as the source file.
The lftp command :
lftp -e "debug 10;set ftp:port-ipv4; " -p 990  -u xxxUser:xxxPWD  ftps://xxxServert
put MyFile.txt

---- resetting retry count
copy-peer: EOF on FD 4
copy: get hit eof
copy: waiting for put confirmation
---- Closing data socket
<--- 226 Transfer complete
---> MFMT 20230606183127 MyFile.txt
<--- 213 Modify=20230606183127; MyFile.txt
copy: put confirmed store
copy: get is finished - all done
37790596 bytes transferred
---- Closing idle connection
---> QUIT
<--- 221 Goodbye.
---- Closing control socket
Unfortunately I cannot post all the logfile because of confidential data. 

Curl is curl 7.61.1
lftp is LFTP | Version 4.8.4
It's running on RHEL 8.7

The target system runs CentOS 6.5 (I know it's out of support)
with ProFTPD Version 1.3.3g

Kind Regards,
Gerhard
</div>

**Comment by bagder** [comment]
First: this is two separate issues that you submit as a single one. That's confusing and hard to deal with. I propose you submit the second issue as a separate one (and remove it from here) so that we can discuss and handle them individually. They are not likely to have the same cause.

For the FTP partial upload it seems likely that adding `-v` to the command line will provide you with some amount of feedback. The 450 response from the server probably has some kind of message for example. Without that, we would need a way to reproduce the issue to work on it.

You are using a curl version that is almost five years old on an OS that is beyond end-of-life. It is likely that a modern curl at least would behave differently or perhaps even not suffering from these issues.

**Comment by Q-coder** [comment]
Hello,
thank you for your respond. I've split this into two issues now.
I've tried to run curl with -v and with -trace. But unfortunately no further details are revealed as to why the 450 occurs. Also running Proftpd with max debug level and tracing does not reveal anything.
I guess it could only be traced using a debugger. 

The curl version is from the RHEL 8 installation. I will try to download a newer and test with that also.
kind Regards,
Gerhard

**Comment by bagder** [comment]
> no further details are revealed

It would still reveal some details to us because we can't even say to which ftp command the 450 was in response to without the output or you telling. If you can't tell us how to reproduce the problem, you need to work on fixing the issue yourself or keep feeding us info to make it possible for us to help you.

**Comment by Q-coder** [comment]
Will try to check the Proftpd logfiles again tomorrow. I don't think there was any error logged on the Proftpd side though. In the mean time I mitigated my issue by changing from ftps to sftp which works for the same file and user to the same Proftpd server.

**Comment by bagder** [comment]
We can't act on this.
