### ISSUE TITLE
AVG Web Shield causes `curl: (60) SSL certificate problem` on Windows in git-bash

### ISSUE THREAD

**Issue by pwintz** [curl/curl#11268]
When [AVG](https://www.avg.com/) Web Shield is installed and enabled, running the following `curl` command in git-bash on Windows fails: 
```
$ curl https://www.example.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
The command works is Web Shield is disabled. 

I don't know if this is a problem you can fix, but it would be nice if you detected it and showed a warning (the output of `curl https://www.example.com --trace-ascii -` can be used to see that AVG is causing problems). I spent several weeks trying to track down this problem, and it seems like it would happen to many other people too.

### curl version
```
curl 7.75.0 (x86_64-w64-mingw32) libcurl/7.75.0 OpenSSL/1.1.1k (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2021-02-03
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP zstd
```

### operating system

Windows 11, using git-bash.

**Comment by bagder** [comment]
This happens because your program is intercepting the connection and is trying to eavesdrop on it. curl rejects this because it then provides a server certificate that is signed by a CA that is not trusted. The CA is not in your CA store.

Intercepting is also called Man-In-The-Middle and TLS is designed exactly to discover and allow users to avoid such. I would strongly urge you disable that horrible feature and remain happy curl pointed out this problem to you.

This is curl working as designed.
