### ISSUE TITLE
Building curl HTTP/3 on mac fails with: error: unknown type name 'OSSL_ENCRYPTION_LEVEL'

### ISSUE THREAD

**Issue by bneradt** [curl/curl#11391]
### I did this

I followed the OpenSSL directions to build HTTP/3 curl natively on my M1 MacBook Pro here:
https://curl.se/docs/http3.html

Here's a script that reproduces my build issue:

```bash
#!/usr/bin/env bash

mkdir /var/tmp/curl_build_failure_repro
cd /var/tmp/curl_build_failure_repro

git clone --depth 1 -b openssl-3.0.9+quic https://github.com/quictls/openssl
cd openssl
./config enable-tls1_3 --prefix=/opt/deleteme_openssl
make -j10 && sudo make install
cd ../

git clone -b v0.12.0 https://github.com/ngtcp2/nghttp3
cd nghttp3
autoreconf -fi
./configure --prefix=/opt/deleteme_nghttp3 --enable-lib-only
make -j10 && sudo make install
cd ../

git clone -b v0.16.0 https://github.com/ngtcp2/ngtcp2
cd ngtcp2
autoreconf -fi
./configure PKG_CONFIG_PATH=/opt/deleteme_openssl/lib/pkgconfig:/opt/deleteme_nghttp3/lib/pkgconfig LDFLAGS="-Wl,-rpath,/opt/deleteme_openssl/lib" --prefix=/opt/deleteme_ngtcp2 --enable-lib-only
make -j10 && sudo make install
cd ../

git clone https://github.com/curl/curl
cd curl
autoreconf -fi
LDFLAGS="-Wl,-rpath,/opt/deleteme_openssl/lib" ./configure --with-openssl=/opt/deleteme_openssl --with-nghttp3=/opt/deleteme_nghttp3 --with-ngtcp2=/opt/deleteme_ngtcp2 --prefix=/opt/deleteme_curl
make -j10 && sudo make install
```

### I got the following

```bash
In file included from vquic/curl_ngtcp2.c:36:
/opt/deleteme_ngtcp2/include/ngtcp2/ngtcp2_crypto_openssl.h:73:5: error: unknown type name 'OSSL_ENCRYPTION_LEVEL'                                  
    OSSL_ENCRYPTION_LEVEL ossl_level);
    ^                                                                                                                                               
/opt/deleteme_ngtcp2/include/ngtcp2/ngtcp2_crypto_openssl.h:82:15: error: unknown type name 'OSSL_ENCRYPTION_LEVEL'                                 
NGTCP2_EXTERN OSSL_ENCRYPTION_LEVEL   
              ^                
  CC       vssh/libcurl_la-wolfssh.lo         
vquic/curl_ngtcp2.c:510:3: error: call to undeclared function 'SSL_set_quic_use_legacy_codepoint'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]                                                                                                     
  SSL_set_quic_use_legacy_codepoint(ctx->ssl, 0);
  ^                                                                       
3 errors generated.          
make[2]: *** [vquic/libcurl_la-curl_ngtcp2.lo] Error 1                                                                                              
make[2]: *** Waiting for unfinished jobs....                              
make[1]: *** [all] Error 2                              
make: *** [all-recursive] Error 1  
```

With `V=1`:

```bash
╰─➤  cd /var/tmp/curl_build_failure_repro/curl
╰─➤  make V=1
Making all in lib
/Library/Developer/CommandLineTools/usr/bin/make  all-am
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H   -I../include -I../lib -I../lib -DBUILDING_LIBCURL  -DCURL_HIDDEN_SYMBOLS -isystem /opt/deleteme_openssl/include -isystem /opt/homebrew/Cellar/libidn2/2.3.4_1/include -isystem /opt/homebrew/Cellar/libnghttp2/1.52.0/include -isystem /opt/deleteme_ngtcp2/include -isystem /opt/deleteme_ngtcp2/include -isystem /opt/deleteme_nghttp3/include  -fvisibility=hidden -Qunused-arguments -O2 -Wno-pointer-bool-conversion -Werror=partial-availability  -MT vquic/libcurl_la-curl_ngtcp2.lo -MD -MP -MF vquic/.deps/libcurl_la-curl_ngtcp2.Tpo -c -o vquic/libcurl_la-curl_ngtcp2.lo `test -f 'vquic/curl_ngtcp2.c' || echo './'`vquic/curl_ngtcp2.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /opt/deleteme_openssl/include -isystem /opt/homebrew/Cellar/libidn2/2.3.4_1/include -isystem /opt/homebrew/Cellar/libnghttp2/1.52.0/include -isystem /opt/deleteme_ngtcp2/include -isystem /opt/deleteme_ngtcp2/include -isystem /opt/deleteme_nghttp3/include -fvisibility=hidden -Qunused-arguments -O2 -Wno-pointer-bool-conversion -Werror=partial-availability -MT vquic/libcurl_la-curl_ngtcp2.lo -MD -MP -MF vquic/.deps/libcurl_la-curl_ngtcp2.Tpo -c vquic/curl_ngtcp2.c  -fno-common -DPIC -o vquic/.libs/libcurl_la-curl_ngtcp2.o
In file included from vquic/curl_ngtcp2.c:36:
/opt/deleteme_ngtcp2/include/ngtcp2/ngtcp2_crypto_openssl.h:73:5: error: unknown type name 'OSSL_ENCRYPTION_LEVEL'
    OSSL_ENCRYPTION_LEVEL ossl_level);
    ^
/opt/deleteme_ngtcp2/include/ngtcp2/ngtcp2_crypto_openssl.h:82:15: error: unknown type name 'OSSL_ENCRYPTION_LEVEL'
NGTCP2_EXTERN OSSL_ENCRYPTION_LEVEL
              ^
vquic/curl_ngtcp2.c:510:3: error: call to undeclared function 'SSL_set_quic_use_legacy_codepoint'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  SSL_set_quic_use_legacy_codepoint(ctx->ssl, 0);
  ^
3 errors generated.
make[2]: *** [vquic/libcurl_la-curl_ngtcp2.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

Looking at the built OpenSSL ssl.h file, I see that symbol in it:

```
   2612 typedef enum ssl_encryption_level_t {
   2613     ssl_encryption_initial = 0,
   2614     ssl_encryption_early_data,
   2615     ssl_encryption_handshake,
   2616     ssl_encryption_application
   2617 } OSSL_ENCRYPTION_LEVEL;
```

I suppose that some `#if` removes it...the file is quite complicated with it's pre-processor directives. When I compile with `-E` I do not see the definition of `OSSL_ENCRYPTION_LEVEL`:

```bash
╰─➤  cd lib                                   
╰─➤  gcc -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /opt/deleteme_openssl/include -isystem /opt/homebrew/Cellar/libidn2/2.3.4_1/include -isystem /opt/homebrew/Cellar/libnghttp2/1.52.0/include -isystem /opt/deleteme_ngtcp2/include -isystem /opt/deleteme_ngtcp2/include -isystem /opt/deleteme_nghttp3/include -fvisibility=hidden -Qunused-arguments -O2 -Wno-pointer-bool-conversion -Werror=partial-availability -MT vquic/libcurl_la-curl_ngtcp2.lo -MD -MP -MF vquic/.deps/libcurl_la-curl_ngtcp2.Tpo -c vquic/curl_ngtcp2.c  -fno-common -DPIC -E -o vquic/.libs/libcurl_la-curl_ngtcp2.i

╰─➤  grep OSSL_ENCRYPTION_LEVEL vquic/.libs/libcurl_la-curl_ngtcp2.i                                           
    OSSL_ENCRYPTION_LEVEL ossl_level);
              OSSL_ENCRYPTION_LEVEL
```

### I expected the following

A successfully compiled curl.

### curl/libcurl version

```bash
╰─➤  git show --quiet
commit 891e25edb8527bb8de79cdca6d943216c230e905 (HEAD -> master, origin/master, origin/HEAD)
Author: Sheshadri.V <sheshadriv32@gmail.com>
Date:   Wed Jun 21 11:03:20 2023 +0530

    curl.h: include <sys/select.h> for vxworks
    
    Closes #11356

```
### operating system

```
╰─➤  uname -a     
Darwin TGW26GQPQ3 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
```

**Comment by icing** [comment]
Your build does not find the correct OpenSSL header files. Probably because you omitted the ` --libdir=$HOME/all/lib` part from the documentation when building OpenSSL. 

OpenSSL may have used another lib dir to install its pkgconfig and the subsequent ngtcp2 build will not find it  and instead see the system openssl headers.

**Comment by bneradt** [comment]
Thanks for the reply @icing 

> Your build does not find the correct OpenSSL header files. Probably because you omitted the ` --libdir=$HOME/all/lib` part from the documentation when building OpenSSL.

I don't believe I omitted anything from the instructions in https://curl.se/docs/http3.html. Are you saying my steps vary from that document? My script does not pass `--libdir` anywhere, bit I don't see that in the http3.html doc. Is that an option to the openssl build or the ngtcp2 build?

> 
> OpenSSL may have used another lib dir to install its pkgconfig and the subsequent ngtcp2 build will not find it and instead see the system openssl headers.

The pkgconfig dir seems correct. Here's the configuration to ngtpc2:

```bash
./configure PKG_CONFIG_PATH=/opt/deleteme_openssl/openssl/lib/pkgconfig:/opt/deleteme_nghttp3/lib/pkgconfig LDFLAGS="-Wl,-rpath,${install_dir}/openssl/lib" --prefix=${install_dir}/ngtcp2 --enable-lib-only
make -j10 && sudo make install

╰─➤  ls /opt/deleteme_openssl/lib/pkgconfig                                   
libcrypto.pc libssl.pc    openssl.pc
```

**Comment by icing** [comment]
@bneradt we are building curl with ngtcp2 on various platforms, using the instructions. The build code used you'll also find in the github workflow files.

Not sure what I can add from here to the problems on your machine. I am myself building on a macOS Intel machine.

**Comment by bneradt** [comment]
> @bneradt we are building curl with ngtcp2 on various platforms, using the instructions. The build code used you'll also find in the github workflow files.
> 

I know this is an imposition and it's OK if you don't have time for this, but did you run my script above? It should only take a few minutes, and the build outputs will only be in `/var/tmp/curl_build_failure_repro` and `/opt/deleteme_*` directories. It would be helpful for triaging to know whether there's an issue with the commands I'm running or whether there's an issue with my environment. I'm starting to guess it's my environment.

> Not sure what I can add from here to the problems on your machine. I am myself building on a macOS Intel machine.

Maybe that's the difference then. I do have an m1 mac and I have noticed differences in behavior with openssl on arm64 and amd64.

Maybe there's something wrong with my environment. I'll ask some colleagues also with m1 macs to try and let me know whether they have issues.

Thank you again for the feedback.

**Comment by icing** [comment]
How does the file tree look like in `/opt/deleteme_openssl`? How many `openssl.pc` files are there, where and with what content?

Since you are omitting the `--libdir` argument in your script (which we use in HTTP3.md), I am wondering.

On macOS intel, if you omit `--libdir`, openssl installs in `lib64` and not `lib`.

**Comment by bneradt** [comment]
> Since you are omitting the `--libdir` argument in your script (which we use in HTTP3.md), I am wondering.

Maybe `--libdir` will help. However I see no mention of `--libdir` here:
https://curl.se/docs/http3.html

Nor here:
https://github.com/curl/curl/blob/master/docs/HTTP3.md

**Comment by bneradt** [comment]
Taking some pointers from [#7030](https://github.com/curl/curl/issues/7030#issuecomment-834569370), it seems like my curl is finding the correct custom (rather than system) openssl:

```
   1976 configure:26513: result: /opt/homebrew/bin/pkg-config                                
   1977 configure:26538: checking for openssl options with pkg-config                                                                                                      
   1978 configure:26552: result: found                                                                          
   1979 configure:26581: pkg-config: SSL_LIBS: "-lssl -lcrypto"                                
   1980 configure:26583: pkg-config: SSL_LDFLAGS: "-L/opt/ats_h3_tools/openssl-quic-openssl-3.0.9+quic/lib"                                
   1981 configure:26585: pkg-config: SSL_CPPFLAGS: "-I/opt/ats_h3_tools/openssl-quic-openssl-3.0.9+quic/include"                                
   1982 configure:26597: checking for HMAC_Update in -lcrypto                                
   1983 configure:26620: gcc -o conftest -O3 -g -Qunused-arguments -Wno-pointer-bool-conversion -Werror=partial-availability   -I/opt/ats_h3_tools/openssl-quic-openssl-3.0.9+quic/include -Wl,-rpath,/opt/ats_h3_tools/openssl-quic-openss
        l-3.0.9+quic/lib -framework CoreFoundation -framework SystemConfiguration  -L/opt/ats_h3_tools/openssl-quic-openssl-3.0.9+quic/lib conftest.c -lcrypto  -lssl -lcrypto -lldap -lz  >&5
```

**Comment by bagder** [comment]
Is this perhaps another version of the brew openssl issue @icing just fixed in the CI builds with #11436 in 5c07439ba3345 ?

**Comment by icing** [comment]
This looks exactly like the issue I had on my machine after updating homebrew.

**Comment by GwynethLlewelyn** [comment]
I can also confirm that the issue lies on Apple's clang.

My developing environment is an old machine, running macOS Big Sur 11.7.9 (20G1426) (currently EOL as I write this):

MacBook Pro (Retina, 15-inch, Mid 2014)
2.8 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3

Apple's `clang`, as shipped for Big Sur, is a trifle too old (besides its own extra quirks):

```sh
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Homebrew, while constantly complaining that Big Sur is deprecated, nevertheless still allows me a much more recent version of `clang`:

```sh
Homebrew clang version 17.0.5
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm/17.0.5/bin
```

Unfortunately, unlike @bneradt, I'm afraid that in my machine `brew link llvm` fails with the message:
```sh
Warning: Refusing to link macOS provided/shadowed software: llvm
```

There might be some sort of workaround, but naturally enough, I can always do:
```sh
export CC=/usr/local/Cellar/llvm/17.0.5/bin/clang
export CXX=/usr/local/Cellar/llvm/17.0.5/bin/clang++
```
and then follow [the usual recipe for HTTP/3 support](https://curl.se/docs/http3.html), reconfiguring everything from scratch.

It works!

Oh, sure, I get the odd warning here and there, because I decided on a whim to include Apple's deprecated GSS-API support libraries — and `clang` frowns its nose at such code (which _is_ marked by Apple as deprecated!). But if that is not a requirement, then you get a fairly clean compilation. Lots of `no symbols` warnings on the produced objects/libraries, though, but this doesn't seem to affect the final executable in any way.

I haven't used `--libdir` — it seems not to matter. What I forgot was to confirm the destination for installing — and so `make install` happily trashed the `curl` version from Homebrew! 😅 It's of no consequence — as said, following @bneradt suggestions and the 'official recipe', I got a perfectly working `curl`, and, as a bonus, well, I guess that all `curl` libraries were also "upgraded" to support HTTP/3 (which _might_ be a good thing, after all!).

I'm sure that different macOS versions, under different platforms, will give different results than mine; nevertheless, the point made here regarding Apple's "broken" `clang` seems to be universally true. It would be interesting to see if someone on macOS Sonoma (or more recent versions!) continues to have issues with Apple's `clang`, or if Apple finally decided to properly patch it on recent versions...

In any case, it _might_ be a good idea to include a warning somewhere (here on GitHub; on the official site; on the README file; on the docs/README.md for the Apple section; on the `configure.ac` file or somewhere else during the compilation process... whatever is more adequate) to instruct users to avoid the Apple native `clang` compiler if it fails, and fall back to Homebrew's own version.

I guess that compiling with `gcc` would be a possible alternative — I haven't tried it out, although I _do_ have Homebrew GCC 13.2.0 installed, for the odd compilation that refuses to work with `clang`...
