### ISSUE TITLE
curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it

### ISSUE THREAD

**Issue by mchittineni** [curl/curl#11475]
### curl/libcurl version

[curl -V output]

### operating system - ubuntu-latest

![Screenshot 2023-07-19 at 16 12 06](https://github.com/curl/curl/assets/116578727/fc692a06-f51a-470f-a058-abf3b4ab4bba)

**Comment by bagder** [comment]
The entire explanation is what you already wrote in the subject:

*curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it*

[read more](https://curl.se/docs/sslcerts.html)

**Comment by patrick-stephens** [comment]
The issue seems to occur for me with curl 7.81.0-1ubuntu1.11 but not curl 7.81.0-1ubuntu1.10.
A working host then triggers the same failure when upgraded.
Using a base image or VM with the 7.81.0-1ubuntu1.11 version fails.

**Comment by peterellisjones** [comment]
We're seeing the same issue since the recent curl security update on Ubuntu Focal.

> curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it
The problem is that the certificate is correct! We are getting this error with a valid wildcard SAN that matches the host.

We were able to reproduce the error by
1. Succesfully running on curl on an ubuntu image built before yesterday
2. `apt-get update && apt-get upgrade -y` to update curl to the latest version
3. See that curl fails with the error

**Comment by patrick-stephens** [comment]
And the certificate is fine across a whole test suite of various OS VMs, only the Ubuntu 22.04 ones are failing for the exact same steps.

In this case it was installing docker but it is the same wildcard certificate.
```
curl -fsSLv "https://download.docker.com/linux/ubuntu/gpg"
```
The issue seems to be curl=7.81.0-1ubuntu1.11, using the previous version it succeeds.

**Comment by bilby91** [comment]
I can confirm that we are experiencing the same problem since this morning. Any curl call to a domain that is backed by a SAN fails validation.

**Comment by patrick-stephens** [comment]
Pinning to the non-security update version seems to resolve it: 

`apt-get install -y curl=7.81.0-1 libcurl4=7.81.0-1`

However, not ideal.

**Comment by tedmielczarek-fastly** [comment]
Related: https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2028170

**Comment by aflansburg** [comment]
> I can confirm that we are experiencing the same problem since this morning. Any curl call to a domain that is backed by a SAN fails validation.

Seeing this as root cause of failures on CircleCI pipelines when installing tooling like the Datadog agent via their install script.

**Comment by ydixken** [comment]
We can confirm this as well. Since this morning docker builds are failing.

**Comment by jacobwoffenden** [comment]
https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2028170/comments/8 fix released

**Comment by bagder** [comment]
So this was Ubuntu patching a security problem with a **broken** backport of a [CVE-2023-28321](https://curl.se/docs/CVE-2023-28321.html) patch that broke certificate validation.

This bug never existed in code shipped by the curl project.

**Comment by SuperSandro2000** [comment]
Cane someone link the commit where the faulty patch was fixed? I can't find it Ubuntus messy infrastructure.

**Comment by dfandrich** [comment]
See the link posted by @tedmielczarek-fastly and @jacobwoffenden.

**Comment by anleib** [comment]
[patch](https://launchpadlibrarian.net/678023483/curl_7.81.0-1ubuntu1.11_7.81.0-1ubuntu1.13.diff.gz)
