### ISSUE TITLE
--Parallel output to text-file that isn't English becomes unreadable but not if I use -v

### ISSUE THREAD

**Issue by Shandoolie** [curl/curl#11667]
### I did this

I did **curl --parallel 100 https://www.douyu.com/[5019555-5019655] > output.txt**, the chinese text only becomes unreadable in output.txt

When I do **curl --parallel 100 -v https://www.douyu.com/[5019555-5019655] > output.txt** the Chinese text is readable but I don't need -v and it is alot slower

It is the same with Korean text

### I expected the following

Expected output to text-file without -v

### curl/libcurl version

curl 8.2.1 (x86_64-w64-mingw32) libcurl/8.2.1 OpenSSL/3.1.2 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 WinIDN libssh2/1.11.0 nghttp2/1.55.1 ngtcp2/0.18.0 nghttp3/0.14.0 libgsasl/2.2.0
Release-Date: 2023-07-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe UnixSockets zstd

### operating system

Windows 10 21H2

**Comment by dfandrich** [comment]
If the output consists of multibyte characters, they will be interleaved
randomly as data from the various URLs is received. This is expected behaviour.
To avoid this, use something like --remote-name-all to store the data from each
URL into separate files then concatenate them at the end of the transfer.
