### ISSUE TITLE
curl multi: Process time takes too long compared to single curl.

### ISSUE THREAD

**Issue by BuddhaProgram** [curl/curl#11744]
### I did this

Hi,

I have an application that I changed recently, from using single curl to multi-curl handling. My code does keep track of the time needed from execution to completion. However, I realised curl multi has a very strange execution time spiking. What I meant by this is that the process can take as fast as 3 ms, but all of a sudden one of the requests just bumps up to 10,000 ms ~ 20,000 ms, and it will go back down to the range of 3 ms - 20ms. This cycle will repeat every few requests.
I have also tried applying setopt timeout and low speed limit/ time but it does not work out. My timeout is set at 4 seconds.

### I expected the following

I understand that there are instances where requests can take some time due to a sudden network concern. However, this is on a cycle that I believe needed an answer to this strange execution time spiking.

### curl/libcurl version

curl 7.47.0 (x86_64-pc-linux-gnu)

### operating system

Linux (customized by my organization) x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
Your libcurl version is approaching its 8th birthday. We have fixed almost 6,000 bugs since that was released. You really should consider upgrading to a modern version, **especially** since you experience problems.

libcurl itself *always* uses multi. The easy interface is itself just a wrapper around the multi interface. The problems you see either already existed for you or your application is causing them.

We cannot help you with this old legacy version. If you insist on sticking to this version, I suppose you can buy commercial support help - but really, upgrading is the most sensible first step either way.

**Comment by jay** [comment]
In addition once you're using the latest version turn on [CURLOPT_VERBOSE](https://curl.se/libcurl/c/CURLOPT_VERBOSE.html) to see what's happening.
