### ISSUE TITLE
When building a static library project for Visual Studio with CMake, the preprocessor variable CURL_STATICLIB does not get set

### ISSUE THREAD

**Issue by Mathias-Fuchs** [curl/curl#11844]
### I did this

I used the CMake GUI on Windows and checked the checkbox next to BUILD_STATIC_LIBS, to generate Visual Studio solution and project files.

### I expected the following

I expected CMake to generate project files which define the preprocessor variable CURL_STATICLIB that appears on line 128 in curl.h. However, this preprocessor variable was not defined. The CMake variables ENABLE_STATIC and CPPFLAG_CURL_STATICLIB (which is the empty string if no static libs are to be built) don't seem to have an effect when using CMake for Visual Studio project generation - they only seem to have an effect on the autoconf files. Maybe, a line such as
``` CMake
add_definitions(${CPPFLAG_CURL_STATICLIB})
```
might have to be added to CMakeLists.txt. Will be happy to submit a pull request. This issue does not yet seem to appear under https://curl.se/docs/knownbugs.html#CMake. 

### curl/libcurl version

curl 8.3.0-DEV

### operating system

Windows 10

**Comment by vszakats** [comment]
CURL_STATICLIB is supposed to be defined via `INTERFACE_COMPILE_DEFINITIONS "CURL_STATICLIB"` automatically in CMake. I wonder if the right codepath isn't hit in lib/CMakeLists.txt or this CMake option isn't effective in this particular build case. 

[ `CPPFLAG_CURL_STATICLIB` is autotools-specific. As a temporary workaround we can be pass this via -DCMAKE_C_FLAGS=-DCURL_STATICLIB to CMake builds. ]

**Comment by vszakats** [comment]
@Mathias-Fuchs: Can you post the invocation of CMake that replicates this issue?

**Comment by alexsharoff** [comment]
IIRC, INTERFACE_COMPILE_DEFINITIONS will only affect the targets linking against the Curl static library. The static library itself will compile without `-DCURL_STATICLIB`, resulting in `CURL_EXTERN` expanding to `__declspec(dllexport)`. This is not good, because it makes DLLs or EXEs that link against static Curl unexpectedly export symbols.

**Comment by vszakats** [comment]
You're right!

Haven't made tests yet, but it now seems safe to always define `CURL_STATICLIB` for both shared and static libs in CMake, because we control DLL exports via `libcurl.def`.

[ Also `libcurl.def` should probably only be used when `HIDES_CURL_PRIVATE_SYMBOLS` is defined. Also we should probably delete `INTERFACE_COMPILE_DEFINITIONS "CURL_STATICLIB"` from `LIB_OBJECT`. ]

**Comment by vszakats** [comment]
```diff
--- CMakeLists.txt	2023-09-22
+++ CMakeLists.txt-PAT	2023-09-22
@@ -127,8 +127,7 @@
   add_library(${LIB_OBJECT} OBJECT ${HHEADERS} ${CSOURCES})
   target_link_libraries(${LIB_OBJECT} PRIVATE ${CURL_LIBS})
   set_target_properties(${LIB_OBJECT} PROPERTIES
-    COMPILE_DEFINITIONS "BUILDING_LIBCURL"
-    INTERFACE_COMPILE_DEFINITIONS "CURL_STATICLIB"
+    COMPILE_DEFINITIONS "BUILDING_LIBCURL;CURL_STATICLIB"
     POSITION_INDEPENDENT_CODE ON)
   if(HIDES_CURL_PRIVATE_SYMBOLS)
     set_target_properties(${LIB_OBJECT} PROPERTIES
@@ -160,7 +159,7 @@
   set_target_properties(${LIB_STATIC} PROPERTIES
     PREFIX "" OUTPUT_NAME "${LIBCURL_OUTPUT_NAME}"
     SUFFIX "${STATIC_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}"
-    COMPILE_DEFINITIONS "BUILDING_LIBCURL"
+    COMPILE_DEFINITIONS "BUILDING_LIBCURL;CURL_STATICLIB"
     INTERFACE_COMPILE_DEFINITIONS "CURL_STATICLIB")
   if(HIDES_CURL_PRIVATE_SYMBOLS)
     set_target_properties(${LIB_STATIC} PROPERTIES
@@ -186,7 +185,7 @@
   list(APPEND libcurl_export ${LIB_SHARED})
   add_library(${LIB_SHARED} SHARED ${LIB_SOURCE})
   add_library(${PROJECT_NAME}::${LIB_SHARED} ALIAS ${LIB_SHARED})
-  if(WIN32)
+  if(WIN32 AND HIDES_CURL_PRIVATE_SYMBOLS)
     set_property(TARGET ${LIB_SHARED} APPEND PROPERTY SOURCES libcurl.rc ${CURL_SOURCE_DIR}/libcurl.def)
   endif()
   target_link_libraries(${LIB_SHARED} PRIVATE ${CURL_LIBS})
@@ -194,7 +193,7 @@
   set_target_properties(${LIB_SHARED} PROPERTIES
     PREFIX "" OUTPUT_NAME "${LIBCURL_OUTPUT_NAME}"
     IMPORT_PREFIX "" IMPORT_SUFFIX "${IMPORT_LIB_SUFFIX}${CMAKE_IMPORT_LIBRARY_SUFFIX}"
-    COMPILE_DEFINITIONS "BUILDING_LIBCURL"
+    COMPILE_DEFINITIONS "BUILDING_LIBCURL;CURL_STATICLIB"
     POSITION_INDEPENDENT_CODE ON)
   if(HIDES_CURL_PRIVATE_SYMBOLS)
     set_target_properties(${LIB_SHARED} PROPERTIES
```

**Comment by jzakrzewski** [comment]
Defining `CURL_STATICLIB` for a shared library seems a bit odd, though.

**Comment by jay** [comment]
> Defining `CURL_STATICLIB` for a shared library seems a bit odd, though.

When you build shared and static together the curl tool is supposed to use the shared one if I'm not mistaken.

**Comment by jzakrzewski** [comment]
> When you build shared and static together the curl tool is supposed to use the shared one if I'm not mistaken.

That's not what I'm referring to. I mean it's odd to build a shared library, that has `CURL_STATICLIB` defined. 
Additionally, every user of the built shared library should probably also define it, which is counter-intuitive.

**Comment by vszakats** [comment]
We use `CURL_STATICLIB` when building libcurl to disable `__declspec(dllexport)` (or equivalent). By using `libcurl.def`, `__declspec(dllexport)` is now unnecessary for shared libcurl. It means both static and shared can be built using the same flags. Meaning we can now use `CURL_STATICLIB` to tell `curl.h` to omit `__declspec`, otherwise it's adding it by default. 

This is how curl-for-win builds were built all along via `Makefile.mk`/`Makefile.m32`.

Not defining `CURL_STATICLIB` now means that the libcurl API will be explicitly exported by default, for both static and shared libcurl, which is indeed not what was intended, though the binaries should link and run without issues. The issue is that binaries linking to the static libcurl now also export the libcurl API.

I'm working on a PR that fixes this issue and some other ones I found while looking into this.

**Comment by jzakrzewski** [comment]
Thanks for the explanation, I get it now.
I guess only the name of this define is a little weird now.

**Comment by vszakats** [comment]
The name is weird now indeed. There is no standard, but many times this matter is handled by a `*_EXPORTS` macro. Such macro is automatically added by some build tools, including CMake.

Another issue is that `CURL_STATICLIB` overrides any custom `CURL_EXTERN_SYMBOL` value that is used on non-Windows platforms, even for static builds. So `CURL_STATICLIB` is also Windows-specific.
