### ISSUE TITLE
where can i find libcurl4

### ISSUE THREAD

**Issue by almoharebh** [curl/curl#1189]
### I did this
search for this file libcurl4
### I expected the following
i didnot find any thing , i need to download it 
### curl/libcurl version
libcurl4 , libcurl4-gnutls-dev , libcurl4-openssl-dev , libcurl4-nss-dev , libcurl4-gnutls-dev
[curl -V output perhaps?]

### operating system
windows 10

**Comment by jay** [comment]
If you are using cygwin you can use its package installer/manager to download libcurl. Otherwise please refer to the curl download page's [windows section](https://curl.haxx.se/download.html#Win32). AFAICS there's no libcurl-4.dll for download. You can try renaming libcurl.dll taken from a package like [this](https://bintray.com/artifact/download/vszakats/generic/curl-7.52.1-win32-mingw.7z).

This is an issue tracker, if you have any more questions about libcurl please ask them on the [curl-library mailing list](https://cool.haxx.se/mailman/listinfo/curl-library) instead of here. Thanks

**Comment by almoharebh** [comment]
ok thank you
