### ISSUE TITLE
wrapping lines in "Warning" each prepended with "Warning: " -- should indent instead

### ISSUE THREAD

**Issue by ostipriu** [curl/curl#1209]
Here's how a warning appears in curl when it wraps:
> Warning: Transient problem: timeout Will retry in 1 seconds. 9999 retries 
> Warning: left.

This is a bit awkward to read. I think it would be fine if the text just wrapped below the first "Warning", but if you feel it's important for the text to line up, simply indenting the wrapped lines (with 9 spaces) could achieve this without the additional "Warning" text needing to be added, which disrupts reading flow.

**Comment by jay** [comment]
It looks like it's done that way purposely. I think this is a matter of taste really, some people are going to like it and some aren't.

**Comment by bagder** [comment]
Yes, it is made like that on purpose (by me). But I don't claim to be right automatically because of that. I did it like this because I remember just just wrapping the line made it look a bit strange and I thought this was an improvement. I still think it is fine and it is mostly this specific example above that is particularly odd-looking because there's only a single word wrapped to the second line.

I think perhaps we should make mock-ups showing how a few example lines would look when wrapped/output differently, and see if there's any clear winner.

**Comment by bagder** [comment]
Nobody seems really interested in working on this and it is a really minor issue. Closing.
