### ISSUE TITLE
CURLUE_BAD_SLASHES for URLs without slashes?

### ISSUE THREAD

**Issue by ad0p** [curl/curl#12205]
### I did this

I am trying to use curl_url_set to validate a string and check whether it's a valid URL. However, it fails with CURLUE_BAD_SLASHES for URLs like [tel:+1-201-555-0123](https://datatracker.ietf.org/doc/html/rfc3966#section-6).

Is it expected behavior?

RFC 3896 allows URL without slashes:
```
URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty


path-rootless = segment-nz *( "/" segment )
segment-nz    = 1*pchar
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
pct-encoded   = "%" HEXDIG HEXDIG
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="
```

but in urlapi.c, there is a check that there is [at least one slash](https://github.com/curl/curl/blob/master/lib/urlapi.c#L1138).

Is this a bug or expected behavior?

### I expected the following

tel: urls to pass

### curl/libcurl version

libcurl 8.4.0

### operating system

Windows

**Comment by bagder** [comment]
It is on purpose, but I suspect we should clarify this better in the documentation.

The libcurl URL parser only supports the kind of hierarchical URLs that has a `://` separator.

**Comment by emanuele6** [comment]
Yes, that is expected because the urlapi only supports "hierarchical URLs" (with `://`).

It also has some URL specific quirks for the supported schemes, e.g.
* It is only allowed to use either no host or a "localhost" (or `::0` or `127.0.0.1` or equivalent) host, and it is not allowed to use a port in `file://` URLs.
* "options" are only parsed, and settable for "e-mail" schemes (`pop3://`, `pop3s://`, `imap://`, `imaps://`, `smtp://`, `smtps://`). If the scheme is not one of those `foo://user:pass;opts@example.org/` the password is parsed as `pass;opts`, but if it is one those, the password is `pass` and `opts` is the options.
* ...

If you want to be able to parse arbitrary URIs without scheme specific quirks, you need another library.
