### ISSUE TITLE
Tarball / zipball URL does not point to release version

### ISSUE THREAD

**Issue by lukepalmer** [curl/curl#12234]
### I did this

The github API provides information about releases. A common automated way to build the latest stable release starts with making a query to, in the case of curl, https://api.github.com/repos/curl/curl/releases/latest

The returned document contains information about release assets and also contains fields 'tarball_url' and 'zipball_url' that are meant to be used directly. I observe that, for curl specifically, release assets correctly point to a release archive but tarball / zipball appear to incorrectly point to a non-release version.

**A worked example:**

A release asset is released source code:
```curl -s -L https://api.github.com/repos/curl/curl/releases/latest |jq -c '.assets[] | select(.name | endswith(".tar.gz")).browser_download_url'```
"https://github.com/curl/curl/releases/download/curl-8_4_0/curl-8.4.0.tar.gz"

The tarball is not released code:
```curl -s -L  https://api.github.com/repos/curl/curl/releases/latest |jq '.tarball_url'```
"https://api.github.com/repos/curl/curl/tarball/curl-8_4_0"
download and untar this and you will find in include/curl/curlver.h
#define LIBCURL_VERSION "8.4.0-DEV"

### I expected the following

The tarball should contain a released version such as 8.4.0.

### curl/libcurl version

curl 8.4.0

### operating system

Rocky Linux 8.8

**Comment by dfandrich** [comment]
This has been an issue since day 1 on GitHub. I believe someone opened a feature request years ago to allow a project to disable the automatic tarballs and zip file that GitHub generates without results. This has been an issue as well for humans going to the releases page and downloading the automatically-generated tarballs and wondering why they don't work as documented. Barring GitHub fixing this, I don't see anything we can do.

**Comment by bagder** [comment]
This is indeed [a GitHub issue](https://github.com/orgs/community/discussions/6003), not a curl issue.
