### ISSUE TITLE
Trouble with  --ca-native flag

### ISSUE THREAD

**Issue by nitrogene** [curl/curl#12303]
### I did this

Using an official 8.4.0 curl installer for windows, I have troubles using the --ca-native flag.  

Here's the current folder content:

```dos
Répertoire de C:\Users\WDAGUtilityAccount\Downloads\curl-8.4.0_6-win32-mingw\curl-8.4.0_6-win32-mingw\bin

11/10/2023  12:25 PM    <DIR>          .
11/10/2023  12:25 PM    <DIR>          ..
11/10/2023  12:15 PM           221,470 curl-ca-bundle.crt
11/10/2023  12:15 PM         4,521,544 curl.exe
11/10/2023  12:15 PM             2,326 libcurl.def
11/10/2023  12:15 PM         4,300,360 libcurl.dll
               4 fichier(s)        9,045,700 octets
               2 Rép(s)  39,957,020,672 octets libres
```

first try OK:
```dos
C:\Users\WDAGUtilityAccount\Downloads\curl-8.4.0_6-win32-mingw\curl-8.4.0_6-win32-mingw\bin>curl https://catfact.ninja/fact
{"fact":"Cats are North America\u2019s most popular pets: there are 73 million cats compared to 63 million dogs. Over 30% of households in North America own a cat.","length":149}
```

second try KO - as expected (we are renaming the crt):
```dos
C:\Users\WDAGUtilityAccount\Downloads\curl-8.4.0_6-win32-mingw\curl-8.4.0_6-win32-mingw\bin>ren curl-ca-bundle.crt curl-ca-bundle.crt.old

C:\Users\WDAGUtilityAccount\Downloads\curl-8.4.0_6-win32-mingw\curl-8.4.0_6-win32-mingw\bin>curl https://catfact.ninja/fact
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

third try KO, but should be OK (we are renaming the crt file, but are using the --ca-native flag):

```dos
C:\Users\WDAGUtilityAccount\Downloads\curl-8.4.0_6-win32-mingw\curl-8.4.0_6-win32-mingw\bin>curl https://catfact.ninja/fact --ca-native
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
What am I missing ?

### curl/libcurl version

curl 8.4.0 (i686-w64-mingw32) libcurl/8.4.0 OpenSSL/3.1.4 (Schannel) zlib/1.3 brotli/1.1.0 zstd/1.5.5 WinIDN libssh2/1.11.0 nghttp2/1.58.0 ngtcp2/1.0.1 nghttp3/1.0.0
Release-Date: 2023-10-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe UnixSockets zstd

### operating system

Windows 10

**Comment by jay** [comment]
`openssl s_client -connect catfact.ninja:443 -servername catfact.ninja < NUL`

~~~
Certificate chain
 0 s:CN = catfact.ninja
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: id-ecPublicKey, 384 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep 25 22:13:26 2023 GMT; NotAfter: Dec 24 22:13:25 2023 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 19:14:03 2021 GMT; NotAfter: Sep 30 18:14:03 2024 GMT
~~~

last certificate shown should have issuer (i) (root) CA: DST Root CA X3

`DST Root CA X3` is in 'Trusted Root Certification Authorities' but it [expired](https://github.com/curl/curl/assets/965580/7242e120-9cbc-47c6-a7bb-3ae18ad35dc2) Sep 2021. libcurl does not import expired certificates from the root store. OTOH `ISRG Root X1` should also be in the CA root store because it's now a root CA (also see [this](https://crypto.stackexchange.com/a/95005)).

Windows is supposed to update the root certificates by using Windows Update. Are you using Windows in a VM? Maybe there is not enough time for it to update the root certificates? It happens different from the normal updates iirc.

ISRG Root X1 is in some of my snapshots of a Windows 10 VM but not others. Some snapshots have hardly any root certificates. I don't know the reasons for that.

**Comment by jay** [comment]
In a Windows 10 VM snapshot without `ISRG Root X1` if I use curl with Schannel backend to do the transfer then it is successful and Windows adds that cert root store. hm

**Comment by nitrogene** [comment]
I am using the windows 10 Sandbox, I'll try the openssl command on monday.

**Comment by jay** [comment]
It may have something to do with Windows not putting the root certificates into the ROOT store until the first time it needs to verify a certificate that goes up to a CA not yet in the root store, but in the Windows Update list of trusted CAs. If that's what it's doing that's a problem because we aren't using Schannel to verify the cert chain, we're using OpenSSL so it never imports the certificate.

**Comment by nitrogene** [comment]
Here are some updates. Testing done on Windows 10 Sandbox:
- using curl embedded in windows 10
```dos
C:\Users\WDAGUtilityAccount>curl -Version
curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
```
```dos
C:\Users\WDAGUtilityAccount>curl.exe https://catfact.ninja/fact
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - La fonction de révocation n'a pas pu vérifier la révocation car le serveur de révocation était déconnecté.
```
```dos
C:\Users\WDAGUtilityAccount>curl.exe https://catfact.ninja/fact --ca-native
curl: option --ca-native: is unknown
curl: try 'curl --help' for more information
```
- the openssl command:
```dos
C:\Program Files\OpenSSL-Win64\bin>openssl s_client -connect catfact.ninja:443 -servername catfact.ninja < NUL
CONNECTED(000001B8)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = catfact.ninja
verify return:1
---
Certificate chain
 0 s:CN = catfact.ninja
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: id-ecPublicKey, 384 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep 25 22:13:26 2023 GMT; NotAfter: Dec 24 22:13:25 2023 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 19:14:03 2021 GMT; NotAfter: Sep 30 18:14:03 2024 GMT
...
```
- it works in the edge browser:
![image](https://github.com/curl/curl/assets/275380/782a38ec-c27e-4a25-9706-6545b7f5b330)

**Comment by nitrogene** [comment]
I am completly lost. I launched a fresh sandbox, downloaded [curl for windows](https://curl.se/windows/dl-8.4.0_6/curl-8.4.0_6-win32-mingw.zip), and here are the results:

```dos
C:\Users\WDAGUtilityAccount\Desktop\curl-8.4.0_6-win32-mingw\curl-8.4.0_6-win32-mingw\bin>curl.exe https://catfact.ninja/fact --ca-native
{"fact":"The first cartoon cat was\u00a0Felix the Cat\u00a0in 1919. In 1940, Tom and Jerry starred in the first theatrical cartoon \u201cPuss Gets the Boot.\u201d In 1981 Andrew Lloyd Weber created the musical\u00a0Cats, based on T.S. Eliot\u2019s Old\u00a0Possum\u2019s Book of Practical Cats.","length":245}
```
```dos
C:\Users\WDAGUtilityAccount\Desktop\curl-8.4.0_6-win32-mingw\curl-8.4.0_6-win32-mingw\bin>curl.exe https://catfact.ninja/fact
{"fact":"The claws on the cat\u2019s back paws aren\u2019t as sharp as the claws on the front paws because the claws in the back don\u2019t retract and, consequently, become worn.","length":155}
C:\Users\WDAGUtilityAccount\Desktop\curl-8.4.0_6-win32-mingw\curl-8.4.0_6-win32-mingw\bin>
```

I'll close the issue.

**Comment by jay** [comment]
The issue is valid. When OpenSSL is used as the backend we import certificates from Windows' ROOT certificate store. It appears Windows only adds third party certificates to the store on demand, so certificates may not yet be in the store to be imported. Most regular Windows users (like myself) have many of those certificates in the certificate store because they've been added over time, but a VM likely does not have it.

I'm not yet sure what we can do about this.

Ref: https://blog.brooksjc.com/2022/01/09/root-certificates-on-windows/

**Comment by bagder** [comment]
It does not seem like a curl problem. curl imports the certs that exist to import. It cannot magically import certs that are not there.

**Comment by bagder** [comment]
This looks like a quirk from outside of curl's territory.
