### ISSUE TITLE
Dos this lib support HTTPS PROXY ?

### ISSUE THREAD

**Issue by beshoo1** [curl/curl#1244]
I am a php programmer and AFAIK , curl dos not support https proxy ,
is there any update about this ?

and if it is , can i compile this lib to work with cpanel/php !

**Comment by jay** [comment]
Please ask your libcurl questions on the [mailing list](https://cool.haxx.se/mailman/listinfo/curl-library). Yes, it does support HTTPS proxy since 7.52 with SSL backends OpenSSL, GnuTLS and NSS. php can be built with libcurl. I'm not sure how cpanel factors into it but I'll guess based on googling just now there is some option that can be used to enable php w/libcurl. You'd have to ask a cpanel discussion about that.
