### ISSUE TITLE
Curl should not offer "ALPN: h2" in ClientHello when using https-proxy.

### ISSUE THREAD

**Issue by phuslu** [curl/curl#1254]
### I did this
`curl -vv -x https://<myproxy>.phus.lu https://httpbin.org/get`
NOTE: <myproxy>.phus.lu is a http2/https both compatiable proxy.
Output:
```
*   Trying 27.102.70.243...
* TCP_NODELAY set
* Connected to (nil) (27.102.70.243) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Proxy certificate:
*  subject: CN=<myproxy>.phus.lu
*  start date: Jan 29 16:44:00 2017 GMT
*  expire date: Apr 29 16:44:00 2017 GMT
*  subjectAltName: host "(nil)" matched cert's "<myproxy>.phus.lu"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Establish HTTP proxy tunnel to httpbin.org:443
> CONNECT httpbin.org:443 HTTP/1.1
> Host: httpbin.org:443
> User-Agent: curl/7.52.1
> Proxy-Connection: Keep-Alive
> 
* TLSv1.2 (IN), TLS alert, Client hello (1):
* Proxy CONNECT aborted
* Curl_http_done: called premature == 0
* Connection #0 to host (nil) left intact
curl: (56) Proxy CONNECT aborted
```

### I expected the following
I expected curl would get the correct response from https://httpbin.org/get
But <myproxy>.phus.lu complains it(the following packet) is not a http/2 frame, so curl always failing.

### curl/libcurl version

    curl 7.52.1 (i686-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2k zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
    Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system
debian testing(stretch)

**Comment by jay** [comment]
I don't know if that's allowed behavior, or a bug in curl. I can stop the ALPN offer by doing this below, but it likely stops h2 for the tunneled connection as well
~~~diff
diff --git a/lib/vtls/openssl.c b/lib/vtls/openssl.c
index eb625fe..2751a0d 100644
--- a/lib/vtls/openssl.c
+++ b/lib/vtls/openssl.c
@@ -1977,7 +1977,8 @@ static CURLcode ossl_connect_step1(struct connectdata *conn, int sockindex)
     unsigned char protocols[128];
 
 #ifdef USE_NGHTTP2
-    if(data->set.httpversion >= CURL_HTTP_VERSION_2) {
+    if(data->set.httpversion >= CURL_HTTP_VERSION_2 &&
+       (!SSL_IS_PROXY() || !conn->bits.tunnel_proxy)) {
       protocols[cur++] = NGHTTP2_PROTO_VERSION_ID_LEN;
 
       memcpy(&protocols[cur], NGHTTP2_PROTO_VERSION_ID,
~~~
CONNECT still doesn't work since there is a chunked encoding reply:
~~~* Establish HTTP proxy tunnel to httpbin.org:443
> CONNECT httpbin.org:443 HTTP/1.1
> Host: httpbin.org:443
> User-Agent: curl/7.53.0-DEV
> Proxy-Connection: Keep-Alive
>
* Read response immediately from proxy CONNECT
< HTTP/1.1 200 OK
< Date: Wed, 08 Feb 2017 06:35:53 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
* Transfer-Encoding: in 200 response
* multi_done
* Connection #0 to host (nil) left intact
curl: (56) Transfer-Encoding: in 200 response
~~~

Please note this is a public issue tracker so anyone can see your proxy. You may want to limit unknown ips to your proxy to just httpbin.org

**Comment by bagder** [comment]
Since we don't (yet) support speaking http2 on the proxy connection we need to make sure h2 isn't asked for there. But is this really a bug in the OpenSSL backend? I would expect it to be generic so that even when built with NSS or gnutls curl does wrong?

**Comment by phuslu** [comment]
@jay Thanks for your quick reply.

For the later error 

> curl: (56) Transfer-Encoding: in 200 response

I beleive it's my proxy(named goproxy-vps) bug. And tried to fix it in https://github.com/phuslu/goproxy/commit/1bd9f57c99e32437faf3a18dbfd0fdfb89a8ad7f

Would you please verify your patch aginst the updated `bwg.phus.lu` proxy? Thank you!

**Comment by jay** [comment]
> Since we don't (yet) support speaking http2 on the proxy connection we need to make sure h2 isn't asked for there.

Though it may not be supported with the patch it's working, I'm able to do h2 over https proxy. `-v -L --proxy https://bwg.phus.lu https://www.google.com`

> Would you please verify your patch against the updated bwg.phus.lu proxy? Thank you!

It works now with my patched curl and your patched goproxy.

Still not sure if this is the best way to solve it.

**Comment by bagder** [comment]
> Though it may not be supported with the patch it's working, I'm able to do h2 over https proxy.

Right, but I meant that h2 to the proxy isn't supported. And since you mention this working *with* your patch, it no longer asks for h2 to the proxy... Talking h2 *through* the proxy should work fine.

Adding support for h2 to the proxy is something I'd like to see getting added so that libcurl could get data from N servers concurrently, over the single connection to the proxy...

**Comment by jay** [comment]
> I meant that h2 to the proxy isn't supported

Ok I see what you mean, I misunderstood. So it would seem the way I handled it in the patch is appropriate then, until h2 proxy is supported? If you agree I will make similar changes for GnuTLS and NSS, or if there is a better way please let me know because I can't think of one atm.

**Comment by bagder** [comment]
I think that seems like the best we can do right now. I think it would feel better if we could switch off at a layer on top of the TLS library, generically, but we don't have any such way at the moment.

**Comment by phuslu** [comment]
Sorry to bother you.

Any thoughts/plan for this problem? Is it a curl side bug we will fix in a future? (sorry for any misunderstanding).

**Comment by jay** [comment]
Yes it's a curl bug. I held off on committing this because I was hoping to have the time to do it in a way that's easier to maintain. If I don't get to it in a few days I'll put it in as is, but if possible with a test so that way we'll know if another backend is changed to support https proxy and does not have this same fix.

https://github.com/curl/curl/compare/master...jay:disable_h2_for_https_proxy?expand=1

**Comment by mdsteele** [comment]
> Adding support for h2 to the proxy is something I'd like to see getting added so that libcurl
> could get data from N servers concurrently, over the single connection to the proxy...

This feature (support for h2 to the proxy) would be very useful to me.  Is there an open issue and/or timeline for adding it?

**Comment by bagder** [comment]
> support for h2 to the proxy

There's no timeline and I'm not aware of anyone working on it.
