### ISSUE TITLE
AppVeyor build failures do not always show in log output

### ISSUE THREAD

**Issue by jay** [curl/curl#12560]
I'm reviewing some CI jobs from a [recent PR](https://github.com/curl/curl/pull/12482) and I noticed that a bunch failed in appveyor. For example [this one](https://ci.appveyor.com/project/curlorg/curl/builds/48795111/job/03e930dvk7t6swi9?fullLog=true). When they fail the last line of the log always looks something like:

`The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: ../../../docs/examples/10-at-a-time.c: In function 'main':`

but that's it, that's the last line. It doesn't actually show the compilation error so I don't know what needs to be fixed.

**Comment by icing** [comment]
Yes, saw that too several times. I  suspect the CI server cancelled maybe?

**Comment by vszakats** [comment]
I've been documenting this issue since moving from MS-DOS batches to PowerShell in `appveyor.yml`. I don't know what the solution is.

PowerShell offers two options:
- 'stop' on error, this will stop on error, but fails to show what the error is! (except the first line)
- 'continue' on error, this will show the full error, but not stop on them.
To make it worse, the PowerShell versions running in CI also consider an error when a called process outputs something to stderr. This has been fixed in recent released.

Current situtation is almost unusable, to show errors one needs to switch between abort/continue back and forth.

This is so wrong, I'm fairly sure I'm missing something, but days/weeks of search didn't help finding a solution.

**Comment by vszakats** [comment]
If there is no better way with PowerShell, another way to fix this is moving to an external shell script. Here's an implementation made back then (with posts related to this issue):
https://github.com/curl/curl/pull/11999#issuecomment-1742092357

More links:
https://github.com/curl/curl/pull/12444#issue-2022050649 (this issue)
https://github.com/curl/curl/pull/11976#issuecomment-1741725058 (why not MS-DOS batches)

**Comment by jay** [comment]
I agree bash would be better or at least easier to manage. Thanks for working on it. Some batch scripts that we use are inescapable because we have them for Windows systems without a unix shell, but as you know they can be called from bash.
