### ISSUE TITLE
--remote-time (-R) doesn't work with --output-dir

### ISSUE THREAD

**Issue by hgdagon** [curl/curl#12614]
### I did this

 curl --create-dirs -JRO --output-dir "some/path/" "https://someurl.com/somefile/download"

### I expected the following

The file to be created at `some/path` with the remote timestamp set

### curl/libcurl version

curl 8.5.0 (x86_64-pc-cygwin) libcurl/8.5.0 OpenSSL/3.2.0 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.58.0
Release-Date: 2023-12-06
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Windows. curl download from MSYS2's MinGW64 repository.

**Comment by Montg0mery** [comment]
Just to help anyone else searching: this is actually only when `--remote-header-name` is also included.

The error I was getting was:
```
Warning: Failed to set filetime 1571296705 on 'foo.iso': No such file or 
Warning: directory
```

If you only used the two options in this issue title, it worked fine. It was the combination of all three that caused the issue (`--remote-header-name`, `--remote-time` and `--output-dir`).

It was fixed in curl 8.6.0 (thanks!).
