### ISSUE TITLE
Reintroducing old bug with LDFLAGS

### ISSUE THREAD

**Issue by dago** [curl/curl#12824]
### I did this

Hi Daniel,

I just wanted to update to 8.6.0 and noted that the old LDFLAGS issue was reintroduced in
  https://github.com/curl/curl/commit/444f64b3e93bbb0b6a65ffa10c5bb3d1becfc140
I still get the old errors from my initial bug report linked from the commit. Is there a suggested way I can resolve this after your revert?

Best regards -- Dago

### curl/libcurl version

curl 8.6.0

### operating system

Solaris 10 Sparc

**Comment by bagder** [comment]
All changes we merge are done because we think they improve the general state of things. If a change introduces a bug, then we work on fixing that bug.

This was not *my* revert so I don't understand why you address me here. Also: as can be seen in the detailed commit message by @vszakats, the change was done to address a problem.

It would help us if you clearly articulated and described the problem you get so that we can help you solve it.

**Comment by vszakats** [comment]
I'd be helpful to know what the issue is that this old hack was addressing. Based on the history available online, this wasn't exactly clear. Also the solution itself isn't something routinely done in projects (AFAICT), and sending `LDFLAGS` twice can (and did) break some things. My impression is there might exist a better fix for the original issue, if we can dig deeper in the root cause.

**Comment by vszakats** [comment]
Also 8.6.0 added support (in b365a34c60fb9fb30ab78edd1c0d8e7f859a9531, one commit earlier than the quoted one here) for the new custom env `CURL_LDFLAGS_LIB` to pass "extra" LDFLAGS to libcurl. We pass this the exact same place as the double `LDFLAGS` was passed prevously. It means that adding any necessary missing linker flags can also be passed via this new `CURL_LDFLAGS_LIB` env as a workaround.

I think the key question remains why the Solaris linker isn't finding existing libs after passing them via `-L` and `-l`.

**Comment by dago** [comment]
Hi Daniel, I somehow thought you applied the merge, sorry for that 😅

@vszakats I mistakenly set `CURL_LDFLAGS_LIB` during _configure_ time in addition to `LDFLAG` quite some time ago and thought it fixed the issue although `LDFLAGS` was still in `Makefile.am`, but of course `CURL_LDFLAGS_LIB` during _configure_ time was in fact ignored. The Solaris build works again now after setting it during _compile_ time.

Sorry for the noise!

**Comment by vszakats** [comment]
@dago: No worries and thanks for your feedback, I'm glad this workaround solved it.
