### ISSUE TITLE
POSTing with command line curl is significantly slower than wget

### ISSUE THREAD

**Issue by kevinkreiser** [curl/curl#1284]
### I did this

As part of a larger project I was writing something that generates and pipes POST bodies to gnu parallel and calls curl with them. I noticed some strange behavior in that it seemed quite slow. I first removed the downstream server as a variable then I tried tweaking the post body. Eventually I realized that GETs with the same POST data were amazingly fast. Then I thought I'd try wget in place of curl. Low and behold POSTs were wicked fast. This was devastating because I am a huge fan of curl (both command line and libcurl). So I'm thinking that there is some extra work curl does by default that I should turn off. Here is a script that demonstrates the problem:

```bash
#!/bin/bash

#make some random post bodies
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 1024 | head -n 1024 > post_bodies

#start a dumb server
python -m SimpleHTTPServer &>/dev/null &
server_pid=$!

#see how long it takes to post them all with wget
wget --version | head -n 1
echo "timing wget POSTs"
time while IFS='' read -r line || [[ -n "${line}" ]]; do wget -q -O /dev/null localhost:8000/foo? --post-data ${line}; done < post_bodies

echo

#see how long it takes to post them all with curl
curl --version | head -n 1
echo "timing curl POSTs"
time while IFS='' read -r line || [[ -n "${line}" ]]; do curl -s -o /dev/null localhost:8000/foo? --data-binary ${line}; done < post_bodies

#stop the dumb server
kill -9 ${server_pid}
```

The output of which is:

```console
GNU Wget 1.17.1 übersetzt unter linux-gnu.
timing wget POSTs

real	0m1.966s
user	0m0.196s
sys	0m0.096s

curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
timing curl POSTs

real	0m9.225s
user	0m2.696s
sys	0m1.340s
```

### I expected the following

What I expected was that curl would be approximately as fast as POSTing with wget. I'm wondering if there is a flag to pass to curl to disable some extra work that it might be doing.

### curl/libcurl version

The version of curl I am using is listed above: `curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3`

### operating system

My OS is Ubuntu Xenial: `Linux HP-ZBook-15 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by kevinkreiser** [comment]
note that I've tried `--data-raw` and `--data-binary` and saw no difference

**Comment by bagder** [comment]
First, looking at the exact requests and responses probably reveal more details, and then you could use curl's `--trace-time` option to see where time is spent.

I will however guess that you're using a stupid web server that doesn't properly support Expect: 100-continue, which makes curl wait a whole second before it sends its payload - and if you send smaller POSTs instead curl won't use that header and the time differences probably go away.

You can disable curl's use of Expect: with `-H Expect:`.

**Comment by kevinkreiser** [comment]
Thats exactly what I was seeing! When I was running it through gnu parallel the logs were looking like they'd have exactly a second between batches of requests. I'll confirm this right away!

**Comment by kevinkreiser** [comment]
It didn't seem to have any affect to disable the `Expect:` header. It looks like my POST payloads weren't big enough to trigger the continue logic for this test! Note that I am using a size of 1024 bytes. This is what I see:

```console
15:05:21.951365 *   Trying 127.0.0.1...
15:05:21.951521 * Connected to localhost (127.0.0.1) port 8000 (#0)
15:05:21.951575 > POST /foo? HTTP/1.1
15:05:21.951575 > Host: localhost:8000
15:05:21.951575 > User-Agent: curl/7.47.0
15:05:21.951575 > Accept: */*
15:05:21.951575 > Content-Length: 1024
15:05:21.951575 > Content-Type: application/x-www-form-urlencoded
15:05:21.951575 > 
15:05:21.951763 * upload completely sent off: 1024 out of 1024 bytes
15:05:21.951822 * HTTP 1.0, assume close after body
15:05:21.951856 < HTTP/1.0 501 Unsupported method ('POST')
15:05:21.951882 < Server: SimpleHTTP/0.6 Python/2.7.12
15:05:21.951920 < Date: Thu, 23 Feb 2017 20:05:21 GMT
15:05:21.951952 < Connection: close
15:05:21.951986 < Content-Type: text/html
15:05:21.952042 < 
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 501.
<p>Message: Unsupported method ('POST').
<p>Error code explanation: 501 = Server does not support this operation.
</body>
15:05:21.952097 * Closing connection 0
```

No continue header. But when I up it to something like 4096:

```console
15:05:50.489552 *   Trying 127.0.0.1...
15:05:50.489684 * Connected to localhost (127.0.0.1) port 8000 (#0)
15:05:50.489735 > POST /foo? HTTP/1.1
15:05:50.489735 > Host: localhost:8000
15:05:50.489735 > User-Agent: curl/7.47.0
15:05:50.489735 > Accept: */*
15:05:50.489735 > Content-Length: 4096
15:05:50.489735 > Content-Type: application/x-www-form-urlencoded
15:05:50.489735 > Expect: 100-continue
15:05:50.489735 > 
15:05:50.489975 * HTTP 1.0, assume close after body
15:05:50.490019 < HTTP/1.0 501 Unsupported method ('POST')
15:05:50.490061 < Server: SimpleHTTP/0.6 Python/2.7.12
15:05:50.490098 < Date: Thu, 23 Feb 2017 20:05:50 GMT
15:05:50.490134 < Connection: close
15:05:50.490168 < Content-Type: text/html
15:05:50.490192 < 
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 501.
<p>Message: Unsupported method ('POST').
<p>Error code explanation: 501 = Server does not support this operation.
</body>
15:05:50.490237 * Closing connection 0
```

You can see that it does send the `Expect` header but the wait time is about the same.

**Comment by kevinkreiser** [comment]
So the next thing I tried was to remove the need for dns by changing the requests to the loopback address. And that cut the time in half but its still more than 2x slower than wget:

```bash
#!/bin/bash

#make some random post bodies
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 1024 | head -n 1024 > post_bodies

#start a dumb server
python -m SimpleHTTPServer &>/dev/null &
server_pid=$!

#see how long it takes to post them all with wget
wget --version | head -n 1
echo "timing wget POSTs"
time while IFS='' read -r line || [[ -n "${line}" ]]; do wget -q -O /dev/null http://127.0.0.1:8000/foo? --post-data ${line}; done < post_bodies

echo

#see how long it takes to post them all with curl
curl --version | head -n 1
echo "timing curl POSTs"
time while IFS='' read -r line || [[ -n "${line}" ]]; do curl -s -o /dev/null http://127.0.0.1:8000/foo? -H "Expect:" --data-binary ${line}; done < post_bodies

#stop the dumb server
kill -9 ${server_pid}
```

has an output of:

```console
GNU Wget 1.17.1 übersetzt unter linux-gnu.
timing wget POSTs

real	0m1.835s
user	0m0.228s
sys	0m0.064s

curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
timing curl POSTs

real	0m4.077s
user	0m0.308s
sys	0m0.088s
```

**Comment by kevinkreiser** [comment]
I noticed that when doing something like:

`time curl --verbose --trace-time -H Expect: 127.0.0.1:8000/foo? --data-binary $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 1024 | head -n 1)`

The manual says that using `--data-binary` means that nothing is done to the POST payload. But the content type is still sent as: `Content-Type: application/x-www-form-urlencoded` is that what I should be seeing?

**Comment by bagder** [comment]
Yes, that's the default content type curl passes for POSTs. So does --trace-time show any obvious time gaps? I was also pondering if `--tcp-nodelay` would have any effect (it is set by default in modern curl versions).

**Comment by kevinkreiser** [comment]
Setting `--tcp-nodelay` didn't seem to have an impact in this case. I cant really see any significant delays in the timing information. The only two of note are the connection and then the time between sending request and receiving response part of the transaction with the server.

**Comment by jay** [comment]
Could it be due to some initial loading of a shared library? Try profiling it, if there is a way to collect statistics on all of them in one report. Not the same but I ran it as a glob and got some results from perf
~~~
perf record curl -s -o /dev/null localhost:8000/foo?[0-1000] --data x
chmod +rwx perf.data
perf report -f
~~~
results:
~~~
  90.58%  curl     [kernel.kallsyms]   [k] __lock_text_start
   0.38%  curl     [kernel.kallsyms]   [k] kfree
   0.38%  curl     libcurl.so.4.4.0    [.] dprintf_formatf
   0.25%  curl     [kernel.kallsyms]   [k] __skb_clone
   0.25%  curl     [kernel.kallsyms]   [k] do_setitimer
   0.25%  curl     [kernel.kallsyms]   [k] nf_iterate
   0.25%  curl     libc-2.23.so        [.] malloc_consolidate
   0.25%  curl     libcurl.so.4.4.0    [.] multi_runsingle
   0.25%  curl     libnettle.so.6.2    [.] _nettle_sha256_compress
~~~

**Comment by kevinkreiser** [comment]
i'll give this a look in my spare time. feel free to close this issue. i know i always hate when i let "performance characteristics" issues linger in github repos ;)

thanks for the help guys!

**Comment by bagder** [comment]
It is clearly either startup or shutdown time. When I trace curl --trace-time I can see each round taking about 10 milliseconds and about 9(!) of them is spent after the operation until the next one starts:

~~~
18:14:15.420599 == Info: Curl_http_done: called premature == 0
18:14:15.420605 == Info: Connection #0 to host localhost left intact
18:14:15.431455 == Info:   Trying 127.0.0.1...
18:14:15.431509 == Info: TCP_NODELAY set
~~~

I get about the same gap when I run my local dev build, but in total my own build runs the 1024 posts in 7 seconds while the Debian curl takes 11 seconds.

I'll dig some more.

**Comment by bagder** [comment]
My curl uses OpenSSL, my wget uses gnutls.

It looks like startup time, mostly due to linking shared libs. So I strace both posts. curl does 45 open() calls, wget does 39. Almost the same amount.

Then I check the time from the first open() (which is for the file "/etc/ld.so.cache" for both tools) until the time for the last common file they open ("/usr/lib/x86_64-linux-gnu/libffi.so.6"). Ie that it all linker code, before curl has even started.

In the curl case, that takes a whipping 8600 us on my machine, where as the same delta with wget takes 3034 us. That explains 5 milliseconds.

From the ffi open() until the tool sends the POST command (curl uses sendto(), wget uses write()) takes 11759 us for curl, 4419 us for wget. This difference is harder to explain. In a test build using gnutls instead of openssl, that first delta remains basically the same while the second delta shrinks to 5800 us, which is at least much closer to wget.

[opens.txt](https://github.com/curl/curl/files/831891/opens.txt)
[strace-curl.txt](https://github.com/curl/curl/files/831893/strace-curl.txt)
[strace-wget.txt](https://github.com/curl/curl/files/831892/strace-wget.txt)

Conclusion: just more arguments for making sure you do multiple requests/transfers per invoke rather than invoking curl many times. I'm not going to spend much more of my time trying to optimize this startup time at this point in time. It's just "room for improvement", not a real bug. I will close this issue soon unless someone else has more feedback, questions or related progress.

**Comment by kevinkreiser** [comment]
That makes sense to me! Thanks for the thorough investigation!
