### ISSUE TITLE
Potential integer overflow in Curl_timediff, Curl_timediff_ceil, Curl_timediff_us

### ISSUE THREAD

**Issue by vulnerabilityspotter** [curl/curl#12991]
### I did this

(reporting here as likely without practical security impact and low probability of occurrence)

In the below
```
timediff_t Curl_timediff(struct curltime newer, struct curltime older)
{
  timediff_t diff = (timediff_t)newer.tv_sec-older.tv_sec;
  if(diff >= (TIMEDIFF_T_MAX/1000))
    return TIMEDIFF_T_MAX;
  else if(diff <= (TIMEDIFF_T_MIN/1000))
    return TIMEDIFF_T_MIN;
  return diff * 1000 + (newer.tv_usec-older.tv_usec)/1000;
}
```
The potential overflow/underflow of ``diff * 1000`` is tested, but adding ``(newer.tv_usec-older.tv_usec)/1000`` to it could still overflow/underflow
Same pattern in Curl_timediff_ceil and Curl_timediff_us

### I expected the following

-

### curl/libcurl version

f47487c219978cd9d9db34f7b1669e5e44051af1

### operating system

All

**Comment by bagder** [comment]
Agreed. Although I would perhaps not even call it "low probability". It is *extremely* unlikely to ever trigger in normal applications since `timediff_t` is (always) a signed 64 bit value.

**Comment by bagder** [comment]
Wait, since the comparisons are done with `>=` and `<=`, I believe  they work fine.

Example for Curl_timediff:

max is 9223372036854775808

Let's say diff equals max/1000 == 9223372036854775, then that will return TIMEDIFF_T_MAX without trying to add anything more (even though in *could* actually fit another 808 milliseconds).

If diff is instead one second less (9223372036854774), then that can add 1000 milliseconds to the final value without overflow.

**Comment by vulnerabilityspotter** [comment]
Agreed. Apologies
