### ISSUE TITLE
Fail to configure with mbedTLS after update libcurl 8.5.0 to 8.6.0

### ISSUE THREAD

**Issue by synchronicbed** [curl/curl#13147]
### I did this

I update from libcurl 8.5.0 to 8.6.0.
I use mbedTLS 
This joined file is the trace in console :
[party.libcurl.8.6.0.log](https://github.com/curl/curl/files/14648051/party.libcurl.8.6.0.log)

### I expected the following

With libcurl 8.5.0, I have no problem like this trace in console :
[party.libcurl.8.5.0.log](https://github.com/curl/curl/files/14648052/party.libcurl.8.5.0.log)

### curl/libcurl version

libcurl 8.6.0

### operating system

Debian 8 - 64 bits : Linux sy-zz-lvm-vi39 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux
Cross compile for ARMv7a
[party.libcurl.8.6.0.log](https://github.com/curl/curl/files/14648051/party.libcurl.8.6.0.log)
[party.libcurl.8.5.0.log](https://github.com/curl/curl/files/14648052/party.libcurl.8.5.0.log)

**Comment by bagder** [comment]
The `[party.libcurl.8.6.0.log](https://github.com/curl/curl/files/14648051/party.libcurl.8.6.0.log)` shows configure invoked twice.

1. On line 3966 it is invoked, but fails because libpsl is not found and not disabled. See this blog post for explanation: https://daniel.haxx.se/blog/2024/01/10/psl-in-curl/
2. On line 4187 it is invoked again, seemingly without any arguments at all. Then it fails because there is no TLS library selected, and TLS is not disabled.

**Comment by synchronicbed** [comment]
Hi,
I added "--without-libpsl" on my configure and it's OK
Thank you.

**Comment by synchronicbed** [comment]
Issue resolved
