### ISSUE TITLE
HTTP/3 fallback broken if UDP port is firewall'ed

### ISSUE THREAD

**Issue by msrd0** [curl/curl#13162]
### I did this

I opened nheko, an application that uses curl for its http(s) traffic, connecting to a server that has an http/3 enabled webserver running (caddy) but allows only incomming tcp connections. Nheko maintainer says this is likely a curl problem, so reporting here.

### I expected the following

The application loads as expected. Instead, I got an unable to connect error.

### curl/libcurl version

local/curl 8.6.0-3

### operating system

arch

**Comment by bagder** [comment]
Please tell us more. Like how to reproduce for example.

**Comment by msrd0** [comment]
Reproduce:

 - Launch synapse server
 - Reverse proxy through caddy
 - Enable ufw firewall for WWW Secure (that forgot to include 443/udp)
 - Open nheko on archlinux that has http/3 enabled
 - Observe the problem

**Comment by icing** [comment]
This seems to be beyond my ken to set up. Maybe the nheko maintainer can provide a detailed curl trace for the situation?

**Comment by bagder** [comment]
Is your local curl version built to support HTTP/3?

**Comment by bagder** [comment]
No response

**Comment by kleinesfilmroellchen** [comment]
This doesn’t seem like a fixed issue, but unfortunately the Nheko reproduction is rather convoluted. I would appreciate if this issue was not marked as closed even if no repro has been performed so far. All you really need to do is:
- have a firewall that blocks all UDP traffic on 443
- connect to a server via HTTP/3 (look for the relevant options in nheko’s use of libcurl)

**Comment by icing** [comment]
We never marked this as fixed. We closed the issue since we did not get any response from the reporter. To reproduce this, we would need to know how libcurl is being configured and what exactly the observed behaviour is. A debug trace would be ideal, of course.

I had a glance at nheko (I assume it is git@github.com:Nheko-Reborn/nheko.git ?), but I did not see how libcurl was used there. Is it just building the curl command line tool itself and run it? Then it should be easy to have it generate a trace.

Please understand that we do have the man power to dive into applications unknown to us and figure out exactly how to reproduce an issue. We need to meet somewhere in the middle and, should the problem require changes in how nehko uses curl, ideally we need its maintainer here as well.

**Comment by kleinesfilmroellchen** [comment]
> We never marked this as fixed. We closed the issue since we did not get any response from the reporter. To reproduce this, we would need to know how libcurl is being configured and what exactly the observed behaviour is. A debug trace would be ideal, of course.

In this case, marking an issue as “completed” is very confusing to outside viewers...

> I had a glance at nheko (I assume it is [git@github.com](mailto:git@github.com):Nheko-Reborn/nheko.git ?),

Yes, that’s the correct project.

> but I did not see how libcurl was used there. Is it just building the curl command line tool itself and run it? Then it should be easy to have it generate a trace.

I wasn’t aware of this, I might try and at least post the command here.

**Comment by kleinesfilmroellchen** [comment]
I tried tracing nheko to see how it runs curl, but on my version it just uses libcurl normally, meaning that there is no easy way of figuring out how it is being invoked.

**Comment by bagder** [comment]
> In this case, marking an issue as “completed” is very confusing to outside viewers...

We closed it because we did not get any responses. If we don't have enough data and details to work on a bug, we close them if they get abandoned by the reporter. Like this was.

**Comment by q234rty** [comment]
> but I did not see how libcurl was used there

I believe nheko uses curl through [coeurl](https://nheko.im/nheko-reborn/coeurl) which does https://nheko.im/nheko-reborn/coeurl/-/blob/master/lib/request.cpp?ref_type=heads#L136-L137
