### ISSUE TITLE
Build error on IBM i

### ISSUE THREAD

**Issue by johnsherrill** [curl/curl#13186]
### I did this

sh makefile.sh > makelog 2>&1 
result was this:
CPC7301:  File DOCS created in library CURLIBMI.
CPC7305:  Member COPYING added to file DOCS in CURLIBMI.
CPCA087:  Object copied.
CPC7305:  Member README added to file DOCS in CURLIBMI.
CPCA087:  Object copied.
CPC7305:  Member CHANGES added to file DOCS in CURLIBMI.
CPC7309:  Member CHANGES removed from file DOCS in CURLIBMI.
CPFA0D9:  Character string not converted.

file CHANGES as a character that can not be converted to EBCDIC.

The problem can be circumvented by making a change to makefile.sh
change line 68: from 
CMD="${CMD} DTAFMT(*TEXT) REPLACE(*YES)"
to this
CMD="${CMD} DTAFMT(*TEXT) REPLACE(*YES) FROMCCSID(819)"

### I expected the following

It to work.

### curl/libcurl version

curl 8.6.0

### operating system

IBM i 7.5

**Comment by dfandrich** [comment]
@monnerat

**Comment by bagder** [comment]
That line has been there since a892cf2c12c77!

**Comment by jay** [comment]
It might be happening because the git log contains utf-8 characters?

> CMD="${CMD} DTAFMT(*TEXT) REPLACE(*YES) FROMCCSID(819)"

819 is latin 1 aka ISO-8859-1, not utf-8

**Comment by monnerat** [comment]
> CMD="${CMD} DTAFMT(*TEXT) REPLACE(*YES) FROMCCSID(819)"

I don't agree:

819 is latin1 ASCII superset, while the sources are initially UTF-8. CCSID 1208 should then be used but depending on how the files have been created, this may be wrong. I would then recommend to store source files in IFS converted into a well known EBCDIC variant CCSID (the conversion is generally done at file creation time: see below).

The problem you have here is probably the files have been stored unconverted (UTF-8), but tagged with the default EBCDIC CCSID of your system, which is used by the `CPY` command when no `FROMCCSID` parameter is given.

The real solution is by resolving a typical OS400 boring task: manage to have your files' CCSID and contents, job CCSID and *LOCALE (`LANG` environment variable) being well defined and oonsistent.

As an example, here is my case, for an iSeries located in germany:
- On the workstation: `tar cf curl.tar curl`, then `scp curl.tar user@iseries.url:`.
- On the OS400: `WRKENVVAR` then change `LANG` to `/QSYS.LIB/DE_DE_PE.LOCALE`
- On the OS400: enter `QSH` then `tar xf curl.tar`.  The files are converted to EBCDIC at this time.
- When you type` ls -S curl/CHANGES`, you should see 273, which is consiistent with `DE_DE_PE` locale. Additionally you can `cat curl/CHANGES` and it should be listed properly.

You should adapt the above to your own case.

**Comment by bagder** [comment]
Maybe we could just leave the text files from the build to be converted or not by the user by themselves?

**Comment by jay** [comment]
@monnerat can you clarify, is this a bug in curl or user error because I can't tell

**Comment by johnsherrill** [comment]
I used WinSCP to ftp the curl directory from my PC to my IBM i. I did the transfer in binary and ended up with all the files tagged as CCSUD 1208. So the cpy does not work for changes since it contains something that can not be converted to CCSID 500. 
I could try ftp in text mode and the file would end up my my case in CCSID 37, then maybe it would work.

**Comment by monnerat** [comment]
> can you clarify, is this a bug in curl or user error because I can't tell

It's definitively not a curl bug, rather a bad OS400 file handling procedure. Explanation:

- OS400 holds a CCSID attribute within each file: it describes the file contents encoding and is established at file creation time. This defaults to the system's configured CCSID (country dependent).
- Nothing prevents creating a text file with inconsistent CCSID attribute and actual data encoding: this is the responsibility of the user and the way he does it.
- An OS400 job also has a CCSID attribute: when some program opens a file in text mode, read data are converted from the file's CCSID to the job one. If file data is inconsistent, converted text will be too, if ever possible.

>  I did the transfer in binary and ended up with all the files tagged as CCSUD 1208.

1208 is UTF-8: the files are consistent, then.

> So the cpy does not work for changes since it contains something that can not be converted to CCSID 500.

No, it doesn't. If you look at the `CHANGES` file on your PC, you'll see it only contains 7-bit ASCII characters.

Again, I wouldn't recommend keeping files as UTF-8 since this may also affect other commands than `CPY`.

> I could try ftp in text mode and the file would end up my my case in CCSID 37, then maybe it would work.

Yes you can. But as you'll mix CCSIDs at build time (37/500), be sure you'll have well-defined job's CCSID and locale. I used to manage this way with success, although the CCSID values were not the same.
