### ISSUE TITLE
libcurl closes HTTPS connection with "excess found in a read" even if CURLOPT_FORBID_REUSE is 0

### ISSUE THREAD

**Issue by Ymitrofanov** [curl/curl#13201]
### I did this

Hello!
I'm using libcurl.a which I built from downloaded curl-curl-8_5_0.zip, i.e. my application uses libcurl API to request web server via HTTPS
My application establishes HTTPS connection with web server, and to have this connection always keep-alived I'm trying to use option CURLOPT_FORBID_REUSE, setting it 'false': curl_easy_setopt(enEasyHandle, CURLOPT_FORBID_REUSE, 0); curl_easy_setopt(enEasyHandle, CURLOPT_FRESH_CONNECT, 0);
I want to use HTTPS keep-alive connection to have best performance without TLS session reestablishing for every request.
But I see that libcurl closes a connection and my application cannot use it.
I see  in tcpdump that my application closes a connection (because libcurl closes it really), and also I debug my application with libcurl and see that libcurl calls sendf.c:connclose(data->conn, "excess found in a read"); which forces a connection to close. It happens because excess_len = 2.

### I expected the following

I expected connection reusing if I set CURLOPT_FORBID_REUSE = 0 and CURLOPT_FRESH_CONNECT = 0 even if web server sends 2 bytes as excess.

Is it possible to force connection reusing in this case?

BTW:  If I commented off (disabled) this call:/*connclose(data->conn, "excess found in a read");*/, then a connection is alive and I have good performance.

Thank you!

### curl/libcurl version

curl 8.5.0

### operating system

Red Hat Enterprise Linux 9.3 (Plow)

**Comment by bagder** [comment]
Excess data is data that should not be there. That data means the server is not playing by the rules and when the other end is not following the protocol, curl plays it safe and closes the connection as it can no longer safely use it. This is done intentionally.

**Comment by Ymitrofanov** [comment]
Thank you for fast response!

Excess characters are 0xA and 0xD (\n\r) at the end of HTTP message body.
Excess is because server specified header in a response "Content-Length: 3928", but really it sent nbytes 3930.
So, libcurl closes TLS connection because of it.

But when we are running the same test on Red Hat Enterprise Linux Server 7.8 (Maipo) with curl-7.31 we have no such issue, connection is alive. But with libcurl 8.5.0 it's not, and it reconnects on every request, and we have performance degrade in 16 times.

As I understgand, it's not possible to know about the reason of connection closing, libcurl doesn't warn about it. I only could undestand the reason debugging libcurl which I have built from source code to static library.

Maybe it will be useful improvement to warn a user with some status with the reason of connection closing in case of unexpected bad things, such as incorrect content length? It will help us to find a reason in a short time, espesially it's important if our service will be blocked in runtime on real system because of just Content-Length.

**Comment by jay** [comment]
> If I commented off (disabled) this call:/connclose(data->conn, "excess found in a read");/, then a connection is alive and I have good performance.

Whether or not that works the way you expect is timing dependent.

1. It's possible the excess two bytes are received after the excess detection check from the first transfer but before the connection can be reused for the second transfer, in which case libcurl will treat the connection as "dead" and open a new connection.

2. or it's possible the excess two bytes are received after the connection is reused and the second transfer request is sent, in which case libcurl will see it in the in status line and error. Example `\n\rHTTP/1.1 200 OK` instead of `HTTP/1.1 200 OK` will cause an error HTTP/0.9 not allowed.

> But when we are running the same test on Red Hat Enterprise Linux Server 7.8 (Maipo) with curl-7.31 with the same server we have no such issue, connection is alive. But with libcurl 8.5.0 it's not, and it reconnects on every request, and we have performance degrade in 16 times.

7.31.0 is over a decade old. Either libcurl is now better at catching the problem, there's a timing difference or the request and response differ when you use that version.

> Maybe it will be useful improvement to warn a user with some status with the reason of connection closing in case of unexpected bad things, such as incorrect content length?

The verbose output already says `* Excess found writing body` but as I said it's timing dependent whether or not you'll actually see that.

I suggest contact the site owner and ask them to fix the problem.
