### ISSUE TITLE
lib/cf-h1-proxy.c: `-Wnull-dereference` warnings with gcc 12 / curl 8.7.1

### ISSUE THREAD

**Issue by vszakats** [curl/curl#13237]
### I did this

Built curl-for-win with gcc + mingw-w64.
Got these warnings:
```
.../curl/lib/cf-h1-proxy.c:1060:17: warning: null pointer dereference [-Wnull-dereference]
 1060 |   cf->connected = FALSE;
      |                 ^
.../curl/lib/cf-h1-proxy.c:1061:8: warning: null pointer dereference [-Wnull-dereference]
 1061 |   if(cf->ctx) {
      |      ~~^~~~~
In function 'tunnel_free',
    inlined from 'cf_h1_proxy_destroy' at .../curl/lib/cf-h1-proxy.c:1053:3:
.../curl/lib/cf-h1-proxy.c:198:27: warning: null pointer dereference [-Wnull-dereference]
  198 |   struct h1_tunnel_state *ts = cf->ctx;
      |                           ^~
```
Ref: https://github.com/curl/curl-for-win/actions/runs/8492022102/job/23264582018#step:3:10749

### I expected the following

No warnings.

### curl/libcurl version

curl 8.7.1

### operating system

Windows (seems OS-agnostic)

**Comment by bagder** [comment]
Grr, this the overcomplaining errors from gcc's static analyzer coming.  Quite annoying.

This happens because in:
~~~c
  CURL_TRC_CF(data, cf, "close");
  cf->connected = FALSE;
~~~
... the macro on the first line checks if `cf` is non-NULL, which then gcc takes as a confirmation it should complain on line two which uses `cf` without a NULL check.

I find this warning annoying and counter-productive. The macro is fine to use protection because it can be used in places where maybe it can be a NULL pointer passed to it. It does mean that a NULL pointer is accepted in every place the macro is used.

**Comment by vszakats** [comment]
I guess a few false positives is the price to pay for detecting real issues.
Also an extra NULL check here in there is probably better than missing
one by accident. But yeah, this is annoying.

The other thing I wondered why this wasn't caught in CI. E.g. in this job (mingw, gcc13, unity): https://ci.appveyor.com/project/curlorg/curl/builds/49500338/job/opyx2nhk46vop8b3?fullLog=true

Then noticed that the affected gcc version was actually 12.0.0, not 13.2.0.
So this may have been fixed, unless I'm missing something other difference.

**Comment by vszakats** [comment]
This remains valid, but I don't want to offend anybody with warnings popping up in tests.
