### ISSUE TITLE
[feature] suggest for add request post body string print out on `verbose` model

### ISSUE THREAD

**Issue by zfjoy520** [curl/curl#1334]
currently, when set verbose `true`, I can get all debug infos, include these types:

```c
typedef enum {
  CURLINFO_TEXT = 0,
  CURLINFO_HEADER_IN,    /* 1 */
  CURLINFO_HEADER_OUT,   /* 2 */
  CURLINFO_DATA_IN,      /* 3 */
  CURLINFO_SSL_DATA_IN,  /* 5 */
  CURLINFO_END
} curl_infotype;
```

except:
```
CURLINFO_DATA_OUT,     /* 4 */
CURLINFO_SSL_DATA_OUT, /* 6 */
```

so, if I need to check the request post body string, I need to custom my on_debug_callback by myself, with the `curb` ruby gem(https://github.com/taf2/curb),  in ruby language, like followings:

```ruby
class LogFormatter
  PROC_MAPPING = {0 => :text, 1 => :header_in, 2 => :header_out, 3 => :data_in, 4 => :data_out}.freeze
  # on_debug types
  # 0 - TEXT
  # 1 - HEADER_IN
  # 2 - HEADER_OUT
  # 3 - DATA_IN
  # 4 - DATA_OUT
  def initialize(type, data)
    PROC_MAPPING.key?(type) ? send(PROC_MAPPING[type], data.lstrip) : nil
  end

  def text(data)
    @data = if data.start_with?('upload completely sent off')
              $RS * 2
            elsif data.start_with?('Curl_http_done')
              ''
            elsif data.start_with?('Connection #0 to', 'Closing connection')
              "Conn close\r\n"
            else
              '* ' + data
            end
  end

  def header_in(data)
    @data = data.chomp.empty? ? '' : data.insert(0, '-> ')
  end

  def header_out(data)
    @data = data.lines.map! { |string| string.chomp.empty? ? nil : string.insert(0, '<- ') }.compact.join
  end

  def data_in(data)
    lines = data.lines
    data = lines[1].chomp if lines.size == 4
    @data = data.inspect.insert(0, '-> ') + "\r\n"
  end

  def data_out(data)
    @data = data.insert(0, '<- ')
  end

  def to_s
    @data
  end
end
```

```ruby
 verbose && http.on_debug { |type, data| $stderr << LogFormatter.new(type, data) }
```

the output like this:

```c
* Trying 0.0.0.0...
* TCP_NODELAY set
* Connected to xxx port 80 (#0)
<- POST /xxx HTTP/1.1
<- Host: xxx
<- Accept: */*
<- Content-Length: xxx
<- {"a":1,"b":2,"c":3}

-> HTTP/1.1 201 Created
-> Server: Tengine
-> Date: Fri, 17 Mar 2017 05:36:50 GMT
-> Content-Length: 67
-> Connection: keep-alive
-> "{\"msgId\":\"xxx\",\"sendStatus\":\"SEND_OK\"}"
Conn close
```
so,  I can check my request body string `<- {"a":1,"b":2,"c":3}`, see it's correct or not.

please add the feature in the source of c language, thanks.

**Comment by jay** [comment]
I like this idea. Racking my brain I can't help but wonder if maybe this is already implemented and I just am not aware of it.

Unfortunately unless someone is willing to work on a feature request they usually are closed out as an issue. We have too many maintenance things that there is little time to work on these.

**Comment by frenche** [comment]
+1
I like it too, in fact I wanted to look at this for a while, especially for the tool's '-v' use case.
From the OP's description it sounds rather a simple change, so if no one picks it up I'll give it a try.

**Comment by bagder** [comment]
The main reason I left out the sent data from verbose output originally is that it can get really large at times. Like when doing uploads.

**Comment by frenche** [comment]
Right, I suspected it may be in purpose, as it could be big and the user should know what he sent anyway.
But sometimes curl fiddles with the data and it helps to see what actually got sent.
Perhaps we can consider a new verbose-plus or -vv options?

**Comment by jay** [comment]
That sounds interesting. In the library it would probably be easy to handle, CURLOPT_VERBOSE  treat 2, 3, 4  as different levels, then when sending post data

if(data->set.verbose >= 2)
  infof(data, "foo");

or just macro it out extra_infof(data, "foo"); infof_L2(data, "foo"); etc

In the tool it looks like actual work though because [the --verbose check](https://github.com/curl/curl/blob/curl-7_53_1/src/tool_getparam.c#L1881-L1896) and trace code in the tool uses [this enum](https://github.com/curl/curl/blob/curl-7_53_1/src/tool_sdecls.h#L122-L127):
~~~c
typedef enum {
  TRACE_NONE,  /* no trace/verbose output at all */
  TRACE_BIN,   /* tcpdump inspired look */
  TRACE_ASCII, /* like *BIN but without the hex output */
  TRACE_PLAIN  /* -v/--verbose type */
} trace;
~~~
so all the resulting logic bourne of that would likely need to be changed, unless there's an easy way that's escaping me
TRACE_PLAIN_V2 but that seems like it is more likely to cause errors if in the future developer x just writes TRACE_PLAIN meaning verbose and nobody checks V2
or a supporting verbose integer and then if TRACE_PLAIN && verbose > 2

just some ideas, i'm not partial to any

**Comment by bagder** [comment]
Since a lot of data sending is binary or just very long strings, some consideration for how to show that nicely is probably suitable.

Since @zfjoy520 asks for this feature for a binding, it wouldn't be enough to just fix it in the curl command line tool. The tool more or less already provides this feature with the `--trace` and `--trace-ascii` options. If the command line tool should be affected, I would probably argue that the default `-v` behavior should be updated.

For libcurl, I would probably vote for a `CURLOPT_VERBOSE` "level".

**Comment by frenche** [comment]
On Mar 21, 2017 10:52 AM, "Daniel Stenberg" <notifications@github.com>
wrote:

Since a lot of data sending is binary or just very long strings, some
consideration for how to show that nicely is probably suitable.

Since @zfjoy520 <https://github.com/zfjoy520> asks for this feature for a
binding, it wouldn't be enough to just fix it in the curl command line
tool. The tool more or less already provides this feature with the --trace
and --trace-ascii options. If the command line tool should be affected, I
would probably argue that the default -v behavior should be updated.

I didn't know trace was showing out-stream, in that case i think the tool
is fine (good for me).

For libcurl, I would probably vote for a CURLOPT_VERBOSE "level".

Or perhaps move the trace option logic to library level, and reimplement
--trace atop of it.

**Comment by frenche** [comment]
> For libcurl, I would probably vote for a CURLOPT_VERBOSE "level".

Actually, after looking at the code, this seem to be the simplest IMO.
Maybe something like this (kind of works):
https://github.com/frenche/curl/commit/663cee47c6d27ef52e8fff583211bfcf809bbc14

**Comment by bagder** [comment]
That's probably fine for text-based protocols, but what if you transfer something binary like a JPEG? (`--trace-ascii` vs `--trace` ...)

**Comment by bagder** [comment]
Stale, closing. Also, not a bug and we don't keep feature requests and their discussions here. They're better off discussed on the mailing lists or when done around pull-requests. Thank you!
