### ISSUE TITLE
CURLOPT_LOW_SPEED_LIMIT and progress.c issue

### ISSUE THREAD

**Issue by paulharris** [curl/curl#1345]
I want to set a very low speed limit for a long-poll scenario.

I set the CURLOPT_LOW_SPEED_LIMIT and _TIME parameters,
but it often tends to timeout.
I set the limit to 1 byte per minute as the lowest limit.

I believe its because data->progress.current_speed = amount/span_ms
where amount is a difference between cells in the data->progress.speeder[] array.
Where the speeder[] array is filled by the maximum of:
data->progress.downloaded or data.progress.uploaded

But, the problem is the initial request is (eg) 300 bytes,
and if (eg) the response is just 1 byte per second (more than the limit, thats 60 bytes/sec),
the 'downloaded' total will still be just 60 bytes after the first minute.
So the speeder[] array will be filled with 300, and would appear that there has been no new traffic at all - the 60 bytes is completely ignored until the total downloaded is greater than total uploaded.

I haven't tested my theory, but this low-speed threshold could be also fail when the initial upload (eg an image) is very large, and the download (eg some analysis on the image) is relatively small but still significant (eg kilobytes).  
As long as uploaded > downloaded, the low speed limit will ignore the download activity.

curl 7.53.1-DEV (Linux) libcurl/7.35.0 GnuTLS/2.12.23 zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

**Comment by bagder** [comment]
I think the problem is different, but still a problem to detect low speeds through a period that is longer than ~5 seconds. I had to dig into that old code to see what it actually does and how it works. Let me try to describe what I think I found:

The `speeder[]` array is filled by the maximum of: data->progress.downloaded or data.progress.uploaded. That's true. But it stores one entry per ~second in that array and then it loops. 6 entries.

The `current_speed` is then set as the difference the last 5 seconds based on number from the speeder[] array. That's then curl's opinion of "speed right now".

Then on to the problems.

1. The low speed check is only really done once per low_time period - which seems wrong.

2. When it considers it time to check the speed, it checks if `current_speed` is lower than `low_speed_limit` so if you got 10 bytes 10 seconds ago and then nothing, you'll still be at speed 0 during the last 5 seconds so under the limit now.

## Fix?

I think we should take the last X seconds into account better so that if you set 30 seconds, it should truly count bytes the last 30 seconds. Ideally it should also still be able to check the speed every second (or so) so that 30 bytes the first second (and then nothing) still times out after 31 seconds for a 1 byte/30 seconds limit.

Are you interested in working on fixing this up for us?

**Comment by paulharris** [comment]
Hi Daniel,
I agree with what you have said, I also noticed the lack of slots,
I also think there should be 2 speeder arrays (one for upload, one for download), so that it avoids the problem I outlined too.  Do you agree with that fix?

I can probably fix this, although I'm busy for the next few weeks.  Hopefully I can spend a little time next week at least.  It doesn't sound like a lot of work to me.   Main issue I foresee is adjusting how the speeder arrays are allocated, as I assume its currently a fixed 6 slot array?  I forget, I'll check when I look at the code again.

**Comment by bagder** [comment]
Yeah it uses 6 fixed slots. I think perhaps we need to leave speeder[] as it is and do a separate handler for the low speed thing (since the existing current speed is also used for the progress callback and progress meter etc). What if you set low_speed_time to 1 byte per 10000 seconds? We can probably get away with setting some sort of maximum limit but it seems bizarre to alloc a 10000 index array just for this. Some sort of moving average perhaps? I'm not sure...

**Comment by paulharris** [comment]
Maybe just remember the start time and start number if bytes.

Then check bytes diff every second.
If enough, then reset start bytes and time.

Then it reaches end of time window, then it is too slow.

**Comment by bagder** [comment]
I think it would work with basically doing this check (every second or so).
~~~
  speed_per_second = speed_limit / speed_time

  /* some magic is needed to handle really low speed limits so that you can actually ask for
     like one byte per minute or so */

  if ( current_speed < speed_per_second ) {
     number_of_seconds_below_threshold++
     if (number_of_seconds_below_threshold > speed_time ) {
        return TIMEOUT;
     }
  }
  else {
    number_of_seconds_below_threshold = 0;
  }

**Comment by bagder** [comment]
One more try with improved logic, better math and doesn't rely as closely on getting called exactly every second - but should still - roughly.
~~~
speed_time  = seconds
speed_limit = bytes/second

INIT:

  moving_average = speed_limit;

EVERY SECOND (or so):

  moving_average -= moving_average / speed_time;
  moving_average += current_speed / speed_time;

  if ( moving_average < speed_limit ) {

     if(!timestamp) {
       timestamp = now; /* when we go under the limit */
     }

     if (time_between(timestamp, now) > speed_time ) {
        return TIMEOUT;
     }
  }
  else {
    timestamp = NULL; /* speed is above limit */
  }

**Comment by bagder** [comment]
@paulharris I realized the algorithm could be made much simpler and I've submitted a PR (#1390), please give it a check and tell me what you think!
