### ISSUE TITLE
Error during building curl-7.53.1 on OSX-EI Captain (10.11.6) with gcc-6.3.0 when using darwinssl

### ISSUE THREAD

**Issue by areuthere** [curl/curl#1353]
### I did this
./configure --prefix=${INSTALL_DIR} \
                                                        --disable-manual --enable-ipv6 --disable-ntlm-wb \
                                                        --without-krb4 --without-gssapi \
                                                        --with-darwinssl \
                                                        --without-gnutls --without-polarssl --without-cyassl \
                                                        --without-nss --without-axtls --without-libmetalink \
                                                        --without-libssh2 --disable-ldap --without-libidn
make

### I expected the following
Expected to build curl properly with HTTPS support enabled

### curl/libcurl version
7.53.1

[curl -V output]
Making install in lib
  CC       vtls/libcurl_la-darwinssl.lo
vtls/darwinssl.c: In function ‘show_verbose_server_cert’:
vtls/darwinssl.c:2090:6: error: ‘SecTrustEvaluateAsync’ undeclared (first use in this function)
   if(SecTrustEvaluateAsync != NULL) {
      ^~~~~~~~~~~~~~~~~~~~~
vtls/darwinssl.c:2090:6: note: each undeclared identifier is reported only once for each function it appears in

### operating system

OSX-EI Captain (10.11.6)

**Comment by bagder** [comment]
I'm puzzled. This must've worked for so many users already. @nickzman, any ideas?

**Comment by nickzman** [comment]
SecTrustEvaluateAsync() has been around since macOS 10.7. The only way that could fail is if the build is picking up an ancient copy of Security/SecTrust.h from before 10.7.

What version of Xcode are you using? You need to be using 7.x for El Capitan; if you have anything older installed, you'll run into trouble. Also, do you have the latest command line tools installed? You can check by running "xcode-select --install" at the command line.

**Comment by bagder** [comment]
Probably a user error and no response. Closing.
