### ISSUE TITLE
Build documentation is incorrect

### ISSUE THREAD

**Issue by pellsson** [curl/curl#1359]
If you have OpenSSL installed, but with the libraries in one place and the header files somewhere else, you have to set the LDFLAGS and **CPPFLAGS** environment variables prior to running configure. Something like this should work:

**CPPFLAGS**="-I/path/to/ssl/include" LDFLAGS="-L/path/to/ssl/lib" ./configure

Fix:
Replace **CPPFLAGS** for **CFLAGS**.

**Comment by pellsson** [comment]
...was a bit quick to post this. The configure script seems to complain about using CFLAGS for the above mentioned purpose, but with it out it drops HTTPS. Not really sure what is going on.

**Comment by bagder** [comment]
I'm not following. Is the document right or wrong? If wrong, are you talking about `INSTALL.md` ?

> configure script seems to complain

What exactly does it say? What curl version are you using?

**Comment by pellsson** [comment]
Sorry for the horribly rushed ticket. Was on my way out.

The quote is from here:
https://curl.haxx.se/docs/install.html

Version is: curl-7.53.1

However, I think you can safely disregard everything I wrote yesterday. CPPFLAGS vs. CFLAGS doesn't seem to matter (nor should they). No idea what was going on yesterday, my best bet is that I confused myself by running "curl" vs. "./curl" making it look like it CFLAGS had solved something.

The actual issue though was that when openssl is built static it creates a dependency on dlopen & friends. -ldl is not provided by the configure script when linking to check if openssl is working as expected, causing ssl support to be dropped. No idea if the fix is to always include -ldl, or if it is cleaner to just pass "-ldl" to the configure script. It would be nice to update the documentation to include the issue if the configure script is not changed.

Sorry for, mostly, wasting your time :(
/ Pelle

**Comment by bagder** [comment]
No worries, i'm glad you got it working.

When it comes to the configure script, it doesn't really do a full job to detect and work with static builds of openssl and in fact most other libs. Mostly because figuring out the dependencies for them is really tedious. OpenSSL adds -lpthreads as required for static builds for example. We've sort of left the static builds for the experts and then you can just pass in a custom LIBS to get that to work.

If someone would feel like working on improving that, we certainly wouldn't mind accepting help and patches, but it is not an area I'm personally going to spend a lot of energy in the short term future at least.
