### ISSUE TITLE
Curl sporadic splay deadlock in Windows

### ISSUE THREAD

**Issue by diecyde** [curl/curl#1360]
### I did this
After extensive testing of Curl across Linux, Windows and OSX we noticed that in the windows case, Curl could get into a deadlock situation.
This happens on very sporadic occasions. ( sometimes after days of constant transactions and sometimes within minutes)
With GDB I have traced it back to lib/splay.c (Curl_splay).
In this specific case both t->smaller and t->larger equal the pointer t itself.
When t=t->smaller or t=t->larger is then executed it will set its own pointer back to t, effectively creating a deadlock with no escape.

I was unable to trace back which part of the code actually pollutes this linked list.
For now I made an patch which protects me from this specific situation:
[curl-7.51.0.patch.zip](https://github.com/curl/curl/files/872363/curl-7.51.0.patch.zip)

```
diff -ur -p0 curl-7.51.0/lib/splay.c libcurl/lib/splay.c
--- curl-7.51.0/lib/splay.c	2016-10-10 14:12:28.000000000 +0200
+++ libcurl/lib/splay.c	2017-03-24 11:40:37.296479186 +0100
@@ -54 +54 @@ struct Curl_tree *Curl_splay(struct time
-      if(t->smaller == NULL)
+      if(t->smaller == NULL || t->smaller == t)
@@ -61 +61 @@ struct Curl_tree *Curl_splay(struct time
-        if(t->smaller == NULL)
+        if(t->smaller == NULL || t->smaller == t)
@@ -69 +69 @@ struct Curl_tree *Curl_splay(struct time
-      if(t->larger == NULL)
+      if(t->larger == NULL || t->larger == t)
@@ -76 +76 @@ struct Curl_tree *Curl_splay(struct time
-        if(t->larger == NULL)
+        if(t->larger == NULL || t->larger == t)
```
But I have the feeling there is still something else going on why this happens only under windows.

### curl/libcurl version
curl 7.48 and 7.51 and probably even more recent.
All the calls that we are doing are Https calls.
### operating system
tested on Linux, OSX and Windows.
Happens ONLY on Windows

**Comment by jay** [comment]
> I have the feeling there is still something else going on why this happens only under windows.

What is the `printf("%s\n", curl_version())` of the libcurl that you are using? Do you have a simple repro case we could try?

Crashes like this are usually due to threading. It's possible there's a bug but if you are using threading it's more possible it's that. See the [thread safety guide](https://curl.haxx.se/libcurl/c/threadsafe.html): 

_You must never share the same handle in multiple threads. You can pass the handles around among threads, but you must never use a single handle from more than one thread at any given time._

**Comment by bagder** [comment]
The splay code has had no real code changed since 2008 (commit eb68aa38e3a79e) if we ignore OOM fixes and code indents, renames etc and we have [unit tests](https://github.com/curl/curl/blob/master/tests/unit/unit1309.c#L68) for the two primary functions: insert and remove. And the same code runs on all platforms. It just seems unlikely that such a change would suddenly be required. Not impossible, but unlikely.

**Comment by diecyde** [comment]
Hello Jay the current curl we use is this:
`
curl_version_info_data *curlversion = curl_version_info( CURLVERSION_NOW );
log_printf(LOG_INFO,LOG_EXTERNAL,NULL,"current versions curl(%s), ssl(%s, %s)", curlversion->version, curlversion->ssl_version, sslThreads);

2017-03-28 08:56:11.236 I-EXT - - current versions curl(7.51.0), ssl(OpenSSL/1.0.2j, Threaded)
`
We are indeed using multiple threads.
I might tell as well that we are using the multi mechanism with an worker thread handling all the curl communication.
All calls to curl :
- curl_multi_perform
- curl_multi_fdset
- curl_multi_add_handle
Are surrounded with pthread_mutex_lock and unlock functions to make it thread safe

Sadly I don't directly have a piece of code with exposes this behaviour.
it is currently part of an larger library

**Comment by bagder** [comment]
Without a way to reproduce this problem elsewhere I'm reluctant to accept a code change like this. Until proven otherwise, my suspicion is that you're somehow not doing the right thing somewhere threading-wise and thereby ending up ruining the splay tree.

**Comment by jay** [comment]
I agree. Until there's a self-contained repro there's nothing to do here. Reopen if you have that.
