### ISSUE TITLE
Curl_http_done: called premature == 1

### ISSUE THREAD

**Issue by jananichellappan** [curl/curl#1363]
I am trying to push a directories with history that is fetched from SVN.
I get the below message

* SSL_write() returned SYSCALL, errno = 10053 | 160.00 KiB/s
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
error: RPC failed; curl 55 SSL_write() returned SYSCALL, errno = 10053
fatal: The remote end hung up unexpectedly
Writing objects: 100% (86142/86142), 2.49 GiB | 104.84 MiB/s, done.
Total 86142 (delta 47545), reused 83848 (delta 45781)
fatal: The remote end hung up unexpectedly
Everything up-to-date

### curl/libcurl version

[curl -V output]

**Comment by jay** [comment]
I don't think this is a libcurl problem, it likely is what it says, the remote end hung up unexpectedly. I notice you are trying to push a particularly large amount, that may have something to do with it. If it is reproducible contact the admin of the git server. Also you could try switching to ssh.

**Comment by jananichellappan** [comment]
Hi

Thanks for the reply!!
Could you share the link as how to use SSH in windows environment?

Regards,
Janani

**Comment by jay** [comment]
This is not the right place for that question, since this is an issue tracker for libcurl. I will cover it briefly. If you have a git repo like for example https://github.com/jananichellappan/trial

~~~
$ git remote -v
origin  https://github.com/jananichellappan/trial.git (fetch)
origin  https://github.com/jananichellappan/trial.git (push)
~~~

Change it to ssh:

~~~
$ git remote set-url origin git@github.com:jananichellappan/trial.git
~~~

You will need to set a key as well. Also, GitHub Desktop directions are probably different.

Read more at https://help.github.com/articles/connecting-to-github-with-ssh/
