### ISSUE TITLE
Android has a broken CLOCK_MONOTONIC_RAW

### ISSUE THREAD

**Issue by AzanovAA** [curl/curl#13826]
### I did this

Simple curl query from a simple Android program times out or hangs.  
To test, run a simple Android program using the curl library for example on Android 6.0(API 23).

I have identified the commit that is causing this error: https://github.com/curl/curl/commit/da5dcb70071fc895852bc17660b0d4fed3ffbfb1

No issue before that commit.

### curl/libcurl version

curl >= 8.4.0

### operating system

Android 8.1 or lower

**Comment by vszakats** [comment]
The patch detects if `clock_gettime(CLOCK_MONOTONIC_RAW, ...)` is supported and uses it if it is. It can mean two things: The detection is wrong, or, despite the correct detection, the feature is unusable on that platform.

What happens if you build with autotools? Is the feature `checking for raw monotonic clock_gettime` detected? Does curl hang/timeout there?

Meanwhile with CMake you can force-disable this with the option: `-DHAVE_CLOCK_GETTIME_MONOTONIC_RAW=OFF`

**Comment by AzanovAA** [comment]
Thank you. Disabling HAVE_CLOCK_GETTIME_MONOTONIC_RAW fixes the issue.
The program works stably on new versions of Android, and the same apk does not work on older ones.
I believe that this option is enabled when building the apk, but the same apk does not work on older versions of Android.

**Comment by vszakats** [comment]
We'd need to make a runtime check to skip this feature on older Android versions as it seems? (We already do that for Apple platforms). We'd be happy to review a patch for that, or an alternate solution to address it, e.g. auto-disabling this feature when targeting an Android version older than N.

**Comment by AzanovAA** [comment]
Yes, that would be useful. It took me several days to figure out this bug. I wouldn't want other people to experience this.

**Comment by bagder** [comment]
Is there an agreed-upon method on how to detect Android for this so that we can mark that as having a buggy implementation?

**Comment by vvb2060** [comment]
avd api 23 works fine

![image](https://github.com/curl/curl/assets/26996262/07006ab8-ea0a-4fba-a041-37f28314723d)

**Comment by vvb2060** [comment]
avd api 21 works fine
![image](https://github.com/curl/curl/assets/26996262/d8ea4ad8-d53e-47e7-bdef-52c9c3e5c5ce)

There are no reports about the CLOCK_MONOTONIC_RAW problem on the Android public issue tracker, so I think it's not a general issue, and it may be that the kernel is not working properly on some specific devices.

**Comment by bagder** [comment]
Thanks for the extra info @vvb2060. This makes it even harder to deal with of course...

**Comment by bagder** [comment]
@AzanovAA since this bug seems to be unique to your environment/device/kernel and not even to a specific Android version, I don't think there is much curl can do about your issue. The bug is not in curl and it seems unlikely to be possible to make a work-around for your problem in a decent generic way.

At least you have found a way to work around your problem.

Therefore, I'm closing this issue.

**Comment by AzanovAA** [comment]
Now it doesn't work on AndroidTV. I made a lib for all Android platforms, and it doesn't work on some devices, depending on whether CLOCK_MONOTONIC_RAW is supported there. I think this feature(CLOCK_MONOTONIC_RAW) should be defined in runtime and not at the compilation stage.

**Comment by AzanovAA** [comment]
The problem is resolved only if you specify two options: 
-DHAVE_CLOCK_GETTIME_MONOTONIC=OFF
-DHAVE_CLOCK_GETTIME_MONOTONIC_RAW=OFF

And it’s not my specific environment. You can build it in any environment and it will not work for you on all possible Android devices if your environment defines one of the flags CLOCK_GETTIME_MONOTONIC or CLOCK_GETTIME_MONOTONIC_RAW (this will almost always happen).

**Comment by vszakats** [comment]
How to detect this at runtime?
