### ISSUE TITLE
curl_easy_cleanup crash

### ISSUE THREAD

**Issue by pain400** [curl/curl#1396]
I have called api `curl_global_init(CURL_GLOBAL_ALL);` before download files

`static void * download_thread_proc(void * arg){`
`  CURL * curl = NULL;`
`  curl = curl_easy_init();`
`  curl_easy_setopt(curl, CURLOPT_URL, url);`
`  curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);`
`  curl_easy_setopt(curl, CURLOPT_WRITEDATA, thread);`
`  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, get_response_body);`
`  curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1);`
`  curl_easy_setopt(curl, CURLOPT_TIMEOUT, REQ_TIMEOUT);`
`  res = curl_easy_perform(curl);`

 ...

`// crashing`
`curl_easy_cleanup(curl);`
`}`

======= Backtrace: =========

/lib/libc.so.6[0x41473bc6]
/lib/libc.so.6[0x4147aa76]
/lib/libc.so.6[0x4147b45a]
/mslib/libcrypto.so.0.9.8(CRYPTO_free+0x19)[0x4182017a]
/mslib/libcrypto.so.0.9.8(lh_delete+0x25)[0x41859772]
/mslib/libcrypto.so.0.9.8[0x4185b15a]
/mslib/libcrypto.so.0.9.8(ERR_remove_state+0x21)[0x4185b58e]
/mslib/libcurl.so.4(Curl_ossl_close_all+0xb)[0x4277bf38]
/mslib/libcurl.so.4(Curl_close+0xb7)[0x42775d38]

**Comment by bagder** [comment]
Which libcurl version? Which OpenSSL version? On Linux?

**Comment by pain400** [comment]
Program run on linux platform and version info of curl as follows
Curl version: 7.21.3
Curl version number: 464131

**Comment by bagder** [comment]
The OpenSSL version probably has a letter to the right of the 8? Anyway, that's a very old OpenSSL version that you should consider upgrading as a step forward here.

You've reported a problem with a curl version we [released almost 6.5 years](https://curl.haxx.se/changes.html#7_21_3) ago. We've done **47** releases since with over **2000** documented bug fixes since. And why not ponder on the [34 known security problems](https://curl.haxx.se/docs/vuln-7.21.3.html).

We'll appreciate if you can try your recipe with a modern libcurl version to see if the problem persists and then we'll be very interested to dig in, but until we have indications that this is a problem in current curl we simply don't have the bandwidth and resources to work on it.

**Comment by bagder** [comment]
No response
