### ISSUE TITLE
32-bit compilation fails on 64 bit host

### ISSUE THREAD

**Issue by falconindy** [curl/curl#1456]
### I did this
```
$ echo 'int main(void){return 0;}' | gcc -m32 -include curl/curl.h -x c - -o t
In file included from /usr/include/curl/curl.h:40:0,                                                                                                                                                                                   
                 from <command-line>:32:
/usr/include/curl/curlrules.h:137:3: error: size of array ‘__curl_rule_01__’ is negative
__curl_rule_01__
^~~~~~~~~~~~~~~~
/usr/include/curl/curlrules.h:147:3: error: size of array ‘__curl_rule_02__’ is negative
__curl_rule_02__
^~~~~~~~~~~~~~~~
```

Also fails similarly with clang, though I don't expect this is a compiler problem.

### I expected the following
A successful compile.

### curl/libcurl version

curl 7.54.0 (x86_64-pc-linux-gnu) libcurl/7.54.0 OpenSSL/1.1.0e zlib/1.2.11 libpsl/0.17.0 (+libicu/59.1) libssh2/1.8.0                                                                                                                 
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy PSL 

### operating system

x86_64 Arch Linux
gcc 6.3.1
clang 4.0.0

**Comment by bagder** [comment]
This [problem is already mentioned in the TODO file](https://curl.haxx.se/docs/todo.html#Remove_the_generated_include_fil). The fix is worked on in #1383, planned to get merged after June 14 (next release).

This timing is selected to allow more people to have run test 1541 on more systems until then, as that test case tests the new header file (`curl/system.h`) and having that polished before we make the switch makes it smoother.
