### ISSUE TITLE
Curl system binary non default location /usr/local/bin/curl instead of /usr/bin/curl on ARM perform.

### ISSUE THREAD

**Issue by carlhung** [curl/curl#1459]
### I did this
I installed curl from github with nghttp2 on my raspberry pi on ARM cpu which running ubuntu 16.04

### I expected the following
I expect when I type curl --version it would show up the version of curl that supports http2 like on x86 performs do.
but it didn't show the version which supports http2. I need to type:
LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/curl --version
which commands will show me the version that i expect.
this only happens on ubuntu on arm cpu. ubuntu on x86, it works fine if i type curl --version that would show the version that supports http2.
as I need to use libcurl which needs to use the version that supports http2.

### curl/libcurl version
curl --version
curl 7.54.0 (armv7l-unknown-linux-gnueabihf) libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/curl --version
curl 7.54.0 (armv7l-unknown-linux-gnueabihf) libcurl/7.54.0 OpenSSL/1.0.2g zlib/1.2.8 nghttp2/1.23.0-DEV librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 

### operating system
ubuntu 16.04 on ARM

**Comment by bagder** [comment]
This is not a bug, this is the default install path used by configure. You can change it with `./configure --prefix=$PATH` - but you should be careful as overwriting another default install may cause unintended side-effects.

You *could* also get the same effect by simply changing your PATH and your /etc/ld.so.conf setup.

**Comment by carlhung** [comment]
ok, i just changed the config using following command:
./configure --with-nghttp2=/usr/local --with-ssl --prefix=/usr
still don't work.

**Comment by bagder** [comment]
> still don't work.

But now `make install` installed in /usr/bin and /usr/lib etc, right? That's what you complained about. So what's wrong now then?

**Comment by jay** [comment]
Your system curl is managed as a package, so I don't think you should replace it. What is probably happening here is bash has cached the old path to curl. For example in Ubuntu if you have only a system curl at `/usr/bin/curl` and you run `curl -V` then that bash instance will remember curl is at `/usr/bin/curl`. Now let's say you install your own build of curl in default `/usr/local` so you have `/usr/local/bin/curl`. Ubuntu PATH by default has `/usr/local/bin` before `/usr/bin` so you might expect if you type `curl -V` it will now execute `/usr/local/bin/curl`. However in that instance it already has the path cached so it will execute `/usr/bin/curl` instead. You can start a new bash instance or clear it in the current one with `hash -d curl`.

I am using Ubuntu 16 x64 and I've built curl with an rpath so that it loads the right libcurl and openssl, it looks like `LDFLAGS="-Wl,-rpath,/usr/local/ssl/lib -Wl,-rpath,/usr/local/lib" ./configure ..` and I leave the system stuff alone.

Also check out https://ubuntuforums.org/ if you have Ubuntu questions.

**Comment by carlhung** [comment]
@bagder, it is still not the curl with http2 support even i installed nghttp2 and that only happens on arm ubuntu and it won't happen on x86 ubuntu.

@jay , I had thought that way. and i also tried installing curl at /usr/bin/curl. but still don't work.
on x86 ubuntu. it won't happen.

**Comment by jay** [comment]
You will have to ask in a Ubuntu forum for more help.

**Comment by carlhung** [comment]
But I have seem that happens on all the arm Linux. I googled it. So, I thought it is a bug.

**Comment by bagder** [comment]
The configure script and the curl build and install procedures are identical on ARM as on x86, so whatever you're seeing is most probably due to installations/config in your ARM Linux case that isn't the same as in the x86 case.

I'd recommend you check your config.log after configure has run and double-check that it really detected and enabled use of nghttp2 for HTTP/2 support.
