### ISSUE TITLE
SSLCERTS.md

### ISSUE THREAD

**Issue by azamovement** [curl/curl#14805]
### Specify which documentation you found a problem with

docs/sslcerts.html

### The problem

OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which may be out of date.

Certificate location [from openssl.cafile ini setting]:
C:\xampp\apache\bin\curl-ca-bundle.crt

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:0A000086:SSL routines::certificate verify failed
Failed to enable crypto
Failed to open stream: operation failed

**Comment by dfandrich** [comment]
Are you talking about a problem in https://curl.se/docs/sslcerts.html ?  Because I don't see any of the text in this issue on that page. What exactly is the problem you see in the documentation, preferably quoting it, and how do you see it being improved? Your mentioning of PHP leads me to believe you may be referring to some PHP documentation, which we don't have any control of here at this project.
