### ISSUE TITLE
7.54.0 build fails on Windows with Visual C++ 2015

### ISSUE THREAD

**Issue by DeadParrot** [curl/curl#1482]
Trying to build curl 7.54.0 on Windows 10 with Visual C++ 2015 with CMake gives this warning:
```schannel.c(306): warning C4013: 'inet_pton' undefined; assuming extern returning int```
and then the link fails with:
```schannel.c.obj : error LNK2019: unresolved external symbol __imp_CertFreeCertificateContext referenced in function schannel_connect_step3```

curl 7.53.1 did not have this issue.

**Comment by bagder** [comment]
The `CertFreeCertificateContext` one is the particular problem here, right? That seems to have been added in commit 6cabd78531, long before 7.53.1 so I'm puzzled why this suddenly is a problem!

**Comment by jay** [comment]
What is the cmake command you are using to create the project files? Can you try from the repo master? I tried edd7603 2017-05-21 with `cmake ..\curl -G "Visual Studio 14" -DCMAKE_USE_WINSSL=ON` and then building with Visual Studio 2015 Community Update 3. I had a problem with missing groff and roffit (reported as #1500) but the build was otherwise successful.
~~~
curl 7.54.1-DEV (Windows) libcurl/7.54.1-DEV WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
~~~

**Comment by DeadParrot** [comment]
Strange. I can no longer reproduce this error 7.54.0 builds fine now, both debug and release.

I was building it as part of a build process within another project (https://github.com/openscenegraph/OpenSceneGraph) which was recently updated but that should not have affected the curl build.

One of those mysteries, I guess. If no one else is hitting this issue you can probably close it for now. If it reappears I'll try to isolate the cause. Thx

**Comment by bagder** [comment]
Thanks for getting back with that info! As it seem to have "solved itself" for now, I'll close this issue. If you run into this or any other issue again, just open a new one and we'll dig into it.
