### ISSUE TITLE
Slow upload speed with HTTP POST in windows but OK in Linux

### ISSUE THREAD

**Issue by RedHotSam** [curl/curl#1485]
Hello,

i have read the known bugs and find nothing about this....
i realized that when i make an HTTP POST a file with curl in windows (curl.exe)  (tried 7,8 and 8.1 without AV,  with versions 7.54.0,  7.53.1 and 7.54.0) the upload speed is very low (capped at 10Mbit/s).
I use the same command, same test file (100MB size) and same server to upload under linux and the speed is maxed out at 200Mbit/s wich is my connection speed.

The way i use curl:

c:/curl/curl.exe -b cookie.txt -X POST http://myserver/upload --data-binary @Myfile -o result.txt

Any idea why this occurs or if it can be fixed?

pd: sorry for my bad english, not my mother language

**Comment by bagder** [comment]
Unfortunately this is something we've been told every once in a while by Windows users since the project started. It also happens regularly for other TCP/IP clients running on Windows. Windows is quite simply not a good OS for networking and there are many issues like this. The transfer logic is pretty much identical for all operating systems, we don't do any special magic for Windows...

But OK, that doesn't help your issue. There is at least one known quirk around TCP/IP on Windows and non-blocking sockets, documented by Microsoft here: https://support.microsoft.com/kb/823764

curl tries to follow that advice with the [Curl_sndbufset](https://github.com/curl/curl/blob/master/lib/connect.c#L947) function. Maybe it doesn't do it correctly?

**Comment by RedHotSam** [comment]
Badger thanks for your reply but i'm not sure if that is the problem because in the documentation it says that " The problem described in this knowledge-base is applied only to pre-Vista
   Windows." but i tried with 7,8 and 8.1...

**Comment by bagder** [comment]
Yes, sorry, I'm just grasping for straws (and I don't run/use Windows myself). Googling for "slow tcp uploads on windows setsockopt" shows lots of other victims and heaps of random advice. One of the most promising articles seems to be this serverfault.com post: [Windows TCP Window Scaling Hitting plateau too early](https://serverfault.com/questions/608060/windows-tcp-window-scaling-hitting-plateau-too-early).

**Comment by RedHotSam** [comment]
Thanks badger i didnt know about CTCP, but i sitll think this is not the problem but Curl, i say this due to we don't get slow speed upload with other tools, only with curl. I did run iperf and got 200mb/s in the 3 windows versions tested out of the box,  Torrent gets 200mb too, all the clues indicate me that the problem is Curl but i think that no much people use curl under windows to post big files and for that reason there aren't issues like this one reported, other reason could be that not much people has connections > 10mbit and uses curl to post big files.

**Comment by bagder** [comment]
This prompted me to fire up a windows 10 laptop next to me. I just now used curl 7.54.0 to upload an 8GB file to a remote HTTPS site (daniel.haxx.se) and it saturated my 100mbps uplink. curl reports a little over 12 megabyte/second.

So okay, maybe 100mbit is a bit too lame. Instead pointing the upload from windows 10 over my 1gigabit ethernet LAN to my linux HTTP server, I get a steady 111 megabytes/second upload speed.

This just shows that this problem is not a generic "curl is slow on Windows" problem. It is much trickier than so...

**Comment by RedHotSam** [comment]
You are right, i just installed one VM with W10 and curl works well, idk why not the same with 7/8/8.1

**Comment by bagder** [comment]
Uploading from my win7 VM, which has its disk mounted as a network disk (exported from the underlying Linux host) it does a 70 megabytes/second upload for me. (Unfortunately this VM has a too limited disk space for me to put a huge file on the local file system for a better test.) 70 megabytes is still over 500 mbits. Not the 10 mbit cap you report.

**Comment by jay** [comment]
This reminds me of #708. This could have to do with any number of things, his build of curl, wifi, the server, the SSL library used or heap fragmentation. There are some test results in that thread that may be of interest. For example the [PostUpload](https://gist.github.com/jay/daac01682f17c2dc213e) test to compare between libcurl and the browser. The curl tool is the same thing except for the speed calculation. Here's a c&p:
~~~
First test the speed in a web browser:
Go to http://testmy.net/mirror and choose the geographically closest mirror.
After the mirror is set click on 'Upload Test'.
Select manual test size 50MB. The browser will download 50MB then upload it.
Note the server as it's uploading. (eg: ny.testmy.net)
After the upload completes it gives upload speed in kB/s. (eg: 633 kB/s)

From the command line make 50MB of POST data and upload it to that server:
perl -e "print 'size_data=52428800&test_type=upload&svrPort=80'" > ulspeedtest
perl -e "print '&svrPort=80&start=9999999999999&data='" >> ulspeedtest
perl -e "print '0' x 52428800" >> ulspeedtest
PostUpload ulspeedtest http://ny.testmy.net/uploader
~~~
... but use the curl tool instead of PostUpload:
~~~
curl -fL -o NUL --data-binary @ulspeedtest http://<CLOSESTSERVER>.testmy.net/uploader
~~~
curl gives results in KB/s (x1024) and not kB/s (x1000) like speedtest so you'll need to do the math for an accurate comparison. For example once the curl upload finishes take from the 'Average Speed' column in the middle and if eg 600k then it's `600 * 1024 / 1000 = 614.4 kB/s` and just compare that to what you get in the browser with the 50MB upload and it should be the same. You can also do it https and check for difference.

**Comment by bagder** [comment]
This problem has not been reproduced in spite of many attempts on several different windows machines and versions, and now time is passing in silence. If additional details or info appear, this issue can of course be reopened but until then we consider it closed.

**Comment by svich** [comment]
Hi there.
I have the same problem, not limited to curl through.
I think it's more a windows tcp/ip stack defaults or algorithms problem.
Because on 10 ms network curl saturate 100 mb/s link, but with 100 ms latency not go over 10 mb/s.
On linux machine network latency do not limit curl upload speed.

Sorry for my english.
