### ISSUE TITLE
CURLE_PARTIAL_FILE returned on Raspbian

### ISSUE THREAD

**Issue by babelouest** [curl/curl#1527]
### I did this

I use `curl_easy_setopt(curl_handle, CURLOPT_WRITEFUNCTION, write_body_function)` on multiple systems to query data and collect them in `write_body_function`. The data transfer works fine, but on a raspberry pi using raspbian Jessie, I always have a `CURLE_PARTIAL_FILE` returned by `curl_easy_perform`.

The function has the following form:
```c
size_t my_write_body(void * contents, size_t size, size_t nmemb, void * user_data) {
  printf("got %s", (char *)contents);
  
  return size * nmemb;
}
```

The exact same code works perfectly on Debian Jessie x86_64 and Ubuntu 17.04 x86_64, no `CURLE_PARTIAL_FILE` returned.

### I expected the following

`curl_easy_perform` return value to be `CURLE_OK`

### curl/libcurl version

curl 7.38.0 (arm-unknown-linux-gnueabihf) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP

### operating system

Linux Raspbian Jessie armv7l GNU/Linux, kernel 4.9.30-v7+,

**Comment by bagder** [comment]
That little snippet is not enough for us to understand your problem - we need more details. libcurl does not return `CURLE_PARTIAL_FILE` because of a wrong/bad return code from the write callback, it returns that when the transfer ends and there's an unexpected discrepancy between the expected amount of data transferred and the amount libcurl counted.

Secondly, that printf() in your write callback is unwise since the input buffer you get is not zero terminated.

**Comment by babelouest** [comment]
Hello again,

After some cross tests, I realized the problem does not come from the client side but the server, so nothing to do with libcurl. I'll close this bug, sorry for the noise.
