### ISSUE TITLE
clang: unknown warning option

### ISSUE THREAD

**Issue by bagder** [curl/curl#1606]
### I did this

The Travis CI debug builds on Mac shows a warning that an unknown warning is used:

`warning: unknown warning option '-Wcomma' [-Wunknown-warning-option]`

[Example](https://travis-ci.org/curl/curl/jobs/244856563#L1050).

### I expected the following

No compiler warnings on unknown options used

### curl/libcurl version

current git

### operating system

Linux

**Comment by MarcelRaad** [comment]
Ah, this is not Linux, this is Mac OS. This Apple clang identifies itself as version 7.3.0, while clang trunk is currently 5.0. Since 7.0, it doesn't give any info about which clang version it's based on anymore.

I'm already looking into that, but as I'm not a Mac user myself, I probably can't maintain a separate Apple clang version list.

Given that every clang was treated as version 4.2.1 until recently, maybe we could just treat every new Apple clang version as the latest version the Apple clang version string contained the actual clang version (3.6 in XCode 6.4)?

**Comment by bagder** [comment]
Iterating over the options and try which ones that work is also probably a bit complicated since it doesn't seem to exit or properly signal for unknown warning options, other than that message on stderr and it feels error-prone to grep for that!

> I guess we don't have access to the operating system used in the m4 scripts easily?

It's there in the `$host` variable:

```
     case $host in
     *-*-darwin*)
        echo "this is mac"
        ;;
     *)
        echo "something else"
        ;;
     esac

```

**Comment by bagder** [comment]
> maybe we could just treat every new Apple clang version as the latest version the Apple clang version string contained the actual clang version (3.6 in XCode 6.4)?

Yes, I think that's a decent default work-around, then we can add support for the specific mac-clangs we know support newer options. The latest mac compiler *does* support -Wcomma though!

 My dev mac has the latest OS and xcode installed I think:

```
$ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0

```

**Comment by bagder** [comment]
For future reference, here's a gist with this info: https://gist.github.com/epipping/ef8b02b0cfaec4a5ebf3a57092145a3f by @epipping
