### ISSUE TITLE
POST requests without body

### ISSUE THREAD

**Issue by jeroen** [curl/curl#1625]
My API has a few `HTTP POST` endpoints that do not require a content (or `content-type` request header) to be posted, i.e. an empty POST. Implementing this in `libcurl` is surprisingly difficult.

If we set `CURLOPT_POST` without setting any of `CURLOPT_POSTFIELDS`, `CURLOPT_READFUNCTION` or `CURLOPT_HTTPPOST` then curl freezes after the HTTP 100:

```r
> handle <- curl::new_handle(verbose = TRUE, post = TRUE)
> curl::curl_fetch_memory("https://httpbin.org/post", handle = handle)
* Connection 0 seems to be dead!
* Closing connection 0
*   Trying 23.21.185.161...
* TCP_NODELAY set
* Connected to httpbin.org (23.21.185.161) port 443 (#1)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: httpbin.org
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> POST /post HTTP/1.1
Host: httpbin.org
User-Agent: R (3.4.0 x86_64-apple-darwin15.6.0 x86_64 darwin15.6.0)
Accept: */*
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

< HTTP/1.1 100 Continue
```

The `CURLOPT_POST` documentation explains why this is, but I think this can be improved:

> A parameter set to 1 tells libcurl to do a regular HTTP post. This will also make the library use a `"Content-Type: application/x-www-form-urlencoded"` header. (This is by far the most commonly used POST method). Use one of `CURLOPT_POSTFIELDS` or `CURLOPT_COPYPOSTFIELDS` options to specify what data to post and `CURLOPT_POSTFIELDSIZE` or `CURLOPT_POSTFIELDSIZE_LARGE` to set the data size.

Wouldn't it make more sense if `CURLOPT_POST` alone would only set the method to `POST` but not assume a content type? And then set both a `Content-Type` and `Content-Length` when we specify `CURLOPT_POSTFIELDS`?

I think at the very least `libcurl` should prevent the freeze by not sending the `Content-Type: application/x-www-form-urlencoded` or `Expect: 100-continue` header if there is no data to post...

**Comment by bagder** [comment]
(The default `Content-Type` is a separate discussion and we keep that for backwards compatibility. New behavior would require a new option to get set to ask for that.)

I can't reproduce a hang. Here's what I did to try:

My test application runs:

```
int main(void)
{
  CURL *curl;
  CURLcode res;

  curl = curl_easy_init();
  if(curl) {
    curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:8080/");
    curl_easy_setopt(curl, CURLOPT_POST, 1L);
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
    res = curl_easy_perform(curl);
    curl_easy_cleanup(curl);
  }
  return 0;
}

```
And my "server" is `nc -l -p 8080 < 100-continue` where the response looks like this:

```
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Connection: close
Content-Length: 2

A

```

**Comment by jeroen** [comment]
Does it not freeze if you set `CURLOPT_URL` to `"https://httpbin.org/post"` instead?

**Comment by bagder** [comment]
If I do, I only seem to get a "HTTP/1.1 100 Continue" and then nothing more, so yes, then it'll sit there waiting for the next response which `httpbin.org` doesn't send. I don't think that's a curl issue, that's a server issue.

**Comment by jeroen** [comment]
Hm okay if you think so then I guess you can ignore this issue. What else would you expect the server to do if you say `Expect: 100-continue` and then the server replies `HTTP/1.1 100 Continue` and then you just remain silent :)

**Comment by bagder** [comment]
The server is expected to send the next response, usually a `HTTP/1.1 200 OK` if everything is fine. If it doesn't, then curl's timeout options can be used to make it fail after a given time or similar.

**Comment by bagder** [comment]
Sorry, I'm wrong there.

**Comment by bagder** [comment]
You can pass data to POST to libcurl two ways:
1. a pointer to `CURLOPT_POSTFIELDS` or `CURLOPT_COPYPOSTFIELDS`
2. with the `CURLOPT_READFUNCTION`

An additional complication is that libcurl has a default read function if you don't set any, which reads data from stdin. That means that if your application doesn't use any of the two above ways, libcurl defaults to the read function method since it has a default one.

When the 100-continue is received, libcurl will read data to send from the read callback that is set. You don't send any data on stdin, the program sits there waiting for data to arrive...

My test program above thus works fine against `https://httpbin.org/post` if you run it like `./debugit < inputfile`, ie you pass data on stdin.

There are at least two ways to send a POST without body:

1. set `CURLOPT_POSTFIELDS` to "", and this is really the method I recommend
2. set `CURLOPT_CUSTOMREQUEST` to "POST", as that will trick libcurl to think it does a normal GET (without body) but still send a "POST" method. This approach is more error-prone on redirects though.

All this taken together, I can't see a bug here other that perhaps we can enhance documentation to make this clearer, but I'm not where how/where we'd do that...

**Comment by jeroen** [comment]
OK that makes sense. Is it possible to set CURLOPT_READFUNCTION to NULL to disable that behavior or will that just segfault?

**Comment by bagder** [comment]
That's documented in the man page:

> If you set this callback pointer to NULL, or don't set it at all, the default internal read function will be used.
