### ISSUE TITLE
Hyperlink in man page needs update

### ISSUE THREAD

**Issue by MaxValue** [curl/curl#1655]
### I did this
Searched the man page of curl for the `--ciphers` parameter and its possible arguments.

### I expected the following
See a list of applicable cipher names or a working weblink to a list of applicable cipher names.

### curl/libcurl version
```
curl 7.38.0 (arm-unknown-linux-gnueabihf) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
```

### operating system
Raspbian (Debian)

### Note
Under `--ciphers <list of ciphers>` the link http://www.openssl.org/docs/apps/ciphers.html is given. The current, working link is https://www.openssl.org/docs/manmaster/man1/ciphers.html

(I know this issue is fussy, but working links help making the use of software more fun. Maybe i'll go through the complete man page in the future and test all the links)

**Comment by bagder** [comment]
Thanks for your report!

The latest up-to-date version of the man page is always available [online here](https://curl.haxx.se/docs/manpage.html) as a web formatted version.

It shows that the link in the ciphers section is fine - and different from the outdated version you have: https://curl.haxx.se/docs/manpage.html#--ciphers

(Fixed in 209b2302272b)
