### ISSUE TITLE
FTP: CURLFTPMETHOD_NOCWD + # not working

### ISSUE THREAD

**Issue by PeterLamare3** [curl/curl#1812]
CURLOPT_FTP_FILEMETHOD set to CURLFTPMETHOD_NOCWD
CURLOPT_CUSTOMREQUEST set to "MLSD"
will not work if the CURLOPT_URL contains a "#" character.

The reason is url.c: parseurlandfillconn() which will cut the path after the hash, because it assumes a URL.
In the CURLFTPMETHOD_NOCWD case, however the path will not be used for CWD but be passed as argument "as is" without url-decoding:

ftp.c:
```
    cmd = aprintf("%s%s%s",
                  data->set.str[STRING_CUSTOMREQUEST]?
                  data->set.str[STRING_CUSTOMREQUEST]:
                  (data->set.ftp_list_only?"NLST":"LIST"),
                  lstArg? " ": "",
                  lstArg? lstArg: "");
```
Maybe in the CURLFTPMETHOD_NOCWD case the lstArg should be url-decoded so that one can encode the hash before passing it to CURLOPT_URL?

-Lama

**Comment by bagder** [comment]
I don't understand. Can you please show a command line or a more complete program that repeats the problem? If a `#` is used as-is in the path part of a URL, the path should be cut off there since that then identifies the "fragment" part. The fragment is an anchor in the requested page.

So yes, if '#' is indeed wanted as part of a path, it needs to be URL encoded in the path and curl needs to URL decode the path before using it.

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!

**Comment by Zenju** [comment]
It seems CURLOPT_CUSTOMREQUEST "MLSD" is needed to reproduce.
