### ISSUE TITLE
Curl handling of self-signed / untrusted TLS certificates is too simplistic

### ISSUE THREAD

**Issue by tlhackque** [curl/curl#1822]
Curl has only two ways to deal with un-trusted TLS certificates: fail, or ignore (-k).

This leads to abuse/over-use of -k, and user frustration.

A model similar to `ssh`'s `known_hosts` could be more helpful.

See the recent discussion on `curl-users` for initial thoughts & discussion.

**Comment by tlhackque** [comment]
Daniel has started a [wiki page](https://github.com/curl/curl/wiki/Trust-On-First-Use) for this.

Wiki pages don't provide change notifications; it would be helpful if updates were posted here.

**Comment by bagder** [comment]
@tlhackque: 

> because the cert is saved, and it contains the subject

The certs do not contain the subjects, hashes could very well be possible and hide the host names. curl would only need the digital signatures (unless we also talk about other things). Again, for the same reasons ssh does it.

> For Unix, "Is there a controlling TTY"

Sure, but
1. I'm sure there are ways that won't either, like perhaps if you run a script from your prompt that uses curl. It just feels error-prone to me.
2. More importantly, since that check won't be possible to do in a portable manner across platforms, I rather use the lowest common denominator here to get the same "universal" behavior

> you may not each "run" to make a connection to the server. It may be possible to use TLS backend hooks to modify the verification status

I don't understand this point. Surely you must connect to the TLS server to get the cert(s)?

**Comment by tlhackque** [comment]
You would save the certificate in the local trust store in order to use it for validation on each future access - you need to pass the certificate to the TLS backend.

Once the locally trusted certificate is saved in the directory, the subject is easily accessible.  E.g.
````
for F in ~/.curl-trust/*.pem; do openssl x509 -in $F -noout -subject ; done
````
For the altnames, something like this will work:
````
for F in ~/.curl-trust/*.pem; do openssl x509 -in $F -noout -text | \
  grep -A1 'X509v3 Subject Alternative Name:" | tail -n1 ; done
````

Thus, hashing the filename doesn't help.

I suppose you could make extra connections to avoid keeping the certificate - but I really don't see the privacy benefit.  curl is transferring a file.  The remote server probably logs it.  The IP address of the server is available to anyone with wireshark/tcpdump on your LAN (and the WAN).  The certificate is available from the server without restriction.  You can't hide the fact that you're talking to that server.  The certificate is not secret.  TLS may hide a virtual server name - but the list of possible names is freely available from the server.  (See the getcert tool.)  At best, you prevent some off-line analysis.  IFF the same server isn't used by a web browser.  Because if it is, the user probably put the certificate into the browser's local trust store.  Bottom line, I see no privacy benefit, just complexity.

SSH is a somewhat different case.  If a host appears in known_hosts, there is a reasonable chance that the host will respond to credentials similar to or stored on the local host.  E.g. if my username is 'fred' here, it's probably 'fred' there.  And if I have SSH private keys on the local host, it's reasonable to guess that one or more of them will work on one or more of the known_hosts.  This is, however, only useful if an intruder has obtained access to the user's local .ssh directory.  It provides some containment by denying knowledge - but not any real security.  Again, wireshark (or even netstat monitoring) will reveal the hosts used by a user if the local machine is compromised.  So protect the directories & files.  SSH helps by not using an open directory.  But while there is some benefit in making it harder to use compromised credentials, I don't see a privacy gain.  

Controlling TTY - is a standard POSIX concept, and is portable.  If you run a script, it is still a tty with a human attached, unless the process is detached.  See http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap10.html for a reference.  Even on VMS, /dev/tty maps to SYS$COMMAND (and the CRTL handles the equivalence).

Yes, you connect to the server to get the certificate.  However, the TLS library may (OpenSSL does) provide a callback while it is doing verification.  IIRC, the callback gets the certificate, verification status (so far), and level in the chain.  That callback can return "verified OK", "verify fail reason code", etc.

Thus, you can register a callback.  It will be told "verification so far failed on this certificate".  The callback can look for the certificate in the local trust store.  If it matches, it returns "verified OK" to the library, and the connection proceeds.  If not, or it's not in the trust store (and not system trusted), the callback can do the interactive query.  If told to trust, it stores the certificate in the local store & returns "verified OK".  Otherwise, it returns "verification failed".  Also, if it's now system trusted but there's a local entry, it deletes the local entry.

Given that, the most efficient technique is check the local trust store for the host:port.pem file.

If it exists, pass it to the backend as a -cafile.  The library will do the validation - even the library doesn't have a validation callback.

If it does not exist, try without the -cafile.  The callback (or retry) will have to validate.

By using the callback, there is no need to connect to the server multiple times, even on first use.  Just once.

If the TLS library doesn't provide such a callback, your scheme of multiple connections will work.

**Comment by bagder** [comment]
> You would save the certificate in the local trust store in order to use it for validation on each future access - you need to pass the certificate to the TLS backend.

The certificate's subject is not the URL of the site. So no, unless we store the site/URL, it can't be deduced from the certificate alone.

> Controlling TTY - is a standard POSIX concept, and is portable

For example Windows is a major operating system for curl and curl users and it is very clearly not POSIX compliant.

> the most efficient technique is check the local trust store for the host:port.pem file.

scheme_host_port perhaps even? I'm not sure it is wise to trust across protocols even if the port number would match...

> there is no need to connect to the server multiple times, even on first use. Just once

I don't think we'll manage that since we're also talking about potentially prompting the user between some of those steps. But generally I don't think the number of connections we might need is very important at this moment in time.

**Comment by bagder** [comment]
What this doesn't solve, and I have no solution for it, is its major weakness: this concept mostly pushes users to switch from `-k` to TOFU (with or without a `--tofu` option) and since it is this automatic it doesn't push users into doing the right thing.

As long as we don't fix this weakness, it makes me personally not too interested in implementing this idea.

**Comment by bagder** [comment]
This is a subject for more and further discussions and ideas going forward. Nobody seems to actively work on exploring the discussed techniques, and there are reasons for concerns using them as well. Since the discussion has stalled here as well, I'm closing this issue. We can reopen again if things develop.

**Comment by rnav** [comment]
Sorry for pitching in here after this was closed, but as a small first step, would it at all be possible to consider providing an option for certificate pinning (distinct from public key pinning)? Let me elaborate.

One of the major reasons I am forced to use `--insecure` is that most self-signed certificates I encounter are badly setup, with an incorrect subject name usually. While I try to report those and get those fixed where possible, it is still too common and many times, I am forced to connect regardless. There are also some appliances (especially intrusive firewalls) that won't set proper SN due to the way they work.

In all such scenarios, what would be really good is if `curl` can provide an option to proceed with the connection as long as the server/peer certificate is what I provide (server/peer 'certificate' pinning in that sense), _without_ bothering to do any further validation. In my view, this is close to how ssh works, except that users will need to obtain and provide the peer certificate out of band.

I like to think that this mode would be way more secure than the all-or-nothing options we have today.
