### ISSUE TITLE
Segfault when free unassigned curl_mime

### ISSUE THREAD

**Issue by moteus** [curl/curl#1961]
### I did this
``` C
curl_mime *mime = curl_mime_init(easy);
curl_mime *alt  = curl_mime_init(easy);
curl_mimepart *part = curl_mime_addpart(mime);
curl_mime_subparts(part, alt);
curl_mime_subparts(part, NULL);
curl_mime_free(mime);
curl_mime_free(alt);
```
### I expected the following
`curl_mime_free(alt);` should not crash process but should correctly free `alt` mime structure.

### curl/libcurl version

curl 7.56.0 (i386-pc-win32) libcurl/7.56.0 WinSSL
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Largefile SSPI Kerberos SPNEGO NTLM SSL

### operating system
Windows 7 x64

**Comment by bagder** [comment]
Feel like taking a look at this @monnerat ?

**Comment by monnerat** [comment]
This is normal, as `alt` has already been freed at the `curl_mime_subparts(part, NULL);` time, since it was bound to the part. From the manual:

`After curl_mime_subparts succeeds, the mime structure handle belongs to the multipart part and must not be freed explicitly.`

The crash is therefore caused by a double free.

It is legal to replace a value previously set, but the housekeeping occurs. The same applies to headers if they were set by a `curl_mime_headers(part, hdrs, TRUE);` then dropped using another call to the same function.

**Comment by bagder** [comment]
Documented behavior. No bug. I don't see what more we can do. What do you think @moteus ?

**Comment by moteus** [comment]
Do not think that this is really intuitive API.
For me resources should be free only if user ask about it.
When you call `curl_mime_headers(part, hdrs, TRUE);` you explicitly define lifetime for list.
But with mime you can easily get invalid pointer without call any free function.
API design do not allow implement some API with gargage collection environment.
I am maintainer for Lua binding.
```Lua
local mime = easy:mime()
local inner = easy:mime()
mime:subparts(inner)
mime:free()
```
In this example there no need freed `inner` mime. More intuitive will be just `detach` `inner` from `mime` and then allows GC to clear it if/when it needed (when user clear `inner` reference). This API allows easily reuse mime objects to build new one.
