### ISSUE TITLE
Can't send form data from stdin

### ISSUE THREAD

**Issue by kitsunyan** [curl/curl#1965]
### I did this

I've tried to send form data from stdin: `curl -F 'f:1=<-' ix.io`

### I expected the following

I expected that can enter a text and make a request after Ctrl+D press. Instead request runs immediately without any prompt.

This also doesn't work if I provide a file to stdin: `curl -F 'f:1=<-' ix.io < mytextfile.txt`

This bug appeared after upgrading curl from 7.55.1 to 7.56.0. I've tried to bisect the bug and found that ce0881edee3c78609eae49665fb70264d8786d29 caused this bug.

### curl/libcurl version

curl 7.56.0 (x86_64-pc-linux-gnu) libcurl/7.56.0 OpenSSL/1.1.0f zlib/1.2.11 libpsl/0.18.0 (+libicu/59.1) libssh2/1.8.0 nghttp2/1.23.1
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system

Arch Linux

**Comment by monnerat** [comment]
The problem occurs because the server at ix.io does not accept chunked transfer encoding:

```
$ curl -v -F 'f:1=<-' ix.io
...
> POST / HTTP/1.1
> Host: ix.io
> User-Agent: curl/7.56.0-DEV
> Accept: */*
> Transfer-Encoding: chunked
> Content-Type: multipart/form-data; boundary=------------------------cd53d282dcb846fd
> Expect: 100-continue
> 
...
< HTTP/1.1 411 Length Required
< Date: Sun, 08 Oct 2017 09:48:47 GMT
< Server: Apache
< Content-Length: 239
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>411 Length Required</title>
</head><body>
<h1>Length Required</h1>
<p>A request of the requested method POST requires a valid Content-length.<br />
</p>
</body></html>
...
```

We have to use chunked transfer encoding because the posted data size is unknown before reading it (at header transmission time, curl does not know if you will just type CTL-D or if you'll input a lot of data).

The code prior to https://github.com/curl/curl/commit/ce0881edee3c78609eae49665fb70264d8786d29 used to load the stdin input in memory before processing it, allowing to determine its size before processing and avoid chunked transfer: this is bad because data can be huge, thus consuming memory resources... think of something like `curl -F 'field=<-' www.example.com < /dev/fd0` !!!

With such a "intolerant" server, you should use either direct data, as `-F 'f:1="your data"'` or provide a regular file as `-F 'f:1=<mytextfile.txt'`.

**Comment by bagder** [comment]
@monnerat: seems like a good subject to mention in the man page!

**Comment by monnerat** [comment]
Pushed: https://github.com/curl/curl/commit/14d6e207d35792e3e10a674b2e27cf2aa3370bf8

**Comment by bagder** [comment]
Thinking further. I'm concerned that this change of behavior is going to cause people problems. It is hard to tell how many users that do this, but @kitsunyan already found and there is surely a very long tail of users who won't upgrade yet for a long time...

**Comment by monnerat** [comment]
Well... I really changed that because of the memory problem. The potential compatibility caveats are the chunked transfer unsupported by the server (our current case) and impossibility to resend.

If we add code back to bring stdin in memory, I really want to implement a size limit to avoid overloading the memory: this will cause an error if stdin is larger. There are then a few questions:
- What limit ? fixed, configured  or option ?
- Implement in cli tool ? in (lame) `curl_formadd()` ? both ?
- What about `--libcurl` generated code (`curl_mime_filedata()` does not support the "-" pseudo filename) ?

**Comment by kitsunyan** [comment]
Maybe it's possible to add a special command line key to disable chunked transfer encoding and buffer all input in memory sending in with content length as it was before? So this thing will become optional and nobody will complain about memory problems.

**Comment by bagder** [comment]
> since Expect: 100-Continueis present by default

Remember that the server-side support for 100-continue is A) very spotty and B) even when present, it is often wrongly done to just say OK even though the backend doesn't really want to have the data. Thus not a terribly good protection for this.

> If we add code back to bring stdin in memory, I really want to implement a size limit to avoid overloading the memory: this will cause an error if stdin is larger.

Why? We support virtually unlimited other things that we read into memory. If someone passes a too large thing it'll simply make curl run out of memory and return failure because of that. Any artificially invented limited is due to cause someone a problem down the line.

> Implement in cli tool ? in (lame) curl_formadd() ? both ?

I think this is primarily for the command line tool where this reading from stdin is so handy (and in use). I think it is less used via the API by programs.

> What about --libcurl generated code (curl_mime_filedata() does not support the "-" pseudo filename) ?

Maybe generate some sort of fake file name there? "/dev/stdin" or something ?

**Comment by buhman** [comment]
I thought I'd toss in there that the 7.56 changes also breaks https://ptpb.pw --the primary use-case for this service is curl one-liners, so it's a pretty big deal for me.

**Comment by bagder** [comment]
Thank you, it helps convincing me this needs to be addressed!

**Comment by Earnestly** [comment]
If you need more help, this also breaks many other curl based pastebins such as https://0x0.st/ and http://sprunge.us/ which I've always personally enjoyed.

**Comment by bagder** [comment]
Thanks @Earnestly, I think we have enough input here now.

@monnerat, will you grab this?

**Comment by monnerat** [comment]
Fix pushed: https://github.com/curl/curl/commit/665b3e48bc95713ecceaddf445fc2049440a6fb3
Feedback welcome!

**Comment by buhman** [comment]
Just tested; 665b3e4 works for me!

**Comment by kitsunyan** [comment]
@monnerat great, it works!

**Comment by bagder** [comment]
This is fixed in git now
