### ISSUE TITLE
Wrong version number is specified in curlver.h for the new curl-7_56_1 tag

### ISSUE THREAD

**Issue by nop144d** [curl/curl#2012]
### I did this
1) git checkout curl-7_56_1
2) build
3) curl -V

### I expected the following
Output the correct version number - 7.56.1

### curl/libcurl version

[curl -V output]
curl 7.57.0-DEV (i386-pc-win32) libcurl/7.57.0-DEV WinSSL WinIDN
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

### operating system
Any

<br/>
Have no clue if/how this should be fixed. Probably by overwriting git history.

**Comment by bagder** [comment]
The tags are set in the repository at the point in time when the release is **generated**. The official releases are the packaged and signed tarballs, they are the output from the `maketgz` script that builds releases. You can update the version info in your local source tree with `./maketgz 7.56.1 only` to make it look similar to the release.

**Comment by agaloyan** [comment]
This is really inconvenient.
We are using (read-only) github mirrors for consuming open source projects in our company. Our different products using different versions of curl and they consume from the required version by tag.  Now we cannot consume this release because fetching repo by 7.56.1 tag brings sources where the cURL lib reports version 7.57.0. This makes different kind of confusions, from build and validation point up to license and legal clearance.
I understand that nothing could be done for already shipped release, but it is possible to adapt the release process/scripts to avoid such discrepancies in the future?
As I understood maketgz script it is possible to run it before tagging the release commit.

**Comment by bagder** [comment]
The version number, the name and the date are not necessarily correct for other tags either. You will for example notice the huge **DEV** in the name string in committed files and that there's no release date. 

This is a release procedure and tag handling model we've used basically since we started this project, so I'm intrigued how this suddenly became an issue for you.

> is it possible to adapt the release process/scripts to avoid such discrepancies in the future?

It is just code, everything is possible. But you would need to present a much stronger case than "it would be nicer for us" if you really intend to argue that we should commit all files that we generate for a release.

> As I understood maketgz script it is possible to run it before tagging the release commit.

But it generates the release in a release directory, it doesn't update the files in the repository - for these reasons. The release is *generated* from the files in the repo with the tag. It is not just the files in the repo.

**Comment by erengy** [comment]
I have a git repository where curl is added as a submodule, which points to the commit with the tag of the latest release. This has been my workflow for the past year:

1. Update the submodule when a new release is made.
2. Run a .bat file to re-build libcurl in static configuration.
3. Re-build my application.

I display `LIBCURL_VERSION` in my application's About dialog, which is more convenient than changing it myself on each upgrade. I haven't had any issues with this until 7.56.1, where now my application displays `7.57.0-DEV` instead. `DEV` is not an issue for me, which can be programmatically removed. But the incorrect version number is, well, confusing.

From what I understand, you [manually update](https://github.com/curl/curl/commits/master/include/curl/curlver.h) `curlver.h` from time to time (as in a4c1c75da30af11ed4ba129308d0a906b54a252e) with the next expected version number, but it doesn't really reflect what the actual number is going to be. Does changing it early provide some benefit in your development process? Wouldn't it be a better idea to make this commit right before releasing a new version and tag it appropriately?

Otherwise, I'm open to suggestions in regards to changing my workflow. Note that I'm building libcurl and my application on a Windows machine with MSVC.

**Comment by bagder** [comment]
> Does changing it early provide some benefit in your development process? Wouldn't it be a better idea to make this commit right before releasing a new version and tag it appropriately?

It makes it show up as "version blabla-DEV" for users, where blabla is the expected *next* release version. The version that is currently in development. It is also used as version number for the [daily snapshots](https://curl.haxx.se/snapshots/). I think listing the former release as "current dev version" isn't as nice.

But also, we generate many files in a release tarball that aren't even present in git, or that are merely the source version in git, so even if I would commit this particular file more often the git repo will not be the release. It would merely make it look a bit more like it...

**Comment by jay** [comment]
Although I agree with Daniel's statements I sympathize with the reporters in this thread since I do something similar. I just made an update to my curl "latest" release tag fetcher and it may help with the use cases described here. It now allows a user-specified release tag or can retrieve the curl/curl release tag marked "latest" on github. It changes the version number in the include headers after checking out the release, to match the tag.

For example:

~~~
./checkout-curl-release.pl latest
./checkout-curl-release.pl curl-7_59_0
./checkout-curl-release.pl 7.59.0
~~~

Since 7.59.0 is the latest that is what would be checked out for "latest". These are the changes it makes:

~~~diff
diff --git a/include/curl/curlver.h b/include/curl/curlver.h
index 5149d2f..d6dbafd 100644
--- a/include/curl/curlver.h
+++ b/include/curl/curlver.h
@@ -30,7 +30,7 @@
 
 /* This is the version number of the libcurl package from which this header
    file origins: */
-#define LIBCURL_VERSION "7.59.0-DEV"
+#define LIBCURL_VERSION "7.59.0"
 
 /* The numeric version number is also available "in parts" by using these
    defines: */
@@ -68,7 +68,7 @@
  *
  * "2007-11-23"
  */
-#define LIBCURL_TIMESTAMP "[unreleased]"
+#define LIBCURL_TIMESTAMP "2018-03-13"
 
 #define CURL_VERSION_BITS(x,y,z) ((x)<<16|(y)<<8|z)
 #define CURL_AT_LEAST_VERSION(x,y,z) \
diff --git a/src/tool_version.h b/src/tool_version.h
index 04f4567..acfcc70 100644
--- a/src/tool_version.h
+++ b/src/tool_version.h
@@ -25,10 +25,10 @@
 
 #define CURL_NAME "curl"
 #define CURL_COPYRIGHT LIBCURL_COPYRIGHT
-#define CURL_VERSION LIBCURL_VERSION
-#define CURL_VERSION_MAJOR LIBCURL_VERSION_MAJOR
-#define CURL_VERSION_MINOR LIBCURL_VERSION_MINOR
-#define CURL_VERSION_PATCH LIBCURL_VERSION_PATCH
+#define CURL_VERSION "7.59.0"
+#define CURL_VERSION_MAJOR 7
+#define CURL_VERSION_MINOR 59
+#define CURL_VERSION_PATCH 0
 #define CURL_ID CURL_NAME " " CURL_VERSION " (" OS ") "
 
 #endif /* HEADER_CURL_TOOL_VERSION_H */
~~~

Since the other LIBCURL_VERSION_ macros are already set properly they are unchanged; however for any release where that is not the case it would change those as well.

**As discussed it is not proper release source.** I have a special repo curl-RELEASE that I use this script on with no other dirtiness, and not my regular curl repo.
