### ISSUE TITLE
Example fopen.c: url_rewind() not working after end of file reached

### ISSUE THREAD

**Issue by bgergo81** [curl/curl#2057]
### I did this
Using fopen.c I read the contents of the whole file till the end. And then called url_rewind().
### I expected the following
The url_fread() method should have worked again, but it didn't because file->still_running was never set back to true.
### curl/libcurl version
2017 October 11.
### operating system
Windows 10

**Comment by bagder** [comment]
`fopen.c` is just an example showing how libcurl can be used. I don't think anyone takes this fopen layer functionality very seriously so don't count on lots of people jumping to the opportunity to fix this. 

For a more "real" take on the same style of API, I once started [fcurl](https://github.com/bagder/fcurl/), although it never took off for real either since there didn't seem to be much interest. I still consider that to be a better project to put efforts into rather than working on the fopen.c example.

**Comment by bgergo81** [comment]
Thanks for the post, I will take a look at fcurl.

Otherwise, I already implemented my own enhanced version based on fopen.c, so I just wanted to report the bug I found.

If anyone interested, here is my version of fopen.c, note that testing is still need to be done:
[url_fopen.zip](https://github.com/curl/curl/files/1459101/url_fopen.zip)
