### ISSUE TITLE
dealing with cookies that expires at the end of the session

### ISSUE THREAD

**Issue by dzmodest** [curl/curl#2077]
### I did this
sent a get request to get cookies variables
sent a post request along with the previous extracted cookies

**get request:**
```
$ckfile = tempnam("/tmp", "CURLCOOKIE");
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_COOKIEJAR, $ckfile);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_VERBOSE, 1);
curl_setopt($ch, CURLOPT_USERAGENT, $useragent);

$html = curl_exec($ch);

curl_close($ch);
```

**verbose:**
> GET /login.php HTTP/1.1
> User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13 ( .NET CLR 3.5.30729)
> Host: sub.domain.com
> Accept: */*
> 
>  HTTP/1.1 200 OK
>  Date: Mon, 13 Nov 2017 21:07:00 GMT
>  Content-Type: text/html; charset=utf-8
>  Transfer-Encoding: chunked
>  Connection: keep-alive
>  Added cookie __cfduid="da91839ea04583306a15b50155bcc8a941510607219" for domain domain.com, path /, expire 1542143219
>  Set-Cookie: __cfduid=da91839ea04583306a15b50155bcc8a941510607219; expires=Tue, 13-Nov-18 21:06:59 GMT; path=/; domain=.domain.com; HttpOnly
>  Cache-Control: private
>  Vary: Accept-Encoding
>  Added cookie SessionId="zau4wvbprtx5bkkooaojrjlo" for domain sub.domain.com, path /, expire 0
>  Set-Cookie: SessionId=zau4wvbprtx5bkkooaojrjlo; path=/; HttpOnly
>  Strict-Transport-Security: max-age=15552001
>  Server: cloudflare-nginx
> 
cookies has been saved as expected no problem here, i guess
however when sending the post request for login (with saved cookies) it fails to login due to that session is expired

**post request**
```
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_COOKIEJAR, $ckfile);
curl_setopt($ch, CURLOPT_COOKIEFILE, $ckfile);
curl_setopt($ch, CURLOPT_HEADER, FALSE);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_REFERER, $url);
curl_setopt($ch, CURLOPT_VERBOSE, 1);
curl_setopt($ch, CURLOPT_USERAGENT, $useragent);
$postfields = array();
$postfields['username'] = $username;
$postfields['password'] = $password;
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postfields);
$html = curl_exec($ch);
curl_close($ch);
```
**verbose:**

> POST /login.php HTTP/1.1
> User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13 ( .NET CLR 3.5.30729)
> Host: sub.domain.com
> Accept: */*
> Referer: https://sub.domain.com/login.php
> Cookie: SessionId=zau4wvbprtx5bkkooaojrjlo; __cfduid=da91839ea04583306a15b50155bcc8a941510607219
> Content-Length: 1626
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=----------------------------516d523ee66b
> 
>  HTTP/1.1 100 Continue
>  HTTP/1.1 200 OK
>  Date: Mon, 13 Nov 2017 21:07:00 GMT
>  Content-Type: text/html; charset=utf-8
>  Transfer-Encoding: chunked
>  Connection: keep-alive
>  Cache-Control: private
>  Vary: Accept-Encoding
>  X-Frame-Options: SAMEORIGIN
>  Strict-Transport-Security: max-age=15552001
>  Server: cloudflare-nginx
> 

### I expected the following
a successful remote login welcome.
i have tested this with cookies that have a specified expiry date, works just perfect
but when a cookie is set to expire at the end of the session, something goes wrong
### curl/libcurl version

curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.28.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets 

### operating system
CentOS Linux release 7.3.1611 (Core)

**Comment by bagder** [comment]
(First, let me point out that your libcurl version is approaching 5 years old and we have more than 2200 bugfixes recorded as done since that release. Whatever problem you experience with this version, chances are we've already fixed them. We have done several fixes to the cookie engine since back then.)

I don't see any cookie problem in the headers you're showing. You show two cookies being received in the first response headers and then in the second request we see two cookies being sent off to the server.

Or did you just show a working case?

**Comment by dzmodest** [comment]
@bagder okay, just upgraded to the latest version
curl 7.56.1 (x86_64-redhat-linux-gnu) libcurl/7.56.1 NSS/3.28.4 zlib/1.2.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.8.0 nghttp2/1.21.1
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy Metalink PSL 

however still facing the same issue.

no the verbose above is the one which does not work (look same as the one that works)
the problem is the session that has been set "zau4wvbprtx5bkkooaojrjlo" seems expired where it should not, that is the problem

**Comment by bagder** [comment]
> Cookie: SessionId=zau4wvbprtx5bkkooaojrjlo; __cfduid=da91839ea04583306a15b50155bcc8a941510607219

... shows it being sent. Thus not expired. What else did you expect to happen?

**Comment by dzmodest** [comment]
> a successful remote login welcome.

**Comment by jay** [comment]
I don't see the problem here. You have a session cookie and curl saves that cookie.

from the curl [book](https://ec.haxx.se/http-cookies.html)
_"When curl writes cookies to this file, it will save all known cookies including those that are session cookies (without a given lifetime). curl itself has no notion of a session and it doesn't know when a session ends so it will not flush session cookies unless you tell it to."_

You could use [CURLOPT_COOKIESESSION](https://curl.haxx.se/libcurl/c/CURLOPT_COOKIESESSION.html) but I don't know if that is really the problem. You said it "seems like". What is the error you are getting? Is it possible you are not making the proper request? Is there a way we can reproduce it (note this is a public tracker, please don't post anything sensitive).

**Comment by bagder** [comment]
This issue says libcurl expires cookies erroneously and yet it sent off the two cookies it received so I see no signs of any cookies being expired so I'm trying to understand what you're saying doesn't work.

You not getting a successful login can happen because a multitude of reasons, most of them not being because of bugs in libcurl.

**Comment by dzmodest** [comment]
@bagder perhaps this has nothing to do with bugs, probably just a missing post parameter, closing issue for now.
ps: thanks for the update notice.
