### ISSUE TITLE
curl keeps nobody/head once set and is unsettable in the same session

### ISSUE THREAD

**Issue by blodan** [curl/curl#2090]
### I did this
This somehow caches the "--head" param for the second request, although it should not:

curl --verbose --no-sessionid --head https://www.yogamania.se/channel_feeds/prisjakt && curl --verbose --no-sessionid https://www.yogamania.se/channel_feeds/prisjakt

### I expected the following
I expect the body to be returned in the second request, although it is not.

If i run them seperately (one per line instead of &&) it works as expected though.

### curl/libcurl version
curl 7.56.1 (amd64-portbld-freebsd11.1) libcurl/7.56.1 OpenSSL/1.0.2l zlib/1.2.11 libidn2/2.0.4 nghttp2/1.27.0
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy

### operating system
FreeBSD 11.1-RELEASE-p1

**Comment by bagder** [comment]
I'm not sure what exactly you refer to or mean with that it sticks, but with my curl 7.56.1 I can see a `GET` request caused by the second command line when I try your exact command line.

The second command line doesn't seem to get any data back though when used like this, but I can't see that this is because of curl. The server seems to not send any.

**Comment by blodan** [comment]
I'm not entirely sure where the problem is, but somehow the server identifies both chained requests as the same "session" because if you look at the Set-Cookie header thats in the response, the same session= id is sent in both chained request (although the server should not be aware of correlation of the two requests).

If i don't chain the requests the server responds with unique session=id cookies

How is the first scenario possible if curl isnt caching something between the chained requests?

**Comment by blodan** [comment]
Worth noting i experience the same issue in php when doing first a nobody request and then a get request, this is where i found the issue initally but it was easier showing the issue with the curl tool

**Comment by bagder** [comment]
It is the server that associates the two requests and decides to not give you data in the second request. I would presume because of them arriving from the same IP within a certain time period. If you just add a sleep between the comands the second curl invoke gets data back:

`curl --verbose --head https://www.yogamania.se/channel_feeds/prisjakt && sleep 3 && curl --verbose https://www.yogamania.se/channel_feeds/prisjakt`

... while of course the second curl request is *identical* and behaves exactly the same, it is just done with different timing.

Doing the second request using another HTTP version, another user-agent or Referrer: set to something doesn't seem to make a difference. If they're done too close in time the second one gets no data.

**Comment by blodan** [comment]
I guess their nginx server has something fishy configured then, closing the issue as nginx is responding wrongly :)
