### ISSUE TITLE
bug: --interface does not consume argument

### ISSUE THREAD

**Issue by ciofeca** [curl/curl#2104]
If the argument of _--interface_ is not a valid interface, it should abort with an error.

### I did this (on a system without any _eth8_ network interface):
    curl --interface eth8 192.168.5.5

### I expected the following:
_"Error: eth8 does not exist"_

### I instead got this:
_"curl: (45) Could not resolve host: eth8"_

### curl/libcurl version
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2g zlib/1.2.11 libidn2/2.0.2 libpsl/0.18.0 (+libidn2/2.0.2) librtmp/2.3
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy PSL 

### operating system
Ubuntu 17.04

**Comment by jay** [comment]
It does consume the argument:

> "curl: (45) Could not resolve host: eth8"

Error code 45 is CURLE_INTERFACE_FAILED so that is the correct error code. The message 
is because if the argument is not an interface then it falls back to treating it as host or ip.

https://github.com/curl/curl/blob/c514af5a4f5ac3ce724065cc6a8e009373436f78/lib/connect.c#L335-L343

If you turn on verbose you should see `* Couldn't bind to 'eth8'`

**Comment by mkauf** [comment]
You get a better error message if you add the prefix "if!" to the interface name. This tells curl that it's really an interface. For more information, please see [CURLOPT_INTERFACE](https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html).

Example:
```
$ curl --interface 'if!eth8' 192.168.5.5
curl: (45) Couldn't bind to interface 'eth8'
```

**Comment by bagder** [comment]
@jay: sounds like a neat improvement

I see no bug or actual issue here. I'm closing...
