### ISSUE TITLE
commit d3ab7c5a21ebfa0e broke boringssl build

### ISSUE THREAD

**Issue by bagder** [curl/curl#2117]
### I did this

build git master with boringssl

```
vtls/openssl.c: In function ‘cert_stuff’:
vtls/openssl.c:854:12: error: implicit declaration of function ‘RSA_flags’; did you mean ‘RSA_sign’? [-Werror=implicit-function-declaration]
         if(RSA_flags(rsa) & RSA_METHOD_FLAG_NO_CHECK)
            ^~~~~~~~~
            RSA_sign
vtls/openssl.c:854:12: warning: nested extern declaration of ‘RSA_flags’ [-Wnested-externs]
vtls/openssl.c:854:29: error: ‘RSA_METHOD_FLAG_NO_CHECK’ undeclared (first use in this function)
         if(RSA_flags(rsa) & RSA_METHOD_FLAG_NO_CHECK)
                             ^~~~~~~~~~~~~~~~~~~~~~~~

```

(@wmark pointed this out in https://github.com/curl/curl/pull/2081#issuecomment-347270218)

**Comment by bagder** [comment]
TODO: add a boringssl build to travis!

**Comment by wmark** [comment]
For the BoringSSL in Travis, I suggest you don't use the latest version but rewind to the latest tag (usually a »something something for cocoapods«) because there's sometimes breaking changes in between which add unnecessary chaos to test builds.

`git checkout "$(git -C . describe --abbrev=0 --tags HEAD --match "*for_cocoapods*")"`

**Comment by bagder** [comment]
See #2118 for my work on getting this added... but yeah, using a dedicated tag for it seems reasonable.
