### ISSUE TITLE
HTTP Download updates DST error on Windows

### ISSUE THREAD

**Issue by a0099** [curl/curl#2164]
### I did this
Invoked curl.exe with -R and -z <filename>
The file on HTTP server was modified when DST was on (May 2017), now DST is off.
Repeated invocations caused download each time (200 OK) instead of 304 response after file was  downloaded the first time.
### I expected the following
If-Modified-Since in the get request to be the same as Last-Modified in HTTP response.
To calculate "If-Modified-Since" (GMT) curl used current time zone offset instead of the offset active at the time the file was last modified. "Last-Modified" (GMT) returned by MS IIS server was calculated correctly.
Also, Curl should keep and use full history of DST on/off dates for each time zone to handle DST for the files created years ago.
### curl/libcurl version 
curl 7.55.1 (i386-pc-win32) libcurl/7.55.1 zlib/1.2.8
Release-Date: 2017-08-14
### operating system
Windows 2008 64bit

**Comment by bagder** [comment]
This sounds like the good old Windows being one hour off problems. curl stores the file normally (with what I believe is the correct timestamp from the remote server) and it uses the OS function calls to retrieve the time and date of the file in the subsequent request. If that then gets the wrong time due to DST or whatever, I don't think curl can do a whole lot about it. It uses the time the OS tells it.

> the file was last modified. "Last-Modified" (GMT) returned by MS IIS server was calculated correctly

Which calculation was correct do you mean? Are you saying it set the correct file stamp on the saved file?

> Curl should keep and use full history of DST on/off dates for each time zone to handle DST for the files created years ago.

No. curl asks the operating system for the file's timestamp.

**Comment by mkauf** [comment]
This article proposes to use ``GetFileInformationByHandle()`` instead of ``stat()`` on Windows: http://search.cpan.org/~shay/Win32-UTCFileTime-1.58/lib/Win32/UTCFileTime.pm#BACKGROUND_REFERENCE

**Comment by mkauf** [comment]
``tool_operate.c`` contains the function ``setfiletime()`` with special code for Windows. It seems that we need a ``getfiletime()`` too.

As a "workaround", compile curl with a recent version of Visual C++, because ``stat()`` has been fixed in Visual C++ 2013: https://msdn.microsoft.com/en-us/library/bb531344.aspx

**Comment by mkauf** [comment]
Fixed, thanks for reporting!
