### ISSUE TITLE
Corrupted double-linked list found using curl and/or openssl with multithreading

### ISSUE THREAD

**Issue by NishantPatelSB** [curl/curl#2178]
### I did this
I used curl-7.55.1 for HTTPS request using multi-threading (10 thread at a time) (Static link).
After so-many request (100 request within 50sec) there is crash found with corrupted double-linked list.

OpenSSL-1.1.0g used (Dynamic link)

In my program i used ssl crypto locking mechanism as per https://curl.haxx.se/libcurl/c/opensslthreadlock.html.

still issue found.

Curlcallback also used for fetch header part of request.

Every times curl session will be destroyed by me as per my requirement and new request will done with new session. At same time curl callback malloc data also freed.

### Expected output
Application should not face crash.

### operating system
Linux (Platform- Arm-linuxv7 of 32 bit)

###Configuration option
Curl-> --enable-crypto-auth --with-ssl --with-nghttp2 --with-zlib
Openssl -> linux-generic32 shared

**Comment by jay** [comment]
OpenSSL 1.1.x doesn't use locking callbacks, the calls to set them are a no-op. It instead has its own thread support enabled at compile time which should happen by default as long as you have pthreads or win32 threads. If you run `openssl version -a` it should say whether it was compiled with threading support. Also please review our [thread safety guide](https://curl.haxx.se/libcurl/c/threadsafe.html). If you still have the same problem please give us a self-contained example that can be used to reproduce and your `curl_version()` information.

**Comment by NishantPatelSB** [comment]
Hi,
Every thing checked.
openssl is compiled with thread safe.
I was create test application, which is shared with you.
All dependent files/folders are also shared with you.

I was test it and it is reproducible. (check crash_debug file)
[Test_apns_send.tar.gz](https://github.com/curl/curl/files/1578696/Test_apns_send.tar.gz)

[Crash_Debug.txt](https://github.com/curl/curl/files/1578730/Crash_Debug.txt)

**Comment by jay** [comment]
~~~
*** glibc detected *** ./a.out: corrupted double-linked list: 0x30006350 ***
~~~

That is not in curl that is in glibc. There is some memory corruption. Try address sanitizer first then valgrind. Also I notice your example has commented out `curl_global_init(CURL_GLOBAL_ALL);` but you can't do that when you're multi-threading:

"If you are using libcurl with multiple threads it is especially important that before use you call curl_global_init or curl_global_init_mem to explicitly initialize the library and its dependents, rather than rely on the "lazy" fail-safe initialization that takes place the first time curl_easy_init is called."

**Comment by NishantPatelSB** [comment]
Thanks,
Actually I forgot to uncomment it in test aap.
Global init is already call in my main app.
I will try your other suggestions.

**Comment by jay** [comment]
I had the file you posted removed because it contained your apple id and private key and other sensitive information (or so it appears). Please remove that sensitive information in the future. This is a public issue tracker and it's possible someone else may have downloaded the file in that 2 hour time before it was deleted so I suggest change that sensitive information.

**Comment by NishantPatelSB** [comment]
Thank you.
I will take care in future...

**Comment by NishantPatelSB** [comment]
Hi,
Issue found.
I used jansson and in that there is one patch file present in which two time json_decref called, which free memory two times.

Thanks for your support.
