### ISSUE TITLE
Header 'Content-Length: 0' is missing when I do curl -X POST $URI

### ISSUE THREAD

**Issue by tzuryby** [curl/curl#2183]
### I did this
`curl -X POST $URI`

### I expected the following
`200 OK`

### I got
`411 length required` instead.

I needed to explicitly add `-H "Content-Length: 0"`
### curl/libcurl version
`curl 7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP`

### operating system
`Linux ubuntu 3.13.0-110-generic #157~precise1-Ubuntu SMP Mon Feb 20 13:10:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jay** [comment]
https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/

-X just changes the method name it does not change how curl processes the response. You could use [--data ""](https://curl.haxx.se/docs/manpage.html#-d) to send an empty POST.

~~~
POST / HTTP/1.1
Host: localhost:8000
User-Agent: curl/7.58.0-DEV
Accept: */*
Content-Length: 0
Content-Type: application/x-www-form-urlencoded
~~~

Also, you are using a version of curl that is 6 years old. A lot of bugs have been fixed since then.

**Comment by tzuryby** [comment]
So one is willing to POST a request, and your idea says, instead of providing -X POST arg, the user should provide `--data/-d` which implicitly switching on `POST`, and provide it with an empty string, so curl will generate the `Content-Length: 0`. Interesting...
Why would one provide `--data` when there is no data to provide?
It is somewhat counterintuitive to me.


In any case, thank you for maintaining this great tool I use every hour at work!
