### ISSUE TITLE
linking error in Windows on library (netcdf) that uses curl

### ISSUE THREAD

**Issue by pedro-vicente** [curl/curl#2208]
in Windows, when using static build.
It's not in the curl build itself, but on a library (netcdf) that uses curl. When using

`-DCURL_STATICLIB=ON`

, the windows sockets library is missing from the curl library , so you get linking errors

`libcurl-d.lib(select.obj) : error LNK2019: unresolved external symbol __imp__select@20 referenced in function _Curl_socket_check`

one way to fix this is to manually edit the generated libcurl.vcxproj and add

```
<Lib>
      <AdditionalOptions>%(AdditionalOptions) /machine:X86 /machine:X86</AdditionalOptions>
      <AdditionalDependencies>ws2_32.lib</AdditionalDependencies>
    </Lib>
    <ProjectReference>
      <LinkLibraryDependencies>true</LinkLibraryDependencies>
    </ProjectReference>
```

but this should be fixed in some way on the curl Cmake script

to reproduce the bug, do

```
git clone https://github.com/pedro-vicente/nco_bld
cd nco_bld
clone.bat
bld.bat
```

this clones and builds curl and netcdf

for curl, it is used

```
cmake .. -G "Visual Studio 14 2015" ^
           -DCMAKE_BUILD_TYPE=Debug ^
           -DBUILD_SHARED_LIBS=OFF ^
           -DBUILD_TESTING=OFF ^
           -DHTTP_ONLY=ON ^
           -DENABLE_DEBUG=ON ^
           -DENABLE_CURLDEBUG=ON ^
           -DCURL_STATICLIB=ON
  msbuild curl.sln /target:build /property:configuration=debug

```

**Comment by snikulov** [comment]
@pedro-vicente This could not be fixed in curl library, because if you build curl as the static library you depend on external windows library.
It will not be packaged to your curl static library when building, so you should add it to your project explicitly.

In CMake, it is solved by IMPORTED targets for your project [ref](https://cmake.org/cmake/help/v3.5/command/add_library.html)

Could you please confirm that we can close this issue?
Because it is nothing to do on curl side.

**Comment by PerMalmberg** [comment]
I agree with @snikulov - ws2_32.lib needs to be linked to the netcdf project either using add_library() or target_link_library(). This is not a curl issue.

**Comment by bagder** [comment]
Thank you. Deemed not to be a curl problem. Closing!
