### ISSUE TITLE
Push Request not Rx at client side for Curl>=7.56.0, Work properly in Curl-7.55.1

### ISSUE THREAD

**Issue by NishantPatelSB** [curl/curl#2213]
### I did this
I try to send APNs Push notification to Client with Curl-7.57.0 [also tried in curl-7.56.0]. Response Rx from Apple side is proper 200, but push is not Rx to client side.
Same code with same client work properly in Curl-7.55.1

### I expected the following
Client should rx push even for updated curl library.

### curl/libcurl version
Tried in Curl-7.56.0 and Curl-7.57.0.
Properly work in Curl-7.55.1

[curl -7.55.1 output]
Client Rx Push within 5 sec.

[curl -7.56.0/7.57.0 output]
Client should not get Push

### operating system
Linux-Armv7

**Comment by bagder** [comment]
Please explain with more details and specifics. What's an "APN push" to start with and exactly what are you telling curl to do and what does it or doesn't it do, protocol wise? What's "rx push" ? That's not a common terminology for any of the protocols or operations curl does that I'm aware of.

Consider providing a full and short example source code that reproduces the problem so that we can 1) understand it and 2) help fix it.

**Comment by bagder** [comment]
Sparse original report and no response to immediate follow-up questions. Closing.
