### ISSUE TITLE
undefined reference to `SSL_SESSION_get_master_key'

### ISSUE THREAD

**Issue by jungle-boogie** [curl/curl#2246]
Hello,

I am attempting to build curl from src on an openBSD -current x64bit machine, but it's failing with this:

```
$ make
Scanning dependencies of target libcurl
[  0%] Building C object lib/CMakeFiles/libcurl.dir/curl_fnmatch.c.o
[  0%] Linking C shared library libcurl.so
[ 17%] Built target libcurl
[ 17%] Linking C executable curl
CMakeFiles/curl.dir/tool_dirhie.c.o: In function `create_dir_hierarchy':
/home/jungle/bin/curl/src/tool_dirhie.c:(.text+0x131): warning: strcpy() is almost always misused, please use strlcpy()
/home/jungle/bin/curl/build/lib/libcurl.so: warning: sprintf() is often misused, please use snprintf()
/home/jungle/bin/curl/build/lib/libcurl.so: undefined reference to `SSL_SESSION_get_master_key'
/home/jungle/bin/curl/build/lib/libcurl.so: undefined reference to `SSL_get_client_random'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in . (src/CMakeFiles/curl.dir/build.make:1145 'src/curl')
*** Error 1 in . (CMakeFiles/Makefile2:1069 'src/CMakeFiles/curl.dir/all')
*** Error 1 in /home/jungle/bin/curl/build (Makefile:141 'all')
```

I think this check-in might have something to do with it:
https://github.com/curl/curl/commit/84fcaa2e7300387e2565d3037bad637f5f6d8372#diff-7dafef8d70eee3940c9184e4e4e93448

```
$ cc -v
OpenBSD clang version 5.0.1 (tags/RELEASE_501/final) (based on LLVM 5.0.1)
Target: amd64-unknown-openbsd6.2
Thread model: posix
InstalledDir: /usr/bin
```

Last successful build of curl was approximately two days before the commit above.

```
$ openssl version
LibreSSL 2.7.0
```

**Comment by bagder** [comment]
Blah, silly libressl ... PR coming up.

**Comment by jay** [comment]
please test #2247

**Comment by jungle-boogie** [comment]
The build compiles, but now I need to specify my cacert:

```
curl https://github.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

is this related to some change above?

**Comment by jay** [comment]
> The build compiles, but now I need to specify my cacert

I doubt it. Use [`-v`](https://curl.haxx.se/docs/manpage.html#-v) to see where it's getting the certificates from.

**Comment by jungle-boogie** [comment]
yeah, you seem to be right. I went back a few commits and same message appears.

```
* Rebuilt URL to: https://www.github.com/
*   Trying 192.30.255.112...
* TCP_NODELAY set
* Connected to www.github.com (192.30.255.112) port 443 (#0)
* ALPN, offering http/1.1
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

**Comment by bagder** [comment]
That message is usually a sign that the server you're talking to is missing to send an intermediate certificate in the handshake.

**Comment by jay** [comment]
If a default cacert or capath was detected at build time then it would have been set at runtime and you would have seen verbose output like this
~~~
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
~~~
So since that is missing I would assume the configure script couldn't find a certificate bundle or path in the default locations that are checked

https://github.com/curl/curl/blob/62c07b5743490ce373910f469abc8cdc759bec2b/acinclude.m4#L2547-L2557

you will have to specify the bundle or path location if they are not one of the places we check. also can you tell us the default location of your system bundle because then we may be able to add it to the configure script

**Comment by jungle-boogie** [comment]
Thanks for the update.

`/etc/ssl/cert.pem` is correct for openBSD, but perhaps it's an issue with the way I build curl...

```
git clone
cd curl
mkdir build
cd build
cmake ..
make
```

I think autoconf complains and says I need a newer autoconf, but I have autoconf 1.15.1 installed and setup to export the variables in my shell. So this is why I'm building with cmake. Is this undesired?

**Comment by bagder** [comment]
> I have autoconf 1.15.1 installed

That sounds like your automake version, not autoconf...

> I'm building with cmake. Is this undesired?

That's your choice. The cmake build should work, but it is not as feature-full as the configure one.

**Comment by jay** [comment]
ah I didn't realize you were using cmake. it does about the same thing though:

https://github.com/curl/curl/blob/62c07b5743490ce373910f469abc8cdc759bec2b/CMakeLists.txt#L665-L681

Since `/etc/ssl/cert.pem` exists then cmake should have detected that. check your cmake output for the `Found CA bundle:` line and then it should have ended up defined CURL_CA_BUNDLE in build/lib/curl_config.h
