### ISSUE TITLE
Over 5GB RAM to download a 10GB file?

### ISSUE THREAD

**Issue by Spritekin** [curl/curl#2259]
Hi, I have a server with 8GB. Partly used so it has 5 GB free (constant, some docker containers running there but restricted to specific amounts of RAM).

I run another docker container, with no RAM restrictions (so it can use all it needs) and inside I run curl to download a file like this:
```
curl -o tmp_local_file ftp://user:pass@host:port/filename
```
This worked fine for a long time but usually the files were 5GB to 8GB tops. However, recently the ftp owner uploaded some 10GB files and the service used up all the RAM then crashed. It always got to around 88% of the file download then it crashes with an error 23.

I did run in another server with 32GB RAM and it essentially consumed like 10GB RAM. I did see the RAM going down from 31GB to around 20GB but it did finish and did write the file.

I'm running curl inside a Debian:jessie docker image. As I said, it runs ok as long as I provide lots of RAM. 

The point is... I was expecting curl to read then flush the data to disk so no need to keep so much data in RAM. However it looks like it keep accumulating it. Is this expected  behaviour?

So for the version:
```
> curl -V
curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
```
Thanks!
Guimo

**Comment by gvanem** [comment]
Must be an issue on Linux; this does not happen on Windows. To follow you claim, if I d/l a 390 MByte file using ftp, curl should consume approx. 185 MByte. Well, it doesn't. The *Private Bytes* are at 34 MByte constant: 
![curl-huge-ftp](https://user-images.githubusercontent.com/945271/35275785-238cc26c-0041-11e8-90c5-b65a84a46f26.png)

Using this command:
`curl --limit-rate 100k -o c:\TEMP\making-rain.m4v ftp://ftp.uib.no/pub/users/hmifs/Making%20rain.m4v`

**Comment by gvanem** [comment]
Ops. Pressed `Close` by mistake.

**Comment by bagder** [comment]
(First, we can note that you reported this on a fairly old version, although nothing ground breaking has been done to change the allocation concept internally in those three plus years since 7.38.0 was released.)

As @gvanem is saying: this isn't curl "using the memory". It is your Linux system using up the memory for caches and buffers. curl itself actually uses fairly small amounts of memory and for downloading, the used memory is basically a fixed amount no matter how large file you download. It'll just vary a little bit depending on what features are used.

## A little experiment.

Here's a widely known 100MB file: `https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.14.14.tar.xz`

Check the size:
```
$ curl -IL https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.14.14.tar.xz
...
content-length: 100829040
```
Download the file (which actually is 96MB if we want to be exact) over HTTPS (and it actually also uses HTTP/2), instrument the heap usage with valgrind's massif tool that takes and logs snapshots of the heap usage through the program's life time.

    $ valgrind --tool=massif ./src/curl https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.14.14.tar.xz -O

Figure out how much help memory this curl executable used at any single point in time when it downloaded that file:

    $ grep ^mem_heap_B massif.out.* | cut "-d=" -f2 | sort -rn | head -n 1
    1329867

So 1.27 MB was allocated at the peak allocation moment by curl and all the libraries and calls it uses. To download a 96 MB file. Okay, so let's download a 80GB file over HTTP and compare?

    $ valgrind --tool=massif ./src/curl http://localhost/80GB -o /dev/null
    $ grep ^mem_heap_B massif.out.* | cut "-d=" -f2 | sort -rn | head -n 1
    1279261

Less memory. Probably because this HTTP/1.1 and no HTTPS involved. 1.22 MB of memory allocated on heap is the peak usage level.

## Conclusion

curl doesn't use a lot of memory!

**Comment by Spritekin** [comment]
As I said I'm using a Docker image based on Debian. The image is allowed to take as much RAM as it needs from the host. No Constraints.
The image was run in 3 different OS for this tests. 
OSX, 16 GB: RAM usage increased until it finished downloading then file was written ok.
AWS RHEL-based EC2 Instance, 8GB RAM: RAM used until process crashed with error 23 at around 88% of the file.
Ubuntu 14.04, 32GB RAM. RAM used from 31Gb to 20 GB. Download finished and file written ok.

In all three cases the same Docker image was run.

So if you say it is not using RAM, so be it. However I can't deny what I observe. We use exactly the same image for a lot of scheduled tasks and they never consume RAM. This one does.

Unfortunately this data is removed as soon as I get them form the FTP so I can't reproduce to send screenshots. Maybe I can ask them to repost a file but may be hard because is quite sensitive data.

**Comment by bagder** [comment]
> RAM used until process crashed with error 23 at around 88% of the file.

That's a write error, not an out-of-memory error. It sounds more like you store the data in a ramdisk or something.

**Comment by Spritekin** [comment]
The command is quite straightforward as sent at the beginning. 
curl -o tmp_local_file ftp://user:pass@host:port/filename

I don't have ramdisks or anything like that. Docker just writes any output to disk.
But true, it might be possible something is in the middle.

Ok I will do something... I will test the command outside of docker and report.
