### ISSUE TITLE
Seems that Curl misunderstand parameter

### ISSUE THREAD

**Issue by napasa** [curl/curl#2267]
### I did this
Under Git-bash
[Screen Shot](https://drive.google.com/file/d/1RC_TGtOcYLjk_6okCuebGsb_mRPjksqo/view?usp=sharing)
### I expected the following
Regard value of variable d8sessionid pair as a string, not file name.
### curl/libcurl version
curl 7.46.0 (i686-w64-mingw32) libcurl/7.46.0 OpenSSL/1.0.2e zlib/1.2.8 libidn/1.32 libssh2/1.6.0 librtmp/2.3

[curl -V output]
* timeout on name lookup is not supported
*   Trying 119.90.39.142...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to upload.doc88.com (119.90.39.142) port 80 (#0)
* couldn't open file "tpl>$sessionid</tpl>"
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (26) couldn't open file "tpl>$sessionid</tpl>"

### operating system
windows 10

**Comment by jay** [comment]
Please don't just link to a screenshot with the command. Instead actually post the command in the issue.

The reporter is basically trying to do this:
`curl -F "uploadsessionid=<tpl>$sessionid</tpl>" http://website`
which fails because starting the content part with < means read from a file. Refer to [-F,--form](https://curl.haxx.se/docs/manpage.html#-F)

IIRC the right workaround is add a space before the content, but I don't see it documented so I'm not sure it's intended. For example this should work:
`curl -F "uploadsessionid= <tpl>$sessionid</tpl>" http://website`

/cc @monnerat

**Comment by napasa** [comment]
But  prepend a space will cause a difference Form value as the HTTP packets I captured.

**Comment by jay** [comment]
Looks like [--form-string](https://curl.haxx.se/docs/manpage.html#--form-string) is the answer.
`curl --form-string "uploadsessionid=<tpl>$sessionid</tpl>" http://website`

I notice --form-string doesn't strip a trailing space for example "foo= bar" even though -F now does. Is the behavior of -F supposed to do that?

**Comment by napasa** [comment]
Thanks It works

**Comment by napasa** [comment]
@jay Hi, Jay, I meet a new problem,  I cant figure out how to urlencode form data as though I have read up relative man page. how to urlencode "110kV变电站一次部分设计-毕业论文.pdf"? I tried to append';encoder=base64' to 'Filename=110kV变电站一次部分设计-毕业论文.pdf' string as 
[man page](https://curl.haxx.se/docs/manpage.html#-F) said which is not work.
`curl  --cookie "$cookie"  -F 'Filename=110kV变电站一次部分设计-毕业论文.pdf' -F "act=upload" --form-string "$d8sessionid" -F "Filedata=@../110kV变电站一次部分设计-毕业论文.pdf"  $url`

**Comment by monnerat** [comment]
The more general alternative is quoting as:

`curl -F "uploadsessionid=\"<tpl>$sessionid</tpl>\"" http://website`

> I notice --form-string doesn't strip a trailing space for example "foo= bar" even though -F now does. Is the behavior of -F supposed to do that?

Leading/trailing spaces are 90% of the times intended to be part of leading/trailing separators (i.e: as a visual highlighting similar to what i've done after "i.e.:" in this parenthesed note), therefore it's more convenient to strip them by default. Leading/trailing spaces can be retained by quoting.
--form-string is meant to provided "as-is" values and does not support additional options.

In curl.1 man page:
```
              Quoting must also be applied to non-file  data  if  it  contains
              semicolons, leading/trailing spaces or leading double quotes:
```

**Comment by monnerat** [comment]
> I tried to append';encoder=base64' to 'Filename=110kV变电站一次部分设计-毕业论文.pdf' string as
man page said which is not work.

encoder=base64 is only a way to set the transfer encoding and represent transferred data as such: it is mainly used to "textualize" binary data without altering it.

In the `-F` case, the HTTP protocol does not need field data to be url-encoded, because the whole post data is transferred with a multipart/form-data content type, not as application/x-www-form-urlencoded.

The only thing you need is to send data in the default encoding expected by the server, or tell explicitly what the character set encoding is, as:

`'Filename=110kV变电站一次部分设计-毕业论文.pdf; type=text/plain; charset=UTF8'`

(substitute your effective encoding to UTF8).

If you really want to urlencode the data for you own needs, you have to do it with an external command, like

``"Filename=`urlencode 110kV变电站一次部分设计-毕业论文.pdf`"``

**Comment by napasa** [comment]
Hi, Sir. It seems caused by curl client  don`t know what the encode of the param I passed. my bash file is encoded in UTF8, run under git-bash.
The below image  is  screen shot of  captured Multipart data sended from curl command line is decoded in UTF8.
![image](https://user-images.githubusercontent.com/8340899/35484140-d2a7e864-0486-11e8-823a-c4150a7c7f79.png)
The below image  is  screen shot of  captured Multipart data sended from Chrome Browser is decoded in UTF8, which is my expected result.
![image](https://user-images.githubusercontent.com/8340899/35484204-c8ea752a-0487-11e8-8ad6-1f15423fdf47.png)

**Comment by napasa** [comment]
Hi, @monnerat I upload ScreenShot of packet captured.

**Comment by napasa** [comment]
The reason is don`t pass UTF8 string to curl. Emmmm, How to pass UTF8 string to curl?

**Comment by monnerat** [comment]
This is definely a character encoding problem.

- Maybe chrome sends data in the server encoding, while curl does not transcode.
- Maybe there's an indication in the stream (not visible on your screenshot) that does the job for wireshark and the server: a full dialog capture with binary rather than screenshots would be more helpful.

Try the "; type=...; charset=UTF8" trick above... this will tell the server about the encoding used by the client anf hopefully make it transcode by itself.

**Comment by monnerat** [comment]
Don't pass UTF8 if you don't have it: rather use use 'Filename=yourfilename; type=text/plain; charset=yourencoding'

**Comment by napasa** [comment]
My server is UTF8 encoding.I ever tried 'Filename=yourfilename; type=text/plain; charset=yourencoding', It don`t have any different result

**Comment by napasa** [comment]
Wow! I know reason now ,  after I export my packet and open it by notepad which shows the string passed is encoded in GB2312.
![image](https://user-images.githubusercontent.com/8340899/35484641-90343e68-048d-11e8-897a-0941bc572916.png)

**Comment by napasa** [comment]
But I have Set git-bash and my bash file in utf8 encoding

**Comment by monnerat** [comment]
From your comments, client-issued- and server-expected- encodings are not clear, although obvioulsy different.
The first thing you have to do is to determine them without doubt.

If you need an external conversion, use the iconv program (http://man7.org/linux/man-pages/man1/iconv.1.html), as:

``-F "Filename=\"`echo -n 110kV变电站一次部分设计-毕业论文.pdf | iconv -f clientencoding -t serverencoding`\""``

**Comment by napasa** [comment]
I test it tomorrow night.  My mom request me go to sleep
