### ISSUE TITLE
Enable --trace using the libcurl api

### ISSUE THREAD

**Issue by martinlindhe** [curl/curl#2283]
### I did this
I want to debug code using libcurl, and I want to enable the feature corresponding to the `---trace` command-line switch.

### I expected the following
I expected to find this exposed in the libcurl api.

Instead I found an example implementing one's own callback at https://curl.haxx.se/libcurl/c/CURLOPT_DEBUGFUNCTION.html
It would be great if the default behavior was exposed through the api.

### curl/libcurl version
curl 7.58.0 (x86_64-apple-darwin17.3.0) libcurl/7.58.0 SecureTransport zlib/1.2.11

### operating system
macOS

**Comment by bagder** [comment]
I wouldn't presume that the `--trace` behavior is what applications in general want, which is why the API is more generic. We do however provide the [debug.c example](https://curl.haxx.se/libcurl/c/debug.html) to let users copy and paste easily in case they actually do want to get inspiration from something that looks quite like curl's output.

I'm not convinced it is worthwhile adding a new callback with this functionality to the library as we the existing one offering this feature is close enough.

(Additionally, we don't keep feature-requests around in the bug tracker, which means that this issue will be closed soonish.)

**Comment by martinlindhe** [comment]
Fair enough. Thank you Daniel for taking your time to explain.
