### ISSUE TITLE
Windows build (Makefile.vc): add bufferoverflowu.lib for VC7 and 8

### ISSUE THREAD

**Issue by rodwiddowson** [curl/curl#2327]
Over [Here ](https://curl.haxx.se/mail/lib-2018-02/0075.html)Daniel noted (channelling Stefan Kanthak):
-----------
apply the following changes to "winbuild/MakefileBuild.vc" to  fix build errors

```

--- curl-7.58.0/winbuild/MakefileBuild.vc    2018-01-22 09:55
+++ curl-patch/winbuild/MakefileBuild.vc
@@ -75,1 +75,7 @@
-WIN_LIBS    = ws2_32.lib wldap32.lib advapi32.lib
+!IF "$(VC)"=="7"
+WIN_LIBS    = ws2_32.lib wldap32.lib bufferoverflowu.lib advapi32.lib
+!ELSEIF "$(VC)"=="8"
+WIN_LIBS    = ws2_32.lib wldap32.lib bufferoverflowu.lib advapi32.lib
+!ELSE
+WIN_LIBS    = ws2_32.lib wldap32.lib advapi32.lib
+!ENDIF

```

    According to "curl-7.58.0/projects/README" the platform SDK
    for Windows Server 2003 SP1 (which contains the VC7 and pre-VC8
    compiler and linker) can be used to build cURL.
    This but fails unless bufferoverflowu.lib is added to WIN_LIBS

**Comment by bagder** [comment]
Do we need to care for those old MSVC versions?

**Comment by jay** [comment]
i think it would be better as

```
!IF "$(VC)"=="8" || "$(VC)"=="9"
WIN_LIBS    = $(WIN_LIBS) bufferoverflowu.lib
!ENDIF
```

> Do we need to care for those old MSVC versions?

If it's already working and we can continue to support them I say why not fix it if there's a bug. OTOH recently MS retired some of the online documentation for older versions of Visual Studio so it's not easy to figure out in those older versions what is supported in what. As to the particular issue in this thread though I suspect it has something to do with this reporter (Kanthak) and the way he's building (see also #2328) so it's probably not affecting anyone else.

**Comment by bagder** [comment]
I don't sense anyone being very interesting in pushing this forward. Would anyone object if we just close this and move on?

**Comment by jay** [comment]
> I don't sense anyone being very interesting in pushing this forward. Would anyone object if we just close this and move on?

As best I can tell by googling bufferoverflowu.lib it may or may not be available depending on the sdk. In Visual Studio 2003 it is needed when /GS is specified but /GS is not the default so we can assume he's probably specifying GS on his own which is why this issue. In VS2005 it is by default and so bufferoverflowu.lib is already added. This seems like it is specific to him. Let's wait for another report of it before investigating further.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/fc6d520c-d53b-4309-8f5e-76be3f0e2b73/link-fatal-error-lnk1104-cannot-open-file-bufferoverflowulib-on-vs2010?forum=vcgeneral
https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-what-s-new-2003-through-2015
