### ISSUE TITLE
Suggestion to change default globbing behaviour

### ISSUE THREAD

**Issue by lassehp** [curl/curl#2352]
### I did this
curl 'http://solr-host/....some-query-with-tagged-fqs-and-exclusions-using{!ex=sometag}-and-{!tag=sometag}'

### I expected the following
the response from the server given that URL. I did not expect a default unsafe tool behaviour that mangles URLs.

After close inspection of the man page I now understand that globbing is a "feature" provided by curl. I would like to suggest that such a "feature" as a default behaviour is confusing (proof: well, it confused me), and should be something that must be explicitly enabled, rather than disabled using -g. In general, I expect tools to not bite my ass like this.

wget does not behave this way, I have been using curl because that is what the Solr documentation uses, and it saves an '-O -' option to send output to stdout.

I understand that this is documented default behaviour working as designed, and I even think it is nice and might be useful now that I know about it, but even so, I would kindly suggest the safer default behaviour of messing with the url only when asked to, for example with a "-G" option for globbing. I am quite sure it will save some other poor souls from suffering painful assbite.

### curl/libcurl version
curl 7.26.0 (x86_64-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

(not really relevant.)

### operating system
Linux, particular version not relevant.

**Comment by bagder** [comment]
I find it ironic that you're using an almost 6 years old version when you ask this, as even if we had changed this the last 6 years you would've have noticed...

Seriously though: we can't change this default without risking damaging numerous curl-using scripts used by users everywhere since a long time back.

It can be further noted that we chose to use the `[` and `{` letters in the URLs for this purpose since no *legal* URL by RFC3986 can contain such letters. They need to be URL encoded to appear in URLs. Over the years however, the URL "standard" has erroded and nowadays URLs are not as strictly defined as they once were.
