### ISSUE TITLE
install failed with openssl1.0.2n

### ISSUE THREAD

**Issue by Igamegum** [curl/curl#2366]
### I did this
I have install openssl 1.0.2n in the path /usr/local/ssl,I compile the curl source code with these command
1. cd curl
2. ./buildconf
3. ./configure --with-ssl=/usr/local/ssl
4. make
### I expected the following
when I run make command ,I get errors like this

> Making all in lib
make[1]: Entering directory '/home/elin/桌面/curl/lib'
make  all-am
make[2]: Entering directory '/home/elin/桌面/curl/lib'
  CCLD     libcurl.la
/usr/bin/ld: /usr/local/ssl/lib/libssl.a(s3_clnt.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/ssl/lib/libssl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:903: recipe for target 'libcurl.la' failed
make[2]: *** [libcurl.la] Error 1
make[2]: Leaving directory '/home/elin/桌面/curl/lib'
Makefile:744: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/elin/桌面/curl/lib'
Makefile:925: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

### curl/libcurl version

[curl -V output]
curl 7.59.0-DEV (x86_64-pc-linux-gnu) libcurl/7.59.0-DEV OpenSSL/1.0.2g zlib/1.2.8
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 

### operating system
ubuntu16.04

How can I solve this problem,thans for your help!

**Comment by Tianjiao** [comment]
It is caused by your Chinese path name maybe. Change it to lowercase Latin path name may solve this problem.

Change 
` '/home/elin/桌面/curl/lib'`
to
` '/home/elin/desktop/curl/lib'`

That is, you can make a new directory using the lowercase Latin name, then extracting the source tarball in there. Then compile it to see if your problem could by solved. 

I have compiled an open-source program and encountered the similar problem, but solved in this way.

However, reporting any possible bug in the Github is appreciated, I think.

**Comment by Igamegum** [comment]
@Tianjiao  Sorry,I try your way.but it does not work!

**Comment by Tianjiao** [comment]
@Igamegum , could you please paste your error log? After you change it to the Latin name.

**Comment by monnerat** [comment]
> /usr/bin/ld: /usr/local/ssl/lib/libssl.a(s3_clnt.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

I suspect this is the proper thing to do: You are trying to build a shared library including code from a static library and the later has not been compiled with options that would allow that.

I suggest you either recompile ssl with option -fPIC or link curl with the ssl shared libraries.

**Comment by Igamegum** [comment]
@Tianjiao emm,the error log is same as above

**Comment by bagder** [comment]
I'll repeat @monnerat's suggestion: either recompile openssl with option -fPIC or link curl with the ssl shared libraries.

**Comment by Tianjiao** [comment]
@Igamegum , Hi, I have reproduced the similar error on my Ubuntu 17.10, but after following the advice from @monnerat , the error has resolved on my computer.

When I compile the [OpenSSL](https://wiki.openssl.org/index.php/Compilation_and_Installation), I do the following:
`export CFLAGS=-fPIC`
or
`./config shared --prefix=/your/path`

And I type in the following command before re-compile:
`make clean`

Here is my complete commands in re-compiling the OpenSSL:

```
cd openssl-1.0.2n/
make clean
export CFLAGS=-fPIC
./config shared
make
make test
sudo make install
```

Then I re-compile the curl:
```
cd curl
make clean
./buildconf
./configure --with-ssl=/usr/local/ssl
make
make test
sudo make install
```
Then everthing goes fine, hope that my experience could be useful to you.
If you encounter any error, feel free to report it here.

**Comment by Igamegum** [comment]
@Tianjiao Thanks for your reply
I re-compiling OpenSSL success
But I got error when I re-compile the curl
when I execute command make test
the error show as below

> make[2]: *** No rule to make target '../../lib/libcurl.la', needed by 'libauthretry'。 停止。
make[2]: Leaving directory '/home/elin/curl/tests/libtest'
Makefile:514: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/elin/curl/tests'
Makefile:1373: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by Tianjiao** [comment]
> It seem that my system lack some dependence
> I run command apt-get install -f to solve this problem

@Igamegum , Congratulations for your successful build.
The command of "apt-get install -f " is a convenient way if it is not clear which dependency is lacked of.

However, on the Ubuntu/Debian system, there is a package for the building tools:
`sudo apt-get install build-essential`

And a list of dependencies by the curl can be seen [here](https://curl.haxx.se/docs/libs.html).
They are optional. And [nghttp2](https://nghttp2.org/), a HTTP/2 library, I have seen some pre-compiled [binary](https://winampplugins.co.uk/curl/) of curl includes it.

Often the [zlib](http://zlib.net/) is missing in the system, because the default installation of Ubuntu/Debian does not include it:
`sudo apt-get install zlib1g-dev`

And IPv6 support(optional but recommended).

**Comment by bagder** [comment]
@Igamegum so this issue is now resolved?

**Comment by Igamegum** [comment]
@bagder Yes,the problem is solved
Thanks everyone！
