### ISSUE TITLE
No torture tests.

### ISSUE THREAD

**Issue by TimJSwan89** [curl/curl#2434]
### I did this
```
git clone https://github.com/curl/curl.git
cd curl/
CC=gcc CFLAGS='-fprofile-arcs -ftest-coverage -g -O0' cmake -DCURL_STATICLIB=ON .
make
$ make test-torture
make: *** No rule to make target 'test-torture'.  Stop.
```
also tried:
```
wget https://curl.haxx.se/download/curl-7.59.0.tar.gz
tar -xzf curl-7.59.0.tar.gz
cd curl-7.59.0/
autoreconf -i
./configure
make test-torture
```
### I expected the following
torture tests run or build
### curl/libcurl version
Building from source.
Tried
```
git checkout 00cda0f9b31e45512776670201f9ec2eec095338
git checkout bea18c7f39d2d470c4965444519271e8ff380fb3
```
### operating system
ubuntu

**Comment by bagder** [comment]
What you check out from git is the sources. They're not identical to the release archives. The release archives are generated at the time of the release from the source code with the associated tag.

Among other things, the release archives get freshly generated `configure` scripts that you ran in the download case but not in the git case.

The configure script sets up the makefiles and other things so that you can build curl, libcurl and the test suite. Optionally, you can use cmake instead, but even then that must be invoked first so that you can build everything.

When configure (or cmake) has run and you've built curl and libcurl, then you can build the test suite and *then* you can run the tests and the torture tests!

**Comment by bagder** [comment]
1. When you build from git instead of tarball you should read up on `GIT-INFO` on how to set things up.

2. I think you can do it with the cmake build as well, but you need to enable debug builds. (I personally normally build with configure + make.) 

3. The torture builds *require* a debug build, yes, because it needs special instrumentation of the code to work. Those special things are not there in non-debug builds as they're impacting performance and more.
