### ISSUE TITLE
Locale issue on test1148

### ISSUE THREAD

**Issue by Oumph** [curl/curl#2436]
### I did this

curl https://curl.haxx.se/download/curl-7.59.0.tar.xz|tar xvJf - && cd curl-7.59.0 && ./configure && make && make check

Test 1148 failed due to locale LC_NUMERIC=fr_FR.UTF-8 (dot vs comma for 100.0% in the progressbar)

```
 1148: output (log/stderrlog1148) FAILED:
--- log/check-expected	2018-03-29 14:40:25.206158459 +0200
+++ log/check-generated	2018-03-29 14:40:25.206158459 +0200
@@ -1 +1 @@
-[CR]######################################################################## 100.0%[LF]
+[CR]######################################################################## 100,0%[LF]
```

### I expected the following

Success for test 1148

### curl/libcurl version

```
curl 7.59.0 (x86_64-pc-linux-gnu) libcurl/7.59.0 OpenSSL/1.1.0g zlib/1.2.8
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 
```

### operating system

Debian Sid x86_64

### Fix

```
$ diff -u curl-7.59.0.old/tests/data/test1148 curl-7.59.0.new/tests/data/test1148
--- curl-7.59.0.old/tests/data/test1148	2017-12-03 00:33:21.000000000 +0100
+++ curl-7.59.0.new/tests/data/test1148	2018-03-29 14:42:08.732211027 +0200
@@ -37,6 +37,10 @@
  <command>
 http://%HOSTIP:%HTTPPORT/1148 -# --stderr log/stderrlog1148
 </command>
+<setenv>
+LC_ALL=
+LC_NUMERIC=en_US.UTF-8
+</setenv>
 </client>
 
 #
```

**Comment by cerium001** [comment]
Hi all,
Even I am Facing similar issue for test 1148.
Since I am new to programming can anyone please help me out?

For me when I try to Build curl on Ubuntu-Host machine
-  curl https://curl.haxx.se/download/curl-7.59.0.tar.xz|tar xvJf - && cd curl-7.59.0 && ./configure && make && make check, Everything passes successfully

But when I try to Build the Same on My target Board(armv7a), it is Failing with the Following Error:
{{{
********* System characteristics ******** 
* curl 7.59.0 (arm-sony-linux-gnueabi) 
* libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.11
* Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 
* Host: 10.0.15.2
* System: Linux 10.0.15.2 
* Servers: HTTP-IPv6 HTTP-unix FTP-IPv6 
* Env: 
***************************************** 
RUN: server/sws --pidfile ".http_server.pid" --logfile "log/http_server.log" --ipv4 --port 8990 --srcdir "../../tests"
test 1148...[progress-bar]

 1148: output (log/stderrlog1148) FAILED:
--- log/check-expected	2018-03-30 14:42:54.913781000 +0000
+++ log/check-generated	2018-03-30 14:42:54.881781000 +0000
@@ -1 +1 @@
-[CR]######################################################################## 100.0%[LF]
+#=#=#                                                                         [CR][CR]######################################################################## 100.0%[LF]
== Contents of files in the log/ dir after test 1148
=== Start of file check-expected
 [CR]######################################################################## 100.0%[LF]
=== End of file check-expected
=== Start of file check-generated
 #=#=#                                                                         [CR][CR]######################################################################## 100.0%[LF]
=== End of file check-generated
=== Start of file curl.log
 ../src/curl --output log/curl1148.out  --include --trace-ascii log/trace1148 --trace-time http://127.0.0.1:8990/1148 -# --stderr log/stderrlog1148 >log/stdout1148 2>log/stderr1148
=== End of file curl.log
=== Start of file curl1148.out
 HTTP/1.1 200 OK
 Date: Thu, 09 Nov 2010 14:49:00 GMT
 Server: test-server/fake
 Last-Modified: Tue, 13 Jun 2000 12:10:00 GMT
 ETag: "21025-dc7-39462498"
 Accept-Ranges: bytes
 Content-Length: 60
 Connection: close
 Content-Type: text/html
 Funny-head: yesyes
 zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
=== End of file curl1148.out
=== Start of file curlverout.log
 curl 7.59.0 (arm-sony-linux-gnueabi) libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.11
 Release-Date: 2018-03-14
 Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
 Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 
=== End of file curlverout.log
=== Start of file http_server.log
 20:12:52.617896 Running HTTP IPv4 version on port 8990
 20:12:52.673896 Wrote pid 1956 to .http_server.pid
 20:12:53.658851 ====> Client connect
 20:12:53.699165 accept_connection 3 returned 4
 20:12:53.741462 accept_connection 3 returned 0
 20:12:53.782417 Read 92 bytes
 20:12:53.824683 Process 92 bytes request
 20:12:53.866981 Got request: GET /verifiedserver HTTP/1.1
 20:12:53.909187 Are-we-friendly question received
 20:12:53.952186 Wrote request (92 bytes) input to log/server.input
 20:12:54.021186 Identifying ourselves as friends
 20:12:54.080817 Response sent (55 bytes) and written to log/server.response
 20:12:54.165382 special request received, no persistency
 20:12:54.215278 ====> Client disconnect 0
 20:12:55.358314 ====> Client connect
 20:12:55.399360 accept_connection 3 returned 4
 20:12:55.441657 accept_connection 3 returned 0
 20:12:55.483894 Read 82 bytes
 20:12:55.526130 Process 82 bytes request
 20:12:55.568458 Got request: GET /1148 HTTP/1.1
 20:12:55.610664 Requested test number 1148 part 0
 20:12:55.653480 - request found to be complete
 20:12:55.695899 Wrote request (82 bytes) input to log/server.input
 20:12:55.821387 Send response test1148 section <data>
 20:12:55.879646 Response sent (311 bytes) and written to log/server.response
 20:12:55.930915 => persistant connection request ended, awaits new request
 20:12:55.982124 Connection closed by client
 20:12:56.033363 ====> Client disconnect 0
=== End of file http_server.log
=== Start of file http_verify.log
 *   Trying 127.0.0.1...
 * TCP_NODELAY set
 * Connected to 127.0.0.1 (127.0.0.1) port 8990 (#0)
 > GET /verifiedserver HTTP/1.1
 > Host: 127.0.0.1:8990
 > User-Agent: curl/7.59.0
 > Accept: */*
 > 
 < HTTP/1.1 200 OK
 < Content-Length: 16
 < 
 { [16 bytes data]
 * Connection #0 to host 127.0.0.1 left intact
=== End of file http_verify.log
=== Start of file http_verify.out
 WE ROOLZ: 1956
=== End of file http_verify.out
=== Start of file server.input
 GET /1148 HTTP/1.1
 Host: 127.0.0.1:8990
 User-Agent: curl/7.59.0
 Accept: */*
=== End of file server.input
=== Start of file server.response
 HTTP/1.1 200 OK
 Content-Length: 16
 WE ROOLZ: 1956
 HTTP/1.1 200 OK
 Date: Thu, 09 Nov 2010 14:49:00 GMT
 Server: test-server/fake
 Last-Modified: Tue, 13 Jun 2000 12:10:00 GMT
 ETag: "21025-dc7-39462498"
 Accept-Ranges: bytes
 Content-Length: 60
 Connection: close
 Content-Type: text/html
 Funny-head: yesyes
 zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
=== End of file server.response
=== Start of file stderrlog1148
 #=#=#                                                                         
 
 ######################################################################## 100.0%
=== End of file stderrlog1148
=== Start of file trace1148
 20:12:55.355811 == Info:   Trying 127.0.0.1...
 20:12:55.356971 == Info: TCP_NODELAY set
 20:12:55.357764 == Info: Connected to 127.0.0.1 (127.0.0.1) port 8990 (#0)
 20:12:55.358772 => Send header, 82 bytes (0x52)
 0000: GET /1148 HTTP/1.1
 0014: Host: 127.0.0.1:8990
 002a: User-Agent: curl/7.59.0
 0043: Accept: */*
 0050: 
 20:12:55.848640 <= Recv header, 16 bytes (0x10)
 0000: HTTP/1.1 200 OK.
 20:12:55.849677 <= Recv header, 36 bytes (0x24)
 0000: Date: Thu, 09 Nov 2010 14:49:00 GMT.
 20:12:55.849830 <= Recv header, 25 bytes (0x19)
 0000: Server: test-server/fake.
 20:12:55.849952 <= Recv header, 45 bytes (0x2d)
 0000: Last-Modified: Tue, 13 Jun 2000 12:10:00 GMT.
 20:12:55.850166 <= Recv header, 27 bytes (0x1b)
 0000: ETag: "21025-dc7-39462498".
 20:12:55.850288 <= Recv header, 21 bytes (0x15)
 0000: Accept-Ranges: bytes.
 20:12:55.850410 <= Recv header, 19 bytes (0x13)
 0000: Content-Length: 60.
 20:12:55.850562 <= Recv header, 18 bytes (0x12)
 0000: Connection: close.
 20:12:55.850654 <= Recv header, 24 bytes (0x18)
 0000: Content-Type: text/html.
 20:12:55.850776 <= Recv header, 19 bytes (0x13)
 0000: Funny-head: yesyes.
 20:12:55.850898 <= Recv header, 1 bytes (0x1)
 0000: .
 20:12:55.850959 <= Recv data, 60 bytes (0x3c)
 0000: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.
 20:12:55.851325 == Info: Closing connection 0
=== End of file trace1148

Test suite total running time breakdown per task...

Spent 0002.665 seconds starting and verifying test harness servers.
Spent 0000.017 seconds reading definitions and doing test preparations.
Spent 0000.802 seconds actually running test tools.
Spent 0000.101 seconds awaiting server logs lock removal.
Spent 0000.009 seconds verifying test results.
Spent 0003.594 seconds doing all of the above.

Test server starting and verification time per test (top 25)...

-time-  test
------  ----
02.665  1148

Test definition reading and preparation time per test (top 10)...

-time-  test
------  ----
00.017  1148

Test tool execution time per test (top 25)...

-time-  test
------  ----
00.802  1148

Test server logs lock removal time per test (top 15)...

-time-  test
------  ----
00.101  1148

Test results verification time per test (top 10)...

-time-  test
------  ----
00.009  1148

Total time per test (top 50)...

-time-  test
------  ----
03.594  1148

TESTDONE: 0 tests out of 1 reported OK: 0%
TESTFAIL: These test cases failed: 1148 
TESTDONE: 1 tests were considered during 4 seconds.
}}}

The Only difference I could find is addition of some extra spaces in the log.
{{{
test 1148...[progress-bar]

 1148: output (log/stderrlog1148) FAILED:
--- log/check-expected	2018-03-30 14:42:54.913781000 +0000
+++ log/check-generated	2018-03-30 14:42:54.881781000 +0000
@@ -1 +1 @@
-[CR]######################################################################## 100.0%[LF]
+#=#=#                                                                         [CR][CR]######################################################################## 100.0%[LF]
}}}

Can anyone Please help in resolving it?
Or is the test successful?

**Comment by cerium001** [comment]
Hi all,
Even I am Facing similar issue for test 1148.
Since I am new to programming can anyone please help me out?

For me when I try to Build curl on Ubuntu-Host machine

curl https://curl.haxx.se/download/curl-7.59.0.tar.xz|tar xvJf - && cd curl-7.59.0 && ./configure && make && make check, Everything passes successfully
But when I try to Build the Same on My target Board(armv7a), it is Failing with the Following Error:
{{{
********* System characteristics ********

curl 7.59.0 ()
libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.11
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
Host: 10.0.15.2
System: Linux 10.0.15.2 armv7a
Servers: HTTP-IPv6 HTTP-unix FTP-IPv6
Env:
RUN: server/sws --pidfile ".http_server.pid" --logfile "log/http_server.log" --ipv4 --port 8990 --srcdir "../../tests"
test 1148...[progress-bar]

1148: output (log/stderrlog1148) FAILED:
--- log/check-expected	2018-03-30 14:42:54.913781000 +0000
+++ log/check-generated	2018-03-30 14:42:54.881781000 +0000
@@ -1 +1 @@
-[CR]######################################################################## 100.0%[LF]
+#=#=# [CR][CR]######################################################################## 100.0%[LF]
== Contents of files in the log/ dir after test 1148
=== Start of file check-expected
[CR]######################################################################## 100.0%[LF]
=== End of file check-expected
=== Start of file check-generated
#=#=# [CR][CR]######################################################################## 100.0%[LF]
=== End of file check-generated
=== Start of file curl.log
../src/curl --output log/curl1148.out --include --trace-ascii log/trace1148 --trace-time http://127.0.0.1:8990/1148 -# --stderr log/stderrlog1148 >log/stdout1148 2>log/stderr1148
=== End of file curl.log
=== Start of file curl1148.out
HTTP/1.1 200 OK
Date: Thu, 09 Nov 2010 14:49:00 GMT
Server: test-server/fake
Last-Modified: Tue, 13 Jun 2000 12:10:00 GMT
ETag: "21025-dc7-39462498"
Accept-Ranges: bytes
Content-Length: 60
Connection: close
Content-Type: text/html
Funny-head: yesyes
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
=== End of file curl1148.out
=== Start of file curlverout.log
curl 7.59.0 () libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.11
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
=== End of file curlverout.log
=== Start of file http_server.log
20:12:52.617896 Running HTTP IPv4 version on port 8990
20:12:52.673896 Wrote pid 1956 to .http_server.pid
20:12:53.658851 ====> Client connect
20:12:53.699165 accept_connection 3 returned 4
20:12:53.741462 accept_connection 3 returned 0
20:12:53.782417 Read 92 bytes
20:12:53.824683 Process 92 bytes request
20:12:53.866981 Got request: GET /verifiedserver HTTP/1.1
20:12:53.909187 Are-we-friendly question received
20:12:53.952186 Wrote request (92 bytes) input to log/server.input
20:12:54.021186 Identifying ourselves as friends
20:12:54.080817 Response sent (55 bytes) and written to log/server.response
20:12:54.165382 special request received, no persistency
20:12:54.215278 ====> Client disconnect 0
20:12:55.358314 ====> Client connect
20:12:55.399360 accept_connection 3 returned 4
20:12:55.441657 accept_connection 3 returned 0
20:12:55.483894 Read 82 bytes
20:12:55.526130 Process 82 bytes request
20:12:55.568458 Got request: GET /1148 HTTP/1.1
20:12:55.610664 Requested test number 1148 part 0
20:12:55.653480 - request found to be complete
20:12:55.695899 Wrote request (82 bytes) input to log/server.input
20:12:55.821387 Send response test1148 section 
20:12:55.879646 Response sent (311 bytes) and written to log/server.response
20:12:55.930915 => persistant connection request ended, awaits new request
20:12:55.982124 Connection closed by client
20:12:56.033363 ====> Client disconnect 0
=== End of file http_server.log
=== Start of file http_verify.log

Trying 127.0.0.1...
TCP_NODELAY set
Connected to 127.0.0.1 (127.0.0.1) port 8990 (#0)
GET /verifiedserver HTTP/1.1
Host: 127.0.0.1:8990
User-Agent: curl/7.59.0
Accept: /

< HTTP/1.1 200 OK
< Content-Length: 16
<
{ [16 bytes data]

Connection #0 to host 127.0.0.1 left intact
=== End of file http_verify.log
=== Start of file http_verify.out
WE ROOLZ: 1956
=== End of file http_verify.out
=== Start of file server.input
GET /1148 HTTP/1.1
Host: 127.0.0.1:8990
User-Agent: curl/7.59.0
Accept: /
=== End of file server.input
=== Start of file server.response
HTTP/1.1 200 OK
Content-Length: 16
WE ROOLZ: 1956
HTTP/1.1 200 OK
Date: Thu, 09 Nov 2010 14:49:00 GMT
Server: test-server/fake
Last-Modified: Tue, 13 Jun 2000 12:10:00 GMT
ETag: "21025-dc7-39462498"
Accept-Ranges: bytes
Content-Length: 60
Connection: close
Content-Type: text/html
Funny-head: yesyes
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
=== End of file server.response
=== Start of file stderrlog1148
#=#=#
######################################################################## 100.0%
=== End of file stderrlog1148
=== Start of file trace1148
20:12:55.355811 == Info: Trying 127.0.0.1...
20:12:55.356971 == Info: TCP_NODELAY set
20:12:55.357764 == Info: Connected to 127.0.0.1 (127.0.0.1) port 8990 (#0)
20:12:55.358772 => Send header, 82 bytes (0x52)
0000: GET /1148 HTTP/1.1
0014: Host: 127.0.0.1:8990
002a: User-Agent: curl/7.59.0
0043: Accept: /
0050:
20:12:55.848640 <= Recv header, 16 bytes (0x10)
0000: HTTP/1.1 200 OK.
20:12:55.849677 <= Recv header, 36 bytes (0x24)
0000: Date: Thu, 09 Nov 2010 14:49:00 GMT.
20:12:55.849830 <= Recv header, 25 bytes (0x19)
0000: Server: test-server/fake.
20:12:55.849952 <= Recv header, 45 bytes (0x2d)
0000: Last-Modified: Tue, 13 Jun 2000 12:10:00 GMT.
20:12:55.850166 <= Recv header, 27 bytes (0x1b)
0000: ETag: "21025-dc7-39462498".
20:12:55.850288 <= Recv header, 21 bytes (0x15)
0000: Accept-Ranges: bytes.
20:12:55.850410 <= Recv header, 19 bytes (0x13)
0000: Content-Length: 60.
20:12:55.850562 <= Recv header, 18 bytes (0x12)
0000: Connection: close.
20:12:55.850654 <= Recv header, 24 bytes (0x18)
0000: Content-Type: text/html.
20:12:55.850776 <= Recv header, 19 bytes (0x13)
0000: Funny-head: yesyes.
20:12:55.850898 <= Recv header, 1 bytes (0x1)
0000: .
20:12:55.850959 <= Recv data, 60 bytes (0x3c)
0000: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.
20:12:55.851325 == Info: Closing connection 0
=== End of file trace1148

Test suite total running time breakdown per task...

Spent 0002.665 seconds starting and verifying test harness servers.
Spent 0000.017 seconds reading definitions and doing test preparations.
Spent 0000.802 seconds actually running test tools.
Spent 0000.101 seconds awaiting server logs lock removal.
Spent 0000.009 seconds verifying test results.
Spent 0003.594 seconds doing all of the above.

Test server starting and verification time per test (top 25)...

-time- test

02.665 1148

Test definition reading and preparation time per test (top 10)...

-time- test

00.017 1148

Test tool execution time per test (top 25)...

-time- test

00.802 1148

Test server logs lock removal time per test (top 15)...

-time- test

00.101 1148

Test results verification time per test (top 10)...

-time- test

00.009 1148

Total time per test (top 50)...

-time- test

03.594 1148

TESTDONE: 0 tests out of 1 reported OK: 0%
TESTFAIL: These test cases failed: 1148
TESTDONE: 1 tests were considered during 4 seconds.
}}}

The Only difference I could find is addition of some extra spaces in the log.
{{{
test 1148...[progress-bar]

1148: output (log/stderrlog1148) FAILED:
--- log/check-expected	2018-03-30 14:42:54.913781000 +0000
+++ log/check-generated	2018-03-30 14:42:54.881781000 +0000
@@ -1 +1 @@
-[CR]######################################################################## 100.0%[LF]
+#=#=# [CR][CR]######################################################################## 100.0%[LF]
}}}

Can anyone Please help in resolving it?
Or is the test successful?

**Comment by bagder** [comment]
Thanks @Oumph, I've merged a fix like that now!

@cerium001: it looks like your problem might be a different one but it would still be worth for you to check how it runs for you with commit 28faaacee28 included. Build from git or try tomorrow's [daily snapshot](https://curl.haxx.se/snapshots/). If there's a problem still, please file a new issue.
