### ISSUE TITLE
What's the point of rejecting system Keychain CA certificates?

### ISSUE THREAD

**Issue by eabalea** [curl/curl#2543]
Allowing the user to add trusted CAs with the cacert option or the default bundle is fine, but why is a chain anchored to a Keychain-trusted CA rejected?

https://github.com/curl/curl/blob/97f63f512d19835a573f6f7635a5164a289cfe9c/lib/vtls/darwinssl.c#L2180

With this, a Keychain-only CA is not valid, with a trust_eval set to kSecTrustResultRecoverableTrustFailure.
Change the "true" to "false", and the same chain is accepted (or rejected the user changes the trust settings in Keychain).

**Comment by nickzman** [comment]
What are you trying, exactly? That line is only ever called if libcurl is configured to load an OpenSSL-style certificate file or bundle; it is not called when the Keychain is in use, and the Keychain is used if no certificate file or bundle was set at compile time or as an option.

**Comment by eabalea** [comment]
On a High Sierra machine, downloaded the curl-7.59.0 tgz file, exploded it, then compiled it starting with
```
./configure --prefix=/tmp/curlroot2 --disable-silent-rules --enable-ipv6 --without-brotli --without-cyassl --without-gnutls --without-gssapi --without-libmetalink --without-librtmp --without-libssh2 --without-nghttp2 --without-nss --without-polarssl --without-spnego --without-ssl --with-darwinssl --disable-ares --enable-ldap --enable-ldaps --with-libidn2=/opt/local --with-zlib=/opt/local ac_cv_prog_AWK=/usr/bin/awk --enable-debug
```
and it seems the CURL_CA_BUNDLE is loaded anyway. I have no .curlrc in my homedir, and the command used is a simple "curl -v https://somewebsite".

**Comment by nickzman** [comment]
That's because High Sierra shipped with a CA bundle in /etc/ssl, something that has not happened in the last few macOS releases. The configure script sees it there, and uses it as the master certificate bundle, overriding the Keychain in the curl/libcurl that is built.

To fix this, run configure with --without-ca-path specified as an argument, then build it again. I think we need to change the Autoconf script so it doesn't go looking for a CA path if either NSS, Schannel, or ST is used as a back-end. I can see how that can cause confusion.
