### ISSUE TITLE
--with-ssl=/nonexistent/path ignores specified path and builds against another SSL implementation

### ISSUE THREAD

**Issue by p** [curl/curl#2580]
### I did this

Attempted to build libcurl against **libre**ssl by specifying a path thusly:

`./configure --with-ssl=/path/to/libressl ...`

However, I neglected to build libressl prior to doing this hence /path/to/libressl didn't exist.

### I expected the following

An error telling me I gave a nonexistent path to --with-ssl.

Ideally if the directory exists but doesn't contain openssl headers/libraries this should also be an error but maybe this is asking too much.

### Actual result

libcurl built itself against system **open**ssl which is an entirely different ssl implementation without any errors.

### Further background

There are two mentions of `/path/to/libressl` in configure output:

<pre>
configure: PKG_CONFIG_LIBDIR will be set to "/path/to/libressl/lib/pkgconfig"
configure: Added /path/to/libressl/lib to CURL_LIBRARY_PATH
</pre>

So, my specified path is simply added (prepended I imagine) to search directories. 

### curl/libcurl version

7.60.0 from source/release tarball

### operating system

Ubuntu Trusty VM

### Note

This issue may well affect other --with-* options, I added a generic guard for directory existence to my build process now.

**Comment by bagder** [comment]
I'm pretty sure this happens because the test for the ssl library still works because it finds a system one installed and uses that (in one of the default paths). So while a check for the dir existing would catch your specific case if you truly point to a missing directory, it would still work like this if you point to an empty directory...

**Comment by PerMalmberg** [comment]
@p You're not alone - we had a spelling error in the path; we ended up building against a very dated openssl. It took us a while to figure out where it went wrong.

**Comment by bagder** [comment]
I can't think of any easy ways to detect this. The linker have a default path that might make it find another library if the given path isn't working. To detect that, we have to add some custom logic that verifies the given path to make sure it actually contains a (working) openssl installation and that does feel very error-prone.

Or do you have any ideas on how this process could be improved?

**Comment by PerMalmberg** [comment]
Well, do we need to know it is a working installation in the specified directory? Wouldn't it be enough that we find at least the "entry header file" in the directory? If the user points to a broken installation, that'll likely become obvious at a later stage when it doesn't compile or otherwise breaks.

Other than that, I can only think of of documenting the possible pitfall.

**Comment by bagder** [comment]
I like that. Simple and easy. Basically logic like this:

```
if ! test -f "$givenpath/include/openssl/ssl.h"; then
   echo "probably the wrong path, run away"
fi
```

I'll put together a PR for it...

**Comment by PerMalmberg** [comment]
That'll work splendidly, @bagder

**Comment by p** [comment]
Seems reasonable, thanks!

**Comment by bagder** [comment]
Thanks both of you!
