### ISSUE TITLE
time_total is wrong

### ISSUE THREAD

**Issue by Kamarey** [curl/curl#2670]
### I did this
curl -w "@D:\curlFormat.txt" -s --request POST -H "Content-Type: application/json" --url http://myelasticsearchdomain/something/_search --data "@D:\curlInput.txt" -o NUL

and got this:
```
    time_namelookup:  0.000001
       time_connect:  0.141000
    time_appconnect:  0.000000
   time_pretransfer:  0.141000
      time_redirect:  0.000000
 time_starttransfer:  0.282000
                    ----------
         time_total:  1.844000

```
### I expected the following
I expect the time_total will be total of all above timings. Or I missed some of them?

### curl/libcurl version
curl 7.60.0 (i386-pc-win32) libcurl/7.60.0 OpenSSL/1.1.0h (WinSSL) zlib/1.2.11 brotli/1.0.4 WinIDN libssh2/1.8.0 nghttp2/1.32.0
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz brotli TLS-SRP HTTP2 HTTPS-proxy MultiSSL

### operating system
Windows 10 64 bit professional

**Comment by bagder** [comment]
> I expect the time_total will be total of all above timings

No it isn't. `time_total` is the total time a a transfer took, the other timers are for individual parts, many of them overlapping but summed up they will not be `time_total` since those sub-parts are not covering the whole transfer. See [documentation](https://curl.haxx.se/libcurl/c/curl_easy_getinfo.html#TIMES).
