### ISSUE TITLE
getaddrinfo() thread failed on HPUX

### ISSUE THREAD

**Issue by Eason-Yu** [curl/curl#2697]
I build curl-7.60.0 on HPUX by running "configure && make && sudo make install", then run the following command:
bash-3.1# /usr/local/bin/curl -x dcmfa02-w2k16d.mfa.cdc:8080 --connect-timeout 5 URL -v 2>&1
* getaddrinfo() thread failed to start

* Couldn't resolve proxy 'dcmfa02-w2k16d.mfa.cdc'
* Closing connection 0
curl: (5) getaddrinfo() thread failed to start`

get a error "getaddrinfo() thread failed to start", then check the lib dependency of curl, pthread lib is not there. 

Btw, using LD_PRELOAD specify with pthread lib, then it works well.  details as follows:
bash-3.1# LD_PRELOAD=/usr/lib/libpthread.1 /usr/local/bin/curl -x dcmfa02-w2k16d.mfa.cdc:8080 --connect-timeout 5 URL -v 2>&1
*   Trying 10.100.50.50...
* TCP_NODELAY set
* Connected to dcmfa02-w2k16d.mfa.cdc (10.100.50.50) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to xxx
> CONNECT xxx HTTP/1.1
> Host: xxx
> User-Agent: curl/7.60.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
<

**Comment by bagder** [comment]
First, I note that the last curl release is provided as binary builds by others so clearly it builds and works for some: https://curl.haxx.se/download.html#HPUX

To me this sounds like something in your run-time environment makes it not find and use the pthread library and since configure both deemed it present and made use of it, this problem will prevent curl from working correctly.

**Comment by Eason-Yu** [comment]
But I use the same commands to build it on RHEL, AIX and Solaris, curl can work well. Just curious why it just can not work on HPUX, seems the building for curl on HPUX needs a different configuration option (e.g. ./configure LIBS="-lpthread"), if so, i think at least curl needs give a doc for it.

**Comment by bagder** [comment]
configure **already checks** for your pthreads library and if it fails to find it, it won't enable the threaded resolver in the first place.

This makes me believe configure found it for you and made use of it correctly (configure's output and even the `config.log` can confirm that), but then when you use built output, something in your environment makes it not work run-time.

**Comment by Eason-Yu** [comment]
yes. configure check pthread and find it. But library pthread is not linked into curl on HPUX. Do you try to  build the latest version of curl on HPUX? If you did, is library pthread included into the library dependencies of curl?

**Comment by bagder** [comment]
> yes. configure check pthread and find it. But library pthread is not linked into curl on HPUX.

Can you please show how this happens by pasting/including the relevant bits from the output or `config.log` file?

> Do you try to build the latest version of curl on HPUX?

No I don't. I'm still willing to help you nail down this problem and if necessary adjust things to make them work better. To do that, I must first understand what fails with the existing configure logic.

**Comment by Eason-Yu** [comment]
I run "configure; make; make install" to build curl, no error occurs except for the following warning during make:
libtool: warning: this platform does not like uninstalled shared libraries
libtool: warning: 'curl' will be relinked during installation

then i check the lib dependencies of curl, pthread is not there. then i gdb debug curl, and found pthread_create always fail, and return errno 251 (function is not available). 

Note: Redhat, Solaris and AIX does not have this issue, and pthread is included into the lib dependencies of the curl on those platforms. just curious, i run the same command, why lib pthread is no t included into the lib dependencies of curl on HPUX.

**Comment by bagder** [comment]
So I ask again:

Can you please show how this happens by pasting/including the relevant bits from the output or config.log file?

**Comment by Eason-Yu** [comment]
[config.log](https://github.com/curl/curl/files/2152322/config.log)

**Comment by bagder** [comment]
> if test "$USE_THREADS_POSIX" != "1" <====== Should it be "$USE_THREADS_POSIX" = 1?

No. That check is there to see if it *isn't* enabled yet and if so, do some additional checks. [This code](https://github.com/curl/curl/blob/9679790b23eb888933af88555a05bedc398d6026/configure.ac#L3785)

But what's curious about your config.log is that when configure checks if it can find and use `pthread_create` without any additional libraries provided, it succeeds! (line 60037 of your attached log file). Since it actually works to build a program using that function without any additional libs it is of course deemed unnecessary to add one. What puzzles me is of course why this works (and it also doesn't cause any link errors when you then go on to build curl which then uses the pthread functions)... and you only get the problems at run-time. Can you understand why this is so?

**Comment by Eason-Yu** [comment]
I'm not sure. But I suspect the checking for pthread_create. I have checked this issue for two days, and i'm not familiar with the building. If you have a HPUX, i think it should be able to be reproduced easily.

**Comment by bagder** [comment]
> line 60037 just tell the conftest is built successfully, but it does not tell if pthread_create is available or not

That's not how linking generally works. The linker *should* check that the functions are available! This is clearly the reason why the pthread check fails on this system...

I don't have an HPUX system and I never had. I logged into one though, once. Like 17 years ago or so...

**Comment by Eason-Yu** [comment]
Google a lot. Found the reason pthread_create is failing with error 251 is the libc library provides stubs for the pthread functions on HPUX.

Do you think you need to deal with this exception on HPUX?

**Comment by bagder** [comment]
> can you provide me a patch for this issue?

Can you try this patch and see if this works for you? It's a bit "crude" as it checks fox hpux specifically, but I really can't figure out a really nice way to do this.

You need to apply the patch and run `./buildconf`, then you can run configure again.

~~~diff
--- a/configure.ac
+++ b/configure.ac
@@ -3779,10 +3779,20 @@ if test "$want_pthreads" != "no"; then
       save_CFLAGS="$CFLAGS"
 
       dnl first check for function without lib
       AC_CHECK_FUNC(pthread_create, [USE_THREADS_POSIX=1] )
 
+      dnl on HPUX, life is more complicated...
+      case $host in
+      *-hp-hpux*)
+         dnl it doesn't actually work without -lpthread
+         USE_THREADS_POSIX=""
+         ;;
+      *)
+         ;;
+      esac
+
       dnl if it wasn't found without lib, search for it in pthread lib
       if test "$USE_THREADS_POSIX" != "1"
       then
         CFLAGS="$CFLAGS -pthread"
         AC_CHECK_LIB(pthread, pthread_create,

**Comment by Eason-Yu** [comment]
It's really a bit "crude". how about using AC_TRY_RUN?

**Comment by bagder** [comment]
AC_TRY_RUN must be avoided as far as possible since it breaks cross-compilation. Since I rather have this "crudeness" limited to HPUX-only such a AC_TRY_RUN could be restricted to HPUX but then it seems like maybe not necessary? Do you think there's a risk different HPUX systems work differently in regards to the pthreads library?

**Comment by Eason-Yu** [comment]
I'm not sure. I would like to have a elegant way to fix it, but i'm not familiar with autoconf. So ask your help here.

**Comment by bagder** [comment]
And I have no HPUX system to test on so working on an "elegant fix" is not up to me. I can't think of a proper way to fix this detection while at the same time avoiding AC_TRY_RUN, but I don't want to "hurt" all other users because of this HPUX weirdness.

An alternative would be to check if cross-compilation is being done, and only do the extra AC_TRY_RUN check if not.

**Comment by bagder** [comment]
So @Eason-Yu, does the "crude" approach work at all? If so, it might be a better idea to land that than doing nothing?

**Comment by michael-o** [comment]
I might jump into this next months. I have been using HP-UX for the last 10 years, but haven't compiled curl on HP-UX for quite some time.

**Comment by Eason-Yu** [comment]
@bagder Sorry for the delay. It works. Thanks a lot.
