### ISSUE TITLE
EGYPT proxy filter and SOLUTION!!!

### ISSUE THREAD

**Issue by Zibri** [curl/curl#2821]
Hello!
I am writing you because in EGYPT proxies with CONNECT are banned/filtered.
The funny thing I just found out is that the filter expect CONNECT host port HTTP1.1... to be on the FIRST line!
So to evade the filter what is needed is just a newline "\n" before the CONNECT string.
I tested it by modifying (LIB)CURL source adding the newline and it works!

I think I am the first one to notice this.
Please give me some credit if you use it.

Zibri
zibri AT zibri DOT org

it would be nice to just have an option in curl for everyone to use...

the mod is this:
in lib/http_proxy.c

instead of

```
        Curl_add_bufferf(req_buffer,
                           "CONNECT %s HTTP/%s\r\n"

```
I have put:

```
        Curl_add_bufferf(req_buffer,
                           "\nCONNECT %s HTTP/%s\r\n"

```
I don't know what other mods are allowed without breaking the protocol... but \n works.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

I'm personally not convinced this is a generic enough feature for people to warrant inclusion in curl though, but I would listen to what others think as well. Also note that if you "advertise" this "circumvention" technique wide enough, chances are probably high that the "hole" will be fixed sooner rather than later.
