### ISSUE TITLE
TCP connection closed when response code >= 300 but with header "Connetion: keep-alive"

### ISSUE THREAD

**Issue by singku** [curl/curl#2846]
### I did this
Using HTTP/1.1 With TSLV1.2 communicate with server.
Sometimes server respond with 
```
100 Continue 
400 Bad Request
```
but the header has 
`Connection: keep-alive `
included.

Based on this:
https://github.com/curl/curl/blob/6f5ef24f068a86d0f61ce39f674462128c1743d1/lib/http.c#L3293-L3329

Then tcp connection will be closed.

### I expected the following
With `keep-alive` identified. the Tcp stream shouldn't be terminated. 

### curl/libcurl version

[curl -V output]

**Comment by bagder** [comment]
You're not explaining exactly what you tell curl to do, leaving us to guess about the missing pieces.

The thing is that you're sending data to a HTTP server and you (most likely) get a >= 300 HTTP response back *before* libcurl has sent all the data it was instructed to send. So, in order to keep the connection alive it would had to keep sending the rest of the data - which would be a bandwidth and time waste. So it opts to instead close the connection.

You can tell libcurl to not make this "optimization" with [CURLOPT_KEEP_SENDING_ON_ERROR](https://curl.haxx.se/libcurl/c/CURLOPT_KEEP_SENDING_ON_ERROR.html).

**Comment by bagder** [comment]
> Are you saying Http headers length has been set so libcurl has to send the rest of the data to keep it alive?

You haven't shown us those details, but that'd be my guess yes.

> that "optimization" maybe not an optimization

... which is a reason why we provide a way for the application to ask libcurl to not do it.
