### ISSUE TITLE
Curl Error (56) recv error when using mbedtls ssl backend on some urls

### ISSUE THREAD

**Issue by jshanab** [curl/curl#2899]
### I did this
Connected to many axis security cameras in https mode and some return curl error (56) : recv error immediatly after getting a complete response. Similar version of curl using openssl back end do not produce the error.

### I expected the following
No error code to stop application.
### curl/libcurl version
7.48, 7.61
### mbedtls 2.2.1 and 2.12.0

~~~
[curl -V output]
C:\Program Files\exacqVision\Server>curl -v -uroot:pass --insecure --digest https://172.19.234.58/axis-cgi/disks/list.cgi?diskid=all
*   Trying 172.19.234.58...
* Connected to 172.19.234.58 (172.19.234.58) port 443 (#0)
* mbedTLS: Connecting to 172.19.234.58:443
* mbedTLS: Set min SSL version to TLS 1.0
* mbedTLS: Handshake complete, cipher is TLS-RSA-WITH-AES-256-CBC-SHA
* Dumping cert info:
* cert. version     : 3
* serial number     : 5B:76:C7:25
* issuer name       : C=us, ST=in, L=fishers, O=exacq, OU=ipcam, CN=172.19.234.58
* subject name      : C=us, ST=in, L=fishers, O=exacq, OU=ipcam, CN=172.19.234.58
* issued  on        : 2018-08-17 13:01:24
* expires on        : 2019-08-17 04:00:00
* signed using      : RSA with SHA-256
* RSA key size      : 2048 bits

* SSL connected
* Server auth using Digest with user 'root'
> GET /axis-cgi/disks/list.cgi?diskid=all HTTP/1.1
> Host: 172.19.234.58
> User-Agent: curl/7.48.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Date: Mon, 20 Aug 2018 14:41:10 GMT
< Server: Apache/2.4.25 (Unix) OpenSSL/1.0.2k
< WWW-Authenticate: Digest realm="AXIS_ACCC8E6882E1", nonce="CSx95t5zBQA=feda953692070ff1fd8247548ded99a94878c6d7", algorithm=MD5, qop="auth"
< Content-Length: 381
< Content-Type: text/html; charset=iso-8859-1
<
* Ignoring the response-body
* Connection #0 to host 172.19.234.58 left intact
* Issue another request to this URL: 'https://172.19.234.58/axis-cgi/disks/list.cgi?diskid=all'
* Found bundle for host 172.19.234.58: 0x44bb30 [can pipeline]
* Re-using existing connection! (#0) with host 172.19.234.58
* Connected to 172.19.234.58 (172.19.234.58) port 443 (#0)
* WARNING: Using weak random seed
* Server auth using Digest with user 'root'
> GET /axis-cgi/disks/list.cgi?diskid=all HTTP/1.1
> Host: 172.19.234.58
> Authorization: Digest username="root", realm="AXIS_ACCC8E6882E1", nonce="CSx95t5zBQA=feda953692070ff1fd8247548ded99a94878c6d7", uri="/axis-cgi/disks/list.cgi?diskid=all", cnonce="YzFhYzUwNjFmMzVmNGQxZGRmZmUxOTU3MmZiOWE5NGY=", nc=00000001, qop=auth,
 response="52ec705ae91950d4f660cd4e140b6c43", algorithm="MD5"
> User-Agent: curl/7.48.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: text/xml
<
<?xml version="1.0"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.axis.com/vapix/http_cgi/disk/list1.xsd">
<disks numberofdisks="2" >  <disk diskid="SD_DISK" name="" totalsize="31154688" freesize="31058560" cleanuplevel="0" cleanupmaxage="7" cleanuppolicy="fifo" locked="no" full="no" readonly="no" status="OK" filesystem="vfat" group="S0" requiredfilesyste
m="none" encryptionenabled="false" diskencrypted="false"/>
  <disk diskid="NetworkShare" name="" totalsize="0" freesize="0" cleanuplevel="90" cleanupmaxage="7" cleanuppolicy="fifo" locked="no" full="no" readonly="no" status="disconnected" filesystem="cifs" group="S1" requiredfilesystem="none" encryptionenabl
ed="false" diskencrypted="false"/>
</disks> </root>
* Closing connection 0
curl: (56) Failure when receiving data from the peer
~~~

### operating system
Windows 7 (64), Windows 10

**Comment by jshanab** [comment]
Patching mbed_recv to return 0 just like the openssl ossl_recv  mentioned in 
https://sourceforge.net/p/curl/bugs/1256/
https://sourceforge.net/p/curl/bugs/1249/
Resulted in identical behaviour as the openssl.

Note: I built curl 7.61 with mbedtls 2.12.0 and the following mbed_recv function:

static ssize_t mbed_recv(struct connectdata *conn, int num,
                         char *buf, size_t buffersize,
                         CURLcode *curlcode)
{
  struct ssl_connect_data *connssl = &conn->ssl[num];
  int ret = -1;
  ssize_t len = -1;

  memset(buf, 0, buffersize);
  ret = mbedtls_ssl_read(&BACKEND->ssl, (unsigned char *)buf, buffersize);
  if(ret <= 0) {
    if(ret == MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY)
      return 0;

    **if(ret == 0)
        return 0;**

    *curlcode = (ret == MBEDTLS_ERR_SSL_WANT_READ) ?
      CURLE_AGAIN : CURLE_RECV_ERROR;
    return -1;
  }
  len = ret;
  return len;
}

**Comment by jay** [comment]
[mbedtls_ssl_read](https://tls.mbed.org/api/ssl_8h.html#aa2c29eeb1deaf5ad9f01a7515006ede5) returns `0 if the read end of the underlying transport was closed,` but isn't specific if it was closed unclean without the close notify. If that's the case then OpenSSL IIRC we allow it but WinSSL we were stricter due to prevention of truncation attack. mbedTLS I don't know though. Can you confirm by checking wireshark to see if the server is returning a close notify alert for those sessions where you receive error 56?

/cc @sbutcher-arm

**Comment by bagder** [comment]
It seems their own example code uses 0 to signal end of file:

https://github.com/ARMmbed/mbedtls/blob/7d728bd70e6a8d129ee07813da1538de1bf95cb2/programs/ssl/ssl_client1.c#L256-L283

I presume the `MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY` check is there for the early close?

**Comment by jshanab** [comment]
[Axis_error_56.zip](https://github.com/curl/curl/files/2320734/Axis_error_56.zip)

Wireshark of an axis camera producing the error 56 with mbedtls backend and not with openssl backend.

Axis claims nothing wrong with camera firmware offering curl with openssl as proof. They asked if we could supply evidence to contrary. I found previous info on openssl having this issue and how it was solved. (Sorry I was out of touch for Debug Week, let me know if there is any other info needed)

**Comment by jshanab** [comment]
I do not see a "close notify alert", would it show in wireshark like the "client hello"?

**Comment by jay** [comment]
> Wireshark of an axis camera producing the error 56 with mbedtls backend and not with openssl backend.

> I do not see a "close notify alert", would it show in wireshark like the "client hello"?

I can confirm mbedtls is not sending it and also your capture shows no alert (it would show as encrypted alerts unless ssl logfile decryption was enabled in wireshark).

try this

~~~diff
diff --git a/lib/vtls/mbedtls.c b/lib/vtls/mbedtls.c
index d7759dc..82e1eed 100644
--- a/lib/vtls/mbedtls.c
+++ b/lib/vtls/mbedtls.c
@@ -768,6 +768,7 @@ static void Curl_mbedtls_close_all(struct Curl_easy *data)
 static void Curl_mbedtls_close(struct connectdata *conn, int sockindex)
 {
   struct ssl_connect_data *connssl = &conn->ssl[sockindex];
+  mbedtls_ssl_close_notify(&BACKEND->ssl);
   mbedtls_pk_free(&BACKEND->pk);
   mbedtls_x509_crt_free(&BACKEND->clicert);
   mbedtls_x509_crt_free(&BACKEND->cacert);
~~~

**Comment by jshanab** [comment]
I reverted the test for 0 and built with this patch. I still get the same error 56 on the command line but the wireshark is now different. In both cases it does look to me that the device is closing the socket and curl is trying to use it one more time.

[axis_error_56_II.zip](https://github.com/curl/curl/files/2321016/axis_error_56_II.zip)

**Comment by jay** [comment]
Oops I misread that in the first dump. The server initiates closing the connection not the client (HTTP 1.0, "assume close after body", no content length) without sending a close notify. The working axis server responses I would expect include the length of the body and wait for the client to close the connection first or they send a close notify before closing.

It would appear by treating 0 as closed we would not be able to detect truncation attacks in this scenario. I [asked anyway](https://forums.mbed.com/t/mbedtls-ssl-read-returns-0-can-you-explain-how-its-different-from-close-notify/3449), we'll see.

**Comment by jay** [comment]
Their reply

> 0 is returned when the read cb function returns EOF. It is not necessarily because the remote peer gracefully shut down the connection, and is not returned when the Close Notify warning has been received.

Based on that I don't think there should be a change. Truncation attacks are not much of an issue when you know the length you are supposed to receive but here we have an unknown length / no terminator so an attack could work in a case like this if we allowed EOF. OTOH it is allowed probably due to legacy with OpenSSL backend IIRC. My feeling is why go backwards though.

**Comment by bagder** [comment]
@jay if I understand you correctly, you're then suggesting that the server in @jshanab's original report was not closing down the connection correctly and thus the error was warranted there too?

(It should be noted it returned a HTTP/**1.0** response with no proper end-of-response signal other than closed connection.)

**Comment by jay** [comment]
It's closing FIN but doesn't send a close notify beforehand. It's the server's responsibility so yes I think it's warranted. I don't know how practical I'm being real-world. RFC [says](https://tools.ietf.org/html/rfc5246#section-7.2.1):

~~~
   Unless some other fatal alert has been transmitted, each party is
   required to send a close_notify alert before closing the write side
   of the connection. 
~~~

My interpretation of that is if the server is going to close the connection then it should send the close notify beforehand.

I think we have only 1 other report and it was for WinSSL. I can't find it. Also since the bulk of curl users use OpenSSL it's hard to say. Truncation attacks it seems to me are only significant in scenarios like this without a known termination point or perhaps [truncating headers](https://bugs.chromium.org/p/chromium/issues/detail?id=244260) which [doesn't look like](https://github.com/curl/curl/blob/curl-7_56_1/lib/http.c#L2966) an issue.

**Comment by bagder** [comment]
While it seems like an attack that's really hard to exploit due to the timing required on the cut-off and that it has to cut off the exact headers exactly at the exact spot, it is indeed a reason to insist on the **close notify**.

**Comment by bagder** [comment]
(too early pressed return)

Although as @jay notes, libcurl doesn't really consider a header until it has been terminated so I can't see right now that we would handle a half cookie for example...

**Comment by hanno-arm** [comment]
Hi,

I'm a member of the Mbed TLS team and would like to comment on this issue. First, however, my apologies that we didn't get back to you any earlier.

I agree with @jay that the server doesn't seem to send a `CloseNotify` alert as part of closing the connection, which would be non-conforming behavior, and curl rightfully returns an error in this case.

Still, the discussion has made apparent that the documentation of the return value `MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY`, and especially its relation to the return value `0`, is insufficiently documented in Mbed TLS, and I have raised issue https://github.com/ARMmbed/mbedtls/issues/2173 to track this.

Apart from the server's behavior, the curl client should send a `CloseNotify` alert on orderly shutdown, too, as @jay suggested. In that regard, however, one should be careful to call `mbedtls_ssl_close_notify()` only if the SSL context and connection are known to be intact; for example, it shouldn't be called after a fatal alert has been received, or an internal error condition was encountered. To this end, it might be worth considering the addition of a connection state parameter to the `BACKEND` structure from which one can infer if it's safe to call `mbedtls_ssl_close_notify()`. Future versions of Mbed TLS might include that logic, so that it's always safe to call `mbedtls_ssl_close_notify()`, but as of 2.13.1, this is not implemented.

Kind regards,
Hanno, Mbed TLS team member

**Comment by jay** [comment]
@hanno-arm Though mbedtls_ssl_close_notify does not include the logic is there any api call that does, like can we do `if(mbedtls_tls_is_still_fine(&BACKEND->ssl)) mbedtls_ssl_close_notify(&BACKEND->ssl)`

**Comment by hanno-arm** [comment]
Hi @jay,

no, currently Mbed TLS does not offer any such API. It is the user's responsibility to using the context after a fatal error occurred. It's debatable whether that should be changed, introducing blocking logic to limit the scope of API misuse at the cost of larger code-size, but as of now, it's not present in upstream Mbed TLS. (I've been working on a potential new messaging layer for Mbed TLS which does have this logic, see https://github.com/hanno-arm/mbedtls/blob/e421be6b2ba84e2ea9b1e5b4173986426d6c415f/include/mbedtls/mps/mps.h#L168, but it's still work in progress and I don't know when it will be available upstream).

Best,
Hanno

**Comment by bagder** [comment]
This is deemed to be a server issue that we should not just ignore in curl. The server closes the TLS connection badly and that is what curl reacts on. We therefor don't consider this a curl bug, it's a server bug.

**Comment by jshanab** [comment]
Right it is an AXIS server issue, Is it still a bug if using MBEDTLS and
not a bug if using OpenSSL ?

**Comment by jay** [comment]
Ideally, treating an https transfer without at least one acceptable termination point (content length, close_notify, chunked) as successful shouldn't be allowed with any backend but it's possible it's currently allowed with some. The OpenSSL backend would be the most likely candidate because some of the libcurl code for OpenSSL is legacy and built to work around issues from 10+ years ago.

If we're currently allowing it with OpenSSL I think we should stop but really I'd try to be cautious about how we went about doing it, maybe let it marinate in the repo for several months so that only when curl is built as a -DEV version does it apply... and see if anyone is affected. I think it's really hard to anticipate how much negative effect there could be from a change like that.

**Comment by jshanab** [comment]
When we switched our curl implementation form using OpenSSL to MBedTLS is when this inconsistency reared it's head.
