### ISSUE TITLE
Inconsistent behaviour with regards to TLS version handing between curl versions

### ISSUE THREAD

**Issue by tomato42** [curl/curl#2918]
The behaviour of curl options changed radically between versions – in earlier releases (and even now with the `--sslv3` option) using an option to specify exact protocol version meant "use this version and this version only" – something that is necessary to support broken implementations that are TLS version intolerant. In newest versions, the meaning of those options is, in practice, completely reversed  - they specify the _minimum_ version not the maximum version acceptable.

This breaks backwards compatibility. 

### I did this

I've used `curl --tlsv1.1`.

### I expected the following

The command should connect with TLS 1.1 or abort the connection if server advertises lower protocol version, same way it worked in 7.34.0

### curl/libcurl version

curl 7.60.0 (x86_64-redhat-linux-gnu) libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.7.5/openssl/zlib nghttp2/1.32.0
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink

### operating system
Fedora 29

### Additional information

The behaviour in 7.34.0 was also consistent with the behaviour of `-tls1_0`, `-tls1_1`, `-tls1_2` and (now) `-tls1_3` option in both OpenSSL s_client and s_server.

**Comment by bagder** [comment]
> The command should connect with TLS 1.1 or abort the connection if server advertises lower protocol version

Yes it should. I presume you know of a site/URL somewhere where curl connects to < TLS 1.1 when using `--tlsv1.1` ? If so, it'll help us if mention which so that we can try to reproduce!

**Comment by tomato42** [comment]
> Yes it should. I presume you know of a site/URL somewhere where curl connects to < TLS 1.1 when using --tlsv1.1 ?

you mean a TLS version intolerant server on the Internet? No, unfortunately I'm not aware of one at the moment

If you want, I can prepare a TLS server in pure python (2 or 3) that has this behaviour, will that help?

**Comment by jay** [comment]
It looks like it was a behavior change introduced in 6015cefb1 due to incompatibility with other SSL backends.

7.34 --tlsv1.1 says:
https://github.com/curl/curl/blob/0966b324d911423c81351fb12e9219f71cd63be8/docs/curl.1#L1538-L1541

7.61 --tlsv1.1 says:
https://github.com/curl/curl/blob/eb8138405a3f747f2c236464932f72e918946f68/docs/cmdline-opts/tlsv1.1.d#L6

You can use [--tls-max](https://curl.haxx.se/docs/manpage.html#--tls-max).

**Comment by jay** [comment]
This seems like a bug. Even if other backends won't do it we had it documented that way and OpenSSL is the predominant the backend.

**Comment by tomato42** [comment]
I know I can use `--tls-max` in 7.61, but it's not available in 7.34, so:
a). I can't use the same script with two different versions (not without querying the version number)
b). If the old script is deployed on system with new curl version it will have unexpected behaviour

**Comment by bagder** [comment]
It was a slight change in behavior, yes, and it was known already at the time. The reason is that there was no way for users to specify an accepted TLS version *range* (with OpenSSL). Like if you're OK with 1.1 and 1.2, or 1.2 and higher. Instead TLS 1.2-only using sites (that are starting to become common) would make curl fail when `--tlsv1.1` was used since the option implied *exactly* 1.1 and nothing else. And users who would've used `--tlsv1.2` would then not get 1.3 used - which was surprising to users and I don't think we did many users a service by having them work like that.

but @tomato42 says `--tlsv1.1` would accept a connection to a *lower* TLS version than 1.1 and that was never intended and neither have I seen it happen.

**Comment by bagder** [comment]
@tomato42 wrote:
> I can prepare an HTTP TLS server in pure python (2 or 3) that has this behaviour, will that help?

That would be great, thanks!

**Comment by tomato42** [comment]
> but @tomato42 says (if I understand things correctly) --tlsv1.1 would accept a connection to a lower TLS version than 1.1 and that was never intended and neither have I seen it happen.

@bagder no, it wouldn't, `--tlsv1.1` meant TLS 1.1 only, and it is necessary if a server does implement TLS 1.1 but is TLS 1.2 intolerant (just closes a connection on Client Hello advertising TLS 1.2)

**Comment by bagder** [comment]
That's not what you wrote above:

> The command should connect with TLS 1.1 or abort the connection if server advertises lower protocol version

With the current curl version, `--tlsv1.1` works like this because of what I explained above. It provides an additional option to avoid the broken server you're talking about. Yes it's a changed behavior. No I don't consider it a bug.

**Comment by tomato42** [comment]
In TLS the client cannot advertise the lowest version it supports, so the server can pick any version equal or _lower_ that the one that the client advertises in Client Hello. With --tlsv1.1 option, for the past 4 years or so, if the server did not support TLS 1.1 but did support TLS 1.0, the server would reply with TLS 1.0 Server Hello, but then the _client_ rejected it as a too low version.

How is that not what I wrote?

I still don't understand why the meaning of the options has to change, if there's need to specify a range, it can be achieved with --tls-min and --tls-max, there is no need to change the meaning of existing options

**Comment by tomato42** [comment]
TLS intolerant server setup:
```
pip install six
git clone https://github.com/tomato42/tlslite-ng.git -b tls-intolerance
cd tlslite-ng
git clone https://github.com/warner/python-ecdsa.git .python-ecdsa
ln -s .python-ecdsa/src/ecdsa/ ecdsa
```
To start the server:
```
PYTHONPATH=. python scripts/tls.py server -c tests/serverX509Cert.pem -k tests/serverX509Key.pem localhost:4433
```

then running `curl --tlsv1.0 --insecure https://localhost:4433/` will make a connection while `curl  --insecure https://localhost:4433/` will fail to connect (with 7.55.1)

**Comment by bagder** [comment]
> With --tlsv1.1 option, for the past 4 years or so, if the server did not support TLS 1.1 but did support TLS 1.0, the server would reply with TLS 1.0 Server Hello, but then the client rejected it as a too low version.

> How is that not what I wrote?

Because you then said:

> --tlsv1.1 meant TLS 1.1 only, and it is necessary if a server does implement TLS 1.1 but is TLS 1.2 intolerant

In the the first case I read it as: `--tlsv1.1` was used but a TLS 1.0 connection was agreed to. Ie it went down without permission.

The the latter case I read it as: `--tlsv1.1` was used, but a TLS 1.2 connection was attempt and failed. Ie it went "up" without you wanting it to.

I view these two as separate behaviors. The first one is clearly wrong and has always been wrong. The second case is what we changed.

**Comment by tomato42** [comment]
> `--tlsv1.1` was used, but a TLS 1.2 connection was attempt and failed. Ie it went "up" without you wanting it to.

I specifically wrote "meant", past tense

> The second case is what we changed.

and that change is breaking connections that previously worked

**Comment by bagder** [comment]
> that change is breaking connections that previously worked

... and there's an option you can use to fix that. You are after all connecting to a broken server.

**Comment by tomato42** [comment]
like I said, it's an option that is not available in old versions of curl

why it couldn't be implemented as a --tls-min option instead?

**Comment by bagder** [comment]
> that is not available in old versions of curl

Right, and therefore you can't for example ask for TLS 1.1 *or higher* with older curl versions - even though that's what a lot of users believe they ask for when they say `--tlsv1.1`...

> why it couldn't be implemented as a --tls-min option instead?

Sure it *could* have. But we're already suffering from a slight option fatigue and users are getting lost in the man page due to the plethora of almost identical sounding and functioning flags. So I'm all for trying hard not to introduce new options. Plus what I've already explained: people already assumed the options worked this way and the option didn't offer a feature people wanted. All that combined.

The fact that we didn't discover and fix this bug much much earlier is another matter of course and I think *that* is the reason why that older version works differently.

**Comment by tomato42** [comment]
> even though that's what a lot of users believe they ask for when they say --tlsv1.1

why would they do that? that's not what documentation introduced with that option stated

the usual case I recommended its use was when they had to interoperate with TLS 1.2 intolerant servers - you had then to specify the version exactly

this was specifically the reason we backported those options to RHEL-7 version of curl

> The fact that we didn't discover and fix this bug much much earlier

which bug? the incorrect documentation for `--tls-max` option? option that was added few years _after_ `--tlsv1.2` option? as for "earlier": people that usually have to deal with broken hardware are not known for upgrading their software at a breakneck speed... e.g. Debian stable, released just over a month ago, is on curl 7.52.1...

**Comment by kdudka** [comment]
> this was specifically the reason we backported those options to RHEL-7 version of curl

Not really.  The patches were backported to RHEL-7 because users needed to enable TLS 1.2 when TLS 1.0 was used by default.  The corresponding internal bug had summary `[RFE] RHEL7 - option to enable TLS 1.2`.

**Comment by tomato42** [comment]
and we didn't change that default until those patches were backported because we had customer reports  from other tools that showed that those switches are necessary if you support versions above TLS 1.0

**Comment by programuotojasgf** [comment]
We have a different(reverse?) issue:
We use
`curl_easy_setopt(m_curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_1);`

Testing results
TlsVersion, ExpectedResult, ActualResult, Result
Tls1.0 ; CertificateError ; CertificateError ; Good
Tls1.1 ; ConnectedOk; ConnectedOk; Good
Tls1.2 ; ConnectedOk; CertificateError ; Bad -> The setting worked as a "specific version" instead of "version or later" 

We tried both 7.57.0 and 7.62.0-DEV

**Comment by tomato42** [comment]
> We have a different(reverse?) issue:

no, that's the same problem

> If we switch to CURL_SSLVERSION_TLSv1_2 the Tls1.2 connection is then ok, but only specifically it

use it with backend that implements TLS 1.3 and a server that implements TLS 1.3 - the connection will end up with TLS 1.3

**Comment by bagder** [comment]
We regret the minor change in behavior but I fail to see how we can backtrack on this subject now. We will not revert the change.

**Comment by tomato42** [comment]
> I fail to see how we can backtrack on this subject now

same way you ended up in this mess...
