### ISSUE TITLE
"--write-out %{http_code}" output when proxy authentication fails with HTTPS protocol

### ISSUE THREAD

**Issue by kinformation** [curl/curl#2923]
### I did this

I am trying to access to the HTTPS protocol site using an authentication proxy.
If proxy authentication fails, "--write-out %{http_code}" is not 407 but 000 is output.
If the connection destination is HTTP protocol, 407 is output as "--write-out %{http_code}" .

```
$ curl https://www.example.com --proxy proxy.example.com --proxy-user user:passwor --insecure --proxy-anyauth --write-out %{http_code}
HTTP/1.1 407 Proxy Authentication Required
...

000
```

```
$ curl http://www.example.com --proxy proxy.example.com --proxy-user user:passwor --insecure --proxy-anyauth --write-out %{http_code}
HTTP/1.1 407 Proxy Authentication Required
...

407
```

### I expected the following

In the case of HTTPS protocol as well, 407 is output

### curl/libcurl version

[curl -V output]
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.0.1e zlib/1.2.3 libidn2/2.0.5
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy

### operating system

CentOS release 5.6 (Final)

**Comment by bagder** [comment]
That's because `%{http_code}` is the code from the remote server. The server you didn't reach when the proxy failed.

When you do HTTPS over a HTTP proxy, curl gets one response code from the proxy and then one from the remote server. In order for a script to extract both, independently, and know which is which, the one from the proxy is called `%{http_connect}'. (named after the CONNECT request curl issues to the proxy.)

**Comment by kinformation** [comment]
Thank you for your reply
I got it.
