### ISSUE TITLE
After last updated libcurl3 on libcurl4, some apps are removed.

### ISSUE THREAD

**Issue by hmble** [curl/curl#2944]
[Bug 1754294](https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294) from Launchpad. One of the maintainer over their said that it is bug from its own package and should report bug over here. Can you please check this bug and tell me whether it is package issue or something else.
Thank You.

**Comment by bagder** [comment]
The curl project doesn't produce the Ubuntu packages involved in your problem. We ship curl and libcurl as source code and they are then packaged by the package maintainers of the Linux distributions, like Ubuntu.

I know this is situation is horrible for those users who suffer from this problem, but unfortunately I can't see anything that we as upstream project can do to help out there.

The suggestion in [#72](https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294/comments/72) is pretty preposterous since Ubuntu/Debian are themselves the origin of that 3/4 SONAME thing to begin with so why couldn't they then introduce a 5 if they want to? Alternatively, if anyone truly thinks we should bump the SONAME in the curl project that someone is very welcome to come here and argue for that.

I can't see any bugs of ours here.
