### ISSUE TITLE
waiting for name resolver threads before quitting can cause delays even with --max-time

### ISSUE THREAD

**Issue by crvv** [curl/curl#2975]
### I did this
1. Edit `/etc/resolve.conf` to use a bad DNS server.
2. `time curl https://github.com/ --max-time 1 -v`
And `curl` exits after 5 seconds. The output is 
```
time curl https://github.com/ --max-time 1 -v
* Resolving timed out after 1000 milliseconds
* Could not resolve host: github.com
* stopped the pause stream!
* Closing connection 0
curl: (28) Resolving timed out after 1000 milliseconds
curl https://github.com/ --max-time 1 -v  0.02s user 0.02s system 0% cpu 5.042 total
```

### I expected the following
`curl` exits after 1 second.
Document at https://ec.haxx.se/usingcurl-timeouts.html says "When the set time has elapsed, curl will exit no matter what is going on at that moment", so I think this is a bug.

### curl/libcurl version
curl 7.61.0 (x86_64-pc-linux-gnu) libcurl/7.61.0 OpenSSL/1.1.0i zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.32.0
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system
Arch Linux

**Comment by jay** [comment]
Yes in your case it calls getaddrinfo which is blocking in a separate thread, however it waits in multi_done for the resolve to complete:
https://github.com/curl/curl/blob/432eb5f5c254ee8383b2522ce597c9219877923e/lib/multi.c#L536-L539
I'm not sure why that is necessary because libcurl threaded resolver was designed to handle cleaning up the resolves in the background, which would happen later on when multi_done calls via Curl_resolver_cancel and in this case that would call asyn-thread's destroy_async_data
https://github.com/curl/curl/blob/432eb5f5c254ee8383b2522ce597c9219877923e/lib/asyn-thread.c#L351-L362

**Comment by jay** [comment]
git blame puts it at ac9a179
~~~
When the application just started the transfer and then stops it while
the name resolve in the background thread hasn't completed, we need to
wait for the resolve to complete and then cleanup data accordingly.

Enabled test 1553 again and added test 1590 to also check when the host
name resolves successfully.

Detected by OSS-fuzz.
Closes #1968
~~~
I think we should just let it leak

**Comment by jay** [comment]
If the thread can be abandoned with ownership of all its resources which it later cleans up itself (I'm assuming here) then I don't see what benefit there is to waiting for it other than to please OSS-Fuzz. I think the fuzzer is wrong in this case.

**Comment by alexeip0** [comment]
Perhaps we should track the number of detached threads and have Curl_resolver_global_cleanup wait for the count to drop to 0 before returning?

**Comment by alexeip0** [comment]
And smarter fix would track detached threads on per-multi-handle basis and do similar wait in curl_multi_cleanup

**Comment by bagder** [comment]
Any wait for the pending thread(s) will risk blocking a call that will effect some users. We can only really fix this issue by removing the wait completely. If the threads don't leak any memory by this, I think it can be done. We just have to keep logic to make sure the OSS-Fuzz and possibly other tests don't consider that a leak.

**Comment by Alexander--** [comment]
> If the threads don't leak any memory by this, I think it can be done.

Threads leak their stacks.

This issue can't be fully fixed in libcurl, but users of libcurl (e.g. the command line `curl` tool) should be able to clean up by invoking exit() instead of curl_multi_cleanup(). GNU `cp` command [does exactly this](https://github.com/coreutils/coreutils/blob/d9a4d98/src/cp.c#L1221), when it isn't built for Valgrind.

**Comment by nickel715** [comment]
I also encountered this issue. 
I'm currently building a PHP application, accessing an external API while the user requests the page. In order to not slow down the page speed in case of any problems with the API, I want to skip the api call after a certain timeout. For that I set CURLOPT_TIMEOUT_MS to 150. Unfortunately this doesn't worked reliably. Since we faced issues with the external API or better said, with the dns resolving, I often got this error: `Resolving timed out after 252 milliseconds`. I've no idea where the 252 ms comes from, but not that 252ms is already too much, I saw the requests in the end takes even longer. For example when the average request took 500ms, some requests took 1200ms or even 1500ms which should never happen if the timeout would be adhered.

My guess: even that were seems to be a timeout of 252ms for the dns resolving, this timeout will be ignored. This could be valid since I figured out with `dig` that the dns resolving some times really took 500ms or longer.

Since I put the domain in the `/etc/hosts` the page speed is much more stable.

I hope this story was helpful for someone!

`curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0`

The php script was similar to this:
```php
<?php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, '...');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FAILONERROR, true)
curl_setopt($ch, CURLOPT_TIMEOUT_MS, 150);
curl_setopt($ch, CURLOPT_PROXY, null);
curl_exec($ch);
var_dump(curl_error($ch));
```
