### ISSUE TITLE
Failed add loading task when use "curl_multi_add_handle" 

### ISSUE THREAD

**Issue by westlifeMF** [curl/curl#3177]
in my project, I use the following codes to add a task:
curl_multi_add_handle(m_curlMultiHandle, job->getInternal()->m_handle);
 
Never had a problem in older version(7.56.7).
When I use the latest version(7.61.0),sometimes jobs cannot be added to the curl's queue,and return "CURLM_RECURSIVE_API_CALL".
I don't understand the reason for using this judgment:
    if(multi->in_callback)
        return CURLM_RECURSIVE_API_CALL;

In my opinion,this lock variable should not prevent user's job.This bug causes user tasks to be lost!

**Comment by bagder** [comment]
That error code was introduced in a general cleanup to more strongly discourage libcurl calls to get done from within libcurl's own callbacks - since that complicates matters a lot of and risk losing state or messing out stuff.

I don't think we should allow `curl_multi_add_handle()` from within callbacks for exactly that reason. The code doesn't take enough precautions before and after callbacks to handle this.

You *can* argue that you've done this before and it worked, but that was then by pure luck and not something we are able to guarantee will actually work in all versions and in the future.

> This bug causes user tasks to be lost!

Surely you check the return code and propagate the error back anyway so it shouldn't be lost without you noticing...

**Comment by withFrank** [comment]
Hi, bagder 
Is that mean can't call curl_multi_add_handle after curl_multi_perform called?

**Comment by bagder** [comment]
No, it just means that you can't call it from within a libcurl callback.

**Comment by withFrank** [comment]
Thanks, I'm clear now.
