### ISSUE TITLE
Curl linking against old openssl instead of custom installed openssl

### ISSUE THREAD

**Issue by ekhanad** [curl/curl#3429]
### I did this

**openssl**
```¨
./config shared --prefix="/usr1/test/openssl" openssldir="/usr1/test/openssl"
make
make install
```
**curl 7.63.0**
```
export LDFLAGS="-L/usr1/test/openssl/lib"
export CPPFLAGS="-I/usr1/test/openssl/include"
export CURL_LIBRARY_PATH="-L/usr1/test/openssl/lib"
export LIBPATH=/usr1/test/openssl/lib
./configure --prefix=$BUILD_DIR --exec-prefix=$THE_PREFIX --without-pic --with-ssl=/usr1/test/openssl --disable-dependency-tracking
gmake
gmake install
```
### I expected the following

Successful install

### Instead I got this
I can see that config is finding the right lib but make fails as it tries to link to the old lib in /opt/freeware/lib.

configure: Added /usr1/nkstd/MaDistrProd/openssl/lib to CURL_LIBRARY_PATH
checking for OpenSSL headers version... 1.1.1 - 0x1010101fL
checking for OpenSSL library version... 1.1.1
checking for OpenSSL headers and library versions matching... yes
....
Making all in lib
......
  CCLD     curl
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_free
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_filename
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_data_cb
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_filedata
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_addpart
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_headers
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_type
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_encoder
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_data
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_name
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_init
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_subparts
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status

I can see in the Makefile 
`CPPFLAGS = -isystem /usr1/test/openssl/include -I/opt/freeware/include -I/usr1/test/openssl/include`
`LDFLAGS = -L/usr1/test/openssl/lib -L/opt/freeware/lib -L/usr1/test/openssl/lib`

as soon as I remove the /opt/freeware/include from both flags, the linking works.

### curl/libcurl version
curl 7.63.0
[curl -V output]

### operating system
AIX

**Comment by bagder** [comment]
The "bad" -I option was probably brought in by a check for some other library, perhaps zlib. See `config.log` and check for when that flag is first used in the file.

I'm building curl with openssl in a custom location very frequently and I don't have this problem.

PS. Setting `CURL_LIBRARY_PATH` is not necessary. That's an internal thing the configure script does and it should not need help doing it.

**Comment by ekhanad** [comment]
Could you please specify which flag?

**Comment by bagder** [comment]
Whichever flag that is wrong, presumably one that mentions `/opt/freeware` for includes.

**Comment by ekhanad** [comment]
As you said /opt/freeware/Include is first included here:


configure:20574: ./conftest
configure:20574: $? = 0
configure:20575: result: yes
configure:20684: checking for pkg-config
configure:20703: found /usr/bin/pkg-config
configure:20715: result: /usr/bin/pkg-config
configure:20740: checking for zlib options with pkg-config
configure:20754: result: found
configure:20819: checking zlib.h usability
configure:20819: gcc -c -Werror-implicit-function-declaration -O2 -Wno-system-headers -isystem /usr1/nkstd/MaDistrProd/openssl/include -I/opt/freeware/include   conftest.c >&5
configure:20819: $? = 0
configure:20819: result: yes
configure:20819: checking zlib.h presence
configure:20819: gcc -E -isystem /usr1/test/openssl/include **-I/opt/freeware/include**   conftest.c
configure:20819: $? = 0
configure:20819: result: yes
configure:20819: checking for zlib.h
configure:20819: result: yes
configure:20907: found both libz and libz.h header
configure:21094: checking for BrotliDecoderDecompress in -lbrotlidec

...
...
...

THE first occurrence of incorrect **/opt/freeware**

configure:44142: Configured to build curl/libcurl:

  Host setup:       powerpc-ibm-aix7.2.2.0
  Install prefix:   /usr1/nkstd/MaDistrProd/curl/Install/AIX/build-7.63.0
  Compiler:         gcc
   CFLAGS:          -Werror-implicit-function-declaration -O2 -Wno-system-headers -pthread
   CPPFLAGS:        -isystem /usr1/test/openssl/include **-I/opt/freeware/include** -I/usr1/nkstd/MaDistrProd/openssl/include
   LDFLAGS:         -L/usr1/test/openssl/lib -L/opt/freeware/lib -L/usr1/nkstd/MaDistrProd/openssl/lib
   LIBS:            -lssl -lcrypto -lssl -lcrypto -lz

  curl version:     7.63.0
  SSL support:      enabled (OpenSSL)
  SSH support:      no      (--with-libssh2)
  zlib support:     enabled
  brotli support:   no      (--with-brotli)
  GSS-API support:  no      (--with-gssapi)
  TLS-SRP support:  enabled
  resolver:         POSIX threaded
  IPv6 support:     enabled
  Unix sockets support: enabled
  IDN support:      no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=yes, Static=no
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  SSPI support:     no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:     no
  ca fallback:      no
  LDAP support:     no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS support:    no      (--enable-ldaps)
  RTSP support:     enabled
  RTMP support:     no      (--with-librtmp)
  metalink support: no      (--with-libmetalink)
  PSL support:      no      (libpsl not found)
  HTTP2 support:    disabled (--with-nghttp2)
  Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP

**Comment by bagder** [comment]
So the zlib pkg-config data brings the compiler and linker options that "poĺlute" things so that the later check for openssl then detects openssl in the wrong directory. This is a known issue with how this configure script and there's no real fix available (as there's no real good known solution), there are just a few work-arounds.

If zlib shouldn't provide those flags, then I propose you clean up there first.

If those flags are fine for zlib, I would propose that you move/remove the openssl libs and headers from there so that configure won't find them in there.

If you really want to keep the wrong openssl in the zlib dir, still use that zlib setup but build to use an openssl installation in a separate place, then I don't think we have an immediate solution for you! I would strongly urge you to not put yourself in that position.

**Comment by bagder** [comment]
This issue is already listed as a [KNOWN_BUG](https://curl.haxx.se/docs/knownbugs.html#configure_finding_libs_in_wrong). Infrequent and tricky are probably two factors making it not a top prio for people to work on...

**Comment by OliPelz** [comment]
Hi, I have the same problem as the OP. I am on AIX 7.2. Here are my configure parameters:
```bash
LDFLAGS="-L/usr/lib" \
CPPFLAGS="-I/usr/include" \
./configure --prefix=/aixbrew/software/curl-7.63.0-aix \
--with-zlib=/aixbrew/software/zlib-1.2.11 \
--disable-static \
--disable-ldap \
--disable-ldaps
```
I get same errors as OP when linking curl, here is the exact compile line:
```bash
 gcc -Werror-implicit-function-declaration -O2 -Wno-system-headers -pthread -o .libs/curl curl-slist_wc.o curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_filetime.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_strdup.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeout.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-nonblock.o ../lib/curl-warnless.o ../lib/curl-curl_ctype.o -L/usr/lib -L/aixbrew/software/zlib-1.2.11/lib -L../lib/.libs -lcurl -lssl -lcrypto -lz -pthread -Wl,-blibpath:/aixbrew/software/curl-7.63.0-ibm/lib:/usr/lib:/lib
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_free
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_filedata
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_filename
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_data_cb
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_addpart
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_headers
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_type
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_encoder
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_init
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_subparts
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_data
ld: 0711-317 ERROR: Undefined symbol: .curl_mime_name
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
```

Whereas the symbols of the included libcurl.so.4 are there, so this should be no problem here!

```bash
ls -al ../lib/.libs/*.so*
-rwxr-xr-x    1 pelz     staff        831333 Jan 11 15:05 ../lib/.libs/libcurl.so.4
```

```bash
nm -g ../lib/.libs/libcurl.so.4 | grep curl_mime_free
.curl_mime_free      T   268538984
curl_mime_free       D   536884212
```
or 

```bash
nm -g ../lib/.libs/libcurl.so.4 | grep curl_mime_filedata
.curl_mime_filedata  T   268540664
curl_mime_filedata   D   536879628
```

For me the problem was that in the included lib dir ```/usr/lib``` there exists an older version of ```libcurl.a``` which has higher precedence because of ```-L``` parameter order . If I manually change the order of imported lib pathes the linking works fine, see:

```bash
gcc -Werror-implicit-function-declaration -O2 -Wno-system-headers -pthread -o .libs/curl curl-slist_wc.o curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_filetime.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_strdup.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeout.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-nonblock.o ../lib/curl-warnless.o ../lib/curl-curl_ctype.o -L/aixbrew/software/zlib-1.2.11/lib -L../lib/.libs -L/usr/lib -lcurl -lssl -lcrypto -lz -pthread -Wl,-blibpath:/usr/lib:/lib
```

Here is the relevant part of the original link- v.s. modified-link step order to make it more clear (taken from above)
```bash
[..]-L/usr/lib -L/aixbrew/software/zlib-1.2.11/lib -L../lib/.libs -lcurl[..]
#vs
[..]-L/aixbrew/software/zlib-1.2.11/lib -L../lib/.libs -L/usr/lib -lcurl[..]
```


Maybe this information can be releavant for a maintainer of the configure script to change the generation of library include order e.g. put the locally generated ```../lib/.libs``` library path BEFORE the system-wide library path (if there are no side-effects in doing so)?

Best,
Oliver

**Comment by bagder** [comment]
> LDFLAGS="-L/usr/lib" \

*you* added that flag that ended up "confusing" configure. How about just not adding that?

> a maintainer of the configure script

That's us here. We all want it to work as good as possible.

> to change the generation of library include order e.g. put the locally generated ../lib/.libs library path BEFORE the system-wide library path. (if there are no side-effects in doing so)?

That path isn't more "system-wide" than any other option, but you set it with LDFLAGS already from start and the rest of the logic appends the flags rather than prepends them. Changing that is very risky as this is a fragile area that is used for a vast number of different systems to configure the curl build.

**Comment by OliPelz** [comment]
Thanks Daniel for your helpful reply!

> > LDFLAGS="-L/usr/lib" \
> 
> _you_ added that flag that ended up "confusing" configure. How about just not adding that?

I added it because the system I am trying to install a new curl version is ```/opt/freeware```-enhanced which means a former sysadmin installed AIX Toolbox and perzl packages which changed default library search pathes. On this system the default library search path and cache is always first searching in ```/opt/freeware/``` before anything else so I had to manually add ```/usr/lib/``` to use it with higher presedence, otherwise only ```/opt/freeware/lib``` is considered for libssl, libcrypto, etc.
> 
> > a maintainer of the configure script
> 
> That's us here. We all want it to work as good as possible.
> 
Yes, I want this too :)

> > to change the generation of library include order e.g. put the locally generated ../lib/.libs library path BEFORE the system-wide library path. (if there are no side-effects in doing so)?
> 
> That path isn't more "system-wide" than any other option, but you set it with LDFLAGS already from start and the rest of the logic appends the flags rather than prepends them. Changing that is very risky as this is a fragile area that is used for a vast number of different systems to configure the curl build.

This was also my concern!

Solution for me is  to stick to your OP's original recommendation and remove the wrong ```/opt/freeware``` libs/includes for the curl build temporarily:

>  I would propose that you move/remove the openssl libs and headers from there so that configure won't find them in there.

If anyone is interested: 

```bash
# temporarily move wrong libssl and libcrypto from /opt/freeware for the time of the curl build
find /opt/freeware/ -type f -name libcrypto.* -o -name libssl.* | 
while IFS= read file_name
do
   mv $file_name $file_name.BaK
done
```
Don't forget to move wrong libssl include dir too
```bash
mv /opt/freeware/include/openssl /opt/freeware/include/openssl.BaK
```
Also we need to temp move old libcurl from ```/usr/lib``` away
```bash
mv /usr/lib/libcurl.a /usr/lib/libcurl.a.BaK
```

Then we can build curl without explicit ```/usr/lib``` includes and any errors!
```bash
./configure --prefix=/migration11/aixbrew/software/curl-7.63.0-ibm --with-zlib=/migration11/aixbrew/software/zlib-1.2.11 --disable-static --disable-ldap --disable-ldaps
```
Afterwards undo our changes

```bash
 find /opt/freeware/ -type f -name '*.BaK' | while IFS= read file_name; do mv $file_name `dirname $file_name`/`basename $file_name .BaK`; done
 mv /opt/freeware/include/openssl.BaK /opt/freeware/include/openssl
 mv /usr/lib/libcurl.a.BaK /usr/lib/libcurl.a
```

Thank you very much Daniel!

**Comment by bagder** [comment]
This is a [known bug](https://curl.haxx.se/docs/knownbugs.html#configure_finding_libs_in_wrong) and @OliPelz provides an excellent way above to work around it. Unfortunately we don't have any good fix for this coming.
