### ISSUE TITLE
Curl delimiter problem

### ISSUE THREAD

**Issue by m-mar** [curl/curl#3489]
For a few days ago, i wrote a bashscript to check some values with curl. sometimes the script crashes, because the delimiter for the http-timetotal response is sometimes a "," (1,232) or a "." (1.232).
i think the problem is between  4 until 7 days old.

the system is a centos 7.6 and the curl version is 7.29.0 (x86_64-redhat-linux-gnu).

kind regards

**Comment by bagder** [comment]
That's your system's locale setting affecting the output. This is not a bug.

To make sure you get consistent output from your scripts/shells, consider setting `LC_NUMERIC` to a suitable value. For example `en_US.UTF-8`.

**Comment by bagder** [comment]
> then i have to change the delimiter back again

How do you "change it back" ? Isn't that done by setting that or another variable? If so, how is that a curl bug?

**Comment by m-mar** [comment]
This is the line:

curl --write-out "%{time_total}\n" "https://google.com" --silent --output /dev/null | awk -F \, '{print $1}'

currently it works with "," . in a few days, curl change the returnvalue from "," to "." .

**Comment by bagder** [comment]
I don't believe curl changes behavior based on time. I think it changes because the environment changed.

You're using a curl version that is about to celebrate **6 years**. We have fixed thousands of bugs in the years since then. If you can reproduce this very strange behavior with a modern version of curl I would be happy to learn how.
