### ISSUE TITLE
Curl 7.21 prompt blocklist when trying to connect using sslv3

### ISSUE THREAD

**Issue by storyinvisible** [curl/curl#3508]
I am trying to collect traffic about sslv3 connection, and part of the program using curl. To enable sslv3 connection, I have used an older version of openssl 1.02k, curl(7.21) and ubuntu (14.04) . However, it prompt me "blocklist" when I try to connect. However should resolve this to have a successful connection?
`zbtest@zbtest-VirtualBox:~$ sudo curl https://orlandofringe.showare.co -3 -k`
`blocklist`
The url was tested with testssl, and it is vulnerable to poodle, thus connecting it with sslv3 should not be an issue

**Comment by storyinvisible** [comment]
Thanks !

**Comment by bagder** [comment]
You need to use a TLS library that has SSLv3 support enabled and then proceed like you did. Most libs these days, including TLS, is built and shipped without SSLv3 support since it is deemed an insecure protocol that shouldn't be used. You can build it yourself and enable the support explicitly if you want to.

**Comment by storyinvisible** [comment]
Hi , I have find out that if you run curl in windows 10 and run it with version of 7.52,  it can established ssslv3 connection, . Hopefully this information if useful for future users.
