### ISSUE TITLE
I got "SSL_write() returned SYSCALL, errno = 32" when upload data has large time gaps

### ISSUE THREAD

**Issue by Konstantinusz** [curl/curl#3593]
I have written an utility, which prints binary data to its STDOUT, but the data isn't continuous, it has time gaps (1-2 minutes), when no data is sent, because data is prepeared in the meantime. Then I pipe another "uploader" application to this utility, which calls the cURL binary under the hood, and uploads the received data to a server (HTTPS), by applying a FIFO file (made by mkfifo), and with chunked transfer encoding.

My problem is, that I always get the abovementioned error ( curl: (55) SSL_write() returned SYSCALL, errno = 32 ), meanwhile the data for upload is prepeared by my utility, and the data stream isn't continuous, and is paused: the uploader application should wait for the data to arrive. Uploading speed decreases to zero in this time interval. I tried to resolve the issue by applying the following options to cURL: "--keepalive-time 1200 --speed-time 1200 --speed-limit 1 --connect-timeout 1200", but no success. 

When I pipe another app to my utility which simply uploads the piped data to an FTP server (by calling cURL of course), in this case I get no error message. I get the error only when I upload to a HTTPS connection.

My utility is intended to upload files, which are in splitted RAR archives, and when an archive part is downloaded, it begins to unpack it, sending the data to STDOUT. When the next archive part is needed by the unrar application, it deletes the previous archive from the disk, and fetches the next one from the net, and then makes the unrar application to continue by sending an enter keypress to its stdin, and so on. This is why the data flow isn't continuous, and has gaps. So it is able to unpack large amount of data by utilizing only small disk space ( the size of only one archive volume ), ideal for low disk space VPS.

**Comment by bagder** [comment]
Now you don't say what OS this runs on, but on Linux errno 32 is `EPIPE`. Together with the rest of the description, I think it matches. It is *probably* just the fact that due to your long pause, the connection is closed. By the server, a NAT or something else.

I'm curious why your attempts to solve this use timeouts at 1200 seconds when you see problems already within 1-2 minutes. You should rather try with keepalives below 60. Also, it is also sometimes seen in some NATs that don't care about TCP keepalive but will only actually keep the connection alive if there's TCP traffic. If that's your situation, then I either have to write your application to restart closed connections or you reduce the silent periods even more.

I don't think this is a curl bug.

**Comment by Konstantinusz** [comment]
I see, I am using Archlinux 32 bit (4.20.2-arch1-1.0-ARCH).

**Comment by Konstantinusz** [comment]
By experimenting with different sleep times, I managed to determine, that a 20 seconds timeout is valid for the uploading process. When there is no data flow for 19 seconds, then I experience no errors yet. When I make sleep the producer side of the FIFO more than 20 seconds, then I always get the SSL_write() error, maybe the remote server close the connection after not getting data for more than 20 seconds.

**Comment by bagder** [comment]
I don't see how this can be a curl bug though. Can you?
