### ISSUE TITLE
curl_init() is not working properly for api

### ISSUE THREAD

**Issue by rohitnehra** [curl/curl#3667]
```
<?php
function SendMessage($mobile, $text)
{
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://www.mysmsapp.in/api/push.json?apikey=xxxxxx&sender=xxxxxx&mobileno=".$mobile."&text=".$text);
curl_exec($ch);
curl_close($ch);
}
 ?>
```

I have this simple function to send messages. But it shows internal server error whenever I execute it for more than 100 results (100 is approximate value, it works for 120 etc but not everytime). I need a solution in which I can execute it properly.

**Comment by xquery** [comment]
Without seeing any code examples we can only guess that there is some issue with the server or interceding network.

If the network and that server is out of your control (yet you get intermittent access) - you are always free to  handle errors in your own code - usually that means checking what is returned from curl_easy_perform (or curl_multi_perform) eg. should be CURL_OK ... on !CURL_OK you would then retry again (and maybe increment a counter for retrying so u do not go into an infinite loop).

The only other thing I can think of is that you are getting an error sometimes because of libcurl timing out (due to poor server/network performance) - curl has a lot of settings/options for telling it how long to wait which you can try and increase. 

Options are defined here https://curl.haxx.se/libcurl/c/easy_setopt_options.html

**Comment by rohitnehra** [comment]
<?php
function SendMessage($mobile, $text)
{
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://www.mysmsapp.in/api/push.json?apikey=xxxxxx&sender=xxxxxx&mobileno=".$mobile."&text=".$text);
curl_exec($ch);
curl_close($ch);
}
 ?>

**Comment by bagder** [comment]
What says "internal server error" ? libcurl has no such error string so it seems likely that's what you got returned in contents from the remote and thus this is not a bug at all, except perhaps in the remote server?

**Comment by nosrednaj1984** [comment]
https://github.com/curl/curl/issues/3667#issue-419443187

**Comment by bagder** [comment]
No reponse and not enough details to work with.
