### ISSUE TITLE
UNICODE filename problems on Windows (again)

### ISSUE THREAD

**Issue by AnrDaemon** [curl/curl#3675]
Since #345 is locked down…

Given recent analysis from [PHP/cURL bug report #77711](https://bugs.php.net/bug.php?id=77711)
> [2019-03-12 11:04 UTC] ab@php.net
> It functionality in the description has been never present in PHP in the claimed form. libcurl still uses ANSI APIs which causes reports like https://github.com/curl/curl/issues/345. A solution needs to be done on the side cURL to
>
> - always handle filenames as UTF-8, use Unicode APIs internally and do conversion, or
> - export additional APIs based on wide chars, or
> - export handlers for I/O operations, that can be overridden
>
> The first option could be the easiest, but it would be a huge BC breach.
>
> The second option might be more compatible, but it might lead to duplicating a lot of APIs.
>
> The third option would regard to fopen, stat and several other I/O APIs involving filenames. Then any consuming library could make this part of cURL compatible to its needs. Perhaps that would be the cleanest way.
>
> cURL could be also compiled with UNICODE, but i'm not sure it would really work. Fe see places like this https://github.com/curl/curl/blob/f762fec323f36fd7da7ad6eddfbbae940ec3229e/src/tool_filetime.c#L40  where ANSI function is used directly so would stay same even with UNICODE.
> And in any case PHP can't be compiled with UNICODE, so that's not an option.

…the issue looks unfixable without some internal changes to cURL.

**Comment by bagder** [comment]
Like in the case of #345 case, I will defer this issue to those who speak Windows to advice, recommend actions and write PR(s). Back then the interest wasn't strong enough to keep the issue alive, let's hope it ends up better this time!

**Comment by bagder** [comment]
This issue speaks of the "libcurl API" in vague terms, but it looks like the PHP bugs talks about doing multipart formposts specifically, and the file name field that is set such a "part". I think it would be beneficial to be as specific as possible so...

The PHP/CURL binding is still using the **deprecated** [curl_formadd()](https://curl.haxx.se/libcurl/c/curl_formadd.html) function. Like here: https://github.com/php/php-src/blob/cc16781e9e910b9b8c027db47d893ad13fad9ecd/ext/curl/interface.c#L2829 I would perhaps consider switching that code over to `curl_mime_*` to be a first priority.

If we focus on the end game here, which is to send over data to the server with the file name field set to UTF-8 name for users of PHP/CURL, curl seems to already provide the necessary means for that since the `curl_mime_`  allows for the application to set the file name totally independent of the contents so it could ready from file A and set the file name to B.

If I'm not missing something here, PHP/CURL *could* be written to read data from the file using whatever rules it wants and it could then just set the file name field to be exactly what it thinks is the right one, without curl having to change at all.

Am I wrong?

**Comment by AnrDaemon** [comment]
In the mentioned bug report, the problem is specifically reading from a given file.
I had to give it a file name in CP1251 encoding to be able to make curl successfully read the contents.
Else error 26.

**Comment by bagder** [comment]
I might be barking up the totally wrong tree here since Windows and its peculiarities are not my backyard, but...

It is about specifically reading from a given file - *for the purpose of including that file in a multipart formpost*, and what I'm saying is that there's a solution - or work-around perhaps - available for this problem that CURL/PHP could implement without libcurl having to do anything.

1. load the contents from file A
2. tell libcurl about the contents
3. tell libcurl the file name for the part is B

This way libcurl doesn't open any file at all. The binding does that and it tells curl what file name to use for the part.

[RFC 7578](https://tools.ietf.org/html/rfc7578#section-5.3) says the following about the `Content-Disposition` header that is set per-part:

>  NOTE: The encoding method described in [RFC5987], which would add a  "filename*" parameter to the Content-Disposition header field, MUST NOT be used.

Which is good for us since we don't do that anyway. Instead it suggests a client should:

> file names normally visible to users MAY be encoded using the percent-encoding method

AFAICT, libcurl provides the necessary APIs already to allow this.

**Comment by gvanem** [comment]
@AnrDaemon Have you tried building with `HAVE_ICONV`? It doesn't seem to do anything for local files; the `CURLOPT_CONV_*` options handles *network data*.  

Should there perhaps be a set of `CURLOPT_CONV_FILE_*`  options to create a uniform API for all targets (not just Windows)?

**Comment by AnrDaemon** [comment]
To make it clear, I'm not building anything. I'm using cURL library/extension as shipped with PHP.
If you say that the libcurl API in question is deprecated (if I understand [the explanation](https://github.com/curl/curl/issues/3675#issuecomment-473191793) correctly), I can only relate the answer to PHP devs and invite them to join the discussion.

**Comment by bagder** [comment]
> To make it clear, I'm not building anything

You filed an issue about a problem in PHP/CURL suggesting it is a (tough) problem within libcurl.

I'm telling you PHP/CURL is using an outdated libcurl API (that indeed has that problem) and I've pointed out how the unicode file problem can be fixed within PHP/CURL - using the new API we have for sending formposts. This is the curl project, we don't author PHP/CURL - that's handled by the PHP project.

So, to me it seems reasonable to at least toy with the idea that this issue can be fixed without us doing anything about libcurl.

**Comment by AnrDaemon** [comment]
I'm not blaming anybody, only trying to make some progress on the issue at hand.
I reported your concerns. Let's wait a bit and see what follows.

**Comment by weltling** [comment]
@badger thanks for the analyze on your side! So it looks, like PHP should rewrite the usage of `curl_formadd` to `curl_mime_*` anyway.

I see an issue with the way you've suggested. Namely, reading the whole file into memory seems suboptimal, as we still want to support an arbitrary size. So we still should use [curl_mime_filedata](https://curl.haxx.se/libcurl/c/curl_mime_filedata.html). And here, we come back to the same issue. The MIME API in cURL uses `fopen`, which in turn uses `CreateFileA`. That API depends on the current code page, say on Windows with the USACII codepage it will be impossible to open a filename with say Chinese symbols. For that, there's `CreateFileW` which uses UTF-16.

If i may suggest the following. I was looking through cURL APIs and it seems [this handler](https://github.com/curl/curl/blob/179927c12a54ea810bbc7c6c6fb970ad90b89eef/lib/mime.h#L111) is responsible for opening files as well. Since PHP 7.1 we have a bunch of functions to support UNCODE in filenames, like [here](https://github.com/php/php-src/blob/master/win32/ioutil.c#L189), so we could easily write a wrapper to mimic the corresponding handler function. Please correct me if I'm wrong, but right now I see that `mime.h` is not public, so one won't be able to assign a custom callback there. Question - were it possible cURL to add an `fopen` handler to `curl_mimepart_s` and provide a way to override it? That would be a good base for PHP to refactor to the `curl_mime_*` API.

Thanks.

**Comment by bagder** [comment]
Yes, the *filedata() function has the same problem already mentioned here. I'm not saying that there isn't a problem there that we could or perhaps *should* fix somehow, but as stated above, this is a complicated question and the method I propose already exists and would allow an application or binding to work around the issue already today.

The public interface to using a read callback for formposting is the [curl_mime_data_cb](https://curl.haxx.se/libcurl/c/curl_mime_data_cb.html) function. You could thus set the callback and the file name for the part, and then you can open the file however you see fit.

Unless I've misunderstood something of course, which is always a possibility! :wink:

**Comment by weltling** [comment]
That looks promising! Thanks for the tip. I'll go for some experiments, will come back if there are any questions.

Thanks

**Comment by cmb69** [comment]
@badger We have landed php/php-src@c68dc6b5e37e74d89e0a387079139c054c8faa81 now, so this ticket can probably be closed. Thanks for pointing out the `curl_mime_*` API!

**Comment by bagder** [comment]
Thanks for notifying. I'm closing this issue now since for multipart formposts (at least) the issue can be worked around with this API.
