### ISSUE TITLE
Man-in-the-middle proxies dont work with CURL + WinSSL

### ISSUE THREAD

**Issue by lietusme** [curl/curl#3727]
We have users that use company wide man-in-the-middle proxies for internal security. However client software with libCURL + WinSSL reports following error in their environments:

**schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.**

All other Windows software work fine. It is also reproducable with Fiddler acting as decrypting proxy - as discussed in this issue https://github.com/curl/curl/issues/264

While solution was implemented:
curl_easy_setopt(m_curl, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NO_REVOKE);

I would argue that this is not enough, especially as it makes CURL + WinSSL software act different from other Windows based software and reduces security.

### I did this

Tested with build: https://curl.haxx.se/windows/ 
1. Run Fiddler
2. set CURL_SSL_BACKEND=Schannel
3. curl https://google.com -x 127.0.0.1:8888
(Got 0x80092012 error)
4. curl https://google.com -x 127.0.0.1:8888 --ssl-no-revoke
(Succeeded as expected)
5. curl https://revoked.badssl.com/ --ssl-no-revoke
(Succeeded, but there should be option to not allow this)

### Also tested with custom proxy server instead of Fiddler

1. Self signed Root CA certificate
	OpenSSL can be used to generate it.
	Easy-RSA utility simplifies that process, more documentation can be found here:
	https://github.com/OpenVPN/easy-rsa/blob/master/README.quickstart.md
	CA certificate should have revocation list configured
2. Burp configured as a proxy with previously generated certificate imported.
3. On client machine Root CA certificate has to be installed into Trusted Root Authorities store.
4. curl https://google.com -x ProxyServerUrl:ProxyPort
(Got 0x80092012 error)

### curl version

curl 7.64.0 (x86_64-pc-win32) libcurl/7.64.0 (OpenSSL/1.1.1a) Schannel zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.8.0 nghttp2/1.36.0
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz brotli TLS-SRP HTTP2 MultiSSL

### operating system

Microsoft Windows [Version 10.0.17134.648]

**Comment by jay** [comment]
It's possible that if a certificate in a chain does not have any revocation point and revocation checks are enabled then the call will fail. The root certificate is checked for revocation as well. Confirm by dumping the chain and inspecting it, and inspect the root certificate. Short of writing our own manual verification process and iterating through each certificate to check revocation I don't see how we could distinguish certs with no revocation points from certs that have revocation points but aren't available for whatever reason.

Using --ssl-no-revoke to disable revocation checking by curl schannel of your generated MITM certificates is practical for a case like this. Fiddler does its own schannel revocation check of the actual certificates if you enable it (but I think it's only interactive). Burp may be similar.

> 5\. curl https://revoked.badssl.com/ --ssl-no-revoke
>     (Succeeded, but there should be option to not allow this)

That's exactly how it works and how it should work.

**Comment by lietusme** [comment]
To clarify - are we are talking about "CRL Distribution Points" field in certificate?

### These are configurations that I know don't work and produces 0x80092012 error:
Fiddler overrides with certificates without any CRL values.  Chain looks like:
```DO_NOT_TRUST_FiddlerRoot [No CRL] / *.service.com [No CRL]```

Certificate chain from user (behind proxy):
```User-root-CA [No CRL]  -> User-CA [CRL]  -> *.service.com [No CRL]```

### These work without any errors with CURL + WinSSL and default revocation checks:
And if connecting CURL to service directly:
```DigiCert [No CRL] -> DigiCert CA [CRL] -> *.service.com [CRL]```

Also we have our internal testing services like this:
```Our-root-CA [No CRL] -> Our CA [CRL] -> *.test-service.com [CRL]```

So there is variety of configurations, but both failing ones have no CRL in end-entity (*.service.com) certificates. Can that be what is causing it?

**Comment by jay** [comment]
If the schannel backend is used and the user does not specify a bundle of certificates then libcurl uses the default OS certificate store with [SCH_CRED_REVOCATION_CHECK_CHAIN](https://docs.microsoft.com/en-us/windows/desktop/api/schannel/ns-schannel-_schannel_cred#SCH_CRED_REVOCATION_CHECK_CHAIN) which is documented as _"When validating a certificate chain, check all certificates for revocation."_

<details>
 <summary>Code for SCH_CRED_REVOCATION_CHECK_CHAIN</summary>

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/vtls/schannel.c#L517-L545
</details>

<br>

If the schannel backend is used and the user specifies a bundle of certificates (eg CAINFO) then libcurl ignores the OS certificate store and uses the bundle with [CERT_CHAIN_REVOCATION_CHECK_CHAIN](https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-certgetcertificatechain#CERT_CHAIN_REVOCATION_CHECK_CHAIN) which is basically the same thing, documented as _"Revocation checking is done on all of the certificates in every chain."_

<details>
 <summary>Code for CERT_CHAIN_REVOCATION_CHECK_CHAIN</summary>

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/vtls/schannel_verify.c#L498-L546
</details>

<br>

Whether or not certificates without revocation points (any point like AIA or CRL or whatever) are accepted is unclear. Based on what you are describing it's likely schannel using such a revocation check must allow for root certificates without any revocation point but not leaf certificates without any revocation point, at least in Windows 10.

Also review [Can't connect to Fiddler proxy if using WinSSL backend](https://github.com/curl/curl/issues/264) which is why I added --ssl-no-revoke (I had forgot or I would've mentioned it yesterday). You'll notice in that issue I said:

> schannel is returning CRYPT_E_NO_REVOCATION_CHECK likely because we pass SCH_CRED_REVOCATION_CHECK_CHAIN in schannel_connect_step1 and in that case schannel requires all root CAs to have some sort of revocation detail when that flag is passed.

Based on what you describe I guess I'm wrong or it's not consistent between OS versions.

**Comment by lietusme** [comment]
P.S. I fixed my top issue description to refer to https://github.com/curl/curl/issues/264 ... pasted wrong link before. I was aware about that issue/fix and wanted followup - as it affects more usual proxy configurations, not only Fiddler.

It seems that original issue https://github.com/curl/curl/issues/264 was not related to root certificate CRLs at all, Fiddler would also make end-entity (leaf) certificates without CRLs as well. Or was there clarification that exactly root certificate checks caused  https://github.com/curl/curl/issues/264 ?

Is there any way to skip end-entity certificate revocation checks if there is none in curl/winssl?

Major reason for this is that all Windows based software works fine with these configurations, but then software that is built on top of CURL + WinSSL is seen as wrong at the end user.

On related note, CRL server offline errors are usually ignored by most of Windows software, but not CURL + WinSSL. While this is much less important, it is inconsistency as well.

**Comment by jay** [comment]
> It seems that original issue #264 was not related to root certificate CRLs at all, Fiddler would also make end-entity (leaf) certificates without CRLs as well. Or was there clarification that exactly root certificate checks caused #264 ?

The reporter in #264 didn't respond to the report so I don't know. It's not documented what happens when a certificate is missing any revocation point and revocation checks are enabled. It most likely falls under the no revocation check error. We have some empirical results here and in the other issue but that's about it. It may be different depending on OS version.

> Is there any way to skip end-entity certificate revocation checks if there is none in curl/winssl?

Disable revocation checks in curl using --ssl-no-revoke. Whether not your MITM does actual revocation checks is outside of curl's control.

> Major reason for this is that all Windows based software works fine with these configurations, but then software that is built on top of CURL + WinSSL is seen as wrong at the end user.

Yeah I'd imagine most developers implement soft revocation checking where it tries and if it cannot succeed it continues with the connection anyway. curl does not do that as I discussed in the other issue, you can have it either fully on or fully off in Windows.

**Comment by lietusme** [comment]
Seems that chromium went route of not using SCH_CRED_AUTO_CRED_VALIDATION because of inconvenient default behaviors, as explained here: https://github.com/adobe/chromium/blob/master/net/socket/ssl_client_socket_win.cc

**Comment by jay** [comment]
Yes, you can get more detail with manual validation. We use manual validation if the user specified a bundle of certificates as shown earlier. Let's say we were to always use manual validation and switch to a manual revocation check via [CertVerifyRevocation](https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-certverifyrevocation), it looks like the best we get is probably the same error CRYPT_E_NO_REVOCATION_CHECK that a revocation check couldn't be done but not _why_ it couldn't be done. 

My advice is disable revocation checking for MITM by using --ssl-no-revoke. If you really want revocation checks but you want to ignore CRYPT_E_NO_REVOCATION_CHECK you can modify your build of curl to make schannel ignore that error by passing [SCH_CRED_IGNORE_NO_REVOCATION_CHECK](https://docs.microsoft.com/en-us/windows/desktop/api/schannel/ns-schannel-_schannel_cred#remarks) like `schannel_cred.dwFlags |= SCH_CRED_REVOCATION_CHECK_CHAIN | SCH_CRED_IGNORE_NO_REVOCATION_CHECK;`

**Comment by lietusme** [comment]
Interesting - I wonder if SCH_CRED_IGNORE_NO_REVOCATION_CHECK should be default in CURL even? Or allow configuring these via set-opt. Changing our fork of CURL may work as well, but that gets ugly when updating versions

**Comment by jay** [comment]
> I wonder if SCH_CRED_IGNORE_NO_REVOCATION_CHECK should be default in CURL even? Or allow configuring these via set-opt.

No because as I've explained 0x80092012/CRYPT_E_NO_REVOCATION_CHECK is not specific to certificates without revocation points therefore ignoring it is tantamount to allowing soft revocation. I won't endorse separate options/flags to handle soft revocation since it's more to maintain for very little gain, and we discourage backend specific options unless there's some significant value. You could implement your own option --ssl-soft-revoke for review (I would guess `SCH_CRED_IGNORE_NO_REVOCATION_CHECK
| SCH_CRED_IGNORE_REVOCATION_OFFLINE`) but my vote will be no.

**Comment by lietusme** [comment]
Applied suggested fix to our fork of CURL, works and still checks for revoked CRL. I think this should be fine for now, will just need to make sure this change is not lost when we update CURL sources. Thanks!

\lib\vtls\schannel.c

```diff
+#ifdef ENABLE_SOFT_REVOCATION_CHECKS
+        schannel_cred.dwFlags |= SCH_CRED_IGNORE_NO_REVOCATION_CHECK | SCH_CRED_IGNORE_REVOCATION_OFFLINE;
+        DEBUGF(infof(data,
+                     "schannel: checking server certificate revocation (soft)\n"));
+#else
         DEBUGF(infof(data,
                      "schannel: checking server certificate revocation\n"));
+#endif
```
