### ISSUE TITLE
CURLOPT_TIMEOUT bug when using multiple connections

### ISSUE THREAD

**Issue by Curlenius** [curl/curl#3728]
### I did this
I set following options:
    CURLOPT_TIMEOUT to 60 seconds
    CURLOPT_HTTP_VERSION to CURL_HTTP_VERSION_1_1
    CURLOPT_PROXYTYPE to CURLPROXY_SOCKS5_HOSTNAME
    CURLOPT_PROXY to locally installed TOR
    CURLMOPT_MAX_TOTAL_CONNECTIONS to 5
    CURLMOPT_MAX_HOST_CONNECTIONS to 2

Then I set some other minor (not related to connection, like http headers) options and run curl multi with hundreds of urls

### I expected the following
   Curl should try to connect to each url, maximum of 2 connection per host and 5 connection to all hosts at the same time. Each connection should timeout after CURLOPT_TIMEOUT seconds since when the connection is started.

It works fine, but after 60 seconds (CURLOPT_TIMEOUT) it starts to timeout repeatedly. It seems that CURLOPT_TIMEOUT is calculated since when execution is started, but not since the connection is made to the server for each URL.

For example, if I add 100 urls to curl multi and start executing curl, it works fine and grabs 20 urls in first 60 seconds (CURLOPT_TIMEOUT) but after that, for other 80 connections it immediately starts to show following errors:

Operation timed out after 1949 milliseconds with 0 out of 0 bytes received
Operation timed out after 296 milliseconds with 0 out of 0 bytes received
Operation timed out after 0 milliseconds with 0 out of 0 bytes received
Operation timed out after 2583 milliseconds with 0 out of 0 bytes received
Operation timed out after 1403 milliseconds with 0 out of 0 bytes received
Operation timed out after 0 milliseconds with 0 out of 0 bytes received
Operation timed out after 3846 milliseconds with 0 out of 0 bytes received
Operation timed out after 237 milliseconds with 0 out of 0 bytes received
Operation timed out after....

### curl/libcurl version
PHP CURL extension version 7.64.0

### operating system
PHP 7.3.3 on macOS 10.14.1

**Comment by bagder** [comment]
`CURLOPT_TIMEOUT` sets a maximum time the transfer is allowed to take, independently of what exactly in that transfer that is slow. It could be the name lookup, the TCP connection, the TLS handshake, crappy bandwidth or just an overloaded remote server. The time-out is counted from the time you add the handle to the multi handle (pretty much).

In your case, you artificially make the connection phase (much) slower by forcing the transfer to queue up and wait for a "free slot" since it isn't allowed to use more than a set number of transfers. In this concept, you're delaying - or slowing down - the connection phase. It could theoretically sit in this state for a very long time.

Is this what happens?

I can see your point of view that it shouldn't start counting the timeout until when it actually starts doing something, but I'm afraid that will then just lead to the opposite effect: someone who today sets a timeout to something reasonable to kill transfers that just aren't completed in time will then consider the timeout value to be a lie.

Using a fixed timeout for a transfer that may vary greatly in time is difficult to use.

> Operation timed out after 1949 milliseconds

The fact that this mentions the *wrong* time here I believe is a bug that is already fixed. If not, that is an independent issue I believe.

**Comment by Curlenius** [comment]
Hi Bagder and thank you for your time on replying me and making CURL go on.

> someone who today sets a timeout to something reasonable to kill transfers that just aren't completed in time will then consider the timeout value to be a lie.

As English is not my mother tongue, I don't know I really understand your point or not. So please pardon me and let explain what I understood from the quote above by an example:

`When a programmer makes many connections and put them in queue by CURLMOPT_MAX_TOTAL_CONNECTIONS or CURLMOPT_MAX_HOST_CONNECTIONS, he expects that the connection must end in CURLOPT_TIMEOUT seconds because otherwise the whole operation can take (CURLOPT_TIMEOUT * number of operations) seconds. (imagine thousands of seconds with unreasonable timeout which could continue for almost forever)`

If I understand you correctly, Imagine you want to download 100 files from a remote server (or in my case, many files from many remote servers) and set timeout to a normal value (30 seconds), and you want to download them one by one, because you don't want to attack remote server by a lot of connections (DOS-Attack). Then first file have problem in connecting to the remote server and so timeout happens, and then all 99 connection after the first one will timeout just because the first connection had some sort of problem.

To address the problem that I explained and I think is your point too, probably CURL should have another option like CURLOPT_EXECUTION_TIMEOUT (or whatever) which which starts counting for timeout as soon as the connection gets out of queue and it's execution starts.

So in example above, programmer can set CURLOPT_EXECUTION_TIMEOUT to 30 and existing CURLOPT_TIMEOUT to 180, then each connection have to execute in up to 30 seconds, and can stay in queue up to 180 seconds. By adding CURLOPT_EXECUTION_TIMEOUT, there is no need to change the way CURLOPT_TIMEOUT works.

A new option like CURLOPT_EXECUTION_TIMEOUT can address the problem, and can be completely backward-compatible with current implementation if CURLOPT_TIMEOUT.

------------------

At first that I sent this issue, I thought this is a bug, and now that I have read your reply I believe it is a lack of feature to not working this way, currently the programmer has to handle queue by himself (which makes current queue feature of CURL almost useless in poor, slow or highly-moderated networks and slow/heavily loaded remote servers).

And if the programmer can't make a proper queue, then he has two solutions:
1. Sets an unreasonable large timeout for all connections
2. Increase CURLMOPT_MAX_TOTAL_CONNECTIONS and CURLMOPT_MAX_HOST_CONNECTIONS

In solution #1 problem remains unsolved (because first connection of a list can take up to CURLOPT_TIMEOUT seconds and make all other connections in queue to timeout.

In solution #2, not only we can bombarding the remote server, but also if all open connections timeout, all the rest connections in queue will timeout too.

So I think adding an option like CURLOPT_EXECUTION_TIMEOUT (or whatever it's name should be) not just solves the problem, but makes current implementation fully backward compatible (as it CURLOPT_TIMEOUT should work the way it is working now).

**Comment by bagder** [comment]
> Imagine you want to download 100 files from a remote server (or in my case, many files from many remote servers) and set timeout to a normal value (30 seconds), and you want to download them one by one. Then first file have problem in connecting to the remote server and so timeout happens, and then all 99 connection after the first one will timeout just because the first connection had some sort of problem.

Yes because you tell curl you want these 100 transfers to be completely done *within 30 seconds*. If they're not done within 30 seconds, they timeout. If you limit how fast curl can do these transfers there's a risk that some of those transfers never even started before they timeout.

In such a situation I would probably say that asking for 100 transfers to be done within such a strict time limit is the wrong move.

`CURLOPT_TIMEOUT` is a very blunt tool that is hard to use since it sets a fixed limit to something that often have a lot of moving parts and parameters that are variable. When this option is not good enough, I recommend perhaps trying `CURLOPT_LOW_SPEED_LIMIT` etc or crafting your own timeout logic using `CURLOPT_XFERINFOFUNCTION`. Or as you mention, queue transfers outside of curl while they're not ready to start.

> adding an option like CURLOPT_EXECUTION_TIMEOUT

That option would still suffer from the same problems with it being fixed while the nature of networks rarely are. You can *easily* implement that timeout yourself in your application by using the progress callback I mention above.
