### ISSUE TITLE
GET requests with gzip encoding fail with CURLE_WRITE_ERROR

### ISSUE THREAD

**Issue by jay** [curl/curl#3796]
### I did this

Dmitri Trembovetski [reported on the mailing list](https://curl.haxx.se/mail/lib-2019-04/0060.html) that when he enables gzip his requests fail with CURLE_WRITE_ERROR. He traced it to process_trailer() in lib/content_encoding.c line 149:

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/content_encoding.c#L136-L157

He provided a trace.log which I constructed into the server response, get it here [trace.zip](https://github.com/curl/curl/files/3100680/trace.zip)

First window:
`while true; do cat response.bin | nc -4l localhost 8000; done`

Second window:
`curld -v --compressed -o out http://localhost:8000`

While inflating the response inflate returns Z_STREAM_END. The [zlib manual](https://www.zlib.net/manual.html) says _"inflate() should normally be called until it returns Z_STREAM_END or an error."_ And following that libcurl calls process_trailer to handle the extra data. Interestingly that's kind of a workaround because most modern zlibs should process the trailer automatically, and it appears that's what's happened here, as expected. What is not expected is that extra data after the stream ends (z->avail_in == 23) but no trailer is expected because as noted modern zlib handles that (zp->trailerlen == 0). 

The 23 bytes that are unexpected:

`1F 8B 08 00 00 00 00 00 00 FF 01 00 00 FF FF 00 00 00 00 00 00 00 00`

Another interesting thing, it starts with a gzip header. gzip RFC 1952 [says in 2.2 file format](https://tools.ietf.org/html/rfc1952#page-5):
~~~
      A gzip file consists of a series of "members" (compressed data
      sets).  The format of each member is specified in the following
      section.  The members simply appear one after another in the file,
      with no additional information before, between, or after them.
~~~

So shouldn't we allow it as a separate member and not treat it as an unexpected trailer?

### I expected the following

A good time

### curl/libcurl version

master from a few days ago 538db66 2019-04-16

~~~
curl 7.65.0-DEV (i386-pc-win32) libcurl/7.65.0-DEV OpenSSL/1.0.2r zlib/1.2.11 nghttp2/1.37.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug HTTP2 HTTPS-proxy IPv6 Largefile NTLM SSL libz
~~~

### operating system

Windows 7 Enterprise

<br>
/cc @monnerat

**Comment by dtrembovetski** [comment]
Thanks for looking at this.

Ok I think I may know why. This particular endpoint streams data (it's a stream of msg-packed structs, so each struct may be zipped individually since the server may not know when it'll run out of stuff to stream).

Now I realize why I don't have this problem with other endpoints - those don't stream but send "normal" complete responses (basically mspacked dictionaries).

We've been doing this forever and other network client APIs don't seem to mind (NSURLSession or Windows networking API) don't bat an eye.

**Comment by dtrembovetski** [comment]
It also explains why it works sometimes on this endpoint - the response sometimes contains a single struct, and in the cases when it fails I know it contains more than that.

**Comment by jay** [comment]
I ran a simple test of two separate gzip members concatenated together in Firefox and Chrome and they both ignore the second member, as do curl versions prior to when the additional validation checks were added.

~~~python
import zlib

data = b"HTTP/1.1 200 OK\r\nContent-Encoding: gzip\r\n\r\n"

gzip_compress = zlib.compressobj(9, zlib.DEFLATED, zlib.MAX_WBITS | 16)
data += gzip_compress.compress('foo') + gzip_compress.flush()

with open('foo.bin', 'wb') as file:
    file.write(data)

gzip_compress = zlib.compressobj(9, zlib.DEFLATED, zlib.MAX_WBITS | 16)
data += gzip_compress.compress('bar') + gzip_compress.flush()

with open('foobar.bin', 'wb') as file:
    file.write(data)
~~~

[foobar.zip](https://github.com/curl/curl/files/3102425/foobar.zip)

~~~
foo member:
1F 8B 08 00 00 00 00 00 02 0A 4B CB CF 07 00 21 65 73 8C 03 00 00 00

bar member:
1F 8B 08 00 00 00 00 00 02 0A 4B 4A 2C 02 00 AA 8C FF 76 03 00 00 00

concatenated:
1F 8B 08 00 00 00 00 00 02 0A 4B CB CF 07 00 21 65 73 8C 03 00 00 00 1F 8B 08 00 00 00 00 00 02 0A 4B 4A 2C 02 00 AA 8C FF 76 03 00 00 00
~~~

~~~
while true; do cat foobar.bin | nc -4l localhost 8000; done
~~~

They all show `foo` and not `foobar` with the foobar.bin response.

**Comment by dtrembovetski** [comment]
Chrome and Firefox wouldn't happen to use libcurl under for their networking?

Have you tried with something that for sure uses native stacks, Safari/IE?

>  ignore the second member, as do curl versions prior to when the additional validation checks were added.

Could you please clarify this? We've used curl 7.56.1 with this endpoint and it did parse all of the (concatenated) response.

**Comment by jay** [comment]
> Have you tried with something that for sure uses native stacks, Safari/IE?

Yes, IE 11 and Edge in Windows 10 show the same output `foo`. 

> > ignore the second member, as do curl versions prior to when the additional validation checks were added.
> 
> Could you please clarify this? We've used curl 7.56.1 with this endpoint and it did parse all of the (concatenated) response.

It's likely you are receiving a series of compressed blocks within the first stream. The second stream from your data is empty. I am not sure whether or not a second stream is correct (hence this issue) or why it is empty. Maybe it is used as a sentinel but I don't know why. Maybe I am wrong and there is other data that you have that will show multiple gzip streams (members) in a single transfer are all processed by browers and curl but not with the data we have now.

**Comment by monnerat** [comment]
This seems similar to https://github.com/curl/curl/issues/2719: the server is not really conformant.

The real question is: do we want to be sure all server data has been delivered correctly or do we tolerate silent data loss for the sake of request success ?
Personnally, I'm in favor of data integrity, because curl is not a browser but an automated tool (most of the time), thus data loss might very easily be unnoticed.

The are some solutions to this problem:

- Let the caller callback decompress the deviant stream by itself (no additional work on libcurl, maybe just a note in the documentation),
- Implement an option to silently drop data that cannot be understand by curl.
- Implement a callback that returns whether to abort or continue with a new stream (in all cases, this cannot be a universal recoverer). This would require us to extend the module to process more than a single stream, which is already deviant

In order to reduce module complexity, I'm also in favor of dropping code dealing with old zlib versions sooner or later.

**Comment by jay** [comment]
I don't think any of that is necessary based on just the two reported issues. I propose we address this as in #3825 by increasing the limit of ignored trailing characters to 23, which should allow for a concatenated null stream [1].

[1]: What I mean by null stream is a stream with a single compressed block that is empty, which is what we have in this issue: `1F 8B 08 00 00 00 00 00 00 FF 01 00 00 FF FF 00 00 00 00 00 00 00 00`
