### ISSUE TITLE
304 response also creates a zero byte file

### ISSUE THREAD

**Issue by bagder** [curl/curl#382]
Since commit `curl-7_41_0-186-g261a0fe` curl supports creating a zero byte output file on a "successful transfer" that didn't send any data.

This was made to fix the case when we actually request a zero byte file and it works.

Now, libcurl itself also says that the transfer is successful for all HTTP response codes so starting from that fix, curl now for example generates zero byte outputs even when you get a 304 response code with for example a custom header as in `curl --header "If-None-Match: blabla"`.

Meaning: we're back to the unfortunate distinction of a "successful transfer" and when creating that zero byte file is sensible, expected and useful and when not. Clearly we've changed behavior since 7.42.0.

**Comment by bagder** [comment]
This has also bitten people on 404: http://stackoverflow.com/questions/32113082/curl-creates-file-size-zero-if-no-file-is-found

**Comment by kdudka** [comment]
I start to think it was a bad idea to touch the code at all.  I guess the "correct" fix would be not to create the output file if --location or --fail takes effect?

**Comment by kdudka** [comment]
I have been experimenting with this for a while.  What exactly is the issue here?

curl seems to work correctly when ```--location``` or ```--fail``` is used.  If only ```-o/-O``` is used, curl IMO should write the output, no matter what the HTTP response code was.  Did this behavior really change?

**Comment by bagder** [comment]
The problem is the definition of "work correctly". We changed behavior when we started to save zero-byte files, and there are a non-insignificant number of users who have built scripts where they use -o or -O where they expect the files to not have been written if they were zero bytes - since that has been our behavior since basically forever. There's no denying of this. I have received questions/concerns from at least two independent users about this and I'm sure they're not the only ones.

I *suspect* that in most cases they expect "successful" and real file transfers like with -o to actually save zero-byte files but when they use conditional requests or more custom things they've gotten used to curl not storing empty responses.

**Comment by kdudka** [comment]
I still fail to see the motivation for relying on the previous (undocumented) behavior.  As far as I understand the stackoverflow article above, it describes a case where the script worked only because the server sent empty body with a 404 response (which is not a common case really).  They should rather fix their script to use the ```--fail``` option of curl.

**Comment by bagder** [comment]
Time has moved on and we have not gotten a lot of push back on this behavior (nothing at all really), so I've decided to just leave it.

**Comment by jay** [comment]
I think we could do something for this though, like add a feature so that the user can say what's a success rather than test after the fact. For example, curl will write the content of a 302 reply to an outfile if redirects aren't enabled. Take for example:

curl -v --fail -O https://github.com/curl/curl/archive/curl-7_48_0.tar.gz

The server replies 302 and some content with a link to the redirect which is written to curl-7_48_0.tar.gz.

03/24/2016  11:51 AM               122 curl-7_48_0.tar.gz

I've occasionally run into a broken script because of something like this where I assume redirects weren't anticipated, and of course I enabled redirects. However what if there was something broader like

curl --match=200 -v -O https://github.com/curl/curl/archive/curl-7_48_0.tar.gz
curl --match=2xx -v -O https://github.com/curl/curl/archive/curl-7_48_0.tar.gz

**Comment by kdudka** [comment]
This issue was originally about a change in behavior introduced by 261a0fe.  I do not think that the case you are talking about was anyhow affected by the commit in question.  So I would treat it as a separate issue.

Nevertheless, I like your proposal!

**Comment by bagder** [comment]
I'd agree with @kdudka that this is a separate discussion, although related. Maybe the solution is even to have --fail return an error for 3xx unless -L is used?

**Comment by jay** [comment]
> Maybe the solution is even to have --fail return an error for 3xx unless -L is used?

Sounds good, let's discuss at #727
