### ISSUE TITLE
howto disable * Rebuilt URL to* 

### ISSUE THREAD

**Issue by zsdevX** [curl/curl#3901]
I use curl(curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 )and find the strange behivour:

>curl "**http://192.167.1.1/../../../../../../../../../../../../etc/passwd**" -vv
>* **Rebuilt URL to: http://192.167.1.1/etc/passwd**
>*   Trying 192.167.1.1...
>* TCP_NODELAY set
>* Connected to 192.167.1.1 (192.167.1.1) port 80 (#0)
> GET /etc/passwd HTTP/1.1
> Host: 192.167.1.1
> User-Agent: curl/7.54.0
> Accept: */*
> 
>* HTTP 1.0, assume close after body
> HTTP/1.0 404 Not Found
> Server: httpd
> Date: Sun, 19 May 2019 10:07:41 GMT
> Content-Type: text/html
> Connection: close
> 

I wannot to disable it , and send the right url.

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

"The right URL" is already sent by curl, since it normalizes the URL as the specs mandate. You can disable that in the curl tool with `--path-as-is`. As documented!
