### ISSUE TITLE
crash in multi_socket when closing connection doing many parallel transfers

### ISSUE THREAD

**Issue by bagder** [curl/curl#3904]
### I did this

@kunalekawde posted this on [the curl-library mailing list on May 11 2019](https://curl.haxx.se/mail/lib-2019-05/0031.html).

There seems to be a problem if several concurrents transfers are done as streams over a single connection and that connection is closed. In `multi_socket` where it iterates over the transfers done on the same connection, it can end up dereferencing a NULL pointer:

~~~
1. multi_socket() -> does multi_runsingle() where disconnect is detected
and tries to reconnect.
2. singlesocket() does sh_delentr().
3. Curl_llist_remove() does:

  e->ptr  = NULL;
  e->prev = NULL;
  e->next = NULL;
4.  During the next iteration, as prev is set to NULL, it finds data NULL

Please correct if my analysis is wrong.
I tried with following fix:
      /* the socket can be shared by many transfers, iterate */
      for(e = list->head; e; e = e->next) {
        data = (struct Curl_easy *)e->ptr;
        // crash fix - temp
        if (!data)
          continue;
~~~

The discussion on the list stopped. There's currently no proposed proper fix and we don't have a reliable way to reproduce.

**Comment by kunalekawde** [comment]
Apologies for late update, but Im still trying to get proper backtrace. somehow symbols and line numbers are not coming for libcurl. libcurl rpm is composed of library built with following options:
./configure --prefix=$LIBCURL_INSTALL_DIR --enable-debug --enable-curldebug --with-nghttp2=$LIBNGHTTP2_INSTALL_DIR
also tried with:
./configure --prefix=$LIBCURL_INSTALL_DIR --enable-debug --enable-curldebug --disable-shared --with-nghttp2=$LIBNGHTTP2_INSTALL_DIR

BT is like:
Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0x8
Process uptime: not available

Thread 0 (crashed)
0  libBaseFramework.so!Curl_llist_insert_next + 0xa4
    rax = 0x0000000000000000   rdx = 0x0000000005a10150
    rcx = 0x0000000005a10150   rbx = 0x00007ffe2ddcd588
    rsi = 0x0000000000000000   rdi = 0x000000000417ef48
    rbp = 0x00007ffe2ddcabd0   rsp = 0x00007ffe2ddcabd0
     r8 = 0x0000000000000000    r9 = 0x00007f201699c8b0
    r10 = 0x000000000000000a   r11 = 0x0000000000000000
    r12 = 0x0000000000618600   r13 = 0x00007ffe2ddd1360
    r14 = 0x00007ffe2ddcd558   r15 = 0x0000000003195ce0
    rip = 0x00007f2031f3f42d
    Found by: given as instruction pointer in context
1  libBaseFramework.so!singlesocket + 0x26d
    rbx = 0x00007ffe2ddcd588   rbp = 0x00007ffe2ddcac60
    rsp = 0x00007ffe2ddcabe0   r12 = 0x0000000000618600
    r13 = 0x00007ffe2ddd1360   r14 = 0x00007ffe2ddcd558
    r15 = 0x0000000003195ce0   rip = 0x00007f2031ef9a17
    Found by: call frame info
2  libBaseFramework.so!multi_socket + 0x39a
    rbx = 0x00007ffe2ddcd588   rbp = 0x00007ffe2ddcad70
    rsp = 0x00007ffe2ddcac70   r12 = 0x0000000000618600
    r13 = 0x00007ffe2ddd1360   r14 = 0x00007ffe2ddcd558
    r15 = 0x0000000003195ce0   rip = 0x00007f2031efa249
    Found by: call frame info
3  libBaseFramework.so!curl_multi_socket_action + 0x4a
    rbx = 0x00007ffe2ddcd588   rbp = 0x00007ffe2ddcadb0
    rsp = 0x00007ffe2ddcad80   r12 = 0x0000000000618600
    r13 = 0x00007ffe2ddd1360   r14 = 0x00007ffe2ddcd558
    r15 = 0x0000000003195ce0   rip = 0x00007f2031efaaaf
    Found by: call frame info
4  libBaseFramework.so!HttpClientManager::TimerTriggered() [httpClientManager.cc : 284 + 0x5]
    rbx = 0x00007ffe2ddcd588   rbp = 0x00007ffe2ddcb1d0
    rsp = 0x00007ffe2ddcadc0   r12 = 0x0000000000618600
    r13 = 0x00007ffe2ddd1360   r14 = 0x00007ffe2ddcd558
    r15 = 0x0000000003195ce0   rip = 0x00007f2031e8190d
    Found by: call frame info
5  libBaseFramework.so!HttpClientManager::CurlTimerCallback(void*, long, void*) [httpClientManager.cc : 434 + 0x5]
    rbx = 0x00007ffe2ddcd588   rbp = 0x00007ffe2ddcb460
    rsp = 0x00007ffe2ddcb1e0   r12 = 0x0000000000618600
    r13 = 0x00007ffe2ddd1360   r14 = 0x00007ffe2ddcd558
    r15 = 0x0000000003195ce0   rip = 0x00007f2031e75acc
    Found by: call frame info
6  libBaseFramework.so!update_timer + 0x1c1
    rbx = 0x00007ffe2ddcd588   rbp = 0x00007ffe2ddcb490
    rsp = 0x00007ffe2ddcb470   r12 = 0x0000000000618600
    r13 = 0x00007ffe2ddd1360   r14 = 0x00007ffe2ddcd558
    r15 = 0x0000000003195ce0   rip = 0x00007f2031efae6f
    Found by: call frame info
7  libBaseFramework.so!curl_multi_add_handle + 0x2fa
    rbx = 0x00007ffe2ddcd588   rbp = 0x00007ffe2ddcb4c0
    rsp = 0x00007ffe2ddcb4a0   r12 = 0x0000000000618600
    r13 = 0x00007ffe2ddd1360   r14 = 0x00007ffe2ddcd558
    r15 = 0x0000000003195ce0   rip = 0x00007f2031ef5ec0
    Found by: call frame info
8  libBaseFramework.so!HttpClientManager::StartConnection(std::shared_ptr<HttpRequestBase> const&) [httpClientManager.cc : 125 + 0x5]
    rbx = 0x00007ffe2ddcd588   rbp = 0x00007ffe2ddcbeb0
    rsp = 0x00007ffe2ddcb4d0   r12 = 0x0000000000618600
    r13 = 0x00007ffe2ddd1360   r14 = 0x00007ffe2ddcd558
    r15 = 0x0000000003195ce0   rip = 0x00007f2031e7a638
    Found by: call frame info


Also there are no multiple threads updating the list as few crashes seen in forum for this top frame function indicates same.
The scenario is mostly:
1. client initiates multiple streams to server
2. server after some successful responses send GOAWAY(0) for connection and still sends HEADER & DATA before client acknowledges FIN. 
3. I think client is updating socket/list by setting some pointer to NULL and since its part of later execution, it also reads from socket and tries to access the list.
