### ISSUE TITLE
dump-header creates file even if no response is received

### ISSUE THREAD

**Issue by wesinator** [curl/curl#3964]
### I did this
```sh
$ curl -D test_header.txt thissitedoesntexist.com
curl: (6) Could not resolve host: thissitedoesntexist.com
```
Created file test_header.txt

### I expected the following
dump-header file is not created until valid response headers are received.

### curl/libcurl version

```
curl 7.65.0 (x86_64-apple-darwin18.6.0) libcurl/7.65.0 SecureTransport zlib/1.2.11
Release-Date: 2019-05-22
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

### operating system
macOS 10.14

**Comment by bagder** [comment]
This is true and has been so virtually forever. I'm not sure I think this is something we should change.

The upside is that you know for sure when no headers have been delivered by curl, especially if you re-run the command line as then it could otherwise have the previous file contents lying around.

The make-no-file-if-nothing-to-write concept was abandoned for cookies for pretty much this reason, which makes me now lean towards favoring empty-files-for-empty-responses. Like this. Especially since this behavior has been here for a long time so scripts and users have gotten used to and come to rely on this by now.

**Comment by wesinator** [comment]
> This is true and has been so virtually forever. I'm not sure I think this is something we should change.
> 
> The upside is that you know for sure when no headers have been delivered by curl, especially if you re-run the command line as then it could otherwise have the previous file contents lying around.
> 
> The make-no-file-if-nothing-to-write concept was abandoned for cookies for pretty much this reason, which makes me now lean towards favoring empty-files-for-empty-responses. Like this. Especially since this behavior has been here for a long time so scripts and users have gotten used to and come to rely on this by now.

Fair.
My only issue is that when running on multiple sites it creates a discrepancy between the number of files created to number of active sites.
