### ISSUE TITLE
curl --fail --negotiate behavior changed between 7.64.0 and 7.65.0

### ISSUE THREAD

**Issue by nicowilliams** [curl/curl#3992]
Per [#3726](https://github.com/curl/curl/issues/3726#issuecomment-499028091) I am opening a new issue for this.

```
$ curl --fail --negotiate -u: http://localhost:54321/x
```

fails with exit code 22 and no useful messages.  Enabling verbose output also shows nothing telling about what happened.

The issue is that if even the initial `gss_init_sec_context()` call fails, then `conn->data->state.authproblem` gets set to `TRUE`.

Certainly for HTTP/Negotiate (and only HTTP/Negotiate) any failures of followup `gss_init_sec_context()` calls (when the `input_token` is non-empty) should be fatal, but not the initial one.

**Comment by bagder** [comment]
We should up our efforts in adding tests for GSS...

**Comment by nicowilliams** [comment]
@bagder yeah...  Heimdal has a useful tool for testing, `kimpersonate`, that might help that.

**Comment by kdudka** [comment]
I do not think that you need to have a working GSS setup to test this class of bugs.  These bugs  are about changes of behavior in cases where `HTTPAUTH_GSSNEGOTIATE` is enabled but no valid GSS credentials (or even configuration) available.

Before 6c6035532383e300c712e4c1cd9fdd749ed5cf59 there was either no failure at all (because `gss_init_sec_context()` was not called unless the server asked for GSS-based authentication) or the failure of `gss_init_sec_context()` did not result in a failed transfer (because the HTTP request  succeeded without any authentication in the end).

**Comment by kdudka** [comment]
It is not only `--fail` what is broken.  If `HTTPAUTH_GSSNEGOTIATE` is used for a POST request and `gss_init_sec_context()` fails, the POST request is now sent with empty body.  I am experimenting with the following patch:
```
--- a/lib/http_negotiate.c
+++ b/lib/http_negotiate.c
@@ -151,7 +151,7 @@ CURLcode Curl_output_negotiate(struct connectdata *conn, bool proxy)
       if(result == CURLE_LOGIN_DENIED) {
         /* negotiate auth failed, let's continue unauthenticated to stay
          * compatible with the behavior before curl-7_64_0-158-g6c6035532 */
-        conn->data->state.authproblem = TRUE;
+        authp->done = TRUE;
         return CURLE_OK;
       }
       else if(result)
```
... and will open a pull request once I have some test-coverage for it...
