### ISSUE TITLE
Maximum value of «Time Spent» in Cmd-window is «0:35:47» (35 min and 47 sec).

### ISSUE THREAD

**Issue by 7-904-001-67-28** [curl/curl#4165]
In last cURL for Windows (https://curl.haxx.se/windows/) 
![Time spent](https://user-images.githubusercontent.com/53446248/62071597-97c0e700-b245-11e9-83d5-cd19a431791e.png)

maximum value of «Time Spent» in Cmd-window is «0:35:47» (35 min and 47 sec). At this point the timer is stopping and other dependent values (average speed, etc) are ruined.

Sorry, I do not speak English, I can not understand ALL from this point to end of field.

### curl/libcurl version

[curl -V output]

**Comment by bagder** [comment]
That's 2147 seconds or 2147,000 milliseconds or 2147,000,000 microseconds.

2^31 is 2147,483,648. Seems like it isn't a coincidence. Are we using a 32 bit counter (on Windows) somewhere somehow where we shouldn't?

**Comment by 7-904-001-67-28** [comment]
Thank you for 2^31 – it is great reason.

**Comment by bagder** [comment]
The problem is here. `timediff_t` is made an `int` for systems where `time_t` is only 32 bit, but it seems a bit too naive. We should make it attempt to use a 64 bit variable for that so that it better can hold microseconds beyond 35 minutes.

https://github.com/curl/curl/blob/d23e87d551d2d99201d7eb275029b6f0660f5136/lib/timeval.c#L205-L212

**Comment by 7-904-001-67-28** [comment]
Thank you!
