### ISSUE TITLE
Ftp file upload on windows XP SP2 in 100M half is very slow

### ISSUE THREAD

**Issue by whrtqa** [curl/curl#4194]
### I did this
curl -T testfile ftp://192.168.1.1

### I expected the following
very slow
![curl ftp](https://user-images.githubusercontent.com/50225221/62518354-f563bd80-b85b-11e9-8908-9e6006da8cb0.png)

### curl/libcurl version
7.65.1

[curl -V output]

### operating system
windows XP SP2
but it works in Gigabit Ethernet very well.
(other system like windows 7 it works very well)
this bug only hapen on windows xp sp2 with  100M half net work .

**Comment by bagder** [comment]
Possibly related code, but I can't understand why a 100Mbit network would do worse than a gigabit one: https://github.com/curl/curl/blob/cee7639b790f29113759f69c4a955c2ead8bff31/lib/connect.c#L953-L995

**Comment by whrtqa** [comment]
Thanks bagder.
download file from ftp server it do very well.
![curftpd](https://user-images.githubusercontent.com/50225221/62527247-5942b200-b86d-11e9-9e7f-569690db0589.png)

**Comment by bagder** [comment]
Since this problem seems specific to Windows XP and not too many people even have those installed anymore, even less so also being curl developers, I suspect that you need to experiment a bit yourself to figure out what you can do to enhance the upload speed.

*Perhaps* it changes things a bit if curl would set the [CURLOPT_UPLOAD_BUFFERSIZE](https://curl.haxx.se/libcurl/c/CURLOPT_UPLOAD_BUFFERSIZE.html) option to something suitably large.

**Comment by whrtqa** [comment]
@bagder 
Thank you very much!!!
I set the  CURLOPT_UPLOAD_BUFFERSIZE  to 1024*512,it work,very well.
Thank you !!!
