### ISSUE TITLE
Loosing connection on iOS hangs request

### ISSUE THREAD

**Issue by lietusme** [curl/curl#4239]
This is continuation to old email thread that was not resolved:
https://curl.haxx.se/mail/lib-2015-11/0060.html

Steps:
1. Execute HTTPS request - gets response and finishes with CURLE_OK. 
2. Turn off WiFi (or loose connection other way) 
3. **Execute HTTPS request - completes only after set timeout with CURLE_OPERATION_TIMEDOUT. This is problematic as timeout could be set to few minutes and appears as hanged operation to user.**
4. Execute HTTPS request - completes instantly with CURLE_COULDNT_RESOLVE_HOST as expected. This is true for all subsequent requests.

Built C++ libCURL into iOS application, using multi/easy interfaces.
Reproduced on iOS 9.x-12.x
libcurl/7.65.3 SecureTransport zlib/1.2.11

**Comment by bagder** [comment]
Which of these do you consider to be an issue and why?

**Comment by lietusme** [comment]
Sorry, did not point out - hanging == timeout. Will change description.

Especially that after first request timeouts (it could be set to seconds to few minutes), it starts returning immediately.

**Comment by bagder** [comment]
In this situation, it is simply the OS being slow. curl asks the TCP stack to connect to a given IP address (possibly using a cached DNS entry) and if the stack doesn't return an error curl will let it keep trying until it reaches the timeout. It works more or less identically on for all platforms and I'm not aware of any extra magic that can be used to improve this for iOS. (I also don't have anything that allows me to particular debug or test this on iOS.)

Does this reproduce if you write a small example and run on other platforms. What's the difference between 3 and 4, is it just longer time since the wifi disconnect or is it a reused handle from step 1 that is used for 3 as well? Does it happen the same way if you don't reuse easy handles? (that would also make it not use a cache DNS entry and could then potentially trigger a different code route)

**Comment by bagder** [comment]
Long time with no response. Closing.
