### ISSUE TITLE
missing HTTP2 build support in the winbuild NMake Makefiles

### ISSUE THREAD

**Issue by BrisingrAerowing** [curl/curl#431]
Would it be possible to add support for HTTP2/NgHTTP2 to the Windows makefiles? NgHTTP2 has MSVC build scripts for the main library, and I would like to be able to build cURL with that.

**Comment by jay** [comment]
Is it supported to build nghttp2 with msvc? I've been building it using mingw32 and then making a lib file using lib.exe. I have an [integration script](https://gist.github.com/jay/431854a56e0079203f28) that I use to integrate the settings needed to enable HTTP2 in the Visual Studio project files (the ones in projects/Windows/VC10+). Warning: I had mothballed it for release since we're eventually going to use templates, so it's probably a little rough around the edges.

I can look into adding the settings to the makefile in the winbuild directory if nghttp2 msvc is supported by them, but I don't see any documentation on it.

cc @tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
We have [Makefile.msvc](https://github.com/tatsuhiro-t/nghttp2/blob/master/lib/Makefile.msvc) by contributed by users to build libnghttp2 with MSVC.  It calls configure, so it will need unix like environment like cygwin.
Note that it only builds libnghttp2; anything in src or examples directory are not built.

**Comment by tatsuhiro-t** [comment]
Yeah, documentation is missing, mostly because I'm lack of cygwin environment in my build box.

**Comment by gvanem** [comment]
> We have Makefile.msvc by contributed by users to build libnghttp2 with MSVC. 

I once wrote that, but is terribly out-dated now.

> It calls configure, so it will need unix like environment like cygwin.

I doesn't *calls configure*. The `Makefile.MSVC` only extracts the version info from that file.

**Comment by tatsuhiro-t** [comment]
Yes, you are correct.  configure is not called.
The last update of Makefile.msvc is 5 Jul, 2015.  Is that still out-dated?

**Comment by jay** [comment]
I don't see this documented in recently released nghttp2 v1.4.0. We can revisit this when documented support for msvc is added, or if you have decided the names already for certain you can give me this info:
the static lib release filename
the static lib debug filename
the dll lib release filename
the dll lib debug filename
These are lib filenames usually without without an api version like nghttp2.lib for example.

**Comment by tatsuhiro-t** [comment]
Current library names defined in Makefile.msvc are:
* nghttp2-static.lib
* nghttp2d-static.lib
* nghttp2.dll
* nghttp2d.dll

I have some difficulty to run this Makefile.msvc on my dev machine, since we don't have msvc and necessary things. I can usually make windows dll/libs with mingw64 cross compiler on Debian box.

I have very small knowledge about windows dll stuff, so I may be missing something.

**Comment by MoSal** [comment]
Note that linking against `libnghttp2.a` built mingw-w64 wouldn't work without defining NGHTTP2_STATICLIB along the dependency chain, as reported in tatsuhiro-t/nghttp2#404.

**Comment by tatsuhiro-t** [comment]
Yes, -DNGHTTP2_STATICLIB is required when compiling application.
I remember that c-ares has the similar behaviour.

**Comment by BrisingrAerowing** [comment]
I kinda hacked the nmake makefile in cURL to link to NGHttp2 (and LibMetalink, which I ported to MSVC rather easily, as well as librtmp, which required no patching whatsoever) with the required libraries and include files. My tests were on v 7.44.0, and I haven't built the latest version yet. 

On a side note, NMake is ever-so-slightly saner that GNU Make, which drives me crazy. NMake mostly doesn't, other than it's inability to use nested variables.

**Comment by jay** [comment]
@BrisingrAerowing Can you give me the directions you used to build nghttp2 with msvc and then to build curl with msvc using the modified makefile, and can you post the modified makefile here at some point? Even if it's not production quality I can use it for reference. Thanks

**Comment by bagder** [comment]
No response in months, this is dead.

**Comment by patrikhson** [comment]
Hey,

I just want to tell you how much I appreciate your help, and therefore I want to share some great stuff with you, just take a  look here <http://tephosacha.christinegeary.com/xyolbu>

In haste, paf@frobbit.se
