### ISSUE TITLE
Update Windows install notes for build options

### ISSUE THREAD

**Issue by SLDiggie** [curl/curl#4545]
There are notes for building for Windows in a couple of places:

https://curl.haxx.se/docs/install.html
/docs/INSTALL.md

Each place lists what I think may be an incomplete set of definitions for customizing the build. Trawling through a few headers, it looks like a more complete list of options (for non-special cases) might be something like this:

HTTP_ONLY
CURL_DISABLE_FTP
CURL_DISABLE_LDAP
CURL_DISABLE_LDAPS
CURL_DISABLE_TELNET
CURL_DISABLE_DICT
CURL_DISABLE_FILE
CURL_DISABLE_TFTP
CURL_DISABLE_HTTP
CURL_DISABLE_RTSP
CURL_DISABLE_POP3
CURL_DISABLE_IMAP
CURL_DISABLE_SMTP
CURL_DISABLE_GOPHER
CURL_DISABLE_SMB
CURL_DISABLE_NTLM
CURL_DISABLE_VERBOSE_STRINGS
CURL_DISABLE_COOKIES

It would be nice to have at least the two aforementioned docs updated with supported options.

**Comment by bagder** [comment]
There are even more `CURL_DISABLE_*` defines that can be set to disable specific parts of curl when building. They all have their own configure options. I wouldn't mind having somewhere to document what they're used for and we could then also generate the list or have a test case verify that the list contains all the used DISABLE defines. But maybe that place isn't in the Windows build section in INSTALL.md since these are not really Windows-specific...
