### ISSUE TITLE
verify_certificate issue for WINCE

### ISSUE THREAD

**Issue by 0310gupta** [curl/curl#4620]
### I did this
Inside verify_certificate function passing CERT_CHAIN_REVOCATION_CHECK_CHAIN to CertGetCertificateChain, is leading to SSL failure. Earlier in 7.32.0 version the flag was set to 0. Changing this flag to 0 back, made things work again.
### I expected the following
Why this is changed, and making it back to 0, will result in breaking the security?
### curl/libcurl version

[curl -V output]

### operating system
WINCE

**Comment by jay** [comment]
What version of curl?

**Comment by 0310gupta** [comment]
> What version of curl?

7.50.1

**Comment by jay** [comment]
Certificate revocation check has been enabled by default for Windows CE with native OS SSL since curl 7.44. You can disable it in libcurl by using curl_easy_setopt(curl, [CURLOPT_SSL_OPTIONS](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_OPTIONS.html), CURLSSLOPT_NO_REVOKE); and in the curl tool by using [--ssl-no-revoke](https://curl.haxx.se/docs/manpage.html#--ssl-no-revoke). Disabling the revocation check will not "break" security but it lessens it. How much is a matter of debate. I think it is important. curl has other SSL backends where it is not enabled.

Is the error from one server or all servers? Do you get a revocation error connecting to https://www.microsoft.com?

**Comment by 0310gupta** [comment]
> Certificate revocation check has been enabled by default for Windows CE with native OS SSL since curl 7.44. You can disable it in libcurl by using curl_easy_setopt(curl, [CURLOPT_SSL_OPTIONS](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_OPTIONS.html), CURLSSLOPT_NO_REVOKE); and in the curl tool by using [--ssl-no-revoke](https://curl.haxx.se/docs/manpage.html#--ssl-no-revoke). Disabling the revocation check will not "break" security but it lessens it. How much is a matter of debate. I think it is important. curl has other SSL backends where it is not enabled.
> 
> Is the error from one server or all servers? Do you get a revocation error connecting to https://www.microsoft.com?

Does that mean this revoking option was not there in earlier version of curl before 7.44, or its not enabled by default only?

**Comment by jay** [comment]
> Does that mean this revoking option was not there in earlier version of curl before 7.44

Prior to 7.44 revocation checking was enabled by default for all versions of Windows except Windows CE. In curl 7.44 revocation checking was enabled by default for Windows CE, and an option was added that can be used to disable it.

**Comment by jay** [comment]
No evidence of a bug here. I don't use Windows CE and I don't think anyone currently collaborating on the project does either, so I don't know for sure but we did it according to the documentation so it should work properly.
