### ISSUE TITLE
Serious bug with CURL with PHP

### ISSUE THREAD

**Issue by batata004** [curl/curl#4622]
Hi,

I have found a very serious and easy to reproduce bug happening with CURL on latest PHP 7.2.X (which is 7.2.24).

Just run the code below on your server running PHP+APACHE+MARIADB:

```
<?php

$curl = curl_init();

$opts = array();

$opts[CURLOPT_URL] = "https://www.sitepor500.com.br";

curl_setopt_array($curl,$opts);

echo curl_exec($curl);

?>
```

It will work just fine, I mean, you will see the contents of the page on `CURLOPT_URL`. Now JUST ADD one single line of code to it and the bug will happen:

```
<?php

$conn = mysqli_connect("localhost","root","your_password");

$curl = curl_init();

$opts = array();

$opts[CURLOPT_URL] = "https://www.sitepor500.com.br";

curl_setopt_array($curl,$opts);

echo curl_exec($curl);

?>
```

Incredibly, just adding a connection to a local database will make CURL fetch the content of the URL specified at `CURLOPT_URL` as "" (empty string). This happens with any URL.

**Comment by bagder** [comment]
That sounds like a problem with CURL/PHP and not with libcurl itself. That module is maintained and cared for by the PHP team themselves so you should really file this issue to the PHP team to get their view and take on it. Not to us. Judging by your description, something within PHP makes it send the wrong URL to libcurl to work on.

**Comment by batata004** [comment]
Do you know where do I file it? I cant find the link.

**Comment by bagder** [comment]
https://bugs.php.net/how-to-report.php I believe explains it

**Comment by batata004** [comment]
Excelent I just did it at https://bugs.php.net/bug.php?id=78845

But I still think CURL team should take a lookt at it cause something inside CURL is preventing the external connection to be opened when there is a databasse connection active (this only happens on the cited PHP version)

**Comment by bagder** [comment]
To you "CURL" may look like a single unit. To us, it is not.

The "CURL" you speak of that you access and use from PHP is a "binding". That's a layer of code written by the PHP team (which is why I like to call it CURL/PHP) that by itself uses libcurl (the product and code we manage in this project). So,  it is two different "layers" done by two different teams.

Given your description, I see no proof that this is a problem in our "layer" as libcurl wouldn't have any clue about any database connection and that can in fact not affect the URL libcurl has been told to use. It rather sounds like libcurl gets told about a bad or wrong URL by the CURL binding.

**Comment by batata004** [comment]
Great explanation! I just hope other people here can test this bug and try it (despite not being responsable for this bug as you clearly explained) cause I thing the PHP community may take a while to look at it. Other time I reported a bug it took 3 weeks for a response!

**Comment by bagder** [comment]
We don't know PHP and we're not suitable to debug or work on this issue so I really don't think you should expect that from us.
