### ISSUE TITLE
例子代码错误

### ISSUE THREAD

**Issue by kouzhudong** [curl/curl#4751]
在http-post.c中curl_global_cleanup();的调用在if之外。
在postinmemory.c中curl_global_cleanup();的调用在if之内。

代码矛盾，肯定有一个是错的。

在下认为postinmemory.c中curl_global_cleanup();的调用是错误的。

**Comment by jay** [comment]
In the future please make your report in English. I will attempt to translate. http-post example has curl_global_cleanup in a different position than postinmemory example. You think postinmemory example is wrong.

I agree because in postinmemory example curl_global_cleanup would not be called if curl_easy_init fails. I have made the change. Thanks.
