### ISSUE TITLE
SCP/SFTP protocols support broken in Windows binaries using default compilation flags.

### ISSUE THREAD

**Issue by fxmauricard** [curl/curl#4848]
Up to version 7.57, default binaries included libssh2 at compilation and adds scp and sftp protocols support.

Since version 7.58, it's not the case. It seems that adding libssh support for handling scp and sftp protocols broke the default compilation behavior and neither include libssh nor libssh2 for Windows binaries.

See this commit : https://github.com/curl/curl/commit/c92d2e14cfb0db662f958effd2ac86f995cf1b5a

**Comment by bagder** [comment]
Which Windows build? I mean, using with method?

**Comment by fxmauricard** [comment]
To be clear, I thought that the "official" Windows binarie for cURL was broken. But by double checking and re-downloads if from https://curl.haxx.se/download.html, that one are OK.

I saw this behavior using Git for Windows. The included curl binary is broken since the usage of cURL 7.58. Git for Windows sources from MSYS2 MinGW packages. The official MSYS2 builds seems OK too. I've open an issues at Git for Windows initially : https://github.com/git-for-windows/git/issues/2491

But if you look at the commit linked in my first comment, it seems that up to 7.57 there was a 
**--without-libssh2** parameter that disabled libssh2 at compilation. (see _configure.ac_ file)

Since 7.58 there is two parameters : **--with-libssh** and **-with-libssh2**.

I think that starting the 7.58, if nothing is set, by default there's no ssh support and before 7.57 version by default libssh2 was used.

**Comment by bagder** [comment]
I don't really consider this a bug.

Right, since back when libssh support was merged, the configure script no longer defaults to libssh2 but you have to explicitly select which of the two SSH libraries you want.

We don't advertise or even strive to maintain "configure compatibility" over versions but it might change between versions, as it did back there.

I wouldn't mind if someone extended the configure script to check for these libs by default in a documented order, but I don't consider it a big problem that you need to specify what you want so it's not priority for me personally. After all, the summary at the end of the configure run is meant to display to the users exactly what is included and enabled in the build and if libssh2 isn't in there, it should function as a clue that it needs some attention!

Starting in 7.69.0 (the pending release), there's even going to be a third SSH library to select from (wolfSSH).

**Comment by fxmauricard** [comment]
I've fixed the issue on the Git for Windows / MSYS2 side by amending the compilation flags in their project.

So the issue can now be closed.
