### ISSUE TITLE
Schannel: TLS 1.3 is not yet supported

### ISSUE THREAD

**Issue by thegulshankumar** [curl/curl#4918]
I found a related topic was closed.

`curl -I https://example.com`

Perhaps duplicate of curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.

OS: Windows 10

```
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
```

```
curl -I --tlsv1.3 https://example.com
curl: (35) Schannel: TLS 1.3 is not yet supported
```

**Comment by bagder** [comment]
What is the issue here? The fact that Schannel doesn't support TLS 1.3 is not something *we* can fix afaik. You better ask Microsoft for that or build a curl version with a TLS library that supports 1.3!

**Comment by jay** [comment]
> I found a related topic was closed.

Link please

> curl -I --tlsv1.3 https://example.com
> curl: (35) Schannel: TLS 1.3 is not yet supported

Yes, that's right:

https://github.com/curl/curl/blob/2cfac302fbeec68f1727cba3d1705e16f02220ad/lib/vtls/schannel.c#L181-L202

There is a SP_PROT_TLS1_3_CLIENT floating around on the internet but it's [undocumented](https://docs.microsoft.com/en-us/windows/win32/api/schannel/ns-schannel-schannel_cred#SP_PROT_TLS1_2_SERVER). I tried changing ssl_version_max to `CURL_SSLVERSION_MAX_TLSv1_3` and grbitEnabledProtocols to `SP_PROT_TLS1_3_CLIENT` (0x00002000) and ran it in Windows 10 1903 (October 2019) but there was an error: "SEC_E_ALGORITHM_MISMATCH (0x80090331) - The client and server cannot communicate, because they do not possess a common algorith". (It's a little truncated at the end because the error buffer isn't big enough.) Until it is documented how to do TLS 1.3 in schannel I don't think we will be attempting it.

> You better ask Microsoft for that or build a curl version with a TLS library that supports 1.3!

It's coming just [not yet](https://social.msdn.microsoft.com/Forums/en-US/440ef859-fc8d-4c48-a6b5-7ad0d410426e/is-schannel-supported-tls-13-for-development?forum=windowssecurity).

**Comment by thegulshankumar** [comment]
I thought this one is related https://github.com/curl/curl/issues/3505

**Comment by jay** [comment]
> I thought this one is related #3505

no, unrelated
