### ISSUE TITLE
(curl version 7.68) "make install" does not work properly on Ubuntu 18.x

### ISSUE THREAD

**Issue by googled** [curl/curl#4931]
# I did this

cd /tmp
wget https://curl.haxx.se/download/curl-7.68.0.tar.gz
tar zxvf curl-7.68.0.tar.gz
cd curl-7.68.0
./configure
make
make install
curl -V
```
curl: symbol lookup error: curl: undefined symbol: curl_multi_poll
```

### I expected the following

curl -V
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1 zlib/1.2.11
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

### This works though
cd /tmp/curl-7.68.0/src
./curl -V
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1 zlib/1.2.11
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

### curl/libcurl version

curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1 zlib/1.2.11
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

### operating system

Linux Prod 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
make install puts curl at /usr/local/ by default, libraries, binaries and
everything. But, it sounds like /usr/local/lib isn't in your /etc/ld.so.conf
file so the system dynamic linker can't find it. So, if /usr/local/bin is in
your PATH, then typing "curl -V" will use the new curl binary with the old
libcurl.so.4 library, which isn't compatible. You need to fix your system
configuration if you really want it to work this way. But, you may not
necessarily want to because it will cause all older existing binaries to use
the newer libcurl, and while it will probably work, there might be some subtle
incompatibilities.

**Comment by googled** [comment]
For the moment, until ubuntu updates it in their package manager I use this hack:


### Hacking curl

Moved the **curl-7.68.0** directory to /opt then:

```
ln -sf /usr/local/bin/curl /opt/curl-7.68.0/src/curl
```

now **curl -V** works as expected.

It doesn't affect the older binaries as you point out but I was wondering if you had a better fix :)

Best

**Comment by bagder** [comment]
This is not a curl bug so I will close this issue. "man ld.so" and "man ldconfig" on a linux machine will describe how to change the path and config things to make your system use libcurl from /usr/local/lib.
