### ISSUE TITLE
unresolved external symbols during linking

### ISSUE THREAD

**Issue by jzer0** [curl/curl#4965]
### I did this
Compiled using the following command from the VC x64 Native Tools command prompt:

nmake /f Makefile.vc RTLIBCFG=static mode=static WITH_SSL=static WITH_ZLIB=static DEBUG=yes GEN_PDB=yes WITH_DEVEL=C:\git\curl\deps SSL_PATH=I:\lws_integration_prep\3rdParty\openssl\1.1.1d\PC\x64\Debug ZLIB_PATH=I:\lws_integration_prep\3rdParty\ZLib\v1.2.11\PC\x64\Debug MACHINE=x64

Compiles successfully

I have also added the following configuration aspects to the project including libcurl:

- added include, library paths and libraries (libcurl and windows .lib dependencies)
- added /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:MSVCRTD  to linker command line options
- added CURL_STATICLIB to the C/C++ preprocessor definitions

### I expected the following
Inclusion of Release builds are fine.  When attempting to build with Debug curl libs results in the following errors:

1>libcurl_a_debug.lib(cookie.obj) : error LNK2019: unresolved external symbol __imp_unlink referenced in function cookie_output
1>OLDNAMES.lib(unlink.obi) : error LNK2001: unresolved external symbol __imp_unlink
1>libcurl_a_debug.lib(mime.obj) : error LNK2019: unresolved external symbol __imp_access referenced in function curl_mime_filedata
1>OLDNAMES.lib(access.obi) : error LNK2001: unresolved external symbol __imp_access
1>libcurl_a_debug.lib(smb.obj) : error LNK2019: unresolved external symbol __imp__getpid referenced in function smb_format_message
1>OLDNAMES.lib(access.obi) : error LNK2001: unresolved external symbol __imp__access
1>I:\SMS\justinh_Workspace\mobile\trunk\Hydra\Builds\PC\Hydra.PC.x64.Dbg.exe : fatal error LNK1120: 4 unresolved externals

### curl/libcurl version
[curl -V output]
7.69.0 - built from master branch
### operating system
Windows 10 x64

**Comment by jay** [comment]
To be clear you're not having problems building curl but rather building your own application and linking, is that right?

> RTLIBCFG=static

RTLIBCFG is not a very commonly used curl build option and can lead to linking problems when multiple CRTs conflict. static basically means the [static version](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019) of the C runtime (/MT;/MTd), it doesn't mean build libcurl as a static library.

**Comment by jzer0** [comment]
I added this parameter following recommendations on resolving these undefined reference errors.  I am using mode=static so I am expecting static libs to be built.

**Comment by jay** [comment]
This sounds like an issue with the way you configured your project, not with the static library built by curl. I am able to build an application and link to libcurl when it is built as both static and runtime library static. The important thing is I made sure the C runtime matched and did not use NODEFAULTLIB. It may be possible to do it that way but we can't provide support for it. Generally when you built libcurl static its on you to add the dependencies. Visual Studio makes it easy because it includes most of the default dependencies.

For example below I use /MTd which is CRT static multithreaded debug (ie you set RTLIBCFG=static). If you didn't set RTLIBCFG you'd use /MDd which is CRT dll multithreaded.
~~~
[x:\j\curl\curl\builds\libcurl-vc10-x86-debug-static-ipv6-sspi-winssl\bin]
> cl /MTd /DCURL_STATICLIB /I..\include X:\j\curl\curl\docs\examples\simple.c /link /LIBPATH:..\lib libcurl_a_debug.lib ws2_32.lib crypt32.lib advapi32.lib wldap32.lib
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

simple.c
Microsoft (R) Incremental Linker Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:simple.exe
/LIBPATH:..\lib
libcurl_a_debug.lib
ws2_32.lib
crypt32.lib
advapi32.lib
wldap32.lib
simple.obj
~~~

**Comment by jzer0** [comment]
Hi, not sure what exactly did it, but this seems to be resolved.  Had to reconstruct my workspace due to a partition table corruption, the reason for the delay in my reply.  Also removed /NODEFAULTLIB:MSVCRTD, so possibly this was causing the issue but can't be certain.  Anyway, closing as this is now resolved.  Thanks for your assistance!
