### ISSUE TITLE
Command line arguments don't behave as expected on Windows

### ISSUE THREAD

**Issue by bagder** [curl/curl#4988]
### I did this

Appveyor builds have failures [like this](https://ci.appveyor.com/project/curlorg/curl/builds/31096689/job/tt048by7xg2jruyf#L4028)

Although related to #731, #3747 and partly #345, commit 4c140a56283703 and the fixes for #4892 by @captain-caveman2k have highlighted this again.

### I expected the following

No Appveyor problems

### curl/libcurl version

git master

### operating system

Windows

**Comment by captain-caveman2k** [comment]
I believe this is a problem with the test suite and UTF-8 characters as it looks like the output fails comparison as the expected characters are replaced with diamonds.

Please tell me if it isn't.

I have the following UTF-8 pre-check in the test cases but I guess that doesn't cause the tests to exit on Windows as we would like?

````
perl -MI18N::Langinfo=langinfo,CODESET -e 'die "Needs a UTF-8 locale" if (lc(langinfo(CODESET())) ne "utf-8");'
````

We could either:

1. Disable these tests temporarily.

2. Add a `win32` feature - modify `runtests.pl` at line 2715 to have `has_win32 = 1` which would then get added to the features list. These tests would then have `!win32` in the `<features>` section.

3. Add support for server side features with UTF-8 in this case and modify `runtests.pl` to check for UTF-8 support.

**Comment by bagder** [comment]
The "diamonds" in the layout is what we see in our browsers. If you download the log you can see exactly what bytes that ends up there and as they're not the expected sequence runtests.pl barfs on it.

The expected (test 955):
~~~
00031150: 202d 4d41 494c 2046 524f 4d3a 3c41 7673   -MAIL FROM:<Avs
00031160: c3a4 6e64 6172 656e 4065 7861 6d70 6c65  ..ndaren@example
00031170: 2e63 6f6d 3e5b 4352 5d5b 4c46 5d0d 0a5b  .com>[CR][LF]..[
~~~

What it got:
~~~
00031190: 4652 4f4d 3a3c 4176 73ef bfbd 6e64 6172  FROM:<Avs...ndar
000311a0: 656e 4065 7861 6d70 6c65 2e63 6f6d 3e5b  en@example.com>[
000311b0: 4352 5d5b 4c46 5d0d 0a5b 3030 3a30 393a  CR][LF]..
~~~

ef bf bd instead of c3 a4.

While I'm fine with (1) or (2) here, doesn't both of those just hide the actual problem?

**Comment by captain-caveman2k** [comment]
> While I'm fine with (1) or (2) here, doesn't both of those just hide the actual problem?

Yeah - it does. 2 is a little nicer as it allows the tests to continue on our non-windows based CI platforms so I will come up with a quick fix based on that.

My understanding is `ä` should be c4 a4 so I am at a loss as to what ef bf bd is :( I thought it might be Latin-1 to begin with but looking at various converters online I cannot find any correlation.

**Comment by jay** [comment]
> ef bf bd

It's the replacement character when the character can't be translated, it's a diamond with the question mark ����. It means there was some problem with conversion. For example you may recall how Win32 API Unicode to ANSI conversions may use straight question marks ???? instead of failing when the codepage didn't support the character. Beats me why it's showing that though.

**Comment by captain-caveman2k** [comment]
After a fair amount of investigation...

**Notes:**
 
**Given that I can't run the tests natively under Windows I had to resort to outputting debug information and running curl either from the command line or through Visual Studio:**

**For comparison and simplicity I used the same email address as I had used in test 955.**

- First of all I started by outputting what address we are sending in Curl_pp_send() in both text and hex forms.
````
* Text: Avsändaren
* Hex: 41 76 73 **e4** 6e 64 61 72 65 6e
````
The good news is the Windows console can display the `ä` character (I'm running v10.0.18363 on my main development machine).

Here we only have one byte, rather than the two (as we would like) or three (as we have seen in the test runs). Whilst `U+00e4` is the official Unicode character it seems that `e4` is an ANSI conversion of it [1].

- I then looked at changing my code page using `chcp` [2] to see how that might effect running curl from the command line. My default code page is 850 (Latin-1), so I changed it to 437 (US extended ASCII), 852 (Latin-2), 1252 (Latin-1 similar to 850), 1250 (Latin-2 similar to 852) and 65001 (UTF-8) and each time I re-ran curl from the command line afterwards. The same results were seen.

- It seems, as others have found [4], that when a console application is compiled with `char` (ANSI) support rather `wchar_t` (Unicode) support that arguments are simply passed to the application as pure ANSI rather than UTF-8.

- I then went on to see if I could perform some simple conversion using the current arguments rather than try and utilise `GetCommandLineW()` [5] as [4] had suggested.

- In `tool_getparam.c' I tried:
1. converting the `nextarg` parameter for mail-rcpt to a `wchar_t' using `MultiByteToWideChar()` using the existing code page from `GetACP()` [6]; and then
2. converting it back to UTF-8 using 'WideCharToMultiByte()' with the following result

````
* Text: AvsÃ¤ndaren
* Hex: 41 76 73 c3 a4 6e 64 61 72 65 6e
````

This seems a little long winded (as I'm not aware of a function to convert directly from ANSI to MultiByte - but then I don't have a huge amount of experience in this area). See prototype code [8].

So I guess the questions I have are (My opinions are quoted underneath each question):

- Do we do this kind of conversion in the SNMP code

>cc2k: I would rather not as our libcurl API is UTF-8 and I think any conversion to UTF-8 should be in the tool**

- If we put this in the tool do we perform it only for the SNMP and custom command arguments?

>cc2k: Are there other commands it could/does effect on Windows?**

- Is a more generic approach possible?

>cc2k: I think we can get the command line in wide format (on ANSI builds) and leave the existing `getparameter()` function alone. I think this could be done our main function before we call `operation()` using `CommandLineToArgvW()` [7]

- Are the any consequences of doing this generically?

>cc2k: I don't know

**References:**

[1] http://ascii-table.com/ansi-codes.php
[2] https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chcp
[3] https://en.wikipedia.org/wiki/Windows_code_page
[4] https://stackoverflow.com/questions/44465412/what-is-the-windows-command-line-parameter-encoding
[5] https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinew
[6] https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getacp
[7] https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw
[8] Prototype code:

````
        int acp = GetACP();
        int wc_len = MultiByteToWideChar(acp, MB_ERR_INVALID_CHARS, nextarg,
                                         -1, NULL, 0);
        if(wc_len > 0) {
          wchar_t *wc_arg = (wchar_t*) malloc(wc_len);
          if(!wc_arg)
            return PARAM_NO_MEM;

          if(MultiByteToWideChar(acp, MB_ERR_INVALID_CHARS, nextarg, -1,
                                 wc_arg, wc_len)) {

            int utf8_len = WideCharToMultiByte(CP_UTF8, 0, wc_arg, -1, NULL, 0,
                                           NULL, NULL);
            if(utf8_len > 0) {
              char *oldarg;
              char *utf8_arg = malloc(utf8_len);
              if(!utf8_arg) {
                free(wc_arg);

                return PARAM_NO_MEM;
              }

              if(!WideCharToMultiByte(CP_UTF8, 0, wc_arg, -1, utf8_arg,
                                      utf8_len, NULL, NULL)) {
                free(utf8_arg);
                free(wc_arg);

                return PARAM_NO_MEM;
              }

              nextarg = utf8_arg;
            }
          }

          free(wc_arg);
        }
````

**Comment by bagder** [comment]
What a mess.

1. I agree that added charset conversions (if any) should rather be in the tool than in the library - but if that's required, we must document that our APIs require UTF-8 for non-ascii characters
2. We don't specifically specify UTF-8 for the URL string and yet we handle IDN host names there even on Windows. Is that by pure chance or how is the URL different than these other strings?

**Comment by captain-caveman2k** [comment]
> 2. We don't specifically specify UTF-8 for the URL string and yet we handle IDN host names there even on Windows. Is that by pure chance or how is the URL different than these other strings?

But that host name has to come into the curl tool as an 8-bit character doesn't it?

...so, my understanding at least is, if a user passes a URL on the curl tool on Windows that contains a character that is supported by their code page but doesn't have a direct ANSI counterpart it won't get through to the IDN conversion routine correctly.

If it does have an ANSI counterpart then it will get through to the routine and will be converted into ACE correctly - as seen in my other SNMP test (>= test962). For example:
````
sender@åäö.se becomes sender@xn--4cab6c.se
````

I've just had a quick scan of the tests, and I can't see any, but do we have some test that have non-Latin characters in?

Using a made up Chinese domain name (The host is "example" translated into simplified Chinese and the TLD is taken from [1]) of 例子.公司

and running that through my currently Proof of Concept curl tool in the Visual Studio debugger I get the following string outputs:

````
ANSI argv "Avsändaren@??.??"
Wide argv: L"Avsändaren@例子.公司"
UTF8 argv: "AvsÃ¤ndaren@ä¾‹å­.å…¬å¸"
````

As such, I beleive a domain of 例子.公司 on Windows with curl as is, will simply not work as there is no ANSI representation for those characters.

Using the current development repo, and because it gets converted into ANSI by Windows to ??.??, our IDN routines simply leave it as that.

Whilst with my modified proof of concept (where I convert all arguments to utf8) our IDN routine  converts it to:

xn--fsqu00a.xn--55qx5d

How does Linux handle this? I guess properly and everything gets passed into the curl tool as UTF-8?

[1] https://domainnamewire.com/2020/01/16/will-chinese-idn-domains-become-widely-used/

**Comment by mback2k** [comment]
@captain-caveman2k You should now be able to perform tests using the Azure Pipelines CI after you have rebased your PRs. At least I am seeing some of your new UTF-8 relevant tests failing [there](https://dev.azure.com/daniel0244/curl/_build/results?buildId=800&view=results).

**Comment by captain-caveman2k** [comment]
@mback2k Cheers Mark - Is it possible to test my branches or do I have to turn them into PRs first?

**Comment by captain-caveman2k** [comment]
Early indications[1] show that PR #4999, by converting the command line arguments to UTF-8 fixes the problem.

It also seems that this has been discussed as a limitation of curl on Windows for a number of years in #345 (Although supporting Unicode arguments is only part of the problem there), #731 and #3747.

[1] https://ci.appveyor.com/project/curlorg/curl/builds/31136821

**Comment by mback2k** [comment]
@captain-caveman2k I think you can use the CI on the curl repository (not your fork) without PRs in branches ending with `/ci`, e.g. `my-branch/ci`. But in case you decide to create a PR from that branch later on, it will not trigger the CI again.
