### ISSUE TITLE
libcurl with static openssl engine on iOS

### ISSUE THREAD

**Issue by ugochirico** [curl/curl#5003]
I'm trying to use libcurl with openssl on iOS with a custom static openssl engine.

I'm not able to build libcurl with openssl static engine. Is there a way to build libcurl with static engine support?

**Comment by bagder** [comment]
You can build curl with a static OpenSSL version, yes. The engine stuff is part of OpenSSL. Can you link them statically? Seems like a question to ask OpenSSL people, isn't it?

**Comment by ugochirico** [comment]
I didn't mean "build openssl statically". I mean openssl with static engine (cryptographic).
OpenSSL comes with ENGINE for cryptographic functions and you can implement your own cryptographic engine with your specific implementation.
Now, libcurl on windows and Linux can use custom static engine simply by building it by setting the flag HAVE_OPENSSL_ENGINE_H. The build configuration for iOS instead does not set the flag HAVE_OPENSSL_ENGINE_H so that it cannot be used with custom static engine.
So, my question is: how to build libcurl with the flag HAVE_OPENSSL_ENGINE_H ?

**Comment by bagder** [comment]
> The build configuration for iOS instead does not set the flag HAVE_OPENSSL_ENGINE_H

Setting that define has no use or purpose in curl so that's not what makes it not work. (#5007 will remove them all)

You want this condition to be true:

https://github.com/curl/curl/blob/5b46790f11ff85bfed3fd5d2563bb3a07b14611b/lib/vtls/openssl.c#L73-L77

... and there's nothing in curl code that prevents that from be true on iOS (or any other OS) that I know of.

**Comment by ugochirico** [comment]
Yes, you are right. The latest version seems to work with static openssl engine. I can use with my engine.
Many thanks
