### ISSUE TITLE
lld-link: error: undefined symbol: sscanf

### ISSUE THREAD

**Issue by muv1** [curl/curl#5082]
Using this file:

<https://curl.haxx.se/libcurl/c/simple.html>

With libraries from here:

<https://curl.haxx.se/windows>

and this compiler:

<https://github.com/mstorsjo/llvm-mingw>

and this command:

~~~
clang \
-DCURL_STATICLIB \
-lbrotlicommon-static \
-lbrotlidec-static \
-lcrypt32 \
-lcrypto \
-lcurl \
-lnghttp2 \
-lssh2 \
-lssl \
-lwldap32 \
-lws2_32 \
-lz \
-static \
simple.c
~~~

I get this result:

~~~
lld-link: error: undefined symbol: __declspec(dllimport) _sys_nerr
>>> referenced by libcurl.a(strerror.o):(Curl_strerror)

lld-link: error: undefined symbol: sscanf
>>> referenced by libcurl.a(cookie.o):(Curl_cookie_add)
>>> referenced by libcurl.a(urlapi.o):(parseurl)
>>> referenced by libcurl.a(urlapi.o):(parseurl)
>>> referenced by libcurl.a(hostip.o):(Curl_loadhostpairs)
>>> referenced by libcurl.a(http.o):(Curl_http_readwrite_headers)
>>> referenced by libcurl.a(http.o):(Curl_http_readwrite_headers)
>>> referenced by libcurl.a(http.o):(Curl_http_readwrite_headers)
>>> referenced by libcurl.a(http.o):(Curl_http_readwrite_headers)
>>> referenced by libcurl.a(ftp.o):(ftp_statemach_act)
>>> referenced by libcurl.a(ftp.o):(ftp_statemach_act)
>>> referenced 12 more times
clang-10: error: linker command failed with exit code 1 (use -v to see
invocation)
~~~

Am I doing something wrong?

**Comment by bagder** [comment]
`sscanf()` is a libc function that you're supposed to provide.

**Comment by jay** [comment]
They're part of the CRT so I don't know why they would be missing. That sounds like a compiler issue.
~~~shell
cat << EOF > a.c
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char *argv[])
{
  char c = 0;
  printf("sys_nerr: %d\n", sys_nerr);
  sscanf("c", "%c", &c);
  printf("c: %c\n", c);
  return 0;
}
EOF
clang -static -o a a.c
./a
~~~

**Comment by muv1** [comment]
https://github.com/mstorsjo/llvm-mingw/issues/95

**Comment by muv1** [comment]
It appears that the Windows cURL library is still being built against the older
MSVC runtime instead of the newer UC runtime:

- <https://docs.microsoft.com/cpp/porting/upgrade-your-code-to-the-universal-crt>
- <https://sourceforge.net/p/mingw-w64/mailman/message/36621319>

So with these files:

~~~
$ cat a.c
#include <stdlib.h>
int sun() {
   return _sys_nerr;
}

$ cat a.h
int sun();

$ cat b.c
#include <stdio.h>
#include "a.h"
int main() {
   int n1 = sun();
   printf("%d\n", n1);
}
~~~

A MSVC runtime program can call a UC runtime library:

~~~
clang -c a.c
clang -D_MSVCRT_ -c b.c
clang a.o b.o
~~~

but a UC runtime program cannot call a MSVC runtime library:

~~~sh
clang -D_MSVCRT_ -c a.c
clang -c b.c
clang a.o b.o # lld-link: error: undefined symbol: _sys_nerr
~~~

this is because UC runtime libraries are backward compatible, but MSVC runtime
libraries are not forward compatible. I think it would make sense to start
building the Windows cURL library with the UC runtime. @vszakats any comment?

**Comment by vszakats** [comment]
After reading the linked articles about the UC runtime, I'm left unconvinced if this solves more problems than it creates (even though its fundamental goals are fine, if not a bit-too-late), at least in case of curl-for-win. Unless I've understood it wrong, the UC runtime relieves **MSVC** users from the pain of versioned CRT files, but curl mingw builds never used those, so this isn't an advantage for this case. Plus, the UC runtime is only distributed via Windows 10 (and equivalent Server editions), not on any previous Windows versions, which means a certain portion of curl-for-win users would then require to install it for their older Windows versions, meaning that curl-for-win wouldn't always work out-of-the-box and would get a new dependency (again, unless there are fine points that I missed.)

So, indeed, curl-for-win and dependencies are using the plain default CRT (`msvcrt.dll`), as documented on the homepage/README. These are always available on supported OS versions and should work with "most" mingw distributions, including clang/llvm + mingw-w64 combos on systems offering these. I haven't specifically tested the mstorsjo/llvm-mingw toolchain though.

For example, on macOS, with Homebrew, this will create the executable without errors:
```bash
# requires: brew install mingw-w64 llvm
export PATH="/usr/local/opt/llvm/bin:${PATH}"

clang \
-target x86_64-w64-mingw32 --sysroot /usr/local/opt/mingw-w64/toolchain-x86_64 -Iinclude -L. \
-DCURL_STATICLIB \
simple.c \
-Wl,--start-group \
-lbrotlicommon-static \
-lbrotlidec-static \
-lcrypt32 \
-lcrypto \
-lcurl \
-lnghttp2 \
-lssh2 \
-lssl \
-lwldap32 \
-lws2_32 \
-lz \
-Wl,--end-group \
-static
```

**Comment by mstorsjo** [comment]
> It appears that the Windows cURL library is still being built against the older
> MSVC runtime instead of the newer UC runtime:

> this is because UC runtime libraries are backward compatible, but MSVC runtime
> libraries are not forward compatible. I think it would make sense to start
> building the Windows cURL library with the UC runtime. @vszakats any comment?

No, this is absolutely incorrect.

I'm the author of the llvm-mingw toolchain, and the one who has added support for UCRT in mingw-w64.

The accurate situation is this: Originally, mingw toolchains have linked against msvcrt.dll, as this is always available on all Windows versions. This is actively discouraged by Microsoft, but is a convenient way of fulfilling the demands of the GPL, without needing to ship a third party CRT with the app. 

A couple years ago, I added support to mingw-w64 for targeting the UCRT instead of msvcrt.dll. This gives a modern more featureful CRT, and is not discouraged like msvcrt.dll. It's shipped out of the box with Windows 10, and installable with a separate redistributable on Windows 7 and 8.

In mingw-w64, one can't generally switch between msvcrt.dll and UCRT at will, but one can choose which one to target by default when building the toolchain from scratch. In general, an object file built with mingw-w64 headers for one of the CRT alternatives can't be linked against the other CRT.

Thus, mixing DLLs is fine as long as one doesn't share CRT objects like file descriptors/handles across DLL boundaries, or free memory in one DLL that was allocated in another one. (The same thing as always has been the case when mixing DLLs between mingw and MSVC.) Mixing object files or static libraries between CRT variants does not work and is not supported.

To clarify the incompatibilities, in the case of UCRT, certain stdio functions (like `sscanf`) are expanded as inline functions in the headers, making the object files refer to symbols like `__stdio_common_vsscanf`. Those result in clear linker errors if things are mixed. But more subtly, certain CRT structs, like `threadlocaleinfostruct` have a different layout in the case of UCRT, and accesses to this struct can be inlined by `ctype.h` functions. Those don't result in clear linker errors but plain corruption.

My toolchain, llvm-mingw, serves as a testbed for more bleeding edge configurations of everything. In addition to using UCRT by default, it also uses libcxx instead of libstdc++, so even if one would configure my toolchain to use msvcrt, any C++ object files from traditional mingw toolchains would still be incompatible - although this isn't relevant for curl.

The poster of this issue seems to be drawing his own incorrect conclusions from his own limited tests, despite being told numerous times in detail that the CRTs are incompatible.

Thus one can't build curl with UCRT and pretend that a static library of that would be any more universally compatible than the current ones targeting msvcrt.dll.

**Comment by mstorsjo** [comment]
> So, indeed, curl-for-win and dependencies are using the plain default CRT (`msvcrt.dll`), as documented on the [homepage/README](https://github.com/curl/curl-for-win/blob/master/README.md). These are always available on supported OS versions and should work with "most" mingw distributions, including clang/llvm + mingw-w64 combos on systems offering them. I haven't specifically tested the [mstorsjo/llvm-mingw](https://github.com/mstorsjo/llvm-mingw) toolchain though.

This is indeed the sensible choice for shipping static libraries at the moment. My toolchain is intentionally and knowingly incompatible by defaulting to UCRT and libcxx, but I guess I need to make this more clear to users.

For the future, there's some talk about changing the default of mingw-w64 to UCRT, but no such change has been made yet, both because needing a runtime which isn't available out of the box before Windows 10 isn't ideal, and because it's hard to upgrade incrementally e.g. in an environment like MSYS2, where there's tons of preexisting libraries. It works fine with a new standalone toolchain and all code built from scratch though.

**Comment by vszakats** [comment]
@mstorsjo Thank you for all the details!

**Comment by vszakats** [comment]
One thing that would help the switch to UCRT, is if Microsoft would opt to include the runtime in earlier Windows versions, that are still widely deployed/used. Surely they'd prefer everyone to use Windows 10 already, and 7 is EOL-d, but switching doesn't happen quickly and even less so on the server-side. This would be more practical than merely discouraging `msvcrt.dll` and "encouraging" UCRT. It would allow (would have allowed) to switch to UCRT as soon as toolchain support became available.

**Comment by mstorsjo** [comment]
> One thing that would help the switch to UCRT, is if Microsoft would opt to include the runtime in earlier Windows versions, that are still widely deployed/used. Surely they'd prefer everyone to use Windows 10 already, and 7 is EOL-d, but switching doesn't happen quickly and even less so on the server-side. This would be more practical than merely discouraging `msvcrt.dll` and "encouraging" UCRT. It would allow (would have allowed) to switch to UCRT as soon as toolchain support became available.

Yup. I think practically speaking, it's bundled and installed by most modern applications you install (so on the average Windows 7 install today I think you'd find it already installed), but if it'd be automatically installed by e.g. Windows Update, it would be easier to consider it generally available even on the older ones.

**Comment by muv1** [comment]
So initially I took the advice of @mstorsjo and just rebuilt libCurl:

~~~sh
git clone --depth 1 git://github.com/curl/curl
cd curl/lib
mingw32-make -f Makefile.m32 CFG=-winssl RCFLAGS='-O coff'
~~~

Then add to `simple.c`:

~~~c
curl_easy_setopt(curl, CURLOPT_CAINFO, "curl-ca-bundle.crt");
~~~

Then it lets me compile:

~~~
clang \
-DCURL_STATICLIB \
-lcrypt32 \
-lcurl \
-lwldap32 \
-lws2_32 \
simple.c
~~~

However after another comment from him, it appears that libCurl can in fact be
linked without rebuilding:

~~~
clang \
-DCURL_STATICLIB \
-lbrotlicommon-static \
-lbrotlidec-static \
-lcrypt32 \
-lcrypto \
-lcurl \
-lmsvcrt-os \
-lnghttp2 \
-lssh2 \
-lssl \
-lwldap32 \
-lws2_32 \
-lz \
-static \
simple.c
~~~

**Comment by vszakats** [comment]
So, the solution was to add `-lmsvcrt-os`.

**Comment by mstorsjo** [comment]
> So, the solution was to add `-lmsvcrt-os`.

Yes, that makes clang link to that lib.

For more context again: Normally, the mingw default CRT import lib has been named libmsvcrt.a, linking against msvcrt.dll. As the idea of choosing a different CRT as default was born, the most practical way of achieving this was making the msvcrt.dll import library available under a different name, libmsvcrt-os.a, and making libmsvcrt.a just be a copy of whichever is configured as default. (The UCRT options are libucrtbase.a, for linking directly against ucrtbase.dll, and libucrt.a, which links against the api-ms-win-crt-*.dll apiset DLLs. The latter is the only choice allowed for UWP apps.) When installing mingw-w64, one can set the default targeted by headers, which should match the default chosen for libmsvcrt.a when installing mingw-w64-crt.

If wanting to link against something else than the default, with clang one can just add e.g. `-lmsvcrt-os`, any `-lmsvcr*` or `-lucrt*` will make clang inhibit the default `-lmsvcrt`. With gcc, one has to make a custom spec file to override the default, otherwise one can end up linking inconsistently against two different CRTs. (Msys2's gcc iirc does ship with a non-upstream patch for a custom option for choosing a different default though.)

If going to link a CRT other than the default, all the newly compiled code has to compiled accordingly as well, by passing `-D__MSVCRT_VERSION__=0` for msvcrt.dll, or `-D_UCRT` or `-D__MSVCRT_VERSION__=0xE00` for UCRT. Missing this detail can go unnoticed until the calling C code calls something more exotic.

Picking a non-default CRT works as long as all statically linked libs were built matchingly, but for e.g. C++, the standard C++ library only exists built against the toolchain's default CRT.

**Comment by vszakats** [comment]
@mstorsjo Thanks for these as well! This process looks quite straightforward, at least for clang, and the spec file tweak for gcc is reasonably automatable as well. (gcc is only used for OpenSSL; could not get it to build with clang so far.) With these, the remaining obstacle is the manual dependency for pre-Windows 10 systems.

I understand that [Windows isn't a CRT delivery channel](https://devblogs.microsoft.com/oldnewthing/20140411-00/?p=1273), though it's a delivery channel for lots of other non-OS things, so it'd be nice to make a practical exception for UCRT and Windows 7/8/8.1. Because, well, user-apps are not a CRT delivery channel as well :) [in case someone from the relevant team(s) may read this!]

**Comment by bagder** [comment]
I think we all agree that this isn't a curl bug and we can close this issue?

**Comment by mstorsjo** [comment]
> I think we all agree that this isn't a curl bug and we can close this issue?

Yes, go ahead and close it.

**Comment by muv1** [comment]
Agreed
