### ISSUE TITLE
tarball and zips both missing packages/OS400/chkstrings.c which is present in the source archive

### ISSUE THREAD

**Issue by jonrumsey** [curl/curl#5142]
### I did this
Unpacked https://github.com/curl/curl/releases/download/curl-7_69_0/curl-7.69.0.tar.gz and attempted to build OS/400, this failed with;

CZS0632:  Source stream file could not be opened.
CZM1613:  The compilation failed.
ERROR: Failed to build CHKSTRINGS *PGM object!

The packages/OS400/chkstrings.c file is missing, however it is present in the source tarball/zips (i.e. https://github.com/curl/curl/archive/curl-7_69_0.tar.gz). I'm not familiar with how the curl distribution archives are constructed, does EXTRA_DIST in packages/Makefile.am add extra files in the packages subtree?

### I expected the following
Clean build

### curl/libcurl version
7.69.0 and 7.69.1 are affected

[curl -V output]

### operating system
OS/400

**Comment by bagder** [comment]
The later one, the one with "archive" in the link name is automatically generated by github and it shoves everything in the git repo (at that label) into an archive - it thus can't miss out anything that's present in git.

Our *actual* releases however are *generated* by the `maketgz` script and will produce a set of files to include in the release that are not present in git (for example `configure` and friends). However, it needs the `EXTRA_DIST` variables in the makefiles to be correct as otherwise it might leave out files. I fixed this issue in PR #5143.

We have basic CI tests that the maketgz includes everything to build a Linux build, but unfortunately your problem was not detected by that test.
