### ISSUE TITLE
cUrl not working with external ip. Got error "Failed to connect port 80 connection refused"

### ISSUE THREAD

**Issue by dhara15101991** [curl/curl#5304]
A call is working successfully but when used with external IP, it throws error. 
Following is code:

```
$postData = [
            'grant_type'    => 'password',
            'client_id'     => 10,
            'client_secret' => 'xHuxxxxxxxflw',
            'username'      => 'admin@abc.com',
            'password'      => 'abc',
            'scope'         => '*',
        ];
        $ch     = curl_init();
        $url = 'http://37.XX.XX.XXX/oauth/token';
        curl_setopt($ch,CURLOPT_URL,$url);
        curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
        curl_setopt($ch,CURLOPT_HEADER, false); 
        curl_setopt($ch, CURLOPT_POST, count($postData));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);

        $data = curl_exec($ch);
        $curl_errno = curl_errno($ch);
        $curl_error = curl_error($ch);
        if ($curl_errno > 0) {
                echo "cURL Error ($curl_errno): $curl_error\n";
        } else {
                echo "Data received\n";
        }
        curl_close($ch);

        echo ($data); 
```
I got following error:

`cURL Error (7): Failed to connect to 37.XX.XX.XXX port 80: Connection timed out`

It should give success as giving on local IP but not working. I tried headers also but not working.

**Comment by dfandrich** [comment]
The 10.x.x.x IP address space is not "external", it's private. I suspect this
code is running on a machine that doesn't have access to the desired machine
running on that private address, whether because it's on a different network or
because it's firewalled away.  This is highly unlikely to be related to curl at
all.

**Comment by dhara15101991** [comment]
@dfandrich Sorry I have added a private address. I have modified it.

**Comment by dfandrich** [comment]
My answer remains otherwise the same. There is very likely to be a firewall
or other equipment between the two machines that is preventing network
connections from being made. Are you able to make a similar connection between
those two machines using a different client? I suspect you won't be able to.

**Comment by dhara15101991** [comment]
@dfandrich but that URL is working through a browser

**Comment by emilengler** [comment]
Firefox has a option "Copy as cURL".
Press F12 on that size, go to network analyses, then refresh the page, right click on the first request and do copy as curl. You then get the exact same thing the browser does as a curl command. From there on you should be able to debug it

**Comment by bagder** [comment]
Maybe the browser is connecting to the host differently. Maybe a configured proxy?

**Comment by dhara15101991** [comment]
Solved this issue. Outbound port need to enable. Thanks all for your kind support.

**Comment by josmanjp** [comment]
> Resuelto este problema. El puerto de salida debe habilitarse. Gracias a todos por su amable apoyo.

como se habilita el puerto de salida?
