### ISSUE TITLE
CURLOPT_SSL_OPTIONS: add *_NATIVE_CA broke Appveyor CI

### ISSUE THREAD

**Issue by bagder** [curl/curl#5367]
It seems like https://github.com/curl/curl/commit/148534db57dda611cf8516e92e4d6e35fc1e5074 broke the AppVeyor tests when both OpenSSL and WinSSL are off. 36 tests are failing with "curl: (48) An unknown option was passed in to libcurl".

_Originally posted by @MarcelRaad in https://github.com/curl/curl/pull/3784#issuecomment-626235893_

**Comment by bagder** [comment]
@MarcelRaad got a link to an example build? Also, any idea where that (new) return is done that makes curl say this?

**Comment by MarcelRaad** [comment]
Example here: https://ci.appveyor.com/project/curlorg/curl/builds/32763641/job/q559w3buywu1staa

I can currently only look at the mobile web version because of my flaky internet connection today, but my theory is:

1. `native_ca_store` is set at
https://github.com/curl/curl/commit/148534db57dda611cf8516e92e4d6e35fc1e5074#diff-70b44ee478e58d4e1ddcf9c9a73d257bR2343 when `USE_WIN32_CRYPTO` is defined, which is also the case for non-SSL builds on Windows.

2. That makes `CURLOPT_SSL_OPTIONS` being set here: https://github.com/curl/curl/commit/148534db57dda611cf8516e92e4d6e35fc1e5074#diff-70b44ee478e58d4e1ddcf9c9a73d257bR1913

3. That option is only handled with `USE_SSL` and otherweise ends up in the default case leading to that error message: https://github.com/curl/curl/commit/148534db57dda611cf8516e92e4d6e35fc1e5074#diff-72ee0eef31d053c9e6d4fb22e81d2407R2120

**Comment by bagder** [comment]
ah yes, it tries to set that SSL option when SSL is disabled... PR pending!
