### ISSUE TITLE
runtests: broken check for test in data/Makefile.inc

### ISSUE THREAD

**Issue by bagder** [curl/curl#5380]
Regression from #5358 commit ad6416986755e41 by @Lekensteyn.

### I did this

    $ ./configure
    $ make
    $ cd tests
    $ make
    $ ./runtests.pl 1
    Warning: test1 not present in tests/data/Makefile.inc

### I expected the following

No warning as `test1` really is present in that file!

The reason for the problem is that the new logic in the ` get_disttests` function assumes that just because there's a `../CMakeCache.txt` file present, we want to use cmake! :thinking: 

### curl/libcurl version

current git

### operating system

independent

**Comment by Lekensteyn** [comment]
How did you end up with CMakeCache.txt in the root of your build directory while also using autotools? (Or source directory if you use the same build and source directory.)

The two cannot be mixed, they will end up overwriting each other Makefiles.

Separate build and source directories are generally recommended as this allows separate build configurations (e.g. curl+ngtcp2, curl+quiche, curl+wolfssl, etc.) with the same source tree.

**Comment by bagder** [comment]
> How did you end up with CMakeCache.txt in the root of your build directory while also using autotools?

Hm right. Clearly I've done a cmake build before within the tree and then done a configure build again and leftovers from the old cmake build is now playing tricks on me... I'm not sure what we can do to make this less likely to happen again.

**Comment by Lekensteyn** [comment]
An option is to update both build systems to detect this condition:

- `configure.ac`: error out when `CMakeCache.txt` is detected.
- `CMakeLists.txt`: cannot simply check for `configure` or `Makefile.in` because autoconf/automake puts its autogenerated files in the source tree. Cannot simply check for `Makefile` because CMake might generate those too. Candidates are `config.status`, `libtool`, and `config.log`. Perhaps error out when `config.status` is found?

Another is to modify the runtests.pl to detect when both CMake (CMakeCache.txt) and autotools (config.status) are found and print a warning or error out.

There will probably not be many people running into this problem, do you think it is worth adding a workaround to detect it?

**Comment by bagder** [comment]
Nah, let's not. Not unless we run into this more at least.  As you say, this should be a rather rare thing. Closing now. Thanks for valuable feedback!
