### ISSUE TITLE
After downloading a file name in Chinese, the file name is escaped

### ISSUE THREAD

**Issue by luziyuan002** [curl/curl#5570]
我现在想使用curl下载一些文件，这些文件的原始文件名是中文的，使用curl下载后文件名被转义，怎么能不被转义，输出原始的中文文件名，我的下载命令是这样写的

#!/bin/sh
curl -O -J  下载的url路径

文件名被转义成如下
2020%E5%85%A8%E5%9B%BD%E5%88%B7%E9%A2%98%E7%8F%AD%E2%80%94%E4%B8%AD%E5%9B%BD%E9%9F%B3%E4%B9%90%E5%8F%B22%E2%80%946.6%E2%80%94%E6%9E%97%E4%BE%9D%E7%84%B6.pdf

请求大神帮忙

---- 
Google translated:

I now want to use curl to download some files. The original file name of these files is Chinese. After downloading with curl, the file name is escaped. How can it not be escaped and output the original Chinese file name. My download command is written like this of

#!/bin/sh
curl -O -J download URL path

The file name is escaped as follows
2020%E5%85%A8%E5%9B%BD%E5%88%B7%E9%A2%98%E7%8F%AD%E2%80%94%E4%B8%AD%E5%9B%BD% E9%9F%B3%E4%B9%90%E5%8F%B22%E2%80%946.6%E2%80%94%E6%9E%97%E4%BE%9D%E7%84%B6.pdf

Ask the gods for help

**Comment by bagder** [comment]
First: please stick to using English here. Most of us don't speak it as a first language but in order to communicate, it is better if we all put in the extra effort and do translations and look up words in dictionaries on the side.

Then: this is not a support forum, this is an issue tracker. For questions and help with the curl tool, we have the curl-users mailing list: https://curl.haxx.se/mail/

Finally: curl doesn't "unescape" file names for you. When you use -J, curl will use the file name exactly as provided by the server in the `Content-Disposition` header, and not the UTF-8 (unicode) version. Handling unicode is a rather big job and curl doesn't do it (yet). There's an outstanding TODO item mentioning it, but I don't know anyone working on that: https://curl.haxx.se/docs/todo.html#UTF_8_filenames_in_Content_Dispo I'm not even sure how feasible it is to do it.
