### ISSUE TITLE
Gopher: Incorrect standardization

### ISSUE THREAD

**Issue by emilengler** [curl/curl#5787]
> The Selector string should be no longer than 255 characters.

cURL does not implement such a limit.

**Comment by bagder** [comment]
What problem does it cause? It seems pretty harmless to me, not to mention that you wouldn't get such a (working) URL from anyone and using a too long string (== garbage) surely will just make the request to fail?

**Comment by emilengler** [comment]
> What problem does it cause?

Possible unreliability without a clear error

**Comment by bagder** [comment]
Why not the other way around because (some) servers support longer than 255 character selectors? From my very poor research, I've found several gopher server implementations that don't seem to care about the length.

So I'm asking for real-world actual problems, not theoretical ones based on reading the spec.

**Comment by bagder** [comment]
I think we can just leave this as-is as I don't think this hurts anyone or is very likely to hurt anyone. It's also a very rarely used protocol so I rather just let it lie.

**Comment by emilengler** [comment]
Ok, I just reported it for the protocol.
