### ISSUE TITLE
curl: (35) Server aborted the SSL handshake

### ISSUE THREAD

**Issue by gmidha** [curl/curl#6007]
*   Trying <ip address>...
* Connected to <proxy url> (<ip address>) port 8181 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to appurl:443
* Proxy auth using Basic with user 'user'
* Server auth using Basic with user 'user'
> CONNECT appurl:443 HTTP/1.1
> Host: url:443
> Proxy-Authorization: Basic token
> User-Agent: curl/7.72.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering http/1.1
* WARNING: disabling hostname validation also disables SNI.
* CONNECT phase completed!
* CONNECT phase completed!
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake

I am getting this error, while doing a curl to url through proxy, can someone please help in identifying the issue.

curl -k -v --cacert /Users/test/test2.pem https://appurl --proxy "http://user:pwd@proxyurl:8181" -u user:pwd

I have masked the user and app info in this issue.

**Comment by bagder** [comment]
By ignoring the template you didn't tell us what TLS backend you're using. This is Secure Transport, isn't it?

The error you see there is quite literally what the TLS library reports: `errSSLClosedAbort`. There's not a lot more to add about that afaik. The [Apple documentation for it](https://developer.apple.com/documentation/security/1503828-secure_transport_result_codes/errsslclosedabort?language=objc) is hilarious: **The connection closed due to an error.**

**Comment by gmidha** [comment]
hi @bagder , can you please explain which template I ignored, I didnt get that. I am trying to connect to https endpoint through curl.

**Comment by bagder** [comment]
> which template I ignored

When you pressed "create new issue", there was a template on how to fill in an issue and one of the subtitles there asked about `curl -V` (or similar) output so that we understand what you're using.

I also asked you in my follow-up and yet you managed to not answer this in your reply either. So let me ask again: what curl build/flavor are you using on what platform? Also: how can we reproduce this problem?

Is there anything particular that makes you think this is not the server's fault?

**Comment by gmidha** [comment]
sorry, didnt mean to miss the template.


### I did this
curl -k -v --cacert /Users/test/test2.pem https://appurl --proxy "http://user:pwd@proxyurl:8181" -u user:pwd

### I expected the following
I ran the above curl command and expected app to respond, which works if I use insecure

### curl/libcurl version
7.72.0
[curl -V output]
curl 7.72.0 (x86_64-apple-darwin18.7.0) libcurl/7.72.0 SecureTransport zlib/1.2.11
Release-Date: 2020-08-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets

### operating system
MacOS Mojave 10.14.6

**Comment by bagder** [comment]
> which works if I use insecure

"insecure" ? Do you mean `--insecure` ? The option that is the same as `-k` which you said you use in the command line that is problematic? I'm very confused.

**Comment by bagder** [comment]
I'd say this is likely to be a server or Secure Transport issue. Can you connect to other sites this way? Can you try building curl with another TLS backend and see if that works better?

Also, you didn't answer my question from a week ago which means I will close this issue soon unless something happens.

**Comment by handle2001** [comment]
On the off chance that it may help, is it possible to get the server-side logs from these requests? I agree with Badger that this is usually a server-side issue, but either way those logs would probably confirm/deny this.

**Comment by gmidha** [comment]
thanks for the support, issue was with proxy. My site wasn't whitelisted on the proxy. It looks like I dont need proxy and curl directly.

I am good, issue can be closed.
