### ISSUE TITLE
Use "Host" header value as base for TLS SNI

### ISSUE THREAD

**Issue by xkr47** [curl/curl#607]
If I override the "Host" header using `-H "Host: foo:8443"` then the "Server Name" in the TLS SNI extension still uses the hostname from the original url. I think the Server name should use the hostname part of the Host header - some servers (e.g. Cloudflare) even reject requests if the Host header does not match the server name in the SNI extension.

For hacking purposes it could also be beneficial to have a commandline parameter to set a custom value for "Server Name" in the SNI extension.

A workaround seems to be to do this:

    curl --resolve foo:8443:127.0.0.1 https://foo:8443/

instead of

    curl -H "Host: foo:8443" https://localhost:8443/

in which case the SNI record Server Name seems to get set to "foo" (which is what I wanted).

**Comment by jay** [comment]
> If I override the "Host" header using -H "Host: foo:8443" then the "Server Name" in the TLS SNI extension still uses the hostname from the original url. I think the Server name should use the hostname part of the Host header - some servers (e.g. Cloudflare) even reject requests if the Host header does not match the server name in the SNI extension.

I think you want [`--resolve`](http://curl.haxx.se/docs/manpage.html#--resolve).

> For hacking purposes it could also be beneficial to have a commandline parameter to set a custom value for "Server Name" in the SNI extension.

It seems like that would be of very limited use but I was intrigued so I wrote it.
[CURLOPT_SNI_HOSTNAME, --sni-hostname](https://github.com/jay/curl/compare/master...jay:curlopt_sni_hostname?expand=1) (OpenSSL only atm)

~~~
Override the hostname to be sent as server name indication (SNI) if SNI
is supported by the ClientHello.
~~~

I'm having trouble thinking of the use cases though, like why you'd use that instead of resolve. Say the IP addresses change every so often and you don't know what they'll be. in that case I guess it would make more sense to set the SNI specifically and you wouldn't have to do DNS lookups each time. OTOH maybe expanding `--resolve` to support an initial dns lookup like `--resolve example.com:443:resolvethishost.com`

**Comment by bagder** [comment]
`--resolve` also has the added benefit that it works for other hostname functions and for non-HTTP like protocols.

**Comment by bagder** [comment]
I would prefer a solid use case for such an --sni-hostname option first before we add something like that. A use case where --resolve and/or Host: changing aren't enough.

**Comment by jay** [comment]
Ok. Let's wait a few days to see if anyone has one and if not I'll close it out.

**Comment by xkr47** [comment]
Well say you want to set up a service that verifies that the host header is the same as the SNI value. Then you could use curl to validate that the service correctly rejects request where the SNI value differs from the host value. Of course since currently the SNI value is NOT taken from the Host header but from the url, this can be achieved using `curl -H "Host: foo:8443" https://localhost:8443/`.

**Comment by bagder** [comment]
I think we've concluded that we won't base SNI on the Host: header
