### ISSUE TITLE
Appveyor autotools builds run no tests?

### ISSUE THREAD

**Issue by bagder** [curl/curl#6120]
### I did this

I checked the appveyor builds for #6117 and noticed that the three autotools builds now fail because *no* test runs!

[example build](https://ci.appveyor.com/project/curlorg/curl/builds/35899795/job/g8xptp4vw5ihkn9u)

### I expected the following

It should run plenty tests

### curl/libcurl version

current git master

### operating system

windows

/cc @mback2k ideas?

**Comment by mback2k** [comment]
This line looks interesting, especially since the tests were running on AppVeyor in the past:
`TESTINFO: "disabled by missing keyword" 1019 times (1, 2, 3, 4, 6, 7, 8, 9, 10 and 1010 more)`
https://ci.appveyor.com/project/curlorg/curl/builds/35899795/job/g8xptp4vw5ihkn9u#L2450

Did you try to find the last commit that ran the tests?

**Comment by mback2k** [comment]
I will try to find the commit that broke it since the latest release at which time the tests still ran:
`TESTDONE: 1086 tests out of 1088 reported OK: 99%`
https://ci.appveyor.com/project/curlorg/curl/builds/35740880/job/5tt0b6ac2x5kpwad#L7430

**Comment by mback2k** [comment]
This is the first commit not running tests in the autotools build on AppVeyor: https://github.com/curl/curl/commit/15997f6db53c70070177739716dc518e667e6090

Seems like the removal of these tests caused a change in the keyword handling maybe?

**Comment by bagder** [comment]
Very puzzling! If that commit broke something, how come it only broke it for autotools builds on appveyor?

**Comment by jay** [comment]
Fixed by e2bcdf5.
