### ISSUE TITLE
winbuild: When SChannel is enabled TLS1.3 communication is successful on Windows Insider build, is there a way to build on non insider builds

### ISSUE THREAD

**Issue by ganeshkamath89** [curl/curl#6218]
I am using the latest libCurl version - 7.73.0
I am using OpenSSL version - 1.1.1h
Windows Insider build (Build 2004 20251.1)

When I run an OpenSSL Server and test TLS 1.3 communication from Windows Insider build, I am able to successfully communicate and make the required transactions when tested from another Windows Insider build enabled system. This is provided I build LibCurl on Windows with SCHANNEL enabled.

I am looking for a solution where LibCurl does not rely on the underlying OS supported SCHANNEL because we want our product to run from previous versions of Windows as well, such as Windows 7/ Windows 8.1 / Windows 10 (without Insider Preview enabled), for this we recently switched from a solution that was using WinHTTP for SSL communication to a solution using LibCurl + OpenSSL.

What can I do to enable TLS 1.3 communication between systems that are non Insider Builds?
Because when I Disable SCHANNEL while building LibCurl, TLS 1.3 is not working on the client side even though the OpenSSL 1.1.1h version supports this protocol - and is tested on the server side.

Insider builds are mostly for testing purpose and don't get deployed in production, so all our users will require to be enabled for TLS 1.3 communication.

**Comment by bagder** [comment]
Schannel is the TLS system provided by Windows itself. When you run a binary on another Windows version, you will use *that* system's Schannel version. If you want to remain independent of which Windows you run on, you need to use another TLS backend.

This is not a bug.

**Comment by ganeshkamath89** [comment]
Okay. 
How do I enable another TLS backend (for TLS 1.3 support on Windows) for my application so that I don't depend on Windows to provide that backend?

I am just asking for help with my problem because this is a new field for me.

**Comment by jay** [comment]
If you built libcurl with support for multiple SSL backends and you have some requirement that only one of them can meet then it's good practice to choose the backend you want to use, since it may or may not be the default depending on the order. You can use [curl_global_sslset](https://curl.se/libcurl/c/curl_global_sslset.html) to do that. For example if you need TLS 1.3 on all versions of Windows you could select the OpenSSL backend and not the Schannel backend.

> What can I do to enable TLS 1.3 communication between systems that are non Insider Builds?
Because when I Disable SCHANNEL while building LibCurl, TLS 1.3 is not working on the client side even though the OpenSSL 1.1.1h version supports this protocol - and is tested on the server side.

That sounds like a server issue not a curl issue. As discussed in #4918 schannel TLS 1.3 support is not documented, so I do not suggest using curl w/ schannel for that. If you are using curl w/ openssl 1.1.1 then it should use TLS 1.3. Try checking TLS info such as https://check-tls.akamai.io/v1/tlsinfo.json

**Comment by ganeshkamath89** [comment]
Your solution has worked for me.

I added the followng code to set SSL backend to openssl now i am able to perform TLS 1.3 communication.
	```
const curl_ssl_backend **list;
	curl_global_sslset(CURLSSLBACKEND_OPENSSL, "openssl", &list);
```
