### ISSUE TITLE
GnuTLS key pinning tests fail on travis

### ISSUE THREAD

**Issue by bagder** [curl/curl#6339]
### I did this

Check [the latest CI builds on master](https://travis-ci.org/github/curl/curl/jobs/750110369).

The GnuTLS builds now repeatedly ends with:

~~~
These test cases failed: 2034 2037 2041 
~~~
### I expected the following

I cannot reproduce this locally, as my GnuTLS builds succeed with those tests!

### curl/libcurl version

current master

### operating system

On Linux, but presumably similar on others.

**Comment by jay** [comment]
I can't reproduce this either, using the same version of GnuTLS as the CI.

curl 7.75.0-DEV (x86_64-pc-linux-gnu) libcurl/7.75.0-DEV GnuTLS/3.5.18 zlib/1.2.8 nghttp2/1.42.0 librtmp/2.3

**Comment by jay** [comment]
The first failed pinning test, 2034, shows some strange errors,

https://travis-ci.org/github/curl/curl/jobs/750110369#L5948

 [ ] Option SO_REUSEADDR set on accept socket
 [!] bind: Address already in use (98)
 [!] Error binding service [curltest] to 0.0.0.0:24680
 [ ] Unbinding service [curltest]
 [ ] Service [curltest] closed

https://travis-ci.org/github/curl/curl/jobs/750110369#L6041

 2020.12.17 00:03:20 LOG5[0]: Service [curltest] accepted connection from 127.0.0.1:60416
 2020.12.17 00:03:20 LOG3[0]: s_connect: connect ::1:37521: Network is unreachable (101)
 2020.12.17 00:03:20 LOG3[0]: s_connect: connect 127.0.0.1:37521: Connection refused (111)
 2020.12.17 00:03:20 LOG3[0]: No more addresses to connect
 2020.12.17 00:03:20 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket

All the failed tests return send error. Maybe the bounce from the https server (stunnel -> http server) fails due to a problem with the http server? I wonder why this would only affect gnutls.

**Comment by bagder** [comment]
I can't really make sense of the logs. It is notable that if you compare with the logs from the 2031 test failure just before, we can see that `http_server.log` seems to be the same one - even though it is supposed to have been removed when the test starts...

But yes, it looks to me like stunnel works and accepts the TLS connect but then when it connects to the http server, it isn't working/running and thus anything HTTP after the TLS fails...

**Comment by jay** [comment]
I thought maybe there's some package that changed in the CI so I went back through a few dozen commits and found the first failed one, 4dc710b (RELEASE-NOTES: synced). The parent is 354bc95 (test1272: fix line ending). I re-ran the gnutls job for that parent twice today and it [still doesn't fail](https://travis-ci.org/github/curl/curl/builds/749853161). This is not making a lot of sense to me. How could release notes change cause this problem...

**Comment by bagder** [comment]
They seem to have stopped occuring...
