### ISSUE TITLE
When using curl command on windows, I want you to be able to send with utf8 instead of cp932

### ISSUE THREAD

**Issue by khayashi4337** [curl/curl#6386]
type:
Implementation request

title:
When using curl command on windows, I want you to be able to send with utf8 instead of cp932

The main language of the drafter
Japanese:

When using the curl command on windows, I want to send the character code in UTF-8.
The character code of the command prompt is cp932, so I can't send it.

If you change the character code of the command prompt to chcp 65001, it will be in utf8 mode, but this time
You will not be able to enter Chinese characters in this mode.

So it's packed.

The current workaround is to create a UTF-8 format file and
--data-binary @filename
Must be done.

Implementation plan 1:
Allow the value of the -d option to be read from the pipeline.

Implementation plan 2:
Allows optional conversion of character code

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by jay** [comment]
I thought we already did this for unicode builds?

/cc @MarcelRaad

**Comment by jay** [comment]
Closing due to no response.

> If you change the character code of the command prompt to chcp 65001, it will be in utf8 mode, but this time
> You will not be able to enter Chinese characters in this mode.
> 
> So it's packed.
> 
> The current workaround is to create a UTF-8 format file and
> --data-binary @filename

If your curl build has unicode support then you should be able to paste a curl command line with unicode characters to the command prompt without changing the code page. If you run `curl -V` you should see Unicode in Features. If not then download the latest [curl for windows](https://curl.se/windows/). 

Examples:

`curl -v --data 平仮名 http://httpbin.org/post` and server should return form unicode characters `\u5e73\u4eee\u540d`.
`curl -v --data спасти http://httpbin.org/post` and server should return form unicode characters `\u0441\u043f\u0430\u0441\u0442\u0438`

If you want to do it from a batch file then I'm pretty sure you would have to change the code page to UTF-8 and restore the old code page at exit. For an example see [utf8_encoded_example.bat](https://gist.github.com/jay/731030525b58ae3845b7ba59c0757b3c).


/cc @bitcrazed
