### ISSUE TITLE
reason phrase from HTTP status line missing in error buffer after upgrade to 7.75.0

### ISSUE THREAD

**Issue by kdudka** [curl/curl#6615]
Commit 58974d25d8173aec154e593ed9d866da566c9811 undocumentedly removed an 8 years old extension from  commit d317ca50ae7d8bb250431f86709e53b94f7f6ddf, which in turn broke the upstream test-suite of pycurl: https://bugzilla.redhat.com/1927655

The fact that the extension was covered by curl's upstream test did not help much: https://github.com/curl/curl/commit/c7dd08ce588a1cccd0eaf779137348d198e69b12#diff-ebfe42e7bcff9545310cc61161351b52265c94a30b021c56e89a0324306c1e57

If the removal was intended, we need to update pycurl's tests-suite to make it work with the new version of libcurl.

**Comment by bagder** [comment]
I don't think libcurl will or can guarantee that error messages remain or are stable over time. A user relying on that is on their own and I would rather urge such user to use the documented and provided API to extract that information.

This change was indeed on purpose as I wanted to make sure the test ran fine with both the built-in HTTP code as well as with Hyper and - at least at that point in time - removing the message was the easiest route to make that happen. I think maybe we could solve that differently now if we *really* want that message in the error buffer.

**Comment by kdudka** [comment]
I agree that programs that obtain structured data out of the error buffer should be fixed.  But this has never been the point of this extension.  The error message is often presented to end users of the whole software stack who have no idea what libcurl or even HTTP is.  For such people `404 Not Found` is much easier to understand than just `404`.

**Comment by bagder** [comment]
Maybe. But you then assume that the reason phrase there is actually that clear and understandable as in your example here. Since the text has no functional purpose in the protocol we can also be sure that it will be totally misleading or downright wrong in some cases and then the message will make a disservice since people might get tricked into thinking that what's in the error message carries a particular weight and actual meaning...

**Comment by kdudka** [comment]
I am not saying that the original solution was perfect.  It was just good enough for its purpose.  As far as I know, we have never received any bug report about the error message being misleading, only bug reports about the information not being available.

**Comment by jay** [comment]
I prefer the old way where it output the status line.

**Comment by bagder** [comment]
I still believe that while we can discuss what curl should show in its error buffer or not for this case, **we do not guarantee error buffer contents** as per our API or ABI so pycurl was wrong to depend on it and assume that we would always and in every situation provide that information. Because even if we would (partially) revert this change, I did the change because it will not work like this with the Hyper backend (at least at that point in time, because it simply didn't offer that information) and I don't think pycurl wants to fail with a curl+hyper either.

So: this really is not a curl bug.

**Comment by kdudka** [comment]
I have notified pycurl upstream about this issue: https://github.com/pycurl/pycurl/issues/679
