### ISSUE TITLE
curl --insecure gnutls error "Error in the certificate." 

### ISSUE THREAD

**Issue by jay** [curl/curl#6634]
_Originally posted by @velpuri1035 in https://github.com/curl/curl/discussions/6633_

```
I am observing issue when I port curl from 7.47.1 to 7.66.0.

curl -kvi -u root:'$pl3nd1D' --request GET https://localhost:8080/redfish/v1/Systems
*   Trying ::1:8080...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
* found 128 certificates in /etc/ssl/certs/ca-certificates.crt
* ALPN, offering http/1.1
* gnutls_handshake() failed: Error in the certificate.
* Closing connection 0
**curl: (35) gnutls_handshake() failed: Error in the certificate.**
root@HostName-637491298417255405:~#

I am wondering the why the curl command is reporting certificate error, with though -k is passed.

Could some one help to provide a suggestion on fixing this issue as I see the GnuTLS is causing the error

**Not working curl version:**
root@HostName-637491298417255405:~# curl -V
curl 7.66.0 (arm-poky-linux-gnueabi) libcurl/7.66.0 GnuTLS/3.6.13 zlib/1.2.11 libidn2/2.2.0
Release-Date: 2019-09-11
Protocols: file ftp ftps http https
Features: AsynchDNS HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets
root@HostName-637491298417255405:~#

**Working curl version:**
@CSI41-1670G01-RM-U27:/# which curl
/usr/bin/curl
root@CSI41-1670G01-RM-U27:/# curl -V
curl 7.47.1 (arm-poky-linux-gnueabi) libcurl/7.47.1 GnuTLS/3.4.9 zlib/1.2.8
Protocols: file ftp ftps http https
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

**Comment by jay** [comment]
Can you try the [latest version](https://curl.se/download.html)? I cannot reproduce in curl 7.75.0. Maybe it has something to do with the server certificate other than verification.

curl 7.75.0-DEV (x86_64-pc-linux-gnu) libcurl/7.75.0-DEV GnuTLS/3.5.18 zlib/1.2.8 nghttp2/1.42.0 librtmp/2.3

**Comment by velpuri1035** [comment]
Yes, I know we have issues with certificate error with multiple extensions.

But my question was, having -k option ideally it shouldn't checking server certificate validation isn't it ?

Is there a way I can do curl config or source patch to skip server certificate validation completely or move forward with errors

**Comment by jay** [comment]
curl doesn't check for certificate verification when [--insecure](https://curl.se/docs/manpage.html#-k). The error is during the [handshake](https://github.com/curl/curl/blob/curl-7_75_0/lib/vtls/gtls.c#L256-L291) which is before the [verification check](https://github.com/curl/curl/blob/curl-7_75_0/lib/vtls/gtls.c#L895-L928). Based on the error text it's probably GNUTLS_E_CERTIFICATE_ERROR which is treated as a fatal error (gnutls_error_is_fatal). Since it's considered fatal I doubt that you can skip it error during the handshake phase. Try this:

~~~diff
diff --git a/lib/vtls/gtls.c b/lib/vtls/gtls.c
index 333ff8b..ca4bc66 100644
--- a/lib/vtls/gtls.c
+++ b/lib/vtls/gtls.c
@@ -261,7 +261,8 @@ static CURLcode handshake(struct Curl_easy *data,
         ssl_connect_2_writing:ssl_connect_2_reading;
       continue;
     }
-    else if((rc < 0) && !gnutls_error_is_fatal(rc)) {
+    else if((rc < 0) &&
+            (!gnutls_error_is_fatal(rc) || rc == GNUTLS_E_CERTIFICATE_ERROR)) {
       const char *strerr = NULL;
 
       if(rc == GNUTLS_E_WARNING_ALERT_RECEIVED) {
~~~

/cc @nmav

**Comment by bagder** [comment]
I'm with @jay here. GnuTLS decides this is a fatal error and curl acknowledges that so the error happens before curl even gets to decide what to do with the server's certificate.

**Comment by nmav** [comment]
Hi,
 It's long time since I've worked on gnutls, but GNUTLS_E_CERTIFICATE_ERROR is about an error in the certificate, this is not about a certificate validation error. The latter issue would have been with a GNUTLS_E_CERTIFICATE_VALIDATION_ERROR, if gnutls was instructed to do the validation during handshake.

**Comment by velpuri1035** [comment]
Yes I knew there are issues with certificate key extensions but how can I make gnutls to pass with having cert errors. Is it possible ?

Why does it works on curl 7.47.1 (arm-poky-linux-gnueabi) libcurl/7.47.1 GnuTLS/3.4.9 zlib/1.2.8.

The reason I am asking is I had to update my linux version which brought latest curl 7.66.0 causing issues. At the same time I can't port 7.47.1 due to open library structure changes, causing to modify curl code again.

The best solution i was thinking to crate a gnutls patch that supersedes the certificate errors.


**Not working curl version:**
root@HostName-637491298417255405:~# curl -V
curl 7.66.0 (arm-poky-linux-gnueabi) libcurl/7.66.0 GnuTLS/3.6.13 zlib/1.2.11 libidn2/2.2.0
Release-Date: 2019-09-11
Protocols: file ftp ftps http https
Features: AsynchDNS HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets
root@HostName-637491298417255405:~#

**Working curl version:**
@CSI41-1670G01-RM-U27:/# which curl
/usr/bin/curl
root@CSI41-1670G01-RM-U27:/# curl -V
curl 7.47.1 (arm-poky-linux-gnueabi) libcurl/7.47.1 GnuTLS/3.4.9 zlib/1.2.8
Protocols: file ftp ftps http https
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

**Comment by nmav** [comment]
I do not and cannot know. You'll have to debug the certificate in question, and check why it is being rejected with `certtool`. I suspect because the later versions of gnutls are less lenient on malformed certificates.

**Comment by bagder** [comment]
I think this is (or isn't) a GnuTLS issue and not a curl one. GnuTLS hosts their issue tracker here: https://gitlab.com/gnutls/gnutls/-/issues

**Comment by jay** [comment]
I agree, this is not a curl bug, closing.
