### ISSUE TITLE
empty error message in ERRORBUFFER when curl_easy_perform returns CURLE_COULDNT_CONNECT

### ISSUE THREAD

**Issue by Eric1211** [curl/curl#6646]
### I did this
when conduct  curl_easy_perform, and the host is error, the errmsg text length is 0

### I expected the following
the error message text length is not 0. and should be "Failed to connect() to host or proxy."

### curl/libcurl version
7.74.0
[curl -V output]
when use curl, always receive curl:（28）time out. but not 7 in cmd line. we found this error in our code.
### operating system
linux

**Comment by jay** [comment]
As documented [CURLOPT_ERRORBUFFER](https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html) "**may** store human readable error messages on failures or problems." If no error was stored then you can use [curl_easy_strerror](https://curl.se/libcurl/c/curl_easy_strerror.html) on the error code returned by curl_easy_perform. If you are seeing a different error from libcurl than you are from the curl tool then that is most likely due to different settings.

**Comment by bagder** [comment]
@Eric1211 if you could help us reproduce this case we could perhaps work on providing an error message for this situation as an enhancement, but as @jay says the documentation already explains that this can and will happen at times. This is not a bug.
