### ISSUE TITLE
Unable to use --cacert to validate HTTPS server

### ISSUE THREAD

**Issue by RyanYang1221** [curl/curl#665]
Hi,

I have built curl on my embedded system.
When I try to validate HTTPS server by using --cacert, I got an error.

```
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:lib(20):func(144):reason(134)
More details here: http://curl.haxx.se/docs/sslcerts.html
```

My command is like 
`curl --cacert ./ca.pem https://ev-root.digicert.com/`

The ca.pem contains
```
-----BEGIN CERTIFICATE-----
MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTA2MTExMDAwMDAwMFoXDTMxMTExMDAwMDAwMFowbDEL
MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3
LmRpZ2ljZXJ0LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgSGlnaCBBc3N1cmFuY2Ug
RVYgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbM5XPm
+9S75S0tMqbf5YE/yc0lSbZxKsPVlDRnogocsF9ppkCxxLeyj9CYpKlBWTrT3JTW
PNt0OKRKzE0lgvdKpVMSOO7zSW1xkX5jtqumX8OkhPhPYlG++MXs2ziS4wblCJEM
xChBVfvLWokVfnHoNb9Ncgk9vjo4UFt3MRuNs8ckRZqnrG0AFFoEt7oT61EKmEFB
Ik5lYYeBQVCmeVyJ3hlKV9Uu5l0cUyx+mM0aBhakaHPQNAQTXKFx01p8VdteZOE3
hzBWBOURtCmAEvF5OYiiAhF8J2a3iLd48soKqDirCmTCv2ZdlYTBoSUeh10aUAsg
EsxBu24LUTi4S8sCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQF
MAMBAf8wHQYDVR0OBBYEFLE+w2kD+L9HAdSYJhoIAu9jZCvDMB8GA1UdIwQYMBaA
FLE+w2kD+L9HAdSYJhoIAu9jZCvDMA0GCSqGSIb3DQEBBQUAA4IBAQAcGgaX3Nec
nzyIZgYIVyHbIUf4KmeqvxgydkAQV8GK83rZEWWONfqe/EW1ntlMMUu4kehDLI6z
eM7b41N5cdblIZQB2lWHmiRk9opmzN6cN82oNLFpmyPInngiK3BD41VHMWEZ71jF
hS9OMPagMRYjyOfiZRYzy78aG6A9+MpeizGLYAiJLQwGXFK3xPkKmNEVX58Svnw2
Yzi9RKR/5CYrCsSXaQ3pjOLAEFe4yHYSkVXySGnYvCoCWw9E1CAx2/S6cCZdkGCe
vEsXCS+0yx5DaMkHJ8HSXPfqIbloEpw8nL+e/IBcm2PN7EeqJSdnoDfzAIJ9VNep
+OkuE6N36B9K
-----END CERTIFICATE-----
```

What does the error mean? How do I solve it?

Thanks.
BRs,
Ryan

**Comment by jay** [comment]
> What does the error mean? How do I solve it?

lib(20) is `ERR_LIB_SSL`
func(144) is `SSL_F_SSL3_GET_SERVER_CERTIFICATE`
reason(134) is `SSL_R_CERTIFICATE_VERIFY_FAILED`

Reference:
[**ERR_LIB_** (lib) codes are in crypto/err/err.h](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2f/crypto/err/err.h#L159)
[**SSL_F_** (func) codes are in ssl/ssl.h](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2f/ssl/ssl.h#L2602)
[**SSL_R_** (reason) codes are in ssl/ssl.h](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2f/ssl/ssl.h#L2840)

Perhaps your OpenSSL wasn't built with the error strings because usually you'll see something more descriptive in place of the numbers.

---

What is your `curl -V`? It works for me in these versions:

~~~
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

curl 7.39.0 (i386-pc-win32) libcurl/7.39.0 OpenSSL/1.0.0s zlib/1.2.8 libidn/1.30 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN Largefile SSPI SPNEGO NTLM SSL libz

curl 7.47.1 (x86_64-pc-linux-gnu) libcurl/7.47.1 OpenSSL/1.0.2f zlib/1.2.8 libidn/1.28 nghttp2/1.7.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets 

curl 7.47.1-DEV (i386-pc-win32) libcurl/7.47.1-DEV OpenSSL/1.0.2f nghttp2/1.7.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug Largefile NTLM SSL HTTP2
~~~

If I intentionally disable SNI support in the build I can force it to fail because the server will send different certificates when SNI is disabled.
You can see the difference using the OpenSSL tool:
~~~
openssl s_client -showcerts -connect ev-root.digicert.com:443
openssl s_client -showcerts -servername ev-root.digicert.com -connect ev-root.digicert.com:443
~~~

The right certificate in such a case is [DigiCert Global Root CA](https://github.com/bagder/ca-bundle/blob/a87bf7b/ca-bundle.crt#L966-L986).

Also: Maybe your SSL is being intercepted, your version of OpenSSL is tool old to properly process the chain, or some algorithm is disabled in your OpenSSL and therefore though it processes a certificate but it may silently ignore the certificate if it's missing the algorithm (I know some SSL libraries do this, I don't remember if OpenSSL does).

**Comment by RyanYang1221** [comment]
Hi Jay,

Thanks for your information!
The CURL inside our device shows
```
curl 7.16.0 (arm-unknown-linux-gnu) libcurl/7.16.0 OpenSSL/1.0.1i
Protocols: tftp ftp telnet dict ldap http file https ftps
Features: Largefile NTLM SSL
```
Is it possible that our curl is too old to deal with?
Our openSSL version is 1.0.1i, but I am not sure whether we added some options to build this openSSL library. Maybe some options could disable some algorithm?

Thanks.
BRs,
Ryan

**Comment by bagder** [comment]
curl 7.16.0 is 9.5 years old, I don't think many of us are very interested in chasing for problems in that version.

**Comment by RyanYang1221** [comment]
Hi,

Right now I can get the new error information
`curl: (51) SSL: certificate subject name '*.azurewebsites.net' does not match target host name 'xxxxxx.net'`

Does that mean the error (60) I met at first is passed?
If it is, how can I solve the problem I met now (51)?

Thanks.
BRs,
Ryan

**Comment by bagder** [comment]
Yes, that means your server gives you the wrong cert and curl sees that.

But this may also happen because your ancient curl version doesn't support SNI.

**Comment by RyanYang1221** [comment]
Thank you!
How do I check if our curl support SNI?
I added "-H Host:xxxxxx.net:443" to the command line, but still got the same error.

BRs,
Ryan

**Comment by bagder** [comment]
You read the [changelog](https://curl.haxx.se/changes.html) and see that it is mentioned as added in [7.18.1](https://curl.haxx.se/changes.html#7_18_1)

Changing Host: header won't help, SNI is a TLS extension. Lots of modern HTTPS servers will assume you support that.

**Comment by RyanYang1221** [comment]
OK! I see.
I'll try to upgrade our curl.
If it is upgraded to support SNI, do I still need to add the header of "Host"?

BRs,
Ryan

**Comment by bagder** [comment]
Changing Host: header won't help, with or without support for SNI. curl takes the host name to use in the SNI extension from the URL.

**Comment by RyanYang1221** [comment]
OK! Got it!
Thanks for your help!
I'll try :)
