### ISSUE TITLE
-F for emails lacks documentation

### ISSUE THREAD

**Issue by webdev3301** [curl/curl#6663]
I have searched the entire internet for this.

I post it here because it literally doesn't work.

Manpage reference: [-F, --form <name=content>](https://curl.se/docs/manpage.html#-F)

Example: the following command sends an SMTP mime e-mail consisting in an inline part in two alternative formats: plain text and HTML. It attaches a text file:

```
 curl -F '=(;type=multipart/alternative' \
  -F '=plain text message' \
  -F '= <body>HTML message</body>;type=text/html' \
  -F '=)' -F '=@textfile.txt' ... smtp://example.com 
```

How in heavens name do you do this? No matter what I try, it says file not found.

Honestly, at this point it can even be a text/plain single part email.

I seriously doubt ANYONE can get this work.

**Comment by danielgustafsson** [comment]
Isn't it `name=content`, so `-F file=@textfile.txt` in this case?

**Comment by venombytes** [comment]
No. I just wanted to see cURL's own example work. You know.. like every example that is provided by the creator works?

Like a single 1?

**Comment by bagder** [comment]
@webdev3301 advice: you being rude will not make anyone (more) willing to help you.

SMTP is not a protocol that is that well-used with curl and it certainly isn't well documented. The solution to that is to dig in and help out, not complain on the people that have given you a free tool.

**Comment by bagder** [comment]
[Test 646](https://github.com/curl/curl/blob/master/tests/data/test646#L30) verifies SMTP with -F and seems to work.

**Comment by webdev3301** [comment]
Not being rude. Just really objective. It's was very difficult to find this example online.

**Comment by bagder** [comment]
I hope you will work with us to enhance the documenttaion so that future users get a smoother ride? Perhaps with the help of that test case work out how your command line could be made to work and then based on that suggest how we can bring that information to wherever a normal user would look for it?

**Comment by monnerat** [comment]
The command snippet you try to execute is taken out its curl man page context where you **did** find it and is just an **example** illustrating the use of the `-F` parameter. In all cases this document does not aim to be a **step-by-step tutorial**. It assumes you are already familiar with sending a simple document using the SMTP protocol. For this to be accomplished, you need at least:

- access to a SMTP server allowing relay, probably via credentials
- a sender address
- one or more recipient address(es)
- existence of external objects you send if some, and read permission on them

In addition, you need to know basics of a multipart MIME document when sending a structured mail.

The use of the snippet **as it is** is in contradiction with the above probably because:

- you do not have relaying access to the SMTP server at `example.com`
- you do not have a readable file named `textfile.txt` in your current directory
- `...` is meant to figure other parameters and is wrongly understood by curl as the URL
- you do not provide a sender address (`--mail-from`)
- you do not provide at least one recipient address (`--mail-rcpt`): how would you expect to see a positive result of your trial ?!

I just tried the example adapted to my personal position and it works perfectly well.

If you do not want to adapt the illustrating examples of a manual to your personal situation, you probably have to write a (nonexistent yet) step-by-step tutorial for the subject. If you'll expose it like curl exposes its man page, a person reacting as you did will probably ask to publish also real credentials allowing your SMTP server to relay (which will, as you might know, give a high spammer worldwide reputation to your server).

IMHO, the curl man page in general and the `-F` description and code snippet in particular perfectly meet their goals. [everything curl](https://everything.curl.dev/) states it will never be finished, but no one will **ever** reveal in it credentials that would give you access to a relaying server. As a consequence, SMTP snippet cut-n'-paste will never be possible.

This is not the role of the curl documentation to explain protocol-related stuff like SMTP and MIME. If you need info on them, read RFCs [5321](https://tools.ietf.org/html/rfc5321), [2045](https://tools.ietf.org/html/rfc2045), [2046](https://tools.ietf.org/html/rfc2046) and [2047](https://tools.ietf.org/html/rfc2047).

**Comment by webdev3301** [comment]
I can write RFC emails in Notepad. What I cannot do, is find a working example of this.

> "I just tried the example adapted to my personal position and it works perfectly well."

 Hey. Thanks for posting the working example instead of talking about it. ;)

 **For those of you who got here and actually wanted to see a working example, your search has finally ended.**

To send a multipart message using `-F` options, you must use the grouping (?) notation: 

`"=(;type=multipart/alternative"` / `"=)"`

(it's a single line, but I wrote here this way for clarification)
```
curl --verbose -ssl smtps://secure.example.com:465
    --login-options AUTH=PLAIN
    --user sarah@sky.net:Letmein#123
    --mail-from sarah@sky.net
    --mail-rcpt john@sky.net --mail-rcpt paul@sky.net
    --mail-rcpt-allowfails
    -H @headers.txt
    -F "=(;type=multipart/alternative"
    -F "=<body.txt;encoder=quoted-printable"
    -F "=<body.html;encoder=quoted-printable"
    -F "=)"
    -F "=@files.zip;encoder=base64"
```
In this example, the first part (`=(`) opens a group and everything inside is considered as the same content in different formats (`type=multipart/alternative`). Then two parts (`=<`) are added, a plain text one and an HTML one, both encoded using the quoted-printable algorithm. The group is closed using `=)`.

The next part is not inside the alternative group, and it's attached (`=@`).

When creating the headers file, take into account:
* It should contain those that the receivers see: Date:, From:, Subject:, To:, Cc:, and Reply-To: —if aplicable—.
* cURL takes care of the mandatory headers.
* You can add other headers and they will be added too. If you don't like one of the headers created by cURL, you can add it to the file to override the default.
* New lines must be CR-LF [2].
* I ran a similar command in Windows and I had to encode the headers file in windows-1252 charset, as using UTF-8 broke the email, but your mileage may vary. I didn't tried it on GNU/Linux.

References:

[1] https://curl.se/docs/manpage.html#-F

[2] https://tools.ietf.org/html/rfc821

**Comment by webdev3301** [comment]
I can write RFC emails in Notepad. What I cannot do, is find a working example of this.

> "I just tried the example adapted to my personal position and it works perfectly well."

 Hey. Thanks for posting the working example instead of talking about it. ;)

> "As a consequence, SMTP snippet cut-n'-paste will never be possible."

Are you saying that I can't use the word `example` in credential arguments then copy & paste that exact example here because security?

 **For those of you who got here and actually wanted to see a working example, your search has finally ended.**

To send a multipart message using `-F` options, you must use the grouping (?) notation: 

`"=(;type=multipart/alternative"` / `"=)"` **[1]**

(it's a single line, but I wrote here this way for clarification)
```
curl --verbose -ssl smtps://secure.example.com:465
    --login-options AUTH=PLAIN
    --user sarah@sky.net:Letmein#123
    --mail-from sarah@sky.net
    --mail-rcpt john@sky.net --mail-rcpt paul@sky.net
    --mail-rcpt-allowfails
    -H @headers.txt
    -F "=(;type=multipart/alternative"
    -F "=<body.txt;encoder=quoted-printable"
    -F "=<body.html;encoder=quoted-printable"
    -F "=)"
    -F "=@files.zip;encoder=base64"
```
In this example, the first part (`=(`) opens a group and everything inside is considered as the same content in different formats (`type=multipart/alternative`). Then two parts (`=<`) are added, a plain text one and an HTML one, both encoded using the quoted-printable algorithm. The group is closed using `=)`.

The next part is not inside the alternative group, and it's attached (`=@`).

When creating the headers file, take into account:
* It should contain those that the receivers see: Date:, From:, Subject:, To:, Cc:, and Reply-To: —if aplicable—.
* cURL takes care of the mandatory headers.
* You can add other headers and they will be added too. If you don't like one of the headers created by cURL, you can add it to the file to override the default.
* New lines must be CR-LF **[2]**.
* I ran a similar command in Windows and I had to encode the headers file in windows-1252 charset, as using UTF-8 broke the email, but your mileage may vary. I didn't tried it on GNU/Linux.

References:

[1] https://curl.se/docs/manpage.html#-F

[2] https://tools.ietf.org/html/rfc821

**Comment by webdev3301** [comment]
**Example of** [test646](https://github.com/curl/curl/blob/master/tests/data/test646#L30)

To send a multipart message using `-F` options, you must use the grouping (?) notation: 

`"=(;type=multipart/alternative"` . . . `"=)"` **[1]**

(it's a single line, but I wrote here this way for clarification)

**Attachments** are **sourced from** the **parts/** directory.

```
curl --verbose -ssl smtps://secure.example.com:465
    --login-options AUTH=PLAIN
    --user sarah@sky.net:Letmein#123
    --mail-from sarah@sky.net
    --mail-rcpt john@sky.net --mail-rcpt paul@sky.net
    --mail-rcpt-allowfails
    -H @headers.txt
    -F "=(;type=multipart/alternative"
    -F "=<parts/body.txt;encoder=quoted-printable"
    -F "=<parts/body.html;encoder=quoted-printable"
    -F "=)"
    -F "=@parts/files.zip;encoder=base64"
```
In this example, the first part (`=(`) opens a group and everything inside is considered as the same content in different formats (`type=multipart/alternative`). Then two parts (`=<`) are added, a plain text one and an HTML one, both encoded using the quoted-printable algorithm. The group is closed using `=)`.

The next part is not inside the alternative group, and it's attached (`=@`).

When creating the headers file, take into account:
* It should contain those that the receivers see: Date:, From:, Subject:, To:, Cc:, and Reply-To: —if aplicable—.
* cURL takes care of the mandatory headers.
* You can add other headers and they will be added too. If you don't like one of the headers created by cURL, you can add it to the file to override the default.
* New lines must be CR-LF **[2]**.
* I ran a similar command in Windows and I had to encode the headers file in windows-1252 charset, as using UTF-8 broke the email, but your mileage may vary. I didn't tried it on GNU/Linux.

References:

[1] https://curl.se/docs/manpage.html#-F

[2] https://tools.ietf.org/html/rfc821

**Comment by webdev3301** [comment]
**Example of** [test646](https://github.com/curl/curl/blob/master/tests/data/test646#L30)

To send a multipart message using `-F` options, you must use the grouping (?) notation: 

`"=(;type=multipart/alternative"` . . . `"=)"` **[2]**

(it's a single line, but I wrote here this way for clarification)

**Attachments** are **sourced from** the **parts/** directory.

```
curl --verbose -ssl smtps://secure.example.com:465
    --login-options AUTH=PLAIN
    --user sarah@sky.net:Letmein#123
    --mail-from sarah@sky.net
    --mail-rcpt john@sky.net --mail-rcpt paul@sky.net
    --mail-rcpt-allowfails
    -H @parts/headers.txt
    -F "=(;type=multipart/alternative"
    -F "=<parts/body.txt;encoder=quoted-printable"
    -F "=<parts/body.html;encoder=quoted-printable"
    -F "=)"
    -F "=@parts/files.zip;encoder=base64"
```

`-H @` Adds a header for each line in the input file `parts/headers.txt`


In this example, the first part (`=(`) opens a group and everything inside is considered as the same content in different formats (`type=multipart/alternative`). Then two parts (`=<`) are added, a plain text one and an HTML one, both encoded using the quoted-printable algorithm. The group is closed using `=)`.

The next part is not inside the alternative group, and it's attached (`=@`).

When creating the headers file, take into account:
* It should contain those that the receivers see: Date:, From:, Subject:, To:, Cc:, and Reply-To: —if aplicable—.
* cURL takes care of the mandatory headers.
* You can add other headers and they will be added too. If you don't like one of the headers created by cURL, you can add it to the file to override the default.
* New lines must be CR-LF **[3]**.
* I ran a similar command in Windows and I had to encode the headers file in windows-1252 charset, as using UTF-8 broke the email, but your mileage may vary. I didn't tried it on GNU/Linux.

References:

[1] https://curl.se/docs/manpage.html#-H

[2] https://curl.se/docs/manpage.html#-F

[3] https://tools.ietf.org/html/rfc821

**Comment by bagder** [comment]
In my eyes this is already documented in the -F section of the man page and I'm not seeing what this comment above adds what isn't there already, but I will of course appreciate a patch/PR that improves the existing documentation.

https://github.com/curl/curl/blob/8cbc16b2f9eb2fca20009235668b7fb751cc1826/docs/cmdline-opts/form.d#L102-L137

**Comment by bagder** [comment]
No further feedback, closing
