### ISSUE TITLE
Test 1014 [Compare curl --version with curl-config --features] fails with --disable-crypto-auth --enable-sspi

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#6803]
### I did this

```
./configure --disable-crypto-auth --enable-sspi --enable-static --disable-shared
make
cd tests && make
./runtests.pl 1014
```
Since https://github.com/curl/curl/commit/cc615f48e712202fc26297bc7597e3a1e9188aac, this results in:
```
Mismatch in features lists:
curl:        alt-svc asynchdns brotli http2 https-proxy idn ipv6 largefile libz psl ssl sspi tls-srp zstd
curl-config: alt-svc asynchdns brotli http2 https-proxy idn ipv6 largefile libz ntlm psl ssl sspi tls-srp zstd
```

### I expected the following

The test to pass.

### curl/libcurl version

7.76.0-DEV

### operating system

MSYS2 MinGW-w64 64 bit on Windows 10

**Comment by mback2k** [comment]
Important question: what is the expected feature set?

**Comment by MarcelRaad** [comment]
NTLM should be disabled because of the `--disable-crypto-auth`. Without `--enable-sspi`, it's disabled.

**Comment by mback2k** [comment]
Okay, I will adjust configure later today.

**Comment by bagder** [comment]
On my first look, I couldn't figure out why this logic isn't good enough:

https://github.com/curl/curl/blob/85e6975643fe52d6c4152969e2353f3ab8ea4554/configure.ac#L5228-L5237

**Comment by bagder** [comment]
This does not reproduce on my Linux box

**Comment by mback2k** [comment]
The problem lies in the next lines:
https://github.com/curl/curl/blob/85e6975643fe52d6c4152969e2353f3ab8ea4554/configure.ac#L5238-L5246

I based that login on this previously existing logic in `CMakeList.txt` which was introduced with https://github.com/curl/curl/commit/f504f18641ebedde8e8b3805472267efa9a9b528 by @MarcelRaad:
https://github.com/curl/curl/blob/71529574215190baa15e49e0f825aed79e6566d4/CMakeLists.txt#L1374-L1378

So I guess CMake was wrong then regarding this and the check for SSPI can just be moved to the logic checking for NTLM core, right? I thought that SSPI does not provide all the required functionality for NTLM core and therefore SMB for which NTLM core was separated out.

Therefore I would like to suggest instead to add a check for `CURL_DISABLE_CRYPTO_AUTH` to the NTLM feature condition, ok?
