### ISSUE TITLE
fail writing body on Cgywin with absolute path

### ISSUE THREAD

**Issue by link89** [curl/curl#7131]
When using curl to download a file with -o option, if the file path is relative, it works correctly, but if it is an absolute path, it fails with the following error
`curl: (23) Failed writing body (0 != 4982)`
It happens even when the relative path and the absolute path actually refers to the same file. Here is an example:

```bash
curl --fail -q -L -C - --progress-bar https://nodejs.org/dist/v14.0.0/node-v14.0.0.tar.xz -o /home/rcadmin/node-v14.0.0.tar.xz
# Warning: Failed to create the file /home/rcadmin/node-v14.0.0.tar.xz: No such
# Warning: file or directory

pwd
# /home/rcadmin

curl --fail -q -L -C - --progress-bar https://nodejs.org/dist/v14.0.0/node-v14.0.0.tar.xz -o node-v14.0.0.tar.xz
# It works
```
Software version

+ curl -V
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: 2017-11-14, security patched: 2019-11-05
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

+ uname -a
CYGWIN_NT-10.0 XMN160 3.1.2(0.340/5/3) 2019-12-21 15:25 x86_64 Cygwin

**Comment by bagder** [comment]
First, that's a very old curl release you're using.

curl just opens the file name as provided on the command line. It doesn't even know if it is absolute or relative. I don't understand what curl does that is wrong there.

**Comment by jay** [comment]
You're using the native curl that comes with Windows 10 in cygwin. It appears cygwin does not make path adjustments to native application arguments  (eg change argument string `/home/rcadmin/node-v14.0.0.tar.xz` => `c:\cygwin\home\rcadmin\node-v14.0.0.tar.xz`) and that's why you are seeing that error message. You can use the native path or install cygwin's packaged version of curl or build your own in cygwin. IMO this is not a bug.
