### ISSUE TITLE
Android - Linking mbedTLS with curl

### ISSUE THREAD

**Issue by ahmad-kemsan** [curl/curl#7207]
I was trying to link mbedTLS with curl and then compile it for ARM, It worked fine (it enabled SSL with mbedTLS), But when I try to do the same for android it fails to do so(does not enable SSL with mbedTLS).

On compiling it shows this message: 

> checking for mbedtls_ssl_init in -lmbedtls... no 

> SSL : no

### Expecting: 
SSL enabled with mbedTLS

**Comment by bagder** [comment]
As always when configure fails, check out your `config.log` file for details.

If you want our help with this, you must provide more details.

**Comment by ahmad-kemsan** [comment]
I have attached a link below to download config.log file:

https://www.dropbox.com/s/ah9xcg28h8ip0z4/config.log?dl=0

Please have a look.

**Comment by bagder** [comment]
See, it tells the story of a library that can't be used since the linker cannot find `mbedtls_ssl_init` inside.

Possibly because you specified the lib dir and not the prefix dir on the command line where you stated `--with-mbedtls=/usr/local/lib` ...

## config.log snippet

configure:25847: checking for mbedtls_ssl_init in -lmbedtls
configure:25869: armv7a-linux-androideabi23-clang -o conftest -Qunused-arguments -Os -I/usr/local/include -I/usr/local/lib/include  -L/usr/local/lib/lib conftest.c -lmbedtls -lmbedx509 -lmbedcrypto  >&5
/opt/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lmbedtls
/opt/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lmbedx509
/opt/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lmbedcrypto
/tmp/conftest-bc9c5d.o:conftest.c:function main: error: undefined reference to 'mbedtls_ssl_init'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:25869: $? = 1
configure: failed program was:
~~~
| /* confdefs.h */
| #define PACKAGE_NAME "curl"
| #define PACKAGE_TARNAME "curl"
| #define PACKAGE_VERSION "-"
| #define PACKAGE_STRING "curl -"
| #define PACKAGE_BUGREPORT "a suitable curl mailing list: https://curl.se/mail/"
| #define PACKAGE_URL ""
| #define PACKAGE "curl"
| #define VERSION "-"
| #define OS "armv7a-unknown-linux-androideabi"
| #define _FILE_OFFSET_BITS 64
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_BUILTIN_AVAILABLE 1
| #define CURL_DISABLE_FTP 1
| #define CURL_DISABLE_FILE 1
| #define CURL_DISABLE_LDAP 1
| #define CURL_DISABLE_LDAPS 1
| #define CURL_DISABLE_RTSP 1
| #define CURL_DISABLE_DICT 1
| #define CURL_DISABLE_TELNET 1
| #define CURL_DISABLE_TFTP 1
| #define CURL_DISABLE_POP3 1
| #define CURL_DISABLE_IMAP 1
| #define CURL_DISABLE_SMTP 1
| #define CURL_DISABLE_GOPHER 1
| #define CURL_DISABLE_MQTT 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_CLOCK_GETTIME_MONOTONIC 1
| #define ENABLE_IPV6 1
| #define HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID 1
| /* end confdefs.h.  */
| 
| 
| #ifdef __cplusplus
| extern "C"
| #endif
| char mbedtls_ssl_init ();
| int main (void)
| {
| return mbedtls_ssl_init ();
|  ;
|  return 0;
| }
~~~
configure:25878: result: no

**Comment by ahmad-kemsan** [comment]
Thank you, It worked!
