### ISSUE TITLE
glibc 2.17 is required after libcurl.a upgrade from 7.75 to 7.76

### ISSUE THREAD

**Issue by gabrieltarpian25** [curl/curl#7232]
Hi, I have a dinamic library that statically links libcurl.a . 
Recently, I have upgrade to libcurl 7.76. I have built libcurl with the following command:

export CPPFLAGS="-I${ROOTDIR}/openssl/include/"
export LDFLAGS="-L${ROOTDIR}/openssl/libs/x64"
export LIBS="-lssl -lcrypto"
export LD_LIBRARY_PATH=${ROOTDIR}/openssl/libs/x64
./configure --prefix=${ROOTDIR}/build --with-ssl --disable-shared

FLAGS64="-O2 -Wall -m64 -fPIC"
make CXXFLAGS="${FLAGS64}" -j8

Everything was successful and a new libcurl.a was generated.
I have built libcurl.a on CentOS 7, with gcc 4.8 and glibc 2.17

If I try to load my dynamic library using dlopen, it fails with the error
/lib64/libc.so.6: version `GLIBC_2.17' not found

The issue happens only on CentOS 6 because glibc is 2.12. The issue is not seen with previous version of libcurl that we used, which is 7.75.0 .

Did I missed something when I built the libcurl.a 7.76?  

Thank you in advance!

**Comment by bagder** [comment]
That's not something curl makes happen. It doesn't care about your libc version.

**Comment by gabrieltarpian25** [comment]
I see. So it might be from openssl then? Because we have not changed anything in our build flow.

**Comment by jzakrzewski** [comment]
No. You build on a system with glibc 2.17, so the compiler automatically links to GLIBC_2.17 version of the library functions. It's normal and expected. The only way you could have a 7.75 version not dependent on glibc 2.17 is that it has been compiled on a system with older glibc.

There are very hacky ways to work around this but the rule of the thumb is: build all your components on the oldest system you intend to support. Otherwise you'll get in trouble.
