### ISSUE TITLE
[RFE] - support metalink in http headers

### ISSUE THREAD

**Issue by dustymabe** [curl/curl#728]
Thanks for the great work in curl/libcurl. I notice that curl has support for metalink (woot!), but doesn't seem to support Metalink in HTTP headers [RFC 6249](http://tools.ietf.org/html/rfc6249).

Would it be possible to support Metalink in HTTP headers via the --metalink option as well? [Here](https://lists.gnu.org/archive/html/bug-wget/2015-06/msg00034.html) is a link to where this functionality was added in wget.

**Comment by bagder** [comment]
Of course it is possible. Feel free to write a patch and submit it!

Note that this is an issue tracker and we won't keep feature requests open here unless someone works on them.

**Comment by dustymabe** [comment]
Hi @bagder thanks for the response! Is there a place where feature requests are held and can be tracked?

**Comment by bagder** [comment]
We don't really have any such place. There's no lack of good ideas or things we could work on, the problem is rather that we have too few persons working on them. We have hundreds of things that would be great to implement. Some obvious ideas we could work on have been added to the [TODO](https://curl.haxx.se/docs/todo.html) document and I figure this idea can be added there.

You'll have much higher chances of actually getting the feature done if you start working on it yourself and ask for help/assistance on the mailing list or similar.

**Comment by dustymabe** [comment]
> Some obvious ideas we could work on have been added to the TODO document and I figure this idea can be added there.

sweet. Does that site have it's source available? Is that something I can do?

> You'll have much higher chances of actually getting the feature done if you start working on it yourself and ask for help/assistance on the mailing list or similar.

I totally feel your pain on this one and I understand completely that this may only ever make it in if I decide to do it myself. Either way I thought it might strike someone's interest at some point (maybe even my own one day in the future :)).

**Comment by bagder** [comment]
The TODO is in the source tree as available here: https://github.com/curl/curl/blob/master/docs/TODO

Metalink goes into section 17 for the command line tool I suppose, since the metalink support is not provided by the library.
