### ISSUE TITLE
Test 2100 failing on Windows CI builds

### ISSUE THREAD

**Issue by mback2k** [curl/curl#7483]
### I did this
Used Azure DevOps Test Analytics to find out since when test 2100 fails and identified this commit being the earliest with test 2100 failing: https://github.com/curl/curl/commit/02dfe7193704817184b522888ffa926e6b73f648

See test outputs:
- https://dev.azure.com/daniel0244/curl/_build/results?buildId=6124&view=logs&j=2a829cdc-de19-55f1-0804-61a537f7925d&t=4aacc08c-e956-5ccc-5e53-e1bcb28a3c96&l=2751
- https://dev.azure.com/daniel0244/curl/_build/results?buildId=6124&view=logs&j=bd08dbef-08e3-5745-a81d-7c3800301c2d&t=76cab039-f851-5b33-4624-8c2f90dc0d9c&l=3407

### I expected the following
Test 2100 to work, also on the Windows (msys-based) CI builds.

**Comment by jay** [comment]
> this commit being the earliest with test 2100 failing: 02dfe71

Probably there is a problem with IPv6 in that CI that started around the time of that commit, but the commit itself has nothing to do with it.

The failed test output shows only one DoH request instead of two. The test check output is slightly misleading because the address family byte is stripped by the test before the comparison so that the order of the requests does not matter. The server input however has the actual raw bytes sent by libcurl before they're stripped and shows the request that is sent is DNS_TYPE_A (IPv4), which means DNS_TYPE_AAAA (IPv6) is the request that is not sent.

The test requires a curl build with IPv6, which it has:

2021-06-11T10:21:31.2871524Z * curl 7.77.1-DEV (i686-pc-mingw32) 
2021-06-11T10:21:31.2872174Z * libcurl/7.77.1-DEV zlib/1.2.11
2021-06-11T10:21:31.2872907Z * Features: alt-svc AsynchDNS Debug IPv6 Largefile libz NTLM TrackMemory

The libcurl doh code requires IPv6 to be working (not just built-in) to actually make a request for AAAA:

https://github.com/curl/curl/blob/bfbde883af33397943df68a3ae01847a634d33bf/lib/doh.c#L431-L439

https://github.com/curl/curl/blob/bfbde883af33397943df68a3ae01847a634d33bf/lib/hostip6.c#L65-L88

Somewhat related, HTTP-IPv6 is available as a test server. IPv6 test 240 is passing and 241 says "IPv6 support has been disabled in this program":

2021-06-11T10:21:31.2880054Z * Servers: SSL HTTP-IPv6 FTP-IPv6 

2021-06-11T10:42:42.3704765Z test 0240...[HTTP-IPv6 GET]
2021-06-11T10:42:42.5715953Z --pd---e--- OK (240 out of 1399, remaining: 23:37, took 1.942s, duration: 04:53)
2021-06-11T10:42:43.4246020Z test 0241 SKIPPED: IPv6 support has been disabled in this program

241 depends on the [test resolver built with CURLRES_IPV6](https://github.com/curl/curl/blob/curl-7_78_0/tests/server/resolve.c#L110)

**Comment by mback2k** [comment]
Thanks for the insight @jay. Although I am unable to derive a possible solution from this, I can add that PR #7180 highlights that the HTTP-IPv6 test server is running and unexpectedly alive at the end of the test run in both msys1-based builds:

- https://dev.azure.com/daniel0244/curl/_build/results?buildId=6581&view=logs&j=527bf187-1e79-5d87-cf1d-f6ea3385033b&t=e9c295b2-53ca-5f4f-595a-9604f84aa781&l=3112
- https://dev.azure.com/daniel0244/curl/_build/results?buildId=6581&view=logs&j=c41e26da-5947-51e5-2cfc-5243ccc2d3b2&t=007e788f-b844-5ee2-f4dc-524a64254874&l=3975

Interestingly test 2100 only fails in msys1-based builds/environments although the msys2-based ones are using the same kind of docker container setup for the Azure Pipelines CI.

**Comment by mback2k** [comment]
What I do not understand is why only classic MinGW using msys1 has this problem, but not the mingw-w64 builds. Any ideas?

**Comment by jay** [comment]
> Any ideas?

Unfortunately no. I have a computer that uses msys1 but it no longer builds OpenSSL since 1.1.x came out so I haven't built curl with it in some time. I think it is a CI issue though where they changed something, because the suspect commit makes no sense.

**Comment by jay** [comment]
CURLRES_IPV6 is not defined (and therefore the ipv6 works tests fail) because getaddrinfo configure test fails. It fails because getaddrinfo requires a minimum Windows version of 0x501 (Windows XP) and original mingw doesn't define a minimum Windows version instead defaulting to 0x400 (Windows NT).

**Comment by mback2k** [comment]
Thanks for that research. So I guess disabling IPv6 tests on classic mingw builds would be the right choice then. Will update PR accordingly.

**Comment by jay** [comment]
> So I guess disabling IPv6 tests on classic mingw builds would be the right choice then.

I don't think that's necessary if we can fix the underlying issues.

I'm proposing #7529 to make Curl_ipv6works function independent of getaddrinfo so that the DoH resolver will be able to request IPv6 addresses even if getaddrinfo was not present at compile time.

Also, IMO getaddrinfo should be available at compile time for mingw builds. We could change the minimum Windows version to Windows XP by detecting in configure if _WIN32_WINNT wasn't already set to something then set it to 0x501 for XP (I don't yet know what configure magic will be required). Anyone using autotools with original mingw to build libcurl for Windows 2000 or Windows NT (is anyone doing that at this point?) would have to change their build script to CFLAGS with _WIN32_WINNT 0x400.

**Comment by bagder** [comment]
Isn't this issue addressed now?
