### ISSUE TITLE
curl on Windows does not work with https links

### ISSUE THREAD

**Issue by FrostShock** [curl/curl#7520]
### I did this
curl -k -o a.htm https://www.github.com

### I got this
a.htm file is empty (zero bytes)

### I expected the following
to work and to save the file a.htm

### curl/libcurl version

curl 7.78.0 (x86_64-pc-win32) libcurl/7.78.0 OpenSSL/1.1.1k (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.9.0 nghttp2/1.44.0 libgsasl/1.10.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd

### operating system

Windows 8.1

### more info
I am not using any proxy

This is the output:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

**Comment by bagder** [comment]
The server responds with a redirect and you didn't ask curl to follow it (with `-L`).

**Comment by FrostShock** [comment]
How do you know it's a redirect? I could not see any indication in the output of the curl program that the server responds with a redirect.

In such cases, the program should remind the user to use -L, is it ok if I submit a feature request for that?

**Comment by bagder** [comment]
Use `-i` or `-v` to see the response headers.

> In such cases, the program should remind the user to use -L,

I disagree.

**Comment by dfandrich** [comment]
On Fri, Jul 30, 2021 at 03:09:36PM -0700, FrostShock wrote:
> How do you know it's a redirect? I could not see any indication in the output
> of the curl program that the server responds with a redirect.

The server returns a valid HTTP response which curl delivers to the user. If
the user didn't request the redirect code or URL with --write-out or similar,
or request it to be followed with -L, then curl is operating as requested.

> In such cases, the program should remind the user to use -L, is it ok if I
> submit a feature request for that?

This will annoy people who expect no body and just want the redirect URL or
code and it changes the behaviour curl has had since almost the beginning.
Maybe if you can reduce the cases where it outputs something to only the cases
when a user is interested it might make sense. Perhaps only if curl has enabled
colored header output?

**Comment by FrostShock** [comment]
> This will annoy people who expect no body and just want the redirect URL or code and it changes the behaviour curl has had since almost the beginning. Maybe if you can reduce the cases where it outputs something to only the cases when a user is interested it might make sense. Perhaps only if curl has enabled colored header output?
You are not getting the redirect URL without -i or -v or --write-out etc, so it can't annoy those users.
When the program outputs a warning, this is not changing the behavior. The download works the same, no matter what kind of warnings the program is showing.
The program can implement a switch like --issue-useful-warnings-for-beginners which, once activated makes the program to show such warnings. The beginners (many of them who are already wget users - like me) will get useful info for actually making sense of curl while the old users will not be affected in any way. I will submit a feature request since the arguments against do not look convincing to me

**Comment by dfandrich** [comment]
The problem is that beginners won't know that
--issue-useful-warnings-for-beginners exists or that they should use it. Your
feature request is noted, but it's unlikely to get implemented unless you can
convince somebody that it's needed.

**Comment by FrostShock** [comment]
They will know it if you add it at the beginning of the documentation.

However, I think the warnings should be issued even without such a switch, since it doesn't negatively affect anyone.

**Comment by jzakrzewski** [comment]
It does negatively effect anyone who reads the output and slowly lead to ignoring all warnings. I don't want to see such warnings like... ever. And yes, it happens that I forget about the "-L". One run with "-v" reveals the problem. If there is one flag you need to know, it's "-v" ;)

**Comment by FrostShock** [comment]
You have a lot more to read with "-v" than reading a single-line warning. So it looks like you prefer complicating things and spending more time than needed to find the cause of the problem. This is not how the vast majority of computer users work. 

Also it is impossible to believe there are many users who are using curl in order to download empty files. And those who would actually want that, they will most likely do it automatically, for many such links, without actually bothering to read the output.

Instead of implementing a switch for issuing warnings for the beginners, curl should implement a switch for the experienced users, to suppress such warnings, so they will be happy. And for them it's not a big deal to learn a new switch since they are experienced already.

This whole thing reminds me of the Linux users who welcome beginners with RTFM and "everyone (even your grandma who just wants to view some pictures at the computer) should know how to recompile the kernel, if you don't know how to do it, you are a lamer".

A program should be friendly to users, especially to new users, so they can learn fairly quick how to use it, without having to add an issue on GitHub or on superuser.com, without having to become an expert and without having to spend hours and hours reading the manuals.

**Comment by jzakrzewski** [comment]
Sorry but curl is much more than a program to download files. And you're talking about just one warning in a particular scenario. Other would like to have other warning for what they think is surprising. Going that route I would get 10+ lines of warnings for each command and would become pretty annoying pretty quickly.

Almost all of the surprises when using curl comes from two sources: 1) not understanding what the tool is about, 2) protocol quirks. It hurts me to say so but if you just want to download files, use wget. Otherwise curl for each protocol does minimum work to do what you, as a user, told it to. "curl -o a.htm https://www.github.com" does not mean "download github's home page". It means "issue a request to that address according to HTTP(s) rules and save the server response body to a file named 'a.htm'". Those two concepts are really different.

I don't oppose having "beginner warnings" behind some CLI flag but I only want to see warnings about important stuff - SSL problems, using the "-k" flag, or why curl declined to write output to the terminal.

> Instead of implementing a switch for issuing warnings for the beginners, curl should implement a switch for the experienced users, to suppress such warnings, so they will be happy. And for them it's not a big deal to learn a new switch since they are experienced already.

It is a big deal having to type that switch 100x a day though.

**Comment by pythontech** [comment]
To my mind, it does seem to violate the principle of least astonishment that curl, "a tool to transfer data" not "a tool to make requests", exits with a success code when it has not transferred data (because there was no data, not even empty data, in the response).
