### ISSUE TITLE
Retry-After handling does not honor --retry-max-time

### ISSUE THREAD

**Issue by kaol** [curl/curl#7675]
### I did this

I made this nginx config to test this out:
```
location /503/ {
  add_header Retry-After 86400 always;
  return 503;
}
location /503-2/ {
  return 503;
}
```

My command:
```
curl -i -m 5 --retry 2 http://localhost/503/
```

### I expected the following

The command to fail within five seconds, not within 3 days. If the `Retry-After` time is after `max-time`'s limit, it should fail immediately.

### curl/libcurl version

> curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
> Release-Date: 2020-12-09
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
> Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

Not the newest version but I saw no mentions of `max-time` or `Retry-After` in the changelog.

### operating system

> Linux sammakko3 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

**Comment by msigoo33** [comment]
ส่งจาก จดหมาย สำหรับ Windows จาก: Kari Pahulaส่งแล้ว: 5 กันยายน 2564 21:30ถึง: curl/curlสําเนาถึง: Subscribedชื่อเรื่อง: [curl/curl] Retry-After handling does not honor --max-time (#7675) I did thisI made this nginx config to test this out:location /503/ {  add_header Retry-After 86400 always;  return 503;}location /503-2/ {  return 503;}My command:curl -i -m 5 --retry 2 http://localhost/503/I expected the followingThe command to fail within five seconds, not within 3 days. If the Retry-After time is after max-time's limit, it should fail immediately.curl/libcurl versioncurl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3Release-Date: 2020-12-09Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftpFeatures: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSocketsNot the newest version but I saw no mentions of max-time or Retry-After in the changelog.operating systemLinux sammakko3 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bagder** [comment]
`--max-time` limits each transfer, if you want to limit all retried transfers you want `--retry-max-time`

**Comment by kaol** [comment]
Did you try it? `--retry-max-time` has no effect either, it's still going to only use `Retry-Timeout`.

I already used `timeout 60 curl` to work around this.

**Comment by bagder** [comment]
I didn't try it because your issue here was incorrect. Now you've clarified it with more details.
