### ISSUE TITLE
 If you use the curl command , there is a problem that the local directory from being displayed all . It serious problem . Or it I write the details here ?

### ISSUE THREAD

**Issue by k4zzk** [curl/curl#775]
### I did this

If you use the curl command , there is a problem that the local directory from being displayed all .
It serious problem .
Or it I write the details here ?

It might "bash" of the problem .
But , it had not only using curl command , for the time being , contacted here

### curl/libcurl version

```
> curl --version
curl 7.43.0 (x86_64-apple-darwin14.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

[curl -V output perhaps?]

**Comment by bagder** [comment]
Sorry, I don't understand that.

If you're saying you've found a security related issue, don't post it here in the public. If you find or simply suspect a security problem in curl or libcurl, mail us at curl-security at haxx.se (closed list of receivers, mails are not disclosed) and tell. 

If its not security-related, please describe your problem here with as much detail as possible.

**Comment by k4zzk** [comment]
thank you for answering.

Yes. I'm saying i have found a security related issue.

**Comment by k4zzk** [comment]
Where is "closed list of receivers" ?

**Comment by k4zzk** [comment]
By the way.
It is said that I revised a security-related problem.
Should I not contribute it to github either?

**Comment by bagder** [comment]
mail us at **curl-security at haxx.se**

No, things that aren't made to be made public at once should not be posted on github.

**Comment by k4zzk** [comment]
OK. Thank you for everything!
