### ISSUE TITLE
add support for IRIs (non-ASCII URIs)

### ISSUE THREAD

**Issue by tuukka** [curl/curl#776]
I'd expect IRIs (non-ASCII URIs) to work in curl like they work in other tools (browsers, Wget etc.).

As curl already supports IDNs (non-ASCII domain names), the host part of the URI can already be non-ASCII. However, curl sends non-ASCII paths to HTTP servers as is, which I understand to be against the HTTP and URI specs, and at least some servers respond with "400 Bad request".

Could curl detect non-ASCII URIs and decode them according to locale charset (UTF-8 these days)? When sending the path to the HTTP server, it should be encoded as UTF-8 and then percent-encoded.

**Comment by bagder** [comment]
curl and libcurl are specifically documented to work on URIs as documented in [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt).

I wouldn't object to supporting IRIs (RFC 3987 style) but that opens up for a busload of charset/encoding problems - and it would have to be an opt-in feature so that it doesn't break existing functionality. Further more, you mention "browsers" in there and browsers most certainly do not support IRIs; they support something way beyond IRIs and usually for example support spaces and all sorts of funny things translated into something from what the browser thinks the user meant. I prefer to stick to following documented specs in this regard.

> However, curl sends non-ASCII paths to HTTP servers as is

Well, it is *documented* to take a URI and a URI cannot have non-ASCII characters and yet you passed in such ones....

I personally have no plans on working on this.

**Comment by bagder** [comment]
Related known bug: [can't handle Unicode arguments in Windows](https://curl.haxx.se/docs/knownbugs.html#can_t_handle_Unicode_arguments_i)
