### ISSUE TITLE
SNI is not sent in lowercase

### ISSUE THREAD

**Issue by timmyrs** [curl/curl#780]
### I did this

I accidentally got a big letter in my URL and did `curl https://Netdex.pw/`, but this somehow gave me this SSL error:
> curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### I expected the following

I expected that it would just normally connect and get information as it actually does when requesting `curl https://netdex.pw/`

### curl/libcurl version

curl 7.26.0
libcurl 7.26.0

### Verbose

> * About to connect() to Netdex.pw port 443 (#0)
*   Trying 104.27.164.176...
* connected
* Connected to Netdex.pw (104.27.164.176) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS alert, Server hello (2):
* error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
* Closing connection #0
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### operating system

Raspbian GNU/Linux 7 (wheezy)

**Comment by jay** [comment]
This is because your server does not appear to be able to process the server name indication unless the hostname is in lowercase. Regarding this issue the [RFC for TLS extensions says in the SNI section](https://tools.ietf.org/html/rfc6066#page-7):

~~~
"HostName" contains the fully qualified DNS hostname of the server,
as understood by the client.  The hostname is represented as a byte
string using ASCII encoding without a trailing dot.  This allows the
support of internationalized domain names through the use of A-labels
defined in [RFC5890].  DNS hostnames are case-insensitive.  The
algorithm to compare hostnames is described in [RFC5890], Section
2.3.2.4.
~~~

*DNS hostnames are case-insensitive*. So I think this is the fault of your server. However it's worth noting that Firefox, Chrome and Internet Explorer will convert the hostname to lowercase so maybe we should be a little flexible on this.

Also, you're using a 4 year old version of curl! Time to upgrade.

**Comment by bagder** [comment]
That looks like nginx on cloudflare. It seems strange that such a well used software on such a big CDN would have a problem like that...

**Comment by timmy14085** [comment]
@jay I don't have my raspberry pi that long, and I did `apt-get update` and `apt-get upgrade` like a week ago.

**Comment by jay** [comment]
Timmy, very well I guess your packaged curl is older but still maintained. Typically though there are numerous bug fixes that only appear in the newer versions.

Regarding this issue I don't think we're in the wrong here. Maybe someone at cloudflare would be interested in this? @vkrasnov

**Comment by vkrasnov** [comment]
Thank you @jay, we will look into this.

**Comment by bagder** [comment]
For the sake of maximum compatibility with existing server we should probably consider lowercasing the name for the SNI field...

**Comment by jay** [comment]
Closing since this has been fixed by Cloudflare.
