### ISSUE TITLE
HTTP/2: libcurl (and nghttp2) do not retry requests who receive a REFUSED_STREAM without an END_STREAM

### ISSUE THREAD

**Issue by kshelton** [curl/curl#804]
### I did this

Used libcurl + nghttp2 to POST data to nginx-1.9.15

### I expected the following

WIth CURLOPT_VERBOSE = 1:
* We are completely uploaded and fine

### I received

NGINX
=====
2016/05/12 21:03:25 [info] 25#25: *5877 client sent stream with data before settings were acknowledged while processing HTTP/2 connection, client: fd98:c3de:6700:2:7c3e:95ff:fec9:c7da, server: [::]:9000

CURL
====
* HTTP/2 stream 1 was not closed cleanly: REFUSED_STREAM (err 7)

### curl/libcurl version

libcurl  == 7.48.0
nghttp2 == 1.10.0

### operating system

Ubuntu docker container under CoreOS 899.15.0

**Comment by kshelton** [comment]
Most likely related to: https://github.com/nginx/nginx/commit/536b5510d1051281bd9411723102333e6d1dbdf2

See similar discussion:
https://github.com/square/okhttp/issues/2506

**Comment by bagder** [comment]
A fairly simple and possible retry schema could be what was discussed on the httpbis mailing list:

Retry another request on the same connection and if that *also* fails, then fail the request anyway.

ping @tatsuhiro-t if you have any ideas on how this integrates (or not) with nghttp2

**Comment by tatsuhiro-t** [comment]
For nghttp2 part, when it receives RST_STREAM, regardless of the error code, it immediately calls nghttp2_on_stream_close callback.  Then it assumes stream ended.  Client can always issue new request since they are separate distinct request for nghttp2.

BTW, according to the issue tracker, it seems nginx devs have an intention to fix this issue, good move.

**Comment by kshelton** [comment]
So, in my case I have currently frozen myself against nginx 1.9.4.  Not really clear what their timeline is to fix this, is it worthwhile adding a stream teardown callback in nghttp2 that gets the stream close reason and code and can allow for retry?

**Comment by tatsuhiro-t** [comment]
nghttp2 nghttp2_on_stream_close callback already passes error code to the application.  The application can use this information to decide whether it should retry the request.
Since this is POST request, and some part of request body has been sent, it would be tricky for the application to retry if it throws away sent request data.  I'm not sure how libcurl handles the request body, but if it has seek-like function, it can do the retry somewhat easily.

**Comment by kshelton** [comment]
So, in the case of nginx it seems like they discard the frames as they are processed (meaning all the data would need to be resent), but I guess in the case of another implementation it may not be true.  This could be a can of worms, perhaps it is better to allow for blocking until settings is ack'ed?  So that the client could try, and if it fails with this error then it could retry with that flag set.

**Comment by tatsuhiro-t** [comment]
It may work, but as far as I know, only nginx has this behaviour.  We are very hard to eliminate blocking while standardizing HTTP/2.  It is very sad that the well known server like nginx has this kind of limitation.

**Comment by kshelton** [comment]
I agree that it's less than desired, but how many people will install 1.9.15-x.x.x (when they fix the issue) and how long will those versions remain in the wild?  I think making block for settings ack optional and default off allows handling the nominal case as a default and gives an option to let the client retry specifying to wait.  Which server needs this could be cached in the app to prevent the extra delay trying without waiting the first time.  Thoughts?

**Comment by tatsuhiro-t** [comment]
IMHO, not upgrading web server software is suicidal act.  If it contains the bug, it could be security related, and everything browns up.  nginx is no exception here.  I don't trust any service using older outdated web server.  There are alternative software for better HTTP/2 server implementation like h2o nowadays.

Personally, if I asked to choose from the ack blocking and retrying after REFUSED_STREAM, I choose latter.  This is because the former is just for the gas stop measure to the current implementation of nginx only.  OTOH, the latter has more broader and robust application for the other scenarios.

**Comment by bch** [comment]
OT: Daniel, you put @tatsuhiro-t in your mail and it showed up as a link to
github for me (using Gmail) - how did you do that?

**Comment by bch** [comment]
/me hopes it's not simply <a href="HTTP://example.com">some link</a> :P If
it is, pardon my noise.

**Comment by bagder** [comment]
> OT: Daniel, you put @tatsuhiro-t in your mail and it showed up as a link to github for me (using Gmail) - how did you do that?

I just posted a response on the github site in the issue, and mentioned @tatsuhiro-t with at-sign + username. I try to do that at times to make sure a particular user gets an extra chance to notice an issue/discussion. If anything magic happened in the outgoing mail, it was put there by github because of that mention.

**Comment by kshelton** [comment]
Closing due to fix in https://trac.nginx.org/nginx/ticket/959 .  Looks like the behavior is fixed in nginx 1.11.0 and I agree that implementing anything here as a one-off to address the broken nginx subset is probably a bad idea.
