### ISSUE TITLE
curl hangs when server closes the connection right after receiving headers

### ISSUE THREAD

**Issue by andreysm** [curl/curl#807]
### I did this
```
curl -H "User-Agent:" -v afd.wikipedia.ru
```
curl stays waiting for something.

### I expected the following

Expected curl to exit with any response.

Just try:
```
telnet 72.52.4.90 80
GET / HTTP/1.1
Host: afd.wikipedia.ru
Accept: */*

Connection closed by foreign host.     <-- Why doesn't curl react to this?
```

### curl/libcurl version

curl 7.47.0 (i586-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 libssh2/1.5.0 nghttp2/1.9.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets 

### operating system

Debian (testing)

**Comment by andreysm** [comment]
Upd: curl exits after 5 minutes with the following:
```
curl: (56) Recv failure: Connection reset by peer
```

**Comment by jay** [comment]
This isn't a curl problem, confirmed in Wireshark. The server is caching content and when trying to figure out which cached version of the page to return takes into account `Vary: User-Agent,Accept-Encoding`. Adding any user agent works so that means the origin server is still online but either the origin and/or caching server can't handle no user agent.
