### ISSUE TITLE
CURLOPT_STDERR error on FILE *

### ISSUE THREAD

**Issue by stef-pellegrino** [curl/curl#8102]
Windows 11
VS2012  (msvcr110) 32 bit
libcurl 7.81 (recompiled with vs2012)

When I debug this, "exception triggered" and crash after...

```
          FILE *filep = fopen("dump", "wb");
          curl = curl_easy_init();
          if(curl) {
            curl_easy_setopt(curl, CURLOPT_URL, "http://example.com");
                        curl_easy_setopt(curl, CURLOPT_STDERR, filep);
                        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1);


            curl_easy_perform(curl);
            curl_easy_cleanup(curl);
          }

```

**Comment by gvanem** [comment]
Looks like an issue of mixing CRTs.

**Comment by stef-pellegrino** [comment]
I was also thinking along this issue, but I'm only using MSVCR110.dll
(and everything "works" but that)

**Comment by bagder** [comment]
You use libcurl as a DLL, right? Then `CURLOPT_STDERR` will not work because of the mixed CRTs when the `FILE *` is passed from the application to the DLL (this limitation is only documented for `CURLOPT_WRITEDATA` and is an omission we should fix). The solution is then to implement a `CURLOPT_DEBUGFUNCTION` callback and handle the output yourself.

**Comment by stef-pellegrino** [comment]
Ok, I'm going to do that.
Thanks for your help !!
