### ISSUE TITLE
[SMTP] Passing NOTIFY option to CURLOPT_MAIL_RCPT

### ISSUE THREAD

**Issue by rperrot** [curl/curl#8232]
Hi, 

is there a way to pass the NOTIFY option to the CURLOPT_MAIL_RCPT option ? 

My goal is to achieve something like that : 

`RCPT TO: <foo@bar> NOTIFY=SUCCESS,FAILURE
`

If I pass the option directly after my recipient, there's a bracket that is inserted at the end, that cause an issue with the SMTP server.

` RCPT TO:<foo@bar> NOTIFY=SUCCESS,FAILURE>
`

In my code, I created the curl_slist and for my only recipient, I set a string that already contains a bracket. For instance something like that : 

` curl_slist_append( recipients, "<foo@bar> NOTIFY=SUCCESS,FAILURE" );
`

**Comment by bagder** [comment]
We could perhaps extend the handling of the address and if the user-provided address starts with a `<` we could *not* add the `<>` pair but assume that the user provides them properly. It would make it possible for an application to provide such address lines...

**Comment by rperrot** [comment]
That would be fine for me.

**Comment by bagder** [comment]
Actually, that will not work since we already do magic on the string when provided with or without `<`. We would have to invent some other means of saying "use this full string exactly as provided". Maybe prefix the string with another "magic" letter that cannot otherwise legally be the first letter of a valid `RCPT TO` line? I suppose `@` or `>` could work.

**Comment by rperrot** [comment]
After a huge delay, we finally tested this fix and it's working great. A huge thank you !
