### ISSUE TITLE
iOS 9.x - if enable ipv6 it will ignore the host file when resolve domain 

### ISSUE THREAD

**Issue by liangwen** [curl/curl#833]
### enviroment 
curl version
v7.49.0 , v7.46.0
device
iPhone 5s , ios 9.2
Xcode version
7.3
### detail 
I got a wifi router and configure it's local hosts file 
if I build configure disable ipv6 it will check the router's local hosts file before real resolve domain
but when I configure enable ipv6 it continue check the hosts file in the first few http request 
and later it will not check the hosts file but resolve domain direct。

I used android device connect to the same wifi router it will always check it's local hosts file 

I compared the two config.log(disable and enable ipv6) but not get some value message 

how to solve this problem or I missed some configure？

**Comment by bagder** [comment]
libcurl uses the libc functions to resolve names (or optionally c-ares if you built curl to use that). libcurl itself has no knowledge about hosts files vs DNS or similar. If the resolves really act differently with and without IPv6 support, it is probably because iOS' functions gethostbyname (that curl uses when built without IPv6 support) and getaddrinfo (used when IPv6 enabled) differ in behavior...

**Comment by liangwen** [comment]
is there any configure or something  to let the libculr aware of the hosts file ?
so may be iOS'  function getaddrinfo do not check the host file .but when  it not check the hosts file I open another app on the same device the app also not check hosts file(I disabled  c-ares). I think it may cache the ip in some place. I can not explain this

**Comment by bagder** [comment]
No, reading the hosts file is not a job for libcurl. It is a job for the resolver, and the resolver in this case is provided by iOS itself in its getaddrinfo() implementation. You need to ask people with knowledge of iOS and its name resolving peculiarities to figure out how that works and what you can do to work around your problems. They really don't sound like they are curl issues. It is unfortunate because it means we can't do much about them within the realms of curl and the curl project.

**Comment by liangwen** [comment]
I understand where is the problem is .I install a DNS server (used Dnsmasq) and config it  so my problem is solved

Thank you very much
