### ISSUE TITLE
azure pipelines suddenly died

### ISSUE THREAD

**Issue by bagder** [curl/curl#8410]
It seems our CI builds on azure no longer works and we need to "request a free parallelism grant" for them?

They worked for #8404 but since #8408 all we get for all individual jobs  is a repeated message saying:

> ##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request

**Comment by bagder** [comment]
I submitted a request. just now.

**Comment by martinwoodward** [comment]
On it

**Comment by bagder** [comment]
Thanks! :heart:

**Comment by martinwoodward** [comment]
My current hypothesis is that curl got caught up in some mitigations that were put in place to resolve this incident. https://status.dev.azure.com/_event/287959626

Working with that team to verify and fix.  Longer term I think GitHub Actions is going to be the best place for these CI jobs so let me know if you need help getting there, but will keep working to try and get your builds restored.

**Comment by bagder** [comment]
We currently have 18 CI jobs setup on Azure Pipelines and 28 on GitHub Actions. I don't think there's anything else preventing us from moving them over than just the mechanics of yaml editing.

**Comment by bagder** [comment]
Azure Pipelines seems to be back and functioning for us again. PR #8418 shows jobs running.

**Comment by mback2k** [comment]
Azure Pipelines is a lot easier to manage than GitHub Actions for at least the Windows-based jobs I put there...

**Comment by bagder** [comment]
The problem came back!

**Comment by JonathanLydall** [comment]
@bagder, I started watching this issue since it is similar to an issue we experienced this week (which I have also reported [here](https://developercommunity.visualstudio.com/t/free-tier-parallelism-disabled-24-hours-after-bein-1/1654583?viewtype=all)), 
yesterday we decided to just start paying for an agent so it would unblock us (even though our operation is currently small enough that we are eligible for the free offering).

Microsoft did post [this](https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/) last year, but it seems they have recently started blocking even older organisations also (presumably to cut down on abuse).

While I appreciate their abuse issues and that people getting stuff for free aren't entitled to real support, I am highly disappointed with Microsoft in regards to the following:

- They don't email organisation administrators about the grant being revoked, instead you only find out when a build fails.
- They revoked parallelism very shortly after their manual review where they granted it.
- Something has clearly changed on their side causing this, but there has been no communication in the form of something like a blog post.

**Comment by mback2k** [comment]
I will look into moving things over to GitHub Actions over the weekend.

**Comment by mback2k** [comment]
Unfortunately I must report that GitHub Actions is not a suitable replacement for the container-based Windows jobs currently running on Azure Pipelines, as GitHub Actions only [supports container-based](https://github.com/actions/runner/issues/904) [Actions on Linux](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer) while Azure DevOps also supported Windows.

Cirrus CI provides the necessary functionality, but is already fully utilized with 4 Windows jobs that have 2 CPUs each while 8 CPUs is the total parallelism limit for Windows jobs. Since Windows jobs run about an hour, putting more jobs on Cirrus CI wouldn't help with our commit and PR churn rate.

Of course I could also rework all the Windows jobs to no longer require a pre-built container, but that would increase the runtime of each job even more as all the tools would need to be installed for each job instead of being able to download a pre-built container image.

Free Azure Pipelines / DevOps going away suddenly and without prior notice is really a shame and leaves my Windows build jobs in a limbo for now. 😞

**Comment by mback2k** [comment]
Comparison of the "Parallel jobs" page of @bagder account used for curl (left) and mine with defaults (right):

<img width="400" alt="image" src="https://user-images.githubusercontent.com/231943/153728317-a95adcfc-592d-46d5-a208-7435be4b8f79.png"><img width="400" alt="image" src="https://user-images.githubusercontent.com/231943/153728303-1aedd5fc-0264-4616-9152-463d70efd1f7.png">

For some unknown reason the free tier was removed.

**Comment by martinwoodward** [comment]
I've just spoken to the team at Microsoft and they are actively working to restore access to projects affected.

Thanks for the feedback around Actions. Will pass that along to the team too.

**Comment by JonathanLydall** [comment]
For what it's worth, the Microsoft representative in my reported issue has since sent a private message indicating they are investigating these grants being revoked.

**Comment by bagder** [comment]
> I think we were previously granted 20 parallel jobs for public projects.

Right, we were given [some extra azure powers](https://github.com/curl/curl/pull/4866#issuecomment-590993179) and that was awesome. This issue is now 7 days old and our Azure Pipelines builds are still dead.

**Comment by martinwoodward** [comment]
I _think_ the team have this resolved for you now, do you want to try again for me?

**Comment by jay** [comment]
Yes it's working now. Thanks
