### ISSUE TITLE
curl doesn't accept space in URL anymore?

### ISSUE THREAD

**Issue by klesh** [curl/curl#8654]
### I did this
./curl-amd64  "http://dict.youdao.com/w/eng/hello world/"
curl: (3) URL using bad/illegal format or missing URL

### I expected the following
some html output, it worked on v7.68 at least

### curl/libcurl version

curl 7.82.0 (x86_64-pc-linux-musl) libcurl/7.82.0 OpenSSL/1.1.1l zlib/1.2.11 libssh2/1.10.0 nghttp2/1.46.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

### operating system

Linux klesh-laptop 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
On Wed, Mar 30, 2022 at 09:20:54AM -0700, Klesh Wong wrote:
> I did this
> 
> ./curl-amd64 "http://dict.youdao.com/w/eng/hello world/"
> curl: (3) URL using bad/illegal format or missing URL

Space characters aren't allowed in URLs—they must be escaped as %20. Recent
versions of curl check this and error out.

**Comment by klesh** [comment]
> On Wed, Mar 30, 2022 at 09:20:54AM -0700, Klesh Wong wrote: I did this ./curl-amd64 "http://dict.youdao.com/w/eng/hello world/" curl: (3) URL using bad/illegal format or missing URL
> Space characters aren't allowed in URLs—they must be escaped as %20. Recent versions of curl check this and error out.

I see, thanks for quick response.
The space came from user input,  no sure how to escape it in shell script, can you point me some direction?
Thanks

**Comment by dfandrich** [comment]
There are a lot of bad characters besides spaces that user can enter in a URL.
It's better to just get the user to enter a valid URL rather than trying to
guess at what the user really meant to enter. That said, you can replace just
spaces with the command 'sed "s/ /%20/g" <<<"$1" ' in bash, where $1 is the
user's bad URL.

**Comment by klesh** [comment]
I see, thanks

**Comment by bagder** [comment]
There is unfortunately not a single definition of "a URL" and exactly as you say here, clients have many different views and parsers that behave differently and will act differently on the same input. Contrary to the idea of URLs.

Spaces were never allowed in RFC 3986 and curl only allowed them by mistake. Browsers support the WHATWG URL Specification and that allows spaces (and a lot of other craziness).

I don't think we should revert this decision now, many years later. Also: if you really want to argue for this, then adding a comment to a closed issue is a rather poor way as we are probably just a handful of people who will see it. Posting a proposal with arguments to the curl-library mailing list might be the best way if you really want to ask the (lib)curl community to change this default behavior. I think you are up for an uphill battle though.

The fact that URLs are weird and not portable is something I've discussed and posted about on my blog for many years and the treatment of space is far from the only problem. It is however not a problem that is easy to fix nor will it be fixed in the near term - if ever. There is actually almost no will "out there" to fix this issue. I think because it does not hurt enough.

**Comment by dfandrich** [comment]
I recall bagder is blogged several times on the topic. It's caused more than one issue over the years.

**Comment by panyusko** [comment]
Please say in what exactly commit this breaking change with URL parsing was introduced? Thanks!

**Comment by panyusko** [comment]
My patch for 8.5.0 release that restores old behavior for me. Maybe it will be useful to someone.
It is created on my repository, so it will not apply to the official GitHub repo.

```
---
 curl/lib/transfer.c | 2 +-
 curl/lib/url.c      | 6 +++---
 2 files changed, 4 insertions(+), 4 deletions(-)

diff --git a/curl/lib/transfer.c b/curl/lib/transfer.c
index 96f1fde755..fa7087c88a 100644
--- a/curl/lib/transfer.c
+++ b/curl/lib/transfer.c
@@ -1517,7 +1517,7 @@ CURLcode Curl_follow(struct Curl_easy *data,
         if(!u)
           return CURLE_OUT_OF_MEMORY;
 
-        uc = curl_url_set(u, CURLUPART_URL, data->state.url, 0);
+        uc = curl_url_set(u, CURLUPART_URL, data->state.url, CURLU_ALLOW_SPACE);
         if(!uc)
           uc = curl_url_set(u, CURLUPART_FRAGMENT, NULL, 0);
         if(!uc)
diff --git a/curl/lib/url.c b/curl/lib/url.c
index b81785fe2e..5fbb35993a 100644
--- a/curl/lib/url.c
+++ b/curl/lib/url.c
@@ -1795,6 +1795,7 @@ static CURLcode parseurlandfillconn(struct Curl_easy *data,
   if(!use_set_uh) {
     char *newurl;
     uc = curl_url_set(uh, CURLUPART_URL, data->state.url,
+                      CURLU_ALLOW_SPACE |
                       CURLU_GUESS_SCHEME |
                       CURLU_NON_SUPPORT_SCHEME |
                       (data->set.disallow_username_in_url ?
@@ -1946,8 +1947,7 @@ static CURLcode parseurlandfillconn(struct Curl_easy *data,
   else if(uc != CURLUE_NO_OPTIONS)
     return Curl_uc_to_curlcode(uc);
 
-  uc = curl_url_get(uh, CURLUPART_PATH, &data->state.up.path,
-                    CURLU_URLENCODE);
+  uc = curl_url_get(uh, CURLUPART_PATH, &data->state.up.path, 0);
   if(uc)
     return Curl_uc_to_curlcode(uc);
 
@@ -2192,7 +2192,7 @@ static CURLcode parse_proxy(struct Curl_easy *data,
   /* When parsing the proxy, allowing non-supported schemes since we have
      these made up ones for proxies. Guess scheme for URLs without it. */
   uc = curl_url_set(uhp, CURLUPART_URL, proxy,
-                    CURLU_NON_SUPPORT_SCHEME|CURLU_GUESS_SCHEME);
+                    CURLU_NON_SUPPORT_SCHEME|CURLU_GUESS_SCHEME|CURLU_ALLOW_SPACE);
   if(!uc) {
     /* parsed okay as a URL */
     uc = curl_url_get(uhp, CURLUPART_SCHEME, &scheme, 0);
-- 
```
