### ISSUE TITLE
mixing --data and --upload-file sets content-length from --data and sends data from --upload-file

### ISSUE THREAD

**Issue by verhovsky** [curl/curl#8704]
### I did this

```sh
cd /tmp
echo some very long text much longer blah blah > my_file.txt
curl -vvv --data 'short message' --upload-file my_file.txt example.com
```

### I expected the following

An error message or for `--data` to win or `--upload-file` to win.

Instead, I see this

```
[...]
> Content-Length: 13
> Expect: 100-continue
[...]
```

`Content-Length: 13` comes from `--data`, but the actual data being sent is the data in `--upload-file`.

I don't blame curl for doing something non-sensical here because passing both of these arguments is non-sensical, but I think it would be better for one option to win completely.

### curl/libcurl version

```
curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.5 zlib/1.2.11 nghttp2/1.45.1
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

### operating system

macOS 12.3.1

**Comment by danielgustafsson** [comment]
As per the [documentation](https://curl.se/docs/manpage.html#-d), `--data` overrides `--upload-file` so it seems the data from `--upload-file` should be discarded here.

**Comment by bagder** [comment]
The phrasing in the man page I think is unfortunate. "This option overrides [-F, --form](https://curl.se/docs/manpage.html#-F) and [-I, --head](https://curl.se/docs/manpage.html#-I) and [-T, --upload-file](https://curl.se/docs/manpage.html#-T)."

That line is generated by the keyword `Mutexed: form head upload-file` in `data.d` but I don't think we should say "overrides" just because the option is mutexed as it isn't true in all cases. We should probably say something more in line with "this option can (should?) not be used together with ..."
