### ISSUE TITLE
build error on macos+gcc

### ISSUE THREAD

**Issue by egorpugin** [curl/curl#8846]
There is a long history of this issue.
https://github.com/curl/curl/issues?q=is%3Aissue+SecTrustEvaluateAsync+is%3Aclosed

curl 7.83.1
macos sdk12.3, gcc11 from homebrew

Error:
```
[org.sw.demo.badger.curl.libcurl-7.83.1]/lib/vtls/sectransp.c
/Users/egor/.sw/storage/pkg/3e/f5/47f6/src/sdir/lib/vtls/sectransp.c: In function 'collect_server_cert':
/Users/egor/.sw/storage/pkg/3e/f5/47f6/src/sdir/lib/vtls/sectransp.c:2967:6: error: 'SecTrustEvaluateAsync' undeclared (first use in this function); did you mean 'SecTrustEvaluate'?
 2967 |   if(SecTrustEvaluateAsync) {
      |      ^~~~~~~~~~~~~~~~~~~~~
      |      SecTrustEvaluate
```

Changing it to [SecTrustEvaluateWithError](https://developer.apple.com/documentation/security/2980705-sectrustevaluatewitherror) (not deprecated) fixes the issue.
You can compare OS version support with [SecTrustEvaluateAsync](https://developer.apple.com/documentation/security/1400632-sectrustevaluateasync).
[SecTrustEvaluate](https://developer.apple.com/documentation/security/1394363-sectrustevaluate) works as well, but it's also deprecated.

**Comment by egorpugin** [comment]
> Changing it to [SecTrustEvaluateWithError](https://developer.apple.com/documentation/security/2980705-sectrustevaluatewitherror) (not deprecated) fixes the issue.
You can compare OS version support with [SecTrustEvaluateAsync](https://developer.apple.com/documentation/security/1400632-sectrustevaluateasync).

Versions overlap, so compile check or something like this may fix the issue reliably.

**Comment by bagder** [comment]
Sorry, I don't understand at all. Neither why this suddenly is a problem somewhere nor what the proposed fix is.

**Comment by egorpugin** [comment]
There is a build error.
Symbol is deprecated.
Possible fix is a replacement with the newer one.

**Comment by nickzman** [comment]
You can't build the Secure Transport code with GCC, because GCC (so far as I understand) does not support Grand Central Dispatch, and both `SecTrustEvaluateAsync()` and its replacement function `SecTrustEvaluateAsyncWithError()` require Grand Central Dispatch support to be present in the compiler.

If you build it with LLVM, then it will work.

If you want to patch this so it'll build using non-GCD-supporting compilers, then please file a pull request, and I'll review it. Thanks.

**Comment by egorpugin** [comment]
1. How do I check for GCD support in gcc?
2. SecTrustEvaluateAsync is not called anywhere https://github.com/curl/curl/blob/master/lib/vtls/sectransp.c#L2967=

**Comment by nickzman** [comment]
The FSF's GCC does not support GCD at all. There may be third-party forks that have support; if they do, then `__BLOCKS__` will be defined as true.

And now I remember why I had to do that: the code uses old-school availability checks (that is, checking to see if the function is defined at runtime) for weak-linking purposes, and not the newer `__builtin_available` function (which I do not think is supported by GCC), and we couldn't check for `SecTrustGetCertificateAtIndex()` because that function was private API prior to macOS 10.7. Let me see if I can quickly fix that.

**Comment by barracuda156** [comment]
> You can't build the Secure Transport code with GCC, because GCC (so far as I understand) does not support Grand Central Dispatch, and both `SecTrustEvaluateAsync()` and its replacement function `SecTrustEvaluateAsyncWithError()` require Grand Central Dispatch support to be present in the compiler.

You probably refer to blocks, which indeed are not yet supported in GCC, but those are distinct thing. There is nothing like GCD support in the compiler, AFAIK.
Pre-release headers of 10.6 did require blocks in `dispatch.h`, but that requirement was dropped in released versions. `libdispatch` itself builds with gcc from source.
