### ISSUE TITLE
vquic/ngtcp2.h:58:3: error: unknown type name 'ngtcp2_crypto_conn_ref'

### ISSUE THREAD

**Issue by paulmenzel** [curl/curl#9003]
Commit https://github.com/curl/curl/commit/d2c6d8be18adfe4c49ca8948d04e228ba1a6e9fb addressing issue https://github.com/curl/curl/pull/8968 seems to require a newer ngtcp2 than 0.5.0. With current curl master I get:

    In file included from quic.h:31,
                     from urldata.h:144,
                     from base64.c:36:
    vquic/ngtcp2.h:58:3: error: unknown type name 'ngtcp2_crypto_conn_ref'
       58 |   ngtcp2_crypto_conn_ref conn_ref;
          |   ^~~~~~~~~~~~~~~~~~~~~~

Should the configure script check for these requirements?

**Comment by bagder** [comment]
HTTP/3 support in curl is still marked experimental partly because of the early nature of several of the involved components, including the h3 libraries curl uses for this purpose. 

We have decided that as long as the h3 libs are beta releases we make sure that the latest curl code works with the latest h3 libraries and we don't maintain functionality with older libs. I don't think ngtcp2 0.5.0 is needs an exception. Does it?

**Comment by paulmenzel** [comment]
Thank you for the quick response.

The question is, what “latest h3 libraries” means. ngtcp2 0.5.0 was released/tagged 29 days ago on May 16th, 2022, which is latest for me. To avoid that, I’d think that these requirements should be checked by the configure script.

**Comment by bagder** [comment]
I mean latest as in their git development branches. We keep current curl working with current ngtcp2 and verify it in CI builds. Adding configure checks for ngtcp2 0.5.0 would be code that basically would be used now for a few weeks by a very small population and then go out of date. Lots of effort and energy for very little gain.

**Comment by bagder** [comment]
I won't stop anyone from working on that.
