### ISSUE TITLE
Licensing: some license identifiers potentially wrong/unprecise

### ISSUE THREAD

**Issue by mxmehl** [curl/curl#9220]
On the [REUSE mailing list](https://lists.fsfe.org/pipermail/reuse/2022q2/000149.html), @karsten-klein pointed out some potential unprecise or wrong licensing information they found with their scanners. They also provided some extra comments on single points in [this email](https://lists.fsfe.org/pipermail/reuse/2022q2/000150.html). I think it's best to address this here. 

My comments, where due, are in the brackets behind the individual points):

1. `m4/ax_compile_check_sizeof.m4` should be tagged as "GPL-3.0-or-later WITH Autoconf-exception-2.0" instead of just be "GPL-3.0-or-later"
2. ~~`lib/curl_path.c` includes an ISC snippet, but this is not marked with an SPDX-License-Identifier~~ (fixed in #9073 already by @jlovejoy)
3. `lib/sha256.c` includes a quote that parts of the code are based on public domain. This is not captured. (Will be possible to do with snippets, upcoming feature of SPDX 2.3 and the next REUSE specification)
4. `lib/md4.c` includes contains code under Public Domain or simple redistribution terms (“heavily cut down BSD license”). This is not captured. (Will be possible to do with snippets, upcoming feature of SPDX 2.3 and the next REUSE specification)
5. `lib/md5.c` includes contains code under Public Domain or simple redistribution terms (“heavily cut down BSD license”). This is not captured. (Will be possible to do with snippets, upcoming feature of SPDX 2.3 and the next REUSE specification)
6. `lib/krb5.c` contains a variant of the BSD-3-Clause. The SPDX-License-Identifier says BSD-3-Clause. In `LICENSES/BSD-3-Clause.txt` is however the standard/default text not matching the original license text. (We can do that with [custom licenses](https://reuse.software/faq/#custom-license))

Being extremely picky:

7. The files

```
tests/data/test222
tests/data/test230
tests/data/test232
tests/data/test314
tests/data/test396
tests/data/test1123
```

contain references to X11 License and suggest that curl is under such license. I would propose to rework those test cases to not cause any ambiguity.

Depending on review by the maintainer(s) I should be able to prepare a pull request to fix these issue.

**Comment by bagder** [comment]
I don't quite understand this issue. It seems to say that most things will be possible in a future version of REUSE. So what do you want to do now? Also, I'm curious on the remarks for public domain. That's not a license. Are you going to work with that as if it is?

2: why mention this here if it is already fixed?

7: that's silly, that's just innocent test data content.

**Comment by karsten-klein** [comment]
7: You may be surprised what content we sometimes find in test data.
As mentioned in the comment this is just a very finical finding. You can gain extra stars when fixing. 
See it as recommendation. No need to get emotional. 

3-5: The snippet aspect has two parts. The license identifier on file level (this can be changed immediately) and the identification of the snippet itself. The latter is - in my understanding - not possible with current REUSE and will be subject to the upcoming spec.

Regards,
Karsten

**Comment by bagder** [comment]
I still don't understand what the desired outcome of this issue is?

**Comment by zhengshuo1** [comment]
The newest version contains GPL license. Does it mean that the work that depends on the newest version of the curl needs to be public?

**Comment by bagder** [comment]
@zhengshuo1 no. It is included because there is **one** file in the curl source tree (`m4/ax_compile_check_sizeof.m4`) which is GPL licensed. Or to be specific, `GPL-3.0-or-later WITH Autoconf-exception-2.0`.

That file has been included in curl for years and nothing has changed license wise, we just made the license situation clearer and easier to find.

**Comment by zhengshuo1** [comment]
> 



> @zhengshuo1 no. It is included because there is **one** file in the curl source tree (`m4/ax_compile_check_sizeof.m4`) which is GPL licensed. Or to be specific, `GPL-3.0-or-later WITH Autoconf-exception-2.0`.
> 
> That file has been included in curl for years and nothing has changed license wise, we just made the license situation clearer and easier to find.

I‘m sorry, but I have asked for the person responsible for the license check in our company. He told me that the GPL license is stricted. Anything that contains GPL license has to be public. So it may prevent us from using curl lib. Is it possible to replace the ax_compile_check_sizeof.m4 by others?

**Comment by dfandrich** [comment]
That's not a correct summary of the GPL. But, if someone were to make a
clean room implementation of ax_compile_check_sizeof.m4 I think it would be
considered for inclusion.

**Comment by jzakrzewski** [comment]
Especially because it's basically a build script, so even if we generously assume GPL had to be expanded on other files (seems really silly), it'd only expand on other autotools stuff because there's no way the source files include that in any shape or form, and the output of GPL'd code is NOT automatically under GPL.

**Comment by bagder** [comment]
to avoid future misunderstandings, I've filed #9291 to remove that GPL reference

**Comment by bagder** [comment]
@zhengshuo1 wrote

> He told me that the GPL license is stricted. Anything that contains GPL license has to be public.

Then you either did not tell him the whole picture or he does not know what he's talking about:

1. that file was for **configure only**, not for the library or end product. It never affected what you shipped. ("was" as in past tense, as I have removed it from git now)
2. the license **does not "spread"** to generated configure code as is quite clearly expressed in the file: *"unlimited permission to copy, distribute and modify the configure scripts that are the output of Autoconf when processing the Macro. You need not follow the terms of the GNU General Public License when using or distributing such scripts"* meaning it covers if you distribute/edit that source file.

**Comment by bagder** [comment]
"Public domain" is not a license, that's a statement from an author that they have (tried to) given up all rights, intentions and ownership of their creation. (In Europe, I've learned that you cannot explicitly do this at will but you always retain some level of responsibility anyway but we can ignore that for now).

Therefore, in my mind, someone's expressed "public domain" code can be adopted into a project and get released under a license (*any* license really) and that is fine by the author since they dropped all associations and rights claims. I consider it a blanket "donation" of code ahead of time.

This leaves the **lib/krb5.c** file, which uses a phrasing in the header that doesn't exactly match the `LICENSES/BSD-3-Clause.txt`. The file has replaced the words "copyright holder" and "copyright holders" with "Institute" in three places.

This is also the *only* use of `BSD-3-Clause` in the project. Is this still reason enough to convert it into a "custom" license as per the REUSE project's FAQ?

I reformatted the files to look similar, but without changing any words, and a diff then looks like this:
~~~diff
--- lib/krb5    2022-08-11 09:47:58.236850896 +0200
+++ LICENSES/BSD-3-Clause.txt   2022-08-11 09:51:56.059010944 +0200
@@ -9,14 +9,14 @@
  *    notice, this list of conditions and the following disclaimer in the
  *    documentation and/or other materials provided with the distribution.
  *
- * 3. Neither the name of the Institute nor the names of its contributors
+ * 3. Neither the name of the copyright holder nor the names of its contributors
  *    may be used to endorse or promote products derived from this software
  *    without specific prior written permission.
  *
- * THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS'' AND
+ * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
- * ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE
+ * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)

**Comment by karsten-klein** [comment]
You should not modify the license text just because you require a dedicated custom license.

In my eyes you violate the terms with such a move. I would recommend such practice.

**Comment by bagder** [comment]
Are you talking about what the original authors of krb5.c did? I don't think they're here to listen.

I also suspect they did that about 27 years ago.

**Comment by bagder** [comment]
BTW, they authored that code so they did not violate any terms. They set the terms.

**Comment by bagder** [comment]
As I laid out in #9299, the krb5 edit does not actually constitute a license change as per SPDX guidelines so we can leave it as is.

I believe that was the last *bug* mentioned in here.
