### ISSUE TITLE
curl strips path when doing request against unix domain sockets

### ISSUE THREAD

**Issue by surlykke** [curl/curl#936]
When doing, eg.,:

    curl --unix-domain-socket /some/unix/socket http:/foo

the request arrives with path `/` and not `/foo` as expected. 

This can be reproduced with socat, like this:

    socat UNIX-LISTEN:/tmp/mysocket STDOUT & src/curl --unix-socket /tmp/mysocket http:/foo

which produces:

    GET / HTTP/1.1
    Host: foo
    User-Agent: curl/7.50.1-DEV
    Accept: */*

Tested with 2bbed9c4f0d2c192cd3b3b61fd6a1c21911936c3
Earlier version - for example cf93a7b364a70b56150cf6ea77492b799ec02a45 - produces:

    GET /foo HTTP/1.1
    Host: http
    User-Agent: curl/7.49.1-DEV
    Accept: */*

Git bisect points to 5409e1d793de755c7433336b80b0c8370a359d45 as the culprit. Reverting it seems to fix (although the revert did not apply cleanly to master).

I'm on Arch linux, but have tested with versions pulled from github.

br. Christian Surlykke

**Comment by bagder** [comment]
I don't see how "/foo" could ever have been expected from such a malformed url. I agree that the behavior is changed but is now more aligned with how browsers parse it.

**Comment by surlykke** [comment]
Ok.
What, then, would be the correct way of issuing a http request against a unix-domain-socket?

br. Chr.

**Comment by surlykke** [comment]
oh - wait. It seems 

    curl --unix-socket /tmp/mysocket http://localhost/foo 

works. 

Ok - you can close this bug then. Sorry for the noise.

br. Chr.

**Comment by thaJeztah** [comment]
This change caught me by surprise as well; using cURL to connect to the Docker API over a socket connection (there _is  no "hostname" there_), leads to either the API version to be stripped, or to a "404" message, because cURL now treats the first element as "hostname" (see the discussion on https://github.com/docker/docker/issues/17960#issuecomment-247564768). 

I scanned the changelog, but this change wasn't apparent from the description ("allow URLs to use one, two or three slashes" sounds like a _relaxation_ of validation rules, not something that leads to a different way of _handling_ those URL's).

This really is a breaking change, because, depending on which version of cURL is used, a "dummy" hostname _must_ be added, or _cannot_ be added to get the correct API endpoint.

**Comment by bagder** [comment]
If you think there's a bug in an existing curl version, I suggest filing a bug report instead of just commenting on an old one. It makes people notice it better.

And yes, unfortunately bug fixes can mean ABI/behavior changes and that is terribly unfortunate. Sometimes we avoid the fix then and make sure to document the behavior. In this case, as you can see, there was no objections and no protests against us fixing the problem.

Because you see, I consider not parsing or not handling a URL properly to be a bug. Users should be able to assume mostly the same operation with or without the use of the unix domain socket there IMHO. The fact that you even managed to get away with a malformed URL in the first place was also just an accident/fluke.
