### ISSUE TITLE
Curl versions after 7.78.0 cannot download specific site

### ISSUE THREAD

**Issue by depler** [curl/curl#9362]
Here is command line:

curl.exe --url "https://www.avito.ru" -o avito.html -v

Version 7.78.0 download file just fine (file size is about ~1mb), but 7.79.0 and later download different content with some dummy warning (file size is about 30kb). 

Probably some bug and/or scrape protection issue. User agent switching is not helping. Log files attached.

[778.txt](https://github.com/curl/curl/files/9419861/778.txt)
[779.txt](https://github.com/curl/curl/files/9419860/779.txt)

**Comment by bagder** [comment]
This is most likely because the site is doing [TLS fingerprinting](https://fingerprint.com/blog/what-is-tls-fingerprinting-transport-layer-security/) and denying "failing" clients access. A client that isn't considered good enough gets a 403 back. This is therefor not really a curl issue, but the server is actively and deliberately stopping your requests.

The first clue is the `server: QRATOR` header, as I then found the service behind this on https://qrator.net/en/. Sounds like they do a fair amount of filtering on incoming traffic.

I ran my fresh dev build of curl (built to use OpenSSL 3.0.5) on the site and I get a **403** back. I rebuilt the exact same curl code to instead use NSS for TLS and tried the same URL again: it now gives me a **200**. I think this is a strong indication as the only notable change between these two invokes is the way the TLS is done.

As a bonus, it can be noted that this is the very reason for projects like [curl-impersonate](https://github.com/lwthiker/curl-impersonate) to exist.

**Comment by depler** [comment]
Wow, thanks for explanation! I didn't know that technical details about TLS and handshaking differencies of "curl vs browser". By the way, for Windows binaries it is possible to switch to `schannel` SSL backend at runtime to archive status code 200:

`set CURL_SSL_BACKEND=schannel`

**Comment by bagder** [comment]
Thanks for confirming. This is thus not a curl bug and I'm closing this issue.

**Comment by depler** [comment]
@bagder I've done this: https://github.com/depler/curl-impersonate-win. Just leaving it here in case if someone else need this. Thanks for the idea!

**Comment by waitspring** [comment]
> Wow, thanks for explanation! I didn't know that technical details about TLS and handshaking differencies of "curl vs browser". By the way, for Windows binaries it is possible to switch to `schannel` SSL backend at runtime to archive status code 200:
> 
> `set CURL_SSL_BACKEND=schannel`

This env parameter may resolve the `NSS error -5961 (PR_CONNECT_RESET_ERROR)` with curl
