### ISSUE TITLE
Repeated parsing of ca-certificates

### ISSUE THREAD

**Issue by tlsa** [curl/curl#9379]
### I did this

Visited [a web site](https://www.bbc.co.uk/news) in [NetSurf](https://www.netsurf-browser.org/), which [uses libcurl](http://git.netsurf-browser.org/netsurf.git/tree/content/fetchers/curl.c) and openssl.

```bash
./nsfb -f sdl https://www.bbc.co.uk/news
```

### I expected the following

Did not expect the X509 certificate parsing to dominate the time spent loading the page.

See the following profile:

![Screenshot from 2022-08-28 12-27-46](https://user-images.githubusercontent.com/8228915/187071797-d709ffe5-da01-4426-8d6a-aea429f77ee2.png)

```bash
valgrind --tool=callgrind ./nsfb -f sdl https://www.bbc.co.uk/news
```

This shows that the `X509_LOOKUP_ctrl_ex` function takes 87% of the total time spent processing the page. That calls through to `X509_load_cert_crl_file_ex`, etc.

Running it again under strace:

```bash
strace -o log -eopenat  ./nsfb -f sdl https://www.bbc.co.uk/news
```

We can see that the certificates file is opened 15 times:

```bash
grep -c "ca-certificates" log
15
grep "ca-certificates" log
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 8
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 11
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 11
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 11
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 12
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 13
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 14
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 12
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 17
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 17
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 17
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 18
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 20
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 20
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 20
```

So it looks like `/etc/ssl/certs/ca-certificates.crt` is opened and parsed over and over again. Can anything be done to change to parsing it once and keeping it cached?

### curl/libcurl version

curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.12
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

Linux happy 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
I assumed at first this was merely some NetSurf inefficiency, so I left that out of the equation by trying a similar test using just the curl command-line. stracing curl and giving it a handful of URLs on the command line (to simulate a browser loading the main page and some images), I found that the certificate bundle is parsed once per host, even in a single curl process. This makes some sense, since multiple URLs on a single host would reuse an existing kept-alive connection where the TLS handshake is already complete.

It would be interesting to see the performance difference if you switched from a certificate bundle to a one-file-per-certificate method (see `c_rehash(1)`). I would expect the performance problem to go away, although it would be nice to minimize it using a bundle, too. I'm not sure if OpenSSL provides a way to fix this. since the parsing is handled by it. If so, then there would need to be a way to force the file to be parsed again when it changes so long-running processes will still pick up new certificates. I'm not familiar enough with the OpenSSL API to know if this is possible.

**Comment by bagder** [comment]
We also have this known bug noted: [Store TLS context per transfer instead of per connection](https://curl.se/docs/knownbugs.html#Store_TLS_context_per_transfer_i) - this is a known area that is suitable for improving.

Another option to consider is using [CURLOPT_CAINFO_BLOB](https://curl.se/libcurl/c/CURLOPT_CAINFO_BLOB.html).

This is not considered a bug though, which will make us not keep this issue open unless someone seems to be working on a fix short term.

**Comment by tlsa** [comment]
> stracing curl and giving it a handful of URLs on the command line (to simulate a browser loading the main page and some images), I found that the certificate bundle is parsed once per host, even in a single curl process

It's once per fetch, even from the *same* host, if you have parallel fetches (`-Z`):

```bash
strace -o log -eopenat curl -Z \
        https://www.netsurf-browser.org/index.html \
        https://www.netsurf-browser.org/netsurf.png \
        https://www.netsurf-browser.org/netsurf.css > /dev/null
```

That causes the certificates file to be opened/parsed three times:

```bash
grep "certificates" log
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 6
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 8
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 8
```

**Comment by bagder** [comment]
It's once per *connection*.
