### ISSUE TITLE
CURLE_RECV_ERROR schannel: SEC_E_DECRYPT_FAILURE

### ISSUE THREAD

**Issue by egorpugin** [curl/curl#9431]
### I did this

libcurl
GET https://raw.githubusercontent.com/SoftwareNetwork/database/master//db.version

### I expected the following

Everything worked ok for a long time.

### curl/libcurl version

7.85.0

### operating system

win11, native tls (schannel)

Output
```
*   Trying 185.199.110.133:443...
* Connected to raw.githubusercontent.com (185.199.110.133) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers h2
* ALPN: offers http/1.1
* ALPN: server accepted h2
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /SoftwareNetwork/database/master//db.version]
* h2h3 [:scheme: https]
* h2h3 [:authority: raw.githubusercontent.com]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x2913cc49bd0)
> GET /SoftwareNetwork/database/master//db.version HTTP/2
Host: raw.githubusercontent.com
accept: */*

* schannel: failed to decrypt data, need more data
* schannel: failed to read data from server: SEC_E_DECRYPT_FAILURE (0x80090330) - The specified data could not be decrypted.
* Failed receiving HTTP2 data
* Connection #0 to host raw.githubusercontent.com left intact
```

Same for http1.1.
`curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);`
```
*   Trying 185.199.110.133:443...
* Connected to raw.githubusercontent.com (185.199.110.133) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
> GET /SoftwareNetwork/database/master//db.version HTTP/1.1
Host: raw.githubusercontent.com
Accept: */*

* schannel: failed to read data from server: SEC_E_DECRYPT_FAILURE (0x80090330) - The specified data could not be decrypted.
* Closing connection 0
* schannel: shutting down SSL/TLS connection with raw.githubusercontent.com port 443
```

**Comment by jay** [comment]
Is this reproducible with the curl tool (curl.exe)? If not, please tell us how you built libcurl and give us minimal self contained example code that can be used to reproduce. FWIW this was not reproducible for me using the curl tool in Windows 7, 8 or 10 (21H2).

**Comment by egorpugin** [comment]
This is custom libcurl build. I re-check my flags. Maybe there was some new `HAVE_...` checks etc.

**Comment by egorpugin** [comment]
Here is a repro.

1. Download `https://curl.se/windows/dl-7.85.0_1/curl-7.85.0_1-win64-mingw.zip` and unpack.
2. `set CURL_SSL_BACKEND=schannel`
3. `curl.exe https://raw.githubusercontent.com/SoftwareNetwork/database/master//db.version -v`

```
>curl.exe https://raw.githubusercontent.com/SoftwareNetwork/database/master//db.version -v
*   Trying 185.199.111.133:443...
* Connected to raw.githubusercontent.com (185.199.111.133) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers h2
* ALPN: offers http/1.1
* ALPN: server accepted h2
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /SoftwareNetwork/database/master//db.version]
* h2h3 [:scheme: https]
* h2h3 [:authority: raw.githubusercontent.com]
* h2h3 [user-agent: curl/7.85.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x2581a4da910)
> GET /SoftwareNetwork/database/master//db.version HTTP/2
> Host: raw.githubusercontent.com
> user-agent: curl/7.85.0
> accept: */*
>
* schannel: failed to decrypt data, need more data
* schannel: failed to read data from server: SEC_E_DECRYPT_FAILURE (0x80090330) - The specified data could not be decrypted.
* Failed receiving HTTP2 data
* Connection #0 to host raw.githubusercontent.com left intact
curl: (56) Failed receiving HTTP2 data
```

**Comment by jay** [comment]
That's reproducible for me in Windows 11 and it happens regardless of HTTP version setting or TLS setting. curl 7.55 (packaged version that comes with Windows) seems to work though so the issue can probably be [bisected](https://github.com/curl/curl/wiki/how-to-git-bisect). I don't have a development environment set up in Windows 11 yet, I'm still in the process of configuring a VM for it.

**Comment by jay** [comment]
It looks like a TLS 1.3 issue, when I set `--tls-max 1.2` I can't reproduce.

/cc @wyattoday

**Comment by wyattoday** [comment]
I agree that this is an issue with how the internals changes in SChannel when using TLS 1.3.

The actual code I wrote runs on Windows 10, 1809 (a.k.a. Windows 10 build 17763) and newer regardless of whether TLS 1.3 is used or not. The only difference is the presence of the `SP_PROT_TLS1_3_CLIENT` flag. So, when `--tls-max 1.2` is present, the only difference in code the being executed (the code in curl itself) is the absence of the `SP_PROT_TLS1_3_CLIENT` flag.

So, this internal SChannel code path difference depending on whether it takes the TLS 1.2 route or the TLS 1.3 route.

I assume this is the exact same issue reported here: https://github.com/curl/curl/issues/9451 . Namely a bug in the ALPN code because SChannel altered the way it handled some internal code.

My guess is that if they disabled HTTP2 and used TLS 1.3 it would work (similar to the other issue).

**Comment by JDepooter** [comment]
I have been doing a bit of investigation into this problem. I am easily able to reproduce the problem on my Windows 11 machine. This is still reproducible after #9756 is merged, so it is not the same problem as reported in #9451. The problem persists regardless of HTTP version used, and whether or not ALPN is used.

Here is the command line I used in my testing:
> curld.exe --verbose --no-alpn --http1.1 https://raw.githubusercontent.com/SoftwareNetwork/database/master/db.version

My full output from this command is here, I will go through this in a bit more detail below.

> * STATE: INIT => CONNECT handle 0x1e511f07a30; line 1880 (connection #-5000)
> * Added connection 0. The cache now contains 1 members
> * STATE: CONNECT => RESOLVING handle 0x1e511f07a30; line 1926 (connection #0)
> *   Trying 185.199.111.133:443...
> * STATE: RESOLVING => CONNECTING handle 0x1e511f07a30; line 2010 (connection #0)
> * Connected to raw.githubusercontent.com (185.199.111.133) port 443 (#0)
> * STATE: CONNECTING => PROTOCONNECT handle 0x1e511f07a30; line 2075 (connection #0)
> * schannel: SSL/TLS connection with raw.githubusercontent.com port 443 (step 1/3)
> * Didn't find Session ID in cache for host HTTPS://raw.githubusercontent.com:443
> * schannel: checking server certificate revocation
> * schannel: disabled automatic use of client certificate
> * schannel: sending initial handshake data: sending 289 bytes.
> * schannel: sent initial handshake data: sent 289 bytes
> * schannel: SSL/TLS connection with raw.githubusercontent.com port 443 (step 2/3)
> * schannel: failed to receive handshake, need more data
> * STATE: PROTOCONNECT => PROTOCONNECTING handle 0x1e511f07a30; line 2093 (connection #0)
> * schannel: SSL/TLS connection with raw.githubusercontent.com port 443 (step 2/3)
> * schannel: encrypted data got 4096
> * schannel: encrypted data buffer: offset 4096 length 4096
> * schannel: sending next handshake data: sending 80 bytes.
> * schannel: encrypted data length: 19
> * schannel: SSL/TLS handshake complete
> * schannel: SSL/TLS connection with raw.githubusercontent.com port 443 (step 3/3)
> * Didn't find Session ID in cache for host HTTPS://raw.githubusercontent.com:443
> * Added Session ID to cache for HTTPS://raw.githubusercontent.com:443 [server]
> * schannel: stored credential handle in session cache
> * STATE: PROTOCONNECTING => DO handle 0x1e511f07a30; line 2112 (connection #0)
> > GET /SoftwareNetwork/database/master/db.version HTTP/1.1
> > Host: raw.githubusercontent.com
> > User-Agent: curl/7.86.0-DEV
> > Accept: */*
> >
> * STATE: DO => DID handle 0x1e511f07a30; line 2192 (connection #0)
> * STATE: DID => PERFORMING handle 0x1e511f07a30; line 2311 (connection #0)
> * schannel: client wants to read 102400 bytes
> * schannel: encdata_buffer resized 103424
> * schannel: encrypted data buffer: offset 19 length 103424
> * schannel: encrypted data got 903
> * schannel: encrypted data buffer: offset 922 length 103424
> * schannel: failed to read data from server: SEC_E_DECRYPT_FAILURE (0x80090330) - The specified data could not be decrypted.
> * schannel: schannel_recv cleanup
> * multi_done: status: 56 prem: 1 done: 0
> * The cache now contains 0 members
> * Closing connection 0
> * schannel: shutting down SSL/TLS connection with raw.githubusercontent.com port 443
> * schannel: clear security context handle
> * Expire cleared (transfer 0x1e511f07a30)
> curl: (56) Failure when receiving data from the peer

I have tracked this down to a problem in "step 2" of the TLS connection. It appears that the initial traffic from the server to libcurl (`ServerHello` and its associated data) are not fully processed.

In step 1, libcurl calls `InitializeSecurityContext` to generate the `ClientHello` and its associated data. This is then sent to the server, as indicated by this line in the log:
> * schannel: sent initial handshake data: sent 289 bytes

We then move to step 2, where we read data from the server and pass it to another call to `InitializeSecurityContext`. Here are the relevant lines:
> * schannel: encrypted data got 4096
> * schannel: encrypted data buffer: offset 4096 length 4096

This is where things get weird. The call to `InitializeSecurityContext` returns `SEC_E_OK`, indicating that this stage of the handshake is complete. It populates a `SECBUFFER_TOKEN` buffer with the outgoing "Client Finished" message for the server. However, it also populates a buffer of type `SECBUFFER_EXTRA` indicating that not all of the 4096 bytes have been consumed. In the above log, there are 19 bytes which have not been consumed:

> * schannel: encrypted data length: 19

Since the return code was `SEC_E_OK`, libcurl moves to step 3 of the TLS handshake, and sends the "Client Finished" message:

> * schannel: sending next handshake data: sending 80 bytes.

After this libcurl calls the `schannel_send` function with the HTTP request, and then the `schannel_recv` function to read the response:
> * schannel: client wants to read 102400 bytes
> * schannel: encdata_buffer resized 103424
> * schannel: encrypted data buffer: offset 19 length 103424
> * schannel: encrypted data got 903
> * schannel: encrypted data buffer: offset 922 length 103424

Notice that the 19 bytes from the initial `ServerHello` message are still there. When libcurl attempts to get the decrypted data via the `DecryptMessage` function, this extra data causes the decryption to fail:

> * schannel: failed to read data from server: SEC_E_DECRYPT_FAILURE (0x80090330) - The specified data could not be decrypted.

If I change the `CURL_SCHANNEL_BUFFER_INIT_SIZE` to a larger value (8192), the connection succeeds. In this case, the entire `ServerHello` message is processed at once. Here is a snippet from a successful request:

> * schannel: SSL/TLS connection with raw.githubusercontent.com port 443 (step 2/3)
> * schannel: encrypted data got 4292
> * schannel: encrypted data buffer: offset 4292 length 8192
> * schannel: sending next handshake data: sending 80 bytes.
> * schannel: encrypted data length: 215
> * schannel: SSL/TLS handshake complete

So it appears that the second call to `InitializeSecurityContext` is returning `SEC_E_OK` when there is still unread handshake data in the socket. At this point it feels as though we are working around a bug in the Windows SChannel library. I think there are a few options to consider here, some of which I have already tried and ruled out.

1. We can just increase the initial buffer size. Obviously this is less than ideal, especially for servers which have long certificate chains which may require a large `ServerHello` message.
2. We can decrease the initial buffer size, trying to force the correct "incomplete message" behaviour from SChannel. This did not work, the `InitializeSecurityContext` function still eventually returned `SEC_E_OK` with an `SECBUFFER_EXTRA` buffer indicating unconsumed bytes.
3. We can add some code to make sure the socket is empty once we get a `SEC_E_OK` return value from `InitializeSecurityContext`. I tried this by adding another call to `Curl_read_plain` after the call to `InitializeSecurityContext`. This also did not work, I guess those remaining bytes are actually important.
4. We can modify the loop in "step 2", so that it continues to read data when any handshake data is not consumed, even if the `InitializeSecurityContext` function returns `SEC_E_OK`. The logic is a bit tricky, because we would need to correctly handle sending the `Client Finished` handshake message while still processing the `ServerHello` hello message. I have a working proof of concept of this, and am working on a pull request now.

**Comment by jay** [comment]
Thanks for the excellent analysis.

> This is where things get weird. The call to `InitializeSecurityContext` returns `SEC_E_OK`, indicating that this stage of the handshake is complete.

I'd agree... [InitializeSecurityContext (Schannel)](https://learn.microsoft.com/en-us/windows/win32/secauthn/initializesecuritycontext--schannel#return-value) return value SEC_E_OK says:

_"The security context was successfully initialized. There is no need for another InitializeSecurityContext (Schannel) call. If the function returns an output token, that is, if the SECBUFFER_TOKEN in pOutput is of nonzero length, that token must be sent to the server."_

> So it appears that the second call to InitializeSecurityContext is returning SEC_E_OK when there is still unread handshake data in the socket.

We already have logic that was added a decade ago in 72a58131 for a large handshake problem with Windows CE. Currently that logic looks like this:

https://github.com/curl/curl/blob/93d092867f0f2c78571983040ef75e078ee1a4c4/lib/vtls/schannel.c#L1538-L1567

Perhaps that logic is too restrictive? We would need to read more data to complete the handshake, so doread would need to be set true, correct? But the comments there worry me. How can we be expected to tell if the extra data is handshake data or app data at that point?

**Comment by egorpugin** [comment]
I've found this page regarding SECBUFFER_EXTRA.
https://learn.microsoft.com/en-us/windows/win32/secauthn/extra-buffers-returned-by-schannel
It says:
```
When the input buffers contains too much information, Schannel does not treat this as an error. The function processes as much of the input as it can, and returns the status code for that processing activity. In addition, Schannel indicates the presence of unprocessed information in the input buffers by returning an output buffer of type SECBUFFER_EXTRA. Testing the output buffers for this type of buffer is the only way to detect this situation. The cbBuffer field of the extra buffer structure indicates how many bytes of input were not processed.
```

**Comment by JDepooter** [comment]
My potential fix for this problem is available here:
https://github.com/JDepooter/curl/tree/9431_schannel_recv_error

Note that that branch includes the commit in #9807, so it is really just the final two commits which are of interest to this issue.

I have some reservations about the fix however. As @jay mentioned in his previous comment, we cannot really know whether the "extra" data reported by the `InitializeSecurityContext` function is further handshake data or application data. We really need to use the return value to indicate this, but it is not reliable at this point. Notably, the TLS 1.3 specification allows for the server to start sending application data with the `ServerHello` message:
https://datatracker.ietf.org/doc/html/rfc8446#section-2

This is unlikely with https, because the server would not know which data to serve without first receiving a request. I imagine this could be possible in other protocols (ftps maybe?).

**Comment by jay** [comment]
@andrey-popov are we doing this wrong or is it a bug in schannel?

**Comment by andrey-popov** [comment]
> @andrey-popov are we doing this wrong or is it a bug in schannel?

A mistag? 🙂

**Comment by JDepooter** [comment]
I've discovered a potential workaround for this issue. When I turn off certificate revocation checking (via `--ssl-no-revoke` or the equivalent libcurl option), the error no longer occurs. Using wireshark, the difference in the `ClientHello` message is the absence of the `status_request` extension when revocation checking is turned off. This leads me to believe this is a problem in the way SChannel is handling CRL or OCSP in TLS 1.3.

Due to the way that TLS 1.3 works, it is not really possible to examine the relevant parts of the `ServerHello` message in Wireshark. So this is a useful clue as to what is going on, but ultimately not too helpful with regards to finding a solution to the problem.

**Comment by jay** [comment]
@JDepooter though we cannot decrypt Schannel client TLS sessions we can decrypt OpenSSL client TLS sessions so let's take a look at that:

~~~
curl 7.86.0 (x86_64-pc-linux-gnu) libcurl/7.86.0 OpenSSL/3.0.7 zlib/1.2.8 nghttp2/1.50.0 librtmp/2.3

SSLKEYLOGFILE=/mnt/hgfs/shared/sslkeylog curl https://raw.githubusercontent.com/SoftwareNetwork/database/master//db.version -v 

client:
TLSv1.3 Record Layer: Handshake Protocol: Client Hello (517 bytes)

server:
TLSv1.3 Record Layer: Handshake Protocol: Server Hello (127 bytes)
TLSv1.3 Record Layer: Change Cipher Spec Protocol: Change Cipher Spec (6 bytes)
TLSv1.3 Record Layer: Handshake Protocol: Encrypted Extensions (41 bytes)
TLSv1.3 Record Layer: Handshake Protocol: Certificate (3073 bytes)
TLSv1.3 Record Layer: Handshake Protocol: Certificate Verify (286 bytes)
TLSv1.3 Record Layer: Handshake Protocol: Finished (74 bytes)
TLSv1.3 Record Layer: Handshake Protocol: New Session Ticket (215 bytes)

client:
TLSv1.3 Record Layer: Change Cipher Spec Protocol: Change Cipher Spec (6 bytes)
TLSv1.3 Record Layer: Handshake Protocol: Finished (74 bytes)
~~~

If `--cert-status` is used (ie `status_request` extension type ocsp added to `Client Hello`) the only difference is the `Certificate` tls record is larger at 3552 bytes.

Note that server's `New Session Ticket` is sent after server's handshake `Finished`, which is allowed in TLS 1.3. We had a problem with that and FTPS in #6149, basically we did not read `New Session Ticket` on upload because sending on a separate socket with FTPS we didn't expect to have to read anything. Though I don't think that's the issue here it's still notable because possibly what's happening is some incomplete part of server's `New Session Ticket` is what can't be decrypted by Schannel. Of course Schannel and OpenSSL TLS 1.3 ClientHello are different but we can assume this is a possibility.

---

Back to Schannel. If I disable the prerecv buffer decryption does not fail. I wonder if you see similar results?

~~~diff
diff --git a/lib/curl_setup.h b/lib/curl_setup.h
index 59efe4d..3adcfbc 100644
--- a/lib/curl_setup.h
+++ b/lib/curl_setup.h
@@ -780,6 +780,7 @@ endings either CRLF or LF so 't' is appropriate.
  * wrappers for WinSock sockets. https://github.com/curl/curl/issues/657
  * Define DONT_USE_RECV_BEFORE_SEND_WORKAROUND to force disable workaround.
  */
+#define DONT_USE_RECV_BEFORE_SEND_WORKAROUND
 #if !defined(DONT_USE_RECV_BEFORE_SEND_WORKAROUND)
 #  if defined(WIN32) || defined(__CYGWIN__)
 #    define USE_RECV_BEFORE_SEND_WORKAROUND
~~~


~~~
--- fail.txt	2022-11-12 04:06:27.722117500 -0500
+++ success.txt	2022-11-12 04:06:32.284378400 -0500
@@ -1,7 +1,19 @@
 * schannel: client wants to read 102400 bytes
 * schannel: encdata_buffer resized 103424
 * schannel: encrypted data buffer: offset 19 length 103424
-* schannel: encrypted data got 716
-* schannel: encrypted data buffer: offset 735 length 103424
-* schannel: failed to read data from server: SEC_E_DECRYPT_FAILURE (0x80090330) - The specified data could not be decrypted.
-* schannel: schannel_recv cleanup
+* schannel: encrypted data got 913
+* schannel: encrypted data buffer: offset 932 length 103424
+* schannel: decrypted data length: 0
+* schannel: decrypted data added: 0
+* schannel: decrypted cached: offset 0 length 102400
+* schannel: encrypted data length: 932
+* schannel: encrypted cached: offset 932 length 103424
+* schannel: remote party requests renegotiation
+* schannel: renegotiating SSL/TLS connection
+* schannel: SSL/TLS connection with raw.githubusercontent.com port 443 (step 2/3)
+* schannel: encrypted data buffer: offset 932 length 103424
+* schannel: encrypted data length: 717
+* schannel: SSL/TLS handshake complete
+* schannel: SSL/TLS connection with raw.githubusercontent.com port 443 (step 3/3)
+* Found Session ID in cache for host HTTPS://raw.githubusercontent.com:443
+* schannel: SSL/TLS connection renegotiated
~~~

What prerecv is for:
https://github.com/curl/curl/blob/cd95ee9f771361acf241629d2fe5507e308082a2/lib/sendf.c#L154-L158

Interestingly, Curl_read_plain does not fetch prerecv data but Curl_recv_plain (which looks functionally the same) does. Guess which one schannel_step2 and schannel_recv calls...

https://github.com/curl/curl/blob/cd95ee9f771361acf241629d2fe5507e308082a2/lib/vtls/schannel.c#L2200-L2204

So here's a theory, possibly some part of the `New Session Ticket` record has been squirreled away in the prerecv buffer and so it is missed by schannel code. Only socks and schannel call Curl_read_plain instead of Curl_recv_plain and I don't know why.

**Comment by jay** [comment]
Please try #9904

**Comment by JDepooter** [comment]
Awesome, this works for me. I had a feeling that pre-recv buffer was involved some how.

**Comment by bagder** [comment]
Reopened by 18383fbf72b31b9ae58f17df8e75158a818c31eb

**Comment by jay** [comment]
> Reopened by [18383fb](https://github.com/curl/curl/commit/18383fbf72b31b9ae58f17df8e75158a818c31eb)

Take 2 in #9949.
