### ISSUE TITLE
SMTP connection refused, if the local host name contains umlaute

### ISSUE THREAD

**Issue by tavi-cacina** [curl/curl#999]
### curl/libcurl version

7.50.1
### operating system

Windows

If the host name contains umlaute, ex. MÜLLER-PC, then the SMTP connection is refused by the Server. Ex from gmail: 

```
curl header out: EHLO MÜLLER-PC
...
curl header in: 501-5.5.4 HELO/EHLO argument "MÜLLER-PC" invalid, closing connection.
curl header in: 501 5.5.4  https://support.google.com/mail/?p=helo
```

Also with other mail Providers is the same issue. The resolution would be to replace the invalid characters, for ex. with '?'. Ex. in curl_gethostname.c after truncate domain:

```
// Replace non ASCII chars with '?'
// https://tools.ietf.org/html/rfc5321#section-4.1.1.1
// https://tools.ietf.org/html/rfc5321#section-4.1.3
// dcontent = %d33-90 / %d94 - 126; Printable US-ASCII excl. "[", "\", "]"

char *p;
for(p = name; *p; p++)
  if(*p < 33 || *p > 126 || (*p > 90 && *p < 94))
    *p = '?';
```

**Comment by bagder** [comment]
Thanks! You up to making a full fledged pull request for this that we can merge?

**Comment by tavi-cacina** [comment]
Should I change the curl_gethostname.c or only specific to SMTP in smtp_parse_url_path?

**Comment by bagder** [comment]
This is probably an SMTP specific thing so I think we should limit to that area for now. So the latter I'd say.

You agree?

**Comment by jay** [comment]
Unfortunately the proposed fix doesn't address the issue in a way that will bring us into compliance. Based on my read of it we cannot send a question mark as a substitute if we're sending a 'Domain' as defined. Empirical testing with smtp.gmail.com shows this.
~~~
ehlo           = "EHLO" SP ( Domain / address-literal ) CRLF

Domain         = sub-domain *("." sub-domain)

sub-domain     = Let-dig [Ldh-str]

Let-dig        = ALPHA / DIGIT

Ldh-str        = *( ALPHA / DIGIT / "-" ) Let-dig

ALPHA          =  %x41-5A / %x61-7A   ; A-Z / a-z

DIGIT          =  %x30-39             ; 0-9

address-literal  = "[" ( IPv4-address-literal /
                 IPv6-address-literal /
                 General-address-literal ) "]"
                 ; See Section 4.1.3
~~~

~~~
> EHLO M?LLER-PC
< 501-5.5.4 HELO/EHLO argument "M?LLER-PC" invalid, closing connection.
~~~

Another thing is we allow URLs like `smtps://smtp.gmail.com/your-hostname-here` or in other words the path is the hostname so that has to be addressed as well, like this [master...jay:pr_1000_amended](https://github.com/curl/curl/compare/master...jay:pr_1000_amended?expand=1).

So more improvement should be made I think, like more strict requirements if it doesn't start with [ and end with ] since then we can assume 'Domain' so we should follow that exactly. The question is what to replace bad domain characters with since we don't want to send the wrong domain, or maybe we should just send localhost or the ip address in those cases?

**Comment by jay** [comment]
On second thought if someone supplies a hostname as the path maybe the burden should be on them, that way if there are servers that allow those bad characters they can still send them if they want to

**Comment by bagder** [comment]
> if someone supplies a hostname as the path maybe the burden should be on them

I think so. Then people can also test their servers for funny input and so on.

**Comment by tavi-cacina** [comment]
Sorry, I made a mistake when testing. Prior to the change in smtp.c, I changed the path of the URL to see if using '?' solves the problem. Having a '?' in the path solved it, but not as expected, because everything after and including the '?' were discarded (as URL query part). So instead of "EHLO M?LLER-PC" was just "EHLO M". By th way, I agree that the burden of validation should be on caller, it he specifies a path.
But, when using the string returned by gethostname, curl must remove or replace the invalid chars, for ex. with '-' or with '_'.

```
curl header out: EHLO MÜLLER-PC
curl header in: 501-5.5.4 HELO/EHLO argument "MÜLLER-PC" invalid, closing connection.

curl header out: EHLO M?LLER-PC
curl header in: 501-5.5.4 HELO/EHLO argument "M?LLER-PC" invalid, closing connection.


curl header out: EHLO M_LLER-PC
curl header in: 250-smtp.gmail.com at your service

curl header out: EHLO M-LLER-PC
curl header in: 250-smtp.gmail.com at your service
```

**Comment by bagder** [comment]
I think that's an excellent question. If we can't pass on the real domain/host name, what's the point in passing in one that is scrambled? Are there actually servers that need/want that?

**Comment by wmark** [comment]
Given support for *libidn* built-in, convert the hostname to Punycode.
`MÜLLER-PC` → `xn--mller-pc-65a`

**Comment by wmark** [comment]
Hostnames after `EHLO` and `HELO` are input to spam classificators, afaik, and not used for anything else. Servers will do a reverse lookup on the IP anyway.

Passing a non-FQDN like `MÜLLER-PC` had been wrong in the first place.

If a FQDN is not available you can use the ip-address in the usual brackets instead: `[192.0.2.1]`

(Bonus: That's a valid domain part in email addresses, and `bagder@[192.0.2.1]` is a valid address.)

**Comment by bagder** [comment]
@wmark you seem to have some knowledge here. Which of these methods do you consider to be the best or perhaps least bad approach?

**Comment by wmark** [comment]
You would need an external »oracle« to get the real FQDN and/or [IP address](http://myexternalip.com/raw). And that is, I guess, outside the scope of *curl*. Hence we have to accept some limitations. (ideal)

A `EHLO [127.0.0.1]` should always be accepted as per the standards. It will almost always trigger *SpamAssassin* and friends. (worst)

1. I'd expand @jay's suggestion and
  * add an option `--smtp-local-host` or the like for the user to provide a hostname
2. If `libidn` is available, convert the hostname.
3. If the hostname is still empty, use the IP address in brackets.
4. Pass that to the remote host.

Any errors are then the responsibility of the caller.

Do not convert the hostname to any proprietary form. `M_LLER-PC` or `m_ller.de` will still be invalid, only that now *curl* assumed responsibility.

**Comment by tavi-cacina** [comment]
The option to manually specify the host name is already available (the path part of the smtp server url). So the options when the host name is not specified by the user/caller, remain to just use 127.0.0.1 or sanitize the local host name (manually as in #1000 or using the `libidn` library, I do not have any knowlege/expertise for this).
